### ISSUE TITLE
CLICK_CELL事件

### ISSUE THREAD

**Issue by kanocence** [VisActor/VTable#1001]
监听事件 `ListTable.EVENT_TYPE.CLICK_CELL` 时 右键也会触发事件

不清楚是不是bug

如何只监听左键或者能够区分左右键呢

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/69da6a64-e0fb-46ce-9d4d-89dbd08efbbe)
可以通过这里的button值来区分下
