### ISSUE TITLE
[question] does vtable support paste data from feishu sheet, google sheet and excel?

### ISSUE THREAD

**Issue by neuqzxy** [VisActor/VTable#1024]
### What problem does this feature solve?

support paste data from feishu sheet, google sheet and excel

### What does the proposed API look like?

interactive api

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/interaction/copy-paste-cell-value
![image](https://github.com/VisActor/VTable/assets/3468473/43494ee8-8de8-49e7-950e-b35595e1bd5f)
支持的了 @neuqzxy
