### ISSUE TITLE
[Bug] setRecords 导致鼠标滚动卡顿

### ISSUE THREAD

**Issue by orionna319** [VisActor/VTable#1025]
### Version

0.18.4

### Link to Minimal Reproduction

Repository: https://github.com/orionna319/v-table-demo
Vercel Link: https://v-table-demo.vercel.app

### Steps to Reproduce

1. pnpm install
2. pnpm run dev
3. visit http://localhost:5173, 点击查询按钮

### Current Behavior

点击查询按钮，上下滚动卡顿

https://github.com/VisActor/VTable/assets/85230052/455fdf6e-96d9-457b-87ea-5f30bfab1951

duplicate issues
[使用update 会有很多的问题](https://github.com/VisActor/VTable/issues/633)

### Expected Behavior

点击查询按钮，上下滚动正常

### Environment

```markdown
- OS: macOS Ventura
- Browser: 120.0.6099.234 (正式版本) (arm64) 
- Framework: Vue@3
```

**Comment by Rui-Sun** [comment]
`const listTable = shallowRef()`
table实例需要使用shallowRef，否则ref会影响内部属性更新，导致渲染异常
可以参考：https://cn.vuejs.org/api/reactivity-advanced.html#shallowref

**Comment by orionna319** [comment]
谢谢解答
