### ISSUE TITLE
[Feature] 表格能否增加表尾

### ISSUE THREAD

**Issue by tianchao1995** [VisActor/VTable#1027]
表格能否增加表尾，目前需要单独为表尾设置样式，像textAlign这种样式好像不支持函数，不能为最后一行设置单独的textAlign样式，如果所有样式都支持函数也可以

**Comment by fangsmile** [comment]
我们后续调研下表尾功能需求。也希望您能提出更加明确的表尾需求 最好有示例。

样式问题的话可以这样：style整体是支持函数 的
![image](https://github.com/VisActor/VTable/assets/3468473/158bb378-98e9-42b8-981a-f3dc256d7856)

**Comment by fangsmile** [comment]
你好 这个需求可以再具体描述下吗 我们现在支持了冻结底部和自定义合并单元格的能力 您所说的表尾应该也是可以实现的了。
这个issue很长时间了  我先关了哈  有问题可以再提
