### ISSUE TITLE
[bug] 透视表排序updateSortRule接口问题

### ISSUE THREAD

**Issue by hw872715125** [VisActor/VTable#1030]
在透视表中的指标列配置了dropDownMenu: [{text: '升序', menuKey: 'asc', ...},{text: '降序', menuKey: 'desc', ...}, ...]，配置dropDownMenu是期望对指标列可以在界面交互进行排序。
在代码中监听了下拉菜单点击的事件：
  pivotTable.on('dropdown_menu_click', (args: any) => {
   pivotTable.setDropDownMenuHighlight([args])
   pivotTable.updatePivotSortState([{dimensions: args.field, order: args.menuKey}])
  })
想通过updatePivotSortState来更新排序，但是没有达到期望的效果，updatePivotSortState仅更新了排序状态，并没有触发表格排序。
请问我该怎么做，才能实现期望的效果。

**Comment by fangsmile** [comment]
这几个接口是之前给自定义树的用户的 ，即columnTree rowTree业务方自己排序后来再更新到表格中。

目前你可以尝试用
![image](https://github.com/VisActor/VTable/assets/3468473/2ecf883a-b20e-4431-b49d-fdcf3e3004ba)
在updatePivotSortState接口调用前尝试调用这个接口试试  如果有bug再提出即可

**Comment by hw872715125** [comment]
感谢解答，我在添加了如下代码后，还是没有触发表格排序。
![image](https://github.com/VisActor/VTable/assets/26103277/5a33f577-bad2-4b48-9223-33d3052dd704)
![image](https://github.com/VisActor/VTable/assets/26103277/bff4560a-4c7d-4923-9c45-14b6d043dc0b)

**Comment by hw872715125** [comment]
在option中配置了排序是可以生效的
dataConfig: {
   sortRules: [{
    query: [10038],
    sortByIndicator: "dnu",
    sortField: "store_day",
    sortType: "DESC"
   }]
  }
![image](https://github.com/VisActor/VTable/assets/26103277/0b49588e-2136-48a5-ab74-d2ba8343c0c8)

**Comment by fangsmile** [comment]
嗯嗯 那就是updateSortRule接口的问题了 写了TODO嘿嘿。
你暂时先用updateOption吧

**Comment by hw872715125** [comment]
收到，感谢解答

**Comment by hw872715125** [comment]
全量更新对于pivotSortState不生效
![image](https://github.com/VisActor/VTable/assets/26103277/3e84c84c-58e1-4256-b60a-dbd6d154cb45)
![image](https://github.com/VisActor/VTable/assets/26103277/c413ba64-aef4-4ddb-a734-0d21551d756c)

**Comment by hw872715125** [comment]
更新到0.19.1后，点击图标，触发dropdown_menu_click的监听函数中，调用了
pivotTable.setDropDownMenuHighlight([args])
pivotTable.updateSortRules([sortRule])
pivotTable.updatePivotSortState([{dimensions: args.field, order: args.menuKey}])
  第一次可以排序成功，点击第二次后就出现一点小问题。（第一次点击升序，第二次点击倒序，跟升序倒序无关，跟点击次数有关）
@fangsmile 
![image](https://github.com/VisActor/VTable/assets/26103277/17bdf3e0-0233-4091-baf7-ba064724a14c)
![image](https://github.com/VisActor/VTable/assets/26103277/307dec0c-6f25-430a-899a-b3c8472fbb8c)

**Comment by pzgz** [comment]
v0.23.0，还是有这个问题，PivotTable组件
