### ISSUE TITLE
[Feature] ListTable有考虑添加总计吗

### ISSUE THREAD

**Issue by z93919112** [VisActor/VTable#1038]
### What problem does this feature solve?

现在PivotTable可以设置汇总、小计总计，  ListTable为啥没有啊

### What does the proposed API look like?

export interface Total {
  // 是否显示总计
  showGrandTotals: boolean;
  // 默认'总计'
  grandTotalLabel?: string;
}

**Comment by fangsmile** [comment]
会增加汇总能力 但还没时间去做

**Comment by fangsmile** [comment]
已经支持 可以到官网查看demo和教程
