### ISSUE TITLE
[Bug] icon name is missing while using customRender

### ISSUE THREAD

**Issue by martesi** [VisActor/VTable#1041]
### Version

0.18.3

### Link to Minimal Reproduction

[Link](https://codesandbox.io/p/sandbox/bug-cant-set-get-name-from-customrender-elements-icon-xv43qn?file=%2Fsrc%2Findex.tsx%3A61%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsjzwf800063j6fws30ha9y%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsjzwf800023j6ff0s1j4sp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsjzwf800033j6f3qt4wy56%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsjzwf800053j6f9nvggmi8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsjzwf800023j6ff0s1j4sp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsjzwf800013j6f8fmsccfs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls1k730300023j6ly3umv02q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A61%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A61%252C%2522endColumn%2522%253A36%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrsjzwf800023j6ff0s1j4sp%2522%252C%2522activeTabId%2522%253A%2522cls1k730300023j6ly3umv02q%2522%257D%252C%2522clrsjzwf800053j6f9nvggmi8%2522%253A%257B%2522id%2522%253A%2522clrsjzwf800053j6f9nvggmi8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsjzwf800043j6fbo7idi5b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrsjzwf800043j6fbo7idi5b%2522%257D%252C%2522clrsjzwf800033j6f3qt4wy56%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrsjzwf800033j6f3qt4wy56%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

- open console in the reproduction page
- click the third column and they click the forth one.
- there first console shows name as undefined and the second one shows and expected.

### Current Behavior

icon name is missing in the `icon_click` event while icon attribute works just fine.

### Expected Behavior

icon name is provided just like using icon attribute.

### Environment

```markdown
- OS: Windows 10
- Browser: Microsoft Edge 121
- Framework: React@18
```

**Comment by fangsmile** [comment]
codesanbox打不开你的demo 是不是有什么权限

**Comment by martesi** [comment]
> codesanbox 打不开你的 demo 是不是有什么权限

似乎是有点问题，我刚刚修改了一下，麻烦再看看
