### ISSUE TITLE
[Bug] 触发编辑使用api，但是按Enter键和Tab键还能触发

### ISSUE THREAD

**Issue by jiffei** [VisActor/VTable#1049]
### Version

0.18.4

### Link to Minimal Reproduction

-

### Steps to Reproduce

-

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS: Win10
- Browser: Microsoft Edge 121.0.2277.83
- Framework: Vue3
```

**Comment by fangsmile** [comment]
https://visactor.bytedance.net/vtable/guide/interaction/keyboard
![image](https://github.com/VisActor/VTable/assets/3468473/ba155079-662a-4fed-aeaf-7a6f95fd1f4e)

**Comment by jiffei** [comment]
moveFousCellOnTab 我希望可以有效，但是不要进入编辑状态

**Comment by fangsmile** [comment]
当前单元格是编辑状态的话  点击tab移动下一个单元格也会是编辑状态。否则就不是的
