### ISSUE TITLE
只读模式下可以粘贴

### ISSUE THREAD

**Issue by 513655915** [VisActor/VTable#1063]
### Version

19.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

只读模式下可以粘贴

### Current Behavior

只读模式下可以粘贴

### Expected Behavior

只读模式下不能粘贴，否则就是可以编辑了

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

no

**Comment by fangsmile** [comment]
具体场景是什么 可以描述清楚一些吧
pasteValueToCell 不能满足你的场景吗？

**Comment by 513655915** [comment]
如：第N列为不可编辑列，在开启pasteValueToCell功能后，可以通过复制粘贴的方式修改第N列的值，由于第N列是不可编辑列，复制粘贴不应该可以修改第N列的值。

**Comment by fangsmile** [comment]
pasteValueToCell如果可以被定义成自定义函数呢？
如：
```
pasteValueToCell: boolean | (col, row, tableInstance)=>boolean
```

另外粘贴内容和粘贴区域需要严格对应：
 如粘贴从第一列到第五列  但是第四列pasteValueToCell函数返回的false，剪贴板的内容也必须是五列全的内容，也就是剪贴板第四列的内容是无效的
@513655915
