### ISSUE TITLE
[Bug] customMergeCell 样式问题

### ISSUE THREAD

**Issue by tianchao1995** [VisActor/VTable#1065]
### Version

0.19.0

### Link to Minimal Reproduction

表格实例中的自定义合并单元格

### Steps to Reproduce

customMergeCell 的style属性中设置textAlign:"right"，然后拖动列宽变小，自定义合并单元格内的文字就会显示不全
![1707011453022](https://github.com/VisActor/VTable/assets/23371257/515cec83-8114-4cfb-8552-c018d37f528a)

### Current Behavior

宽度足够宽，但文本被截断

### Expected Behavior

文本能正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed by [0.19.1](https://www.npmjs.com/package/@visactor/vtable/v/0.19.1)
