### ISSUE TITLE
[Question] 表格Tooltip支持自定义Dom元素么

### ISSUE THREAD

**Issue by happypayne** [VisActor/VTable#1066]
当前Tooltip支持纯文本类型的内容，可以支持html标签么

**Comment by fangsmile** [comment]
https://visactor.bytedance.net/vtable/demo/component/tooltip_custom_content
这个是纯自定义的

https://visactor.bytedance.net/vtable/demo/component/tooltip 这个是调用的接口

**Comment by oliver34** [comment]
> https://visactor.bytedance.net/vtable/demo/component/tooltip_custom_content 这个是纯自定义的
> 
> https://visactor.bytedance.net/vtable/demo/component/tooltip 这个是调用的接口

链接无法打开
