### ISSUE TITLE
mouseenter_cell事件可以区分具体hover了单元格中的哪个元素吗

### ISSUE THREAD

**Issue by happypayne** [VisActor/VTable#1067]
使用customLayout自定义单元格内容，包括Text，Image等，希望hover到Image的时候，有一些自定义逻辑，目前鼠标进入单元格事件，区分不了具体的target，click事件是可以区分的

**Comment by Rui-Sun** [comment]
这种情况应该使用mousemove_cell吧，mouseenter_cell只在鼠标越过单元格边界线触发一次

**Comment by happypayne** [comment]
> 这种情况应该使用mousemove_cell吧，mouseenter_cell只在鼠标越过单元格边界线触发一次

如果用mousemove_cell，事件触发太频繁了吧。

我在customLayout中，用下面这种方式自定义了一个图片，
```
const icon = new CustomLayout.Image({
        width: 15,
        height: 15,
        cursor: 'pointer',
        pickable: true,
        image: 'xxx'
 });
```

效果如图所示:
<img width="168" alt="image" src="https://github.com/VisActor/VTable/assets/17510040/42be2075-6e44-4876-b0bb-d121eace5ed2">

对于JavaScript中的DOM元素来说，mouseenter事件只在鼠标指针进入（移动到）元素上时触发一次。想请教一下，有没有类似mouseenter_cell这种事件，来监听自定义单元格中指定内容呢？

**Comment by Rui-Sun** [comment]
![image](https://github.com/VisActor/VTable/assets/25134429/2f2e040a-58f5-440c-bd24-4f6e1d6b5402)
可以在自定义布局的图元上绑定 pointerenter 和 pointerleave 事件

**Comment by fangsmile** [comment]
@happypayne 如果已经解决的话 我先关闭issue了 如果有问题可以再提
