### ISSUE TITLE
[Feature] 单元格希望支持只允许选中单个单元格，不需要拖拽选中多个单元格

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1068]
### What problem does this feature solve?

目前点击点击单元格会选中单元格，但是不希望拖拽选选中多个单元格，希望能够支持通过配置项设置满足多选和单选的需求

### What does the proposed API look like?

select: {
  disableMultipleSelect: true
}

**Comment by linkviv** [comment]
同样有这个需求，希望能够通过配置，禁用列头框选，禁用单元格框选。

**Comment by fangsmile** [comment]
https://github.com/VisActor/VTable/pull/2312
