### ISSUE TITLE
如何创建可交互的tooltip功能

### ISSUE THREAD

**Issue by happypayne** [VisActor/VTable#1083]
官网给出的自定义tooltip示例：
https://visactor.io/vtable/demo/component/tooltip_custom_content
<img width="846" alt="image" src="https://github.com/VisActor/VTable/assets/17510040/03026a1d-0ad9-4dda-a818-faca02ad86db">

鼠标光标无法移动到tooltip内容区域，但是业务场景中tooltip内容区域是可交互的

可以参考一下s2的交互，鼠标光标hover到单元格的时候，在光标位置出现tooltip内容，并且光标可以点击tooltip内容区域

s2示例链接：https://s2.antv.antgroup.com/examples/react-component/tooltip/#custom-show-tooltip

<img width="966" alt="image" src="https://github.com/VisActor/VTable/assets/17510040/03dc7151-d1d9-46e8-b1ae-4734be64dafa">

**Comment by fangsmile** [comment]
这个问题 解决了吗  如果是业务逻辑控制显示隐藏的话  可以通过延迟调用hideTooltip来解决。如果使用VTable的tooltip能力 其中有个配置可以延迟消失  如果鼠标hover到Tooltip上也是可以交互的了
![image](https://github.com/VisActor/VTable/assets/3468473/0527ea08-b849-4da7-954b-c6af2be0e40b)

**Comment by fangsmile** [comment]
问题先关闭了  有问题可以再提issue
