### ISSUE TITLE
The MOUSELEAVE_CELL event was not triggered.

### ISSUE THREAD

**Issue by fuxingjun** [VisActor/VTable#1088]
### What problem does this feature solve?

Currently, the MOUSELEAVE_CELL event does not trigger when the mouse leaves the cells at the edge of the table. Although adding a mouseleave event on the table container can achieve the same effect, I personally think it is better to optimize it.

### What does the proposed API look like?

Trigger the MOUSELEAVE_CELL event when the mouse leaves cells at the edge of the table.

**Comment by fangsmile** [comment]
问题收到 我们后续做下优化
