### ISSUE TITLE
编辑可否支持校验？

### ISSUE THREAD

**Issue by SeeMeJuiner** [VisActor/VTable#1101]
编辑功能是否支持一些校验功能，并且实时提示错误信息？

例如：
1.固定值列表校验
2.正则表达式校验
3.范围校验
4.值种类校验
5.table中的勾稽校验？

**Comment by fangsmile** [comment]
这个可以通过自定义编辑器来实现哦 （https://visactor.io/vtable/guide/edit/edit_cell），并且实现后通用的话 可以贡献到我们的开源库中

**Comment by SeeMeJuiner** [comment]
了解了
