### ISSUE TITLE
[Feature] VTable能否新增支持单元格表达式计算？

### ISSUE THREAD

**Issue by SeeMeJuiner** [VisActor/VTable#1109]
### What problem does this feature solve?

单元格新增表达式计算，类似于Excel中的公式和函数，并且实现自动计算；
例如：
1.单元格$C$4=($1$4+$2$5)/$3$4
2.单元格$M$5=SUM($M$1:$M$4)

### What does the proposed API look like?

Cell新增formula支持，并且引入Excel常用的函数

**Comment by fangsmile** [comment]
收到  这个需求建议上层业务方自己来实现哈
