### ISSUE TITLE
[Bug] cellType为函数和字符串时，样式表现不一致

### ISSUE THREAD

**Issue by tianchao1995** [VisActor/VTable#1119]
### Version

0.19.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/celltype-v94sl3?file=%2Fsrc%2Findex.ts%3A22%2C23

### Steps to Reproduce

1.cellType 为函数时，动态返回类型，autoWrapText为true，文本不换行
2.cellType为字符串时，autoWrapText为true，文本换行

### Current Behavior

1.cellType 为函数时，动态返回类型，autoWrapText为true，文本不换行
2.cellType为字符串时，autoWrapText为true，文本换行

### Expected Behavior

cellType为函数时和字符串样式表现一致

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到

**Comment by fangsmile** [comment]
0.20.0 修复掉该问题
