### ISSUE TITLE
[Feature] 增加配置项 可以限定滚动触发只有鼠标落在表格内时才有响应

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1134]
### Version

0.19.1

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/performance/100W

### Steps to Reproduce

<img width="1288" alt="image" src="https://github.com/VisActor/VTable/assets/158560738/3f6a77f4-218b-43f2-9d19-3998531cf14b">

1. 减少到至只有两列
2. 鼠标移动至红色空白区域
3. 滚动鼠标滚轮会触发表格滚动

### Current Behavior

超出内容范围滚动也会触发表格滚动

### Expected Behavior

期望表格内容区域外不触发表格的滚动

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
eventOptions:{
scrollResponseInTable: true
}
0.21.0发布该功能
