### ISSUE TITLE
[Feature] 缓存listTable树列表的展开/收起状态

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1148]
### What problem does this feature solve?

树列表手动展开或收起后，修改listTable的records，table重新渲染导致展示/收起的状态被重置

### What does the proposed API look like?

暂无

**Comment by fangsmile** [comment]
不太好找到通用的解决方案，可以先hack解决下（可以关注后续支持数据分组的功能后这个问题是怎么处理）
![img_v3_028g_61930f54-3123-41fd-9e90-ce3e520c0b7g](https://github.com/VisActor/VTable/assets/3468473/7e04211c-3589-4c33-b1c9-6514c5631227)
