### ISSUE TITLE
[Bug] columns数量超过59条展示文本错误

### ISSUE THREAD

**Issue by qiyintian** [VisActor/VTable#1155]
### Version

0.19.1

### Link to Minimal Reproduction

如下代码即可

### Steps to Reproduce

自定义列维度树后，当一级列维度枚举值超过60条，展示文案错误

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/161022597/bf92f263-d21b-413f-8bd7-68534feb1fea)

### Expected Behavior

正常展示文本内容

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed in [0.21.1](https://www.npmjs.com/package/@visactor/vtable/v/0.21.1)
