### ISSUE TITLE
[Feature] 透视表表格内容支持渲染自定义图片

### ISSUE THREAD

**Issue by fanlz** [VisActor/VTable#1159]
### What problem does this feature solve?

<img width="213" alt="image" src="https://github.com/VisActor/VTable/assets/6118579/c6ecb4eb-9fae-4cbc-bf8f-7f310a05b744">

### What does the proposed API look like?

```
{
  "dimensionKey": "xxx",
  "dimensionTitle": "xxx",
  "width": "auto",
  "showSort": false,
  "headerIcon": {
    xxx
  }
}
```

**Comment by fangsmile** [comment]
目前是支持的吧  可以看看 有问题可以在提或者加飞书群提问
![image](https://github.com/VisActor/VTable/assets/3468473/3e785112-fb5c-47e7-8653-5ce4c8df2937)
