### ISSUE TITLE
[Feature] checkbox支持修改背景色

### ISSUE THREAD

**Issue by liuboying1119** [VisActor/VTable#1161]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/134760419/d86aed88-9fed-4db5-bd0a-04b183dc2c5c)
如图，希望修改checkbox的背景色

### What does the proposed API look like?

bgColor

**Comment by fangsmile** [comment]
边线和背景色都支持上吧

**Comment by fangsmile** [comment]
0.20.3 已发版
