### ISSUE TITLE
能否全局配置 样式 

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#1165]
### What problem does this feature solve?

希望能全局配置 样式 就不用在每个页面都配一遍，能否支持个配置的方法，在main.js 入口配置 覆盖默认的样式 这样就不用每个页面都配一遍 后续升级的时候直接改 不用改全部页面

### What does the proposed API look like?

有个方法能先覆盖默认的样式

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/theme/register  注册主题可以

**Comment by TryChai** [comment]
注册主题会不会 丢失原来的样式 ，比如我只想改部分的 其他的地方我并不想改 如果注册主题是不是要全部都写一遍 这样的话就不太实用
