### ISSUE TITLE
[Bug] 横向滚动条拖拽到最后的位置，使用updateColumns新增加一列，表格渲染不全

### ISSUE THREAD

**Issue by user920123** [VisActor/VTable#1171]
### Version

0.19.0

### Link to Minimal Reproduction

tableInstance.updateColumns

### Steps to Reproduce

1.横向滚动条拖拽到最后的位置
2.使用updateColumns新增加一列,新增列的格子没有渲染出来，只多出了空白区域
3. 横向滚动条不拖拽到最后的位置，进行上述的新增列操作，则渲染的没问题

### Current Behavior

https://github.com/user920123/vtable-/blob/main/index2.vue

### Expected Behavior

在最末端新增一列时，表格能够正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
图片没有上传完

**Comment by user920123** [comment]
> 图片没有上传完

<img width="543" alt="image" src="https://github.com/VisActor/VTable/assets/157792169/d134b52b-3470-4680-99be-5cf590e9927e">

**Comment by user920123** [comment]
> 图片没有上传完

<img width="557" alt="Snipaste_2024-02-29_18-29-24" src="https://github.com/VisActor/VTable/assets/157792169/1175a899-fe8f-4993-b111-26d90f9d3991">

**Comment by fangsmile** [comment]
![20240301-120846](https://github.com/VisActor/VTable/assets/3468473/182251f1-966a-49a6-b440-f82c19f9d810)
可以把你的demo给到我们吗 或者建一个codesanbox 我这块没有复现呢
加飞书群进一步沟通吧

![飞书20240301-121041](https://github.com/VisActor/VTable/assets/3468473/e831b217-c415-4fb3-b398-b98db3c6295e)

**Comment by user920123** [comment]
请看这里  https://github.com/user920123/vtable-/blob/main/index2.vue

**Comment by user920123** [comment]
请看这里 https://github.com/user920123/vtable-/blob/main/index2.vue

**Comment by fangsmile** [comment]
ok 可以复现
