### ISSUE TITLE
[Bug] 树列表的合并行文字被截断

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1177]
### Version

0.20.0

### Link to Minimal Reproduction

暂无

### Steps to Reproduce

https://github.com/VisActor/VTable/assets/158560738/a06d0120-d6b2-49b9-b785-f27665a5e2b8
1. 创建一个树的分组列表
2. 连续点击 展开/收起图标
3. 合并行文字被截断

### Current Behavior

文字被截断

### Expected Behavior

期望正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed in [0.21.1](https://www.npmjs.com/package/@visactor/vtable/v/0.21.1)
