### ISSUE TITLE
[Feature] low level of cpu consume

### ISSUE THREAD

**Issue by ayizhi** [VisActor/VTable#1188]
### What problem does this feature solve?

Vtable has a nice fluency performance by our experience, but it takes too much cpu consuming, our application scenarios is update our data every 1s, we used vue virtual table with <10% cpu consuming but not that smooth like vtable, but after we spending many of time change for vtable, we find vtable takes average 80% cpu consuming, almost on rendering(about 1k rows data). 

Hope your awesome team makes some update about this issue.

![Screenshot 2024-03-01 at 18 18 02](https://github.com/VisActor/VTable/assets/14844688/9ec9814e-b740-46d2-bf2f-358e8c3aa522)

### What does the proposed API look like?

maybe do some diff before rendering.

we accept mark key on row data, if only the cpu consuming lower to normal level

**Comment by fangsmile** [comment]
收到
