### ISSUE TITLE
[Bug] CustomLayout.Text 计算文本包含“=”时，宽度计算有误

### ISSUE THREAD

**Issue by th-wu** [VisActor/VTable#1196]
### Version

0.18.4

### Link to Minimal Reproduction

暂无

### Steps to Reproduce

<img width="1347" alt="image" src="https://github.com/VisActor/VTable/assets/29245385/90fc6719-552c-4836-9b95-493228f81397">
https://www.visactor.io/vtable/demo/custom-render/custom-cell-layout
在该实例第122行修改为 text:record.bloggerName === 'Virtual Anchor Xiaohua' ? '==============' : record.bloggerName 即可重现

### Current Behavior

含有 ”=“ 字符时，宽度展示不正常

### Expected Behavior

期望正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed in [0.21.1](https://www.npmjs.com/package/@visactor/vtable/v/0.21.1)

**Comment by slipperpeng** [comment]
> fixed in [0.21.1](https://www.npmjs.com/package/@visactor/vtable/v/0.21.1)
如果是字符里面含有 — 符号，也会导致宽度计算有问题
