### ISSUE TITLE
[Bug] 冻结列，frozenColCount === allowFrozenColCount时，没有冻结效果（官方示例可复现）

### ISSUE THREAD

**Issue by oooah** [VisActor/VTable#1200]
### Version

0.20.0

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/basic-functionality/frozen-col

### Steps to Reproduce

当frozenColCount === allowFrozenColCount时，冻结列失效，
示例如下图：
![20240304145154](https://github.com/VisActor/VTable/assets/16513587/3772e7d6-8797-4090-b484-29981fbaf833)

### Current Behavior

nothing

### Expected Behavior

nothing

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
我们内部的优化  当左侧冻结区域过大的时候 会将冻结区域和body区域 一起滚动，否则冻结区域过大 body太窄的话 影响数据查看。
