### ISSUE TITLE
树形结构动态添加子节点后，点击父节点伸缩/展开图标，数据显示有问题

### ISSUE THREAD

**Issue by lin199303** [VisActor/VTable#1219]
![7b5834d5-3acd-4b6d-884b-f37d123b46e7](https://github.com/VisActor/VTable/assets/41189066/a90285bb-b918-4e5b-9fd6-0386b341b21d)

_this.tableInstance = await _this.$VTable.listTable(document.getElementById('treeTable'), _this.treeTalbeOption)
      _this.tableInstance.on('icon_click', (args) => {
        const { col, row, name } = args
        if (name === 'delete') {
          const recordIndex = _this.tableInstance.getRecordShowIndexByCell(args.col, args.row)
          _this.tableInstance.deleteRecords([recordIndex])
          // 需要更新option，否则无法显示伸缩展开按钮
          // _this.tableInstance.updateOption(_this.treeTalbeOption)
        } else if (name === 'add') {
          const childrenRecord = [{ xh: '', content: '', type: '', scale: '', unit: '', price: '', invest: '', remark: '', isEdit: true }]
          _this.tableInstance.setRecordChildren(childrenRecord, args.col, args.row)
          // 需要更新option，否则无法显示伸缩展开按钮
          _this.tableInstance.updateOption(_this.treeTalbeOption)
        }
      })``

**Comment by fangsmile** [comment]
![飞书20240306-140304](https://github.com/VisActor/VTable/assets/3468473/0c814698-e3ec-44e6-8b40-b259fbe32634)
加群沟通吧  具体了解下你的用法 看代码使用上好像有点问题  @lin199303
