### ISSUE TITLE
[Bug] 合并单元格合并错误

### ISSUE THREAD

**Issue by tianchao1995** [VisActor/VTable#1223]
### Version

0.20.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/mergecell-fnf9ht?file=%2Fsrc%2Findex.ts%3A76%2C3-76%2C13

### Steps to Reproduce

请看案例代码，添加分页信息和不添加时的效果

### Current Behavior

合并单元格将聚合结果的那一行也给合并了，显示错误

### Expected Behavior

能正确合并单元格

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/d5abdd07-dac4-4c30-8644-233290642c91)
codescodesanbox的链接 share时需要变成public  否则访问不了 @tianchao1995 
可以加飞书群及时沟通

**Comment by tianchao1995** [comment]
好了，改为public了 @fangsmile
