### ISSUE TITLE
[Feature] 能否支持多维表(PivotTable)的指标横向排列？多个行列维度和指标时转一维表配置不方便

### ISSUE THREAD

**Issue by Huangjiahui2233** [VisActor/VTable#1228]
### What problem does this feature solve?

一些分析同学和老板喜欢看横向指标排列的，虽然对行列维度转换一下都可以支持到特定维度的数据对比，但是展示方式都是以列的方式排列，有些需求强制要求用横向的查看，手动转一维表去做很难搞，要做不特定层数的columns，一个个嵌套下来要疯了，希望可以加一个配置项能够支持横向展示

### What does the proposed API look like?

无

**Comment by fangsmile** [comment]
能否截图来具体描述下需求？ 文字没有特别明白

**Comment by Huangjiahui2233** [comment]
> 能否截图来具体描述下需求？ 文字没有特别明白

抱歉表述的不太明白。
这个是默认状态下的多维表，做数据条的时候都是纵向去显示同一个指标
![image](https://github.com/VisActor/VTable/assets/64945423/c23c39a5-f959-43e9-9f86-42c36b9b5767)

原始数据是这个结构
![image](https://github.com/VisActor/VTable/assets/64945423/506b0257-ab3d-4714-91f0-84bdf621c9e9)

业务方有需求做成这样的多维表
![image](https://github.com/VisActor/VTable/assets/64945423/98056764-4a46-4a01-b3e8-1811722685b1)

将数据修改成了这个结构
![image](https://github.com/VisActor/VTable/assets/64945423/4957c8e4-a0a6-49ce-8817-945f14b6a9d2)

如果改成这个结构，本质上第二个表依然是个多维表，我将value作为指标，将其隐藏了而已，但这样的话就无法做图一中的数据条了，因为指标是纵向排列的。
奈何他们就是想横着看，实在没招。
而如果我将数据做成一个一维表，虽然可以实现，但是左侧的行维度 就需要根据数据去动态的配置计算了，而ListTable下columns一层一层套下去会很复杂。我们这个功能并不是针对一些固定的表，都是有人负责去配置的，所以他行列维度的数量不一定就只有这两个，也不一定就是国家地区这些固定的字段，维度数量多的情况下，转成一个一维表去做太复杂了。
不清楚这样解释大佬能否理解
我看了下文档，目前好像没有PivotTable去转制这样的一个配置项。

**Comment by Huangjiahui2233** [comment]
顺便一提：
![image](https://github.com/VisActor/VTable/assets/64945423/e4724be6-ef36-49d7-89b3-d8a3de0dec58)

这里 日期类型 这个字段的颜色我们产品是需要支持自定义的，但是多维表的情况下，rows和columns的headerStyle只针对日期类型的值去设置，对维度的单元格本身做颜色的话，corner的headerStyle设置又是对整个角头生效，无法对单个进行配置，于是我用了customMergeCell配置项将其假合并了一下再读取它的style去配上去，但是因为是随时配置随时生效的，updateOption的api是个函数无法动态获取页面组件内部最新的配置数据，于是又要销毁实例重新加载，虽然是能用了，但是整个用起来还是很折腾的，所以也希望支持一下在row和columns的配置中，支持一个对其本身单元格的一个样式配置项

**Comment by fangsmile** [comment]
抱歉 我们文档有缺失
```
indicatorsAsCol：指标是否作为列表头展示，默认为true
```
我看你是想要这个效果吧，指标默认显示在列表头 以列为方向展示一个指标的数据 ，配置indicatorsAsCol为false写话 就是以行展示指标了。配置和数据都不用变  只配置这个为false即可  @Huangjiahui2233

**Comment by fangsmile** [comment]
上面你提到的样式的话 style都是支持函数的 color单个配置也是支持函数的 可以配置成函数来区分返回值设置不同颜色

**Comment by Huangjiahui2233** [comment]
> 抱歉 我们文档有缺失
> 
> ```
> indicatorsAsCol：指标是否作为列表头展示，默认为true
> ```
> 
> 我看你是想要这个效果吧，指标默认显示在列表头 以列为方向展示一个指标的数据 ，配置indicatorsAsCol为false写话 就是以行展示指标了。配置和数据都不用变 只配置这个为false即可 @Huangjiahui2233

原来有配置项啊，好的好的，我查看ts源文件的时候只注意看文档中已有的配置项，没注意还有到这个，并且在你们的实例文档中也没有看到有引用的例子，所以还以为你们不支持，谢谢哈

**Comment by fangsmile** [comment]
教程会今天更新下哈
