### ISSUE TITLE
[Feature] 文字 fixed 位置, 跟随滚动条

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#1235]
current:

![Image](https://github.com/VisActor/VTable/assets/49136199/eebca1d0-6e26-429e-a89c-f03db5f4e441)

expected:
![Image](https://github.com/VisActor/VTable/assets/49136199/81514bb7-efcf-4efc-a571-127a5d74a3df)

**Comment by Rui-Sun** [comment]
fixed in [0.21.0-alpha.0](https://www.npmjs.com/package/@visactor/vtable/v/0.21.0-alpha.0)
