### ISSUE TITLE
VTable和@antv/s2的区别

### ISSUE THREAD

**Issue by guojb824** [VisActor/VTable#1237]
@antv/s2 也有多维表格的功能，想咨询一下vtable和@antv/s2在功能定位和特性差异等方面的区别

 @antv/s2 官网：
https://s2.antv.antgroup.com/

**Comment by fangsmile** [comment]
![飞书20240310-095232](https://github.com/VisActor/VTable/assets/3468473/c95b1b8c-cc13-4199-accb-be866eccc2e2)
可以加群具体交流你那边的场景，s2目前能力vtable都是支持的。具体看你需求场景
