### ISSUE TITLE
[Feature] 新增ListTable虚拟列数加载数量的设置

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1255]
### What problem does this feature solve?

jsx自定义表格中，列表较多的表格相比于列数较少的表格,卡顿感更明显，希望能通过配置项设置实际加载的列数

### What does the proposed API look like?

暂无

**Comment by fangsmile** [comment]
可以使用最新版 现在应该性能都优化好了。有问题可以再提哈
