### ISSUE TITLE
[Feature] 希望支持多维表指标自定义分组

### ISSUE THREAD

**Issue by Huangjiahui2233** [VisActor/VTable#1256]
### What problem does this feature solve?

指标过多时可以自定义指标的分组，能够解决不同人查看同一个图表时能够迅速着重关心自己需要查看的数据。
类似ListTable中columns嵌套columns的效果

### What does the proposed API look like?

![image](https://github.com/VisActor/VTable/assets/64945423/69d327a7-15f0-4e9b-805d-9a3b7282e493)

_图中仅为测试数据_

分别将前两个指标和后两个指标分组为A类B类，指标在行时左侧新增一列显示分组，指标在列时上方新增一行显示分组。
和ListTable中columns相似的配置成这样应该就可以
```TypeScript
const option = {
  indicator: [{
    title: 'A类',
    indicator: [{
      title: '达标首单商户数',
      indicatorKey: 'test1'
    },{
      title: '达标首单商户数占比',
      indicatorKey: 'test2'
    }]
  },{
    title: 'B类',
    indicator: [{
      title: '目标首单商户数',
      indicatorKey: 'test3'
    },{
      title: '目标首单商户数占比',
      indicatorKey: 'test4'
    }]
  }]
}
```

**Comment by Huangjiahui2233** [comment]
代码中的配置和图里画的不一致，领会意思就好

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/1b97285d-fb4c-445f-aadd-5f354895bdc4)
目前是可以自定义的
https://workspace-ws7ff8843a58ad4e8aba91c12c1e32f61c-http-5173.ide.byted.org/vtable/guide/table_type/Pivot_table/pivot_table_dataAnalysis
![image](https://github.com/VisActor/VTable/assets/3468473/607c0678-c1d2-4471-a889-7dada28cde6b)

**Comment by Huangjiahui2233** [comment]
> ![image](https://private-user-images.githubusercontent.com/3468473/311916862-1b97285d-fb4c-445f-aadd-5f354895bdc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTQ2MTIsIm5iZiI6MTcxMDIxNDMxMiwicGF0aCI6Ii8zNDY4NDczLzMxMTkxNjg2Mi0xYjk3Mjg1ZC1mYjRjLTQ0NWYtYWFkZC01ZjM1NDg5NWJkYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDMzMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkxY2Q1NDk1ZWUwZDIxMDUyY2EyNTI5NzkyY2QxOTQ2ZjBiZGQyNDI3OGMzZjZjODQ1ODllY2Q3NTFlNWI0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T17R-LeHtGVKO1Hwl_AFGCBbIpsZBPFePK9ecOXnK8o) 目前是可以自定义的 https://workspace-ws7ff8843a58ad4e8aba91c12c1e32f61c-http-5173.ide.byted.org/vtable/guide/table_type/Pivot_table/pivot_table_dataAnalysis ![image](https://private-user-images.githubusercontent.com/3468473/311917147-607c0678-c1d2-4471-a889-7dada28cde6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTQ2MTIsIm5iZiI6MTcxMDIxNDMxMiwicGF0aCI6Ii8zNDY4NDczLzMxMTkxNzE0Ny02MDdjMDY3OC1jMWQyLTQ0NzEtYTg4OS03ZGFkYTI4Y2RlNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDMzMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA2Y2NmOWRkZjZhNWNkZGMwZGIzOGUxMzQ0MWU0ZTZhYTAzNjJlMjY5N2NjNmI4YzM5MjcyMzExMWM1ZTVjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gtG-7bdu5GXQO8wisK694emqT383fUCWn_hycD8_bQ4)

好像和需求不太一致，这个是对维度进行自定义，而我这边想实现的是对指标进行分组自定义

**Comment by Huangjiahui2233** [comment]
我看了下文档，好想和需求不太一样，这个是对维度进行自定义，我这边需要实现的是对指标进行分组自定义

**Comment by fangsmile** [comment]
维度和指标都包括了  整个树自定义   可以实现你的需求。你提的这个配置方式有些定制，最近也没有时间安排开发， 所以想要解决的话 可以用完整自定义的方式来做

**Comment by Huangjiahui2233** [comment]
> 维度和指标都包括了 整个树自定义 可以实现你的需求。你提的这个配置方式有些定制，最近也没有时间安排开发， 所以想要解决的话 可以用完整自定义的方式来做

好的，谢谢

**Comment by mzc9915** [comment]
> 用完整自定义的

这个需求感觉还是比较常见的。在目前的文档中，vtable.options.groupBy配置只支持传入字符串；但有些时候，分组字段可能不是字符串，是对象或者其他；这时候按照目前的方式就没法将具有相同的信息分在一组了。 是否可以支持groupBy也可以是一个自定义函数？由用户自己决定分组的逻辑
