### ISSUE TITLE
在packages\vtable下 rushx build报错: Cannot find module '../output/bootstrap'是少了什么步骤呢？ rushx demo成功启动了

### ISSUE THREAD

**Issue by ChenBin12138** [VisActor/VTable#1260]
![image](https://github.com/VisActor/VTable/assets/33656314/0ad10991-4d7e-40dc-a19d-4549d63a3439)

![1710213110004](https://github.com/VisActor/VTable/assets/33656314/3113c4d8-4975-4122-804f-373423d1d27e)

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/2f4001d3-d5fc-4069-96cd-2813e859b305)
就只是这些哈

**Comment by ChenBin12138** [comment]
我的nodejs 版本是16.18.0 你们开发的版本是多少呢， 我换一下试试

**Comment by fangsmile** [comment]
我是16.20  应该差不多

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/86c394e0-d0a9-4b46-84da-019c579ef343)
rush update 之后 这些都有了

**Comment by ChenBin12138** [comment]
找到原因了，你们开发不是window系统吧？
tools\bundler package.json

![image](https://github.com/VisActor/VTable/assets/33656314/6c7fde94-7ef1-4889-82d3-4c781aadcc4a)


`    "build": "rm -rf ./output && tsc --project ./tsconfig.json",`
替换成下面就可以了
`    "build": "tsc --project ./tsconfig.json",`

**Comment by xuanhun** [comment]
> 找到原因了，你们开发不是window系统吧？ tools\bundler package.json
> 
> ![image](https://private-user-images.githubusercontent.com/33656314/311933936-6c7fde94-7ef1-4889-82d3-4c781aadcc4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTgwODUsIm5iZiI6MTcxMDIxNzc4NSwicGF0aCI6Ii8zMzY1NjMxNC8zMTE5MzM5MzYtNmM3ZmRlOTQtN2VmMS00ODg5LTgyZDMtNGM3ODFhYWRjYzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkN2EyZThmNDE1Y2VmNjVhNTIwNjQwNzBkODcyNmQ5ZDZkOTAwNDcwNWUxODViZTRlNTc0ZWVjYzQ2ZDU4YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BjAsGmoYe8mMT66KsW7O80Otg02EMIXeBi-SzWxgTRg)
> 
> ` "build": "rm -rf ./output && tsc --project ./tsconfig.json",` 替换成下面就可以了 ` "build": "tsc --project ./tsconfig.json",`

@xile611 这个统一看一下吧，每个项目都需要兼容一下 Windows

**Comment by fangsmile** [comment]
![飞书20240313-105944](https://github.com/VisActor/VTable/assets/3468473/0575d6f4-a1cb-42a4-9cc7-ba2ba28a299d)
可以加下飞书群找我验证下吧 @ChenBin12138

**Comment by xile611** [comment]
> > 找到原因了，你们开发不是window系统吧？ tools\bundler package.json
> > ![image](https://private-user-images.githubusercontent.com/33656314/311933936-6c7fde94-7ef1-4889-82d3-4c781aadcc4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTgwODUsIm5iZiI6MTcxMDIxNzc4NSwicGF0aCI6Ii8zMzY1NjMxNC8zMTE5MzM5MzYtNmM3ZmRlOTQtN2VmMS00ODg5LTgyZDMtNGM3ODFhYWRjYzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkN2EyZThmNDE1Y2VmNjVhNTIwNjQwNzBkODcyNmQ5ZDZkOTAwNDcwNWUxODViZTRlNTc0ZWVjYzQ2ZDU4YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BjAsGmoYe8mMT66KsW7O80Otg02EMIXeBi-SzWxgTRg)
> > ` "build": "rm -rf ./output && tsc --project ./tsconfig.json",` 替换成下面就可以了 ` "build": "tsc --project ./tsconfig.json",`
> 
> @xile611 这个统一看一下吧，每个项目都需要兼容一下 Windows

https://github.com/VisActor/VChart/pull/2377

参考这个PR修改一下
