### ISSUE TITLE
[Bug] 列宽模式设置为'autoWidth'时,使用updateColumns新增加一列，表格渲染不全

### ISSUE THREAD

**Issue by user920123** [VisActor/VTable#1262]
### Version

v0.21.0

### Link to Minimal Reproduction

https://github.com/user920123/vtable-/blob/main/index3.vue

### Steps to Reproduce

1.列宽计算模式设置为'autoWidth'
2.列数多一点（大于30列）单元格为空,表头内容较少(比如只写一个数字，测试发现表头内容多一些时，渲染没有问题)
3.将横向滚动条拖到最末端 再点击此处进行更新 表格渲染异常

### Current Behavior

https://github.com/VisActor/VTable/assets/157792169/8ae32f25-19ff-43d2-a218-b71abec7a72d

### Expected Behavior

表格能够正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
哪个版本？我记得前几天你提过这个吧

**Comment by user920123** [comment]
> 哪个版本？我记得前几天你提过这个吧

v0.21.0 最新发布的版本

**Comment by user920123** [comment]
> 哪个版本？我记得前几天你提过这个吧

使用 v0.19.1 版本的时候，也是同样的现象， 所以提了一个问题 ， 昨天使用v0.21.0版本这个问题还是存在。如果表头内容再多几个字，就会正常渲染了。列宽计算模式不设置'autoWidth' ，直接使用固定列宽也没有这个现象。 救救孩子吧 真的很需要这个功能🙏🙏

**Comment by fangsmile** [comment]
我们今天给你弄好
