### ISSUE TITLE
[Feature] 希望能出一个根据行id或者某个字段高亮一整行的api

### ISSUE THREAD

**Issue by LinQianduan** [VisActor/VTable#1293]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/86899601/a1c17f11-5b3f-4ab5-aa18-ab480355f79b)
目前使用updateTheme Api更新主题实现行高亮效果，但是当数据量多了之后，需要等待很长时间才能响应

![image](https://github.com/VisActor/VTable/assets/86899601/23c75bb6-6829-4588-a18d-f770f933de7e)
两万多条数据的时候 等待了40秒才响应
测试过vtable默认的选中api实现框线，响应也很慢

### What does the proposed API look like?

希望能传入一个List，快速高亮某些行数据，实现行选中行效果

**Comment by Rui-Sun** [comment]
https://www.visactor.io/vtable/guide/custom_define/custom_style

**Comment by LinQianduan** [comment]
目前使用的就是自定义样式，但是数据量很大的情况下会卡很久， 两万条数据全选时候 使用自定义样式等待了40秒才响应

**Comment by fangsmile** [comment]
您好 现在还有这个问题吗 ？ 如果还有这个问题可以加我们的飞书群进行及时的沟通  
![image](https://github.com/VisActor/VTable/assets/3468473/67f6ad9b-dfff-4e87-a38b-33895cc411c1)
