### ISSUE TITLE
[Refactor] Can't see Freeze Icon under Dark Theme 

### ISSUE THREAD

**Issue by RAAMENN** [VisActor/VTable#1308]
### Version

0.21.2

### Link to Minimal Reproduction

any

### Steps to Reproduce

![img_v3_0294_856b50d1-3091-41b1-bda5-2f0d7b251chu](https://github.com/VisActor/VTable/assets/18249275/6c756ac3-ea15-417f-8cdd-249cf41d0db3)

### Current Behavior

Can't see the icon

### Expected Behavior

Can see the icon

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到，后续会对暗黑模式的各个图标专门出一份

**Comment by fangsmile** [comment]
Welcome to build! ICONS can have an internal logic that is selected according to the theme  @RAAMENN

**Comment by fangsmile** [comment]
#2151
