### ISSUE TITLE
[Bug] 透视图表中 chartSpec配置 类型为common时， series中添加了多条线的配置，但是只显示了一条。

### ISSUE THREAD

**Issue by zzsssssss** [VisActor/VTable#1334]
### Version

0.21.1

### Link to Minimal Reproduction

11

### Steps to Reproduce

配置项如下：
`const option = {
	indicatorsAsCol: false,
	records: [
		{
			col_190: "2023-12-17",
			col_191_0: 7,
		},
		{
			col_190: "2023-12-24",
			col_191_0: 6,
		},
		{
			col_190: "2023-12-26",
			col_191_0: 5,
		},
		{
			col_190: "2023-12-14",
			col_191_0: 4,
		},
		{
			col_190: "2023-12-25",
			col_191_0: 3,
		},
		{
			col_190: "2023-12-19",
			col_191_0: 2,
		},
		{
			col_190: "2023-12-17",
			col_191_1: 6.2857,
		},
		{
			col_190: "2023-12-24",
			col_191_1: 5.5714,
		},
		{
			col_190: "2023-12-26",
			col_191_1: 4.8571,
		},
		{
			col_190: "2023-12-14",
			col_191_1: 4.1429,
		},
		{
			col_190: "2023-12-25",
			col_191_1: 3.4286,
		},
		{
			col_190: "2023-12-19",
			col_191_1: 2.7143,
		},
		{
			col_190: "2023-12-17",
			col_191_2: 8.0476,
		},
		{
			col_190: "2023-12-24",
			col_191_2: 6.3619,
		},
		{
			col_190: "2023-12-26",
			col_191_2: 4.6762,
		},
		{
			col_190: "2023-12-14",
			col_191_2: 2.9905,
		},
		{
			col_190: "2023-12-25",
			col_191_2: 1.3048,
		},
		{
			col_190: "2023-12-19",
			col_191_2: -0.381,
		},
		{
			col_190: "2023-12-17",
			col_207_0: 2181.7781,
		},
		{
			col_190: "2023-12-24",
			col_207_0: 1456.7815,
		},
		{
			col_190: "2023-12-26",
			col_207_0: 731.785,
		},
		{
			col_190: "2023-12-14",
			col_207_0: 6.7884,
		},
		{
			col_190: "2023-12-25",
			col_207_0: -718.2082,
		},
		{
			col_190: "2023-12-19",
			col_207_0: -1443.2048,
		},
		{
			col_223: "公司",
			col_191: 11,
			col_190: "2023-12-17",
		},
		{
			col_223: "消费者",
			col_191: 9,
			col_190: "2023-12-24",
		},
		{
			col_223: "小型企业",
			col_191: 11,
			col_190: "2023-12-26",
		},
		{
			col_223: "消费者",
			col_191: 5,
			col_190: "2023-12-26",
		},
		{
			col_223: "小型企业",
			col_191: 3,
			col_190: "2023-12-24",
		},
		{
			col_223: "小型企业",
			col_191: 1,
			col_190: "2023-12-14",
		},
		{
			col_223: "消费者",
			col_191: 12,
			col_190: "2023-12-14",
		},
		{
			col_223: "小型企业",
			col_191: 8,
			col_190: "2023-12-17",
		},
		{
			col_223: "消费者",
			col_191: 1,
			col_190: "2023-12-17",
		},
		{
			col_223: "公司",
			col_191: 6,
			col_190: "2023-12-24",
		},
		{
			col_223: "公司",
			col_191: 3,
			col_190: "2023-12-25",
		},
		{
			col_223: "公司",
			col_191: 1,
			col_190: "2023-12-26",
		},
		{
			col_223: "公司",
			col_191: 6,
			col_190: "2023-12-19",
		},
		{
			col_207: 2687.07,
			col_223: "公司",
			col_190: "2023-12-17",
		},
		{
			col_207: 3534.58,
			col_223: "消费者",
			col_190: "2023-12-24",
		},
		{
			col_207: -3019.44,
			col_223: "小型企业",
			col_190: "2023-12-26",
		},
		{
			col_207: 863.24,
			col_223: "消费者",
			col_190: "2023-12-26",
		},
		{
			col_207: 102.76,
			col_223: "小型企业",
			col_190: "2023-12-24",
		},
		{
			col_207: 26.88,
			col_223: "小型企业",
			col_190: "2023-12-14",
		},
		{
			col_207: -418.96,
			col_223: "消费者",
			col_190: "2023-12-14",
		},
		{
			col_207: 2683.52,
			col_223: "小型企业",
			col_190: "2023-12-17",
		},
		{
			col_207: 23.8,
			col_223: "消费者",
			col_190: "2023-12-17",
		},
		{
			col_207: -3803.55,
			col_223: "公司",
			col_190: "2023-12-24",
		},
		{
			col_207: -519.51,
			col_223: "公司",
			col_190: "2023-12-25",
		},
		{
			col_207: -102.7,
			col_223: "公司",
			col_190: "2023-12-26",
		},
		{
			col_207: 158.03,
			col_223: "公司",
			col_190: "2023-12-19",
		},
	],
	columns: [],
	rows: [],
	indicators: [
		{
			indicatorKey: "col_191",
			title: "数量",
			width: 50,
			cellType: "chart",
			chartModule: "vchart",
			disableHeaderHover: true,
			chartSpec: {
				type: "common",
				series: [
					{
						type: "bar",
						data: {
							id: "col_191",
						},
						bar: {
							state: {
								selected_reverse: {
									fill: "#ddd",
									fillOpacity: 0.2,
								},
							},
							style: {
								cursor: "pointer",
								fill: {
									scale: "col_191",
									field: "col_223",
								},
							},
						},
						barMinWidth: 1,
						barMaxWidth: 30,
						barMinHeight: 1,
						xField: "col_190",
						yField: "col_191",
						axes: [
							{
								orient: "left",
								min: 0,
							},
						],
						tooltip: {
							throttleInterval: 10,
							mark: {
								content: [{}, {}, {}],
							},
							dimension: {
								content: [{}],
							},
							style: {
								titleLabel: {
									textAlign: "left",
									fontSize: 14,
								},
								keyLabel: {
									textAlign: "left",
									fontSize: 12,
								},
								valueLabel: {
									textAlign: "left",
									fontSize: 12,
								},
							},
						},
						seriesField: "col_223",
					},
					{
						type: "line",
						data: {
							id: "col_191_0",
						},
						xField: "col_190",
						yField: "col_191_0",
						line: {
							visible: true,
							style: {
								curveType: "linear",
								stroke: "#ccc",
								lineDash: [5],
								lineWidth: 2,
							},
						},
						point: {
							visible: false,
						},
						tooltip: {
							visible: true,
							mark: {
								content: {
									key: "[数量]",
									value: "= dfdfdgggf",
								},
							},
						},
					},
					{
						type: "line",
						data: {
							id: "col_191_1",
						},
						xField: "col_190",
						yField: "col_191_1",
						line: {
							visible: true,
							style: {
								curveType: "linear",
								stroke: "#ccc",
								lineDash: [5],
								lineWidth: 2,
							},
						},
						point: {
							visible: false,
						},
					},
					{
						type: "line",
						data: {
							id: "col_191_2",
						},
						xField: "col_190",
						yField: "col_191_2",
						line: {
							visible: true,
							style: {
								curveType: "linear",
								stroke: "#ccc",
								lineDash: [5],
								lineWidth: 2,
							},
						},
						point: {
							visible: false,
						},
					},
				],
				color: {
					type: "ordinal",
					range: ["#1763FF"],
				},
				label: {
					visible: false,
				},
				scales: [
					{
						id: "col_191",
						type: "ordinal",
						range: ["#72ccff", "#76f2f2", "#d2f5a6"],
					},
				],
			},
			style: {
				padding: 1,
			},
		},
		{
			indicatorKey: "col_207",
			title: "利润",
			width: 50,
			cellType: "chart",
			chartModule: "vchart",
			disableHeaderHover: true,
			chartSpec: {
				type: "common",
				series: [
					{
						type: "bar",
						data: {
							id: "col_207",
						},
						bar: {
							state: {
								selected_reverse: {
									fill: "#ddd",
									fillOpacity: 0.2,
								},
							},
							style: {
								cursor: "pointer",
							},
						},
						barMinWidth: 1,
						barMaxWidth: 30,
						barMinHeight: 1,
						xField: "col_190",
						yField: "col_207",
						axes: [
							{
								orient: "left",
								min: -4000,
							},
						],
						tooltip: {
							throttleInterval: 10,
							mark: {
								content: [{}, {}, {}],
							},
							dimension: {
								content: [{}],
							},
							style: {
								titleLabel: {
									textAlign: "left",
									fontSize: 14,
								},
								keyLabel: {
									textAlign: "left",
									fontSize: 12,
								},
								valueLabel: {
									textAlign: "left",
									fontSize: 12,
								},
							},
						},
						seriesField: "col_223",
						label: {
							visible: true,
							position: "outside",
							style: {
								fill: "#909090",
								fontSize: 14,
								fontFamily: "微软雅黑",
								fontWeight: "400",
							},
						},
					},
					{
						type: "line",
						data: {
							id: "col_207_0",
						},
						xField: "col_190",
						yField: "col_207_0",
						line: {
							visible: true,
							style: {
								curveType: "linear",
								stroke: "#ccc",
								lineDash: [5],
								lineWidth: 2,
							},
						},
						point: {
							visible: false,
						},
						tooltip: {
							visible: true,
							mark: {
								content: {
									key: "[数量]",
									value: "= dfdfdgggf",
								},
							},
						},
					},
				],
				color: {
					type: "ordinal",
					range: ["#1763FF"],
				},
				label: {
					visible: false,
				},
				scales: [
					{
						id: "col_207",
						type: "ordinal",
						range: ["#1763FF"],
					},
				],
			},
			style: {
				padding: 1,
			},
		},
	],
	corner: {
		titleOnDimension: "row",
		disableHeaderHover: true,
	},
	widthMode: "autoWidth",
	heightMode: "autoHeight",
	defaultRowHeight: 200,
	defaultHeaderRowHeight: 50,
	defaultColWidth: 280,
	defaultHeaderColWidth: 120,
	autoFillWidth: true,
	autoFillHeight: true,
};`

### Current Behavior

只绘制出了一条数据线。

### Expected Behavior

可以绘制多条线

### Environment

```markdown
- OS: Windows
- Browser:chrome
- Framework: Vue@3
```

### Any additional comments?

我这边测了一下就是 records配置这边数据导致的问题。

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/73b43241-7959-460f-8993-e930769cc8c3)
绘制没有问题 ！
你设置进去的数据不同系列但是趋势完全一样 可以设置不同线不同颜色 或者把数据改一改就看出来了
