### ISSUE TITLE
[Feature] filter rules support tree data

### ISSUE THREAD

**Issue by cuihu** [VisActor/VTable#1365]
### What problem does this feature solve?

filter any data

### What does the proposed API look like?

export interface FilterRule {
  filterKey?: string;
  filteredValues?: unknown[];
  filterFunc?: (row: Record<string, any>) => boolean;
  treeDepth?: number
}

**Comment by fangsmile** [comment]
可验证最新版本

**Comment by fangsmile** [comment]
先关了哈 有问题可以再提
