### ISSUE TITLE
[Feature] CHANGE_CELL_VALUE 事件希望增加原单元格值

### ISSUE THREAD

**Issue by z93919112** [VisActor/VTable#1367]
### What problem does this feature solve?

 希望change_cell_value 可以同时返回修改之前的值， 现在在单元格修改之后做数据校验时，失败的时候没有办法将单元格还原为修改之前的值， 目前参数中rawValue是数据源最原始值

### What does the proposed API look like?

change_cell_value 增加返回单元格修改之前的值

**Comment by z93919112** [comment]
还有就是现在有修改单个单元值的方法吗， 文档里没找着

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/b35b57a4-7207-475f-be34-29152c7aad3b)
@z93919112 目前就是有的呀

**Comment by z93919112** [comment]
![企业微信截图_20240407094103](https://github.com/VisActor/VTable/assets/45417438/077b6856-e097-4ce3-9fee-1ba9a80fab0d)
![企业微信截图_20240407093930](https://github.com/VisActor/VTable/assets/45417438/7ebc6891-6715-46f9-988a-7570e7790cd8)

目前返回的是数据源最原始值，  数据无论修改多少次返回的都是一样的，需要的是在多次修改的时候可以返回修改前单元格的值， 如上图中第二次打印希望返回John1231231

**Comment by fangsmile** [comment]
目前还有个currentValue的参数 可以看看
![image](https://github.com/VisActor/VTable/assets/3468473/20be5590-072b-4d10-946e-036f0e1c8bcc)
