### ISSUE TITLE
[Bug] 使用数据源,删除数据后,引发调用栈爆栈问题;  

### ISSUE THREAD

**Issue by creasy2010** [VisActor/VTable#1385]
### Version

0.19.0~0.22.0

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/performance/async-data

### Steps to Reproduce

1. 删除某行数据,  
2. 等待table重新渲染;
3. console 中出现 爆栈问题;  

大概定位了下, 是因为 listtable在删除数据后,没有更新proxy->highPerformanceGetCell 中cellGroup中的行号; 导致
![image](https://github.com/VisActor/VTable/assets/1592277/6870ec6c-c4c9-4aed-8b75-11d46df88d08)

### Current Behavior

https://github.com/VisActor/VTable/issues/1384

### Expected Behavior

删除行数据后, 及时更新cellGroup中的row标识;; 
列也应该是一样的操作; 

### Environment

```markdown
- OS:macOs
- Browser: chrome
```

**Comment by Rui-Sun** [comment]
0.23.0版本还有问题吗？如果有的话麻烦提供一下复现环境吧，试了一下好像没有复现这个问题
