### ISSUE TITLE
[Bug] ListTable表格中CheckBox复选框在移动端中无法点击选中

### ISSUE THREAD

**Issue by waljl** [VisActor/VTable#1405]
### Version

0.22.3

### Link to Minimal Reproduction

https://visactor.io/vtable/guide/cell_type/checkbox

### Steps to Reproduce

https://visactor.io/vtable/guide/cell_type/checkbox

### Current Behavior

ListTable表格中CheckBox复选框在移动端中无法点击选中

### Expected Behavior

 ListTable表格中CheckBox复选框在移动端中无法点击选中

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed in VRender

**Comment by fangsmile** [comment]
@waljl 可以验证下 有问题的话再提吧
