### ISSUE TITLE
[feature]VTable上隐藏指标+值计算派生指标

### ISSUE THREAD

**Issue by JasonZhuAtamation** [VisActor/VTable#1423]
### What problem does this feature solve?

场景：行维度：大区-地区，列维度：月份，指标：销量、金额、去年销量(隐藏指标)、去年金额(隐藏指标) 销量同比(派生指标)、金额同比(派生指标)
我隐藏的指标不想在页面上看到，但是隐藏的指标又需要参与派生的指标计算

### What does the proposed API look like?

https://applink.feishu.cn/client/message/link/open?token=AmU%2FQqHXB0ADZgpll9ASAAQ%3D

**Comment by fangsmile** [comment]
可以通过计算字段来完成上述需求 在dataConfig中配置calculatedField
