### ISSUE TITLE
jsx组件ts类型定义错误

### ISSUE THREAD

**Issue by ConfidenceNZ** [VisActor/VTable#1443]
![image](https://github.com/VisActor/VTable/assets/158560738/304b16c2-dee7-4008-9591-5c71626e0fff)
所有的jsx组件id和name被设置成了必填
![image](https://github.com/VisActor/VTable/assets/158560738/a5b882f8-0ecd-49be-9e0e-f65cb4aa252b)
所有的jsx组件在attribute中设置id时，报ts错误

**Comment by ConfidenceNZ** [comment]
重现方式，vscode中

**Comment by Rui-Sun** [comment]
VRender已修改，待更新
