### ISSUE TITLE
[Feature] 透视表自定义列头

### ISSUE THREAD

**Issue by xiaochong444** [VisActor/VTable#1454]
### What problem does this feature solve?

最近想把s2替换成vtable，发现s2的自定义行列头的功能，vtable暂时不支持。如下面s2的示例。
https://s2.antv.antgroup.com/examples/layout/custom-header-group/#custom-pivot-col-header
如果透视表只有行，列没有绑定字段。想把如果值很多，想把他们组合成不同的分组。

### What does the proposed API look like?

类似S2这样可以自动义透视表的列

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/table-type/pivot-table
支持自定义表头树形结构  不过行列都需要自定义

**Comment by xiaochong444** [comment]
> https://visactor.io/vtable/demo/table-type/pivot-table 支持自定义表头树形结构 不过行列都需要自定义

所以还是有差异，最好能像s2那样自由度更高，现在用这个我无法实现。并且现在列不绑字段也不行，像s2是只绑行和值，列头都是虚拟的树，这样才能实现我的功能，希望能够支持

**Comment by xiaochong444** [comment]
@fangsmile 后期会考虑增加这个功能吗

**Comment by fangsmile** [comment]
已支持，可以参考虚拟节点用法 https://visactor.io/vtable/demo/table-type/pivot-table-virtual-header
