### ISSUE TITLE
[Bug] 右键菜单点击触发多次 onDropdownMenuClick

### ISSUE THREAD

**Issue by xiaoosnggao** [VisActor/VTable#1458]
### Version

0.23.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/react-vtable-forked-4g4rr2?file=%2Fsrc%2Findex.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7k1yim0006356kgxv6ob8h%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7k1yil0002356kc202jikz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7k1yik0001356ki478393g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clru3yaiz0002356i1z9f10tg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A245%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A245%252C%2522endColumn%2522%253A25%257D%255D%257D%252C%257B%2522id%2522%253A%2522cltcn7mcy00023b6klu1f4dqr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%252C%2522activeTabId%2522%253A%2522clru3yaiz0002356i1z9f10tg%2522%257D%252C%2522clr7k1yil0005356k95l0e6vw%2522%253A%257B%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%252C%2522activeTabId%2522%253A%2522clu7rgw0b003a3b6kkvph4c74%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clu7rgw0b003a3b6kkvph4c74%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr7k1yil0003356k313qrry0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

右键点击菜单

### Current Behavior

触发多次回调 onDropdownMenuClick，如果组件多次重新渲染 触发次数会变多

### Expected Behavior

只触发一次

### Environment

```markdown
- OS:macos
- Browser:chrome
- Framework:react
```

**Comment by fangsmile** [comment]
这里事件触发两次，是由于每次执行useEffect时，handleCheckboxStateChange和handleDropdownMenuClick函数都是新创建的，和之前的函数不全等导致的，可以用useMemo包一下这两个函数就可以了。这里我简单解释一下原理，在settimeout引起的更新中，进行了两次state更新，一次是
![img_v3_029r_c9ae05b9-056d-4663-9a38-9f596ed4cfag](https://github.com/VisActor/VTable/assets/3468473/76780c84-bf22-429c-84c2-d69e8d3f59f1)

一次是
![img_v3_029r_e1f3980a-bdec-420c-8df7-209f666e654g](https://github.com/VisActor/VTable/assets/3468473/eaa1492a-a423-4018-9aa4-d8e4e63d4ecb)

这两次更新分别会引起两次表格的更新，每次表格更新会进行事件对比，避免事件的重复绑定。对比会比较事件类型和回调函数，两者都完全相等才会认为是一个事件监听；如果此时相同事件类型的回调函数不同，会被认为有新的事件监听，加到事件绑定中来，事件触发就会多次调用回调函数。
这里我们补充一下说明文档，重点说明一下事件绑定的注意事项
