### ISSUE TITLE
[Bug] onCheckboxStateChange回调中返回的数据格式问题

### ISSUE THREAD

**Issue by xiaoosnggao** [VisActor/VTable#1468]
### Version

0.23.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/react-vtable-forked-chw8cw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7k1yim0006356kgxv6ob8h%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7k1yil0002356kc202jikz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7k1yik0001356ki478393g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clru3yaiz0002356i1z9f10tg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A452%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A452%252C%2522endColumn%2522%253A7%257D%255D%257D%252C%257B%2522id%2522%253A%2522cltcn7mcy00023b6klu1f4dqr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%252C%2522activeTabId%2522%253A%2522clru3yaiz0002356i1z9f10tg%2522%257D%252C%2522clr7k1yil0005356k95l0e6vw%2522%253A%257B%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%252C%2522activeTabId%2522%253A%2522clus2p0yq00i63b6kk16my1c5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clus2p0yq00i63b6kk16my1c5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr7k1yil0003356k313qrry0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

1.选择一行
2.再选择一行
3.点击全选

### Current Behavior

1.点击选择时回调中只会返回当前点击的一行
2.如果选择了多行，只会返回最后选中的行
3.onCheckboxStateChange 中通过getCheckboxState函数传入不存在的field，返回undefined组成的数组

https://github.com/VisActor/VTable/assets/16183057/0e6405c8-f13f-4880-a2b6-d765a4912e47

### Expected Behavior

1.是否应该返回当前操作行，再额外返回一个被选中的行集合
2.getCheckboxState函数传入不存在的field，是否应该报错或者给出警告提示

### Environment

```markdown
- OS:macos
- Browser:chrome
- Framework:react
```

**Comment by Rui-Sun** [comment]
1. 不确定是不是所有用户都需要获取全部选中的数据，所以事件只返回了当前这次选中信息，如果用户需要获取全部选中信息，需要在事件中自行获取（getCheckboxState(filed)），这样性能比较好
2. getCheckboxState是通过字段数据层面的选中信息，数据层面目前不太好判断该字段是不是真正的列，目前先不做处理，当做全未选中处理，后续我们想到更好的方案再优化

**Comment by xiaoosnggao** [comment]
> 1. 不确定是不是所有用户都需要获取全部选中的数据，所以事件只返回了当前这次选中信息，如果用户需要获取全部选中信息，需要在事件中自行获取（getCheckboxState(filed)），这样性能比较好
> 2. getCheckboxState是通过字段数据层面的选中信息，数据层面目前不太好判断该字段是不是真正的列，目前先不做处理，当做全未选中处理，后续我们想到更好的方案再优化

好的明白
