### ISSUE TITLE
[Feature] 希望支持单击任意单元格就可以选中当前单元格所在行，然后进行拖拽当前行

### ISSUE THREAD

**Issue by 131661** [VisActor/VTable#1485]
### What problem does this feature solve?

1、单击任意单元格就可以选中当前单元格所在行
2、选中所在行后可进行拖拽

### What does the proposed API look like?

目前尝试采用SELECTED_CELL事件监听获取单击的单元格，再使用selectCells方法选中单击单元格所在行，效果不太理想，有延迟。

**Comment by AcWrong02** [comment]
您好，能否额外添加一个配置，不是单击任意单元格就可以选中当前单元格所在行，而是在当前行的最前面的单元格添加一个图标，选中当前行是通过点击图标。

**Comment by fangsmile** [comment]
@131661 现在可以通过行序号的功能来实现你的需求

**Comment by fangsmile** [comment]
如果还有问题可以重新提issue这个我先关了哈
