### ISSUE TITLE
[Feature] 透视表列头和行头支持自定义编辑

### ISSUE THREAD

**Issue by Keithcaiqian** [VisActor/VTable#1492]
### What problem does this feature solve?

目前单元格可以编辑，但是列头和行头加上编辑配置后无反应。

### What does the proposed API look like?

和body单元格一样，且在onStart中可以接收到 1.table实例 2.单元格如果是合并的，可以获取到合并的所有单元格

**Comment by fangsmile** [comment]
最新版本已经支持
