### ISSUE TITLE
[Feature] 希望事件回调信息中有与该单元格相关的所有合并的单元格信息

### ISSUE THREAD

**Issue by Keithcaiqian** [VisActor/VTable#1496]
### What problem does this feature solve?

在单元格的右键或是点击事件的回调参数中没有查询到与该单元格合并的其他单元格的信息，因为需要改变单元格的内容或是样式。

### What does the proposed API look like?

1.事件的回调参数中有与该单元格相关的所有单元格的信息
2.或是有全局api根据该单元格col和row去查询所有合并的单元格

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/9279d7e2-61bb-4a0d-bb06-e8257db53553)
这个接口 可以获取合并单元格的范围  。可以在获取单元格信息getCellInfo
