### ISSUE TITLE
[Bug] 右击Canvas区域, 没有复制canvas菜单.

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#1500]
pivot-chart支持, 但listTable没有

![Image](https://github.com/VisActor/VTable/assets/49136199/6c5a118a-6a3c-4f59-b393-e2663edd2e63)

**Comment by fangsmile** [comment]
![Uploading img_v3_029s_2a732bf5-6bbc-40a2-a295-3b5ee772325g.jpg…]()
