### ISSUE TITLE
[Bug] OKRTable高度异常

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#1501]
![Image](https://github.com/VisActor/VTable/assets/49136199/1fcd4c10-6d0f-4444-b50a-d575b0731e48)

bugserver id: 6617e2ec983c0500de616323

**Comment by Rui-Sun** [comment]
![image](https://github.com/VisActor/VTable/assets/25134429/8a323147-6934-48d7-bba1-3e30fd7bcd5a)
