### ISSUE TITLE
[Bug] scroll will get an error.

### ISSUE THREAD

**Issue by zy-zero** [VisActor/VTable#1502]
### Version

0.23.1

### Link to Minimal Reproduction

No link

### Steps to Reproduce

This code in react will get an error.
error is : 
Cannot read properties of null (reading 'col')
TypeError: Cannot read properties of null (reading 'col')
    at InertiaScroll.scrollHandle (http://localhost:3001/static/js/bundle.js:52969:677)
    at InertiaScroll.inertia (http://localhost:3001/static/js/bundle.js:53780:244)
![image](https://github.com/VisActor/VTable/assets/23359848/d0f03aa9-6691-40f3-b7bd-b0b6b1708c74)
![image](https://github.com/VisActor/VTable/assets/23359848/0791b359-cf8d-4713-a2a0-7a27f246139e)

Code:
```
import { ListTable } from "@visactor/vtable";
import { useEffect, useRef } from "react";
const Table = () => {

  const tableRef = useRef<ListTable | null>(null);
  useEffect(() => {
    if(tableRef.current == null){
      const option = {
        container: document.getElementById("table_1"),
        columns : [
            {
                "field": "订单 ID",
                "title": "订单 ID",
                "sort": true,
                "width":'auto',
            },
            {
                "field": "邮寄方式",
                "title": "邮寄方式"
            },
            {
                "field": "类别",
                "title": "类别"
            },
            {
                "field": "子类别",
                "title": "子类别"
            },
            {
                "field": "销售额",
                "title": "销售额"
            },
        ],
        "records": [
            {
                "订单 ID": "CN-2019-1973789",
                "邮寄方式": "标准级",
                "类别": "办公用品",
                "子类别": "信封",
                "销售额": "125.44"
            },
            {
                "订单 ID": "CN-2019-1973789",
                "邮寄方式": "标准级",
                "类别": "办公用品",
                "子类别": "装订机",
                "销售额": "31.92",
            },
            // ...
        ],
      }
      tableRef.current = new ListTable(option);
    }
  }, []);
  

  return <div>
    <div id="table_1" style={{
      width: "800px",
      height: "300px",
    }}></div>
  </div>;
}

export default Table;
```
![image](https://github.com/VisActor/VTable/assets/23359848/750a468b-e3cd-4b5d-92bb-97928426da83)

### Current Behavior

Get an error.
Cannot read properties of null (reading 'col')
TypeError: Cannot read properties of null (reading 'col')
    at InertiaScroll.scrollHandle (http://localhost:3001/static/js/bundle.js:52969:677)
    at InertiaScroll.inertia (http://localhost:3001/static/js/bundle.js:53780:244)

### Expected Behavior

No error throw.

### Environment

```markdown
- OS:Win10 Home.
- Browser: Chrome 123.0.6312.106
- Framework: React.
```

**Comment by fangsmile** [comment]
可以提供一个codesanbox链接吗

**Comment by zy-zero** [comment]
> 可以提供一个codesanbox链接吗

https://codesandbox.io/p/sandbox/vtable-test-zr2wp3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluwdhcuw0006356hnx5p7gtj%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluwdhcuv0002356h25k8f107%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluwdhcuv0003356heen1iwrk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluwdhcuv0005356huwmagc0s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluwdhcuv0002356h25k8f107%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluwdhcuv0001356h5auaic9m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cluwdhcuv0002356h25k8f107%2522%252C%2522activeTabId%2522%253A%2522cluwdhcuv0001356h5auaic9m%2522%257D%252C%2522cluwdhcuv0005356huwmagc0s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluwdhcuv0004356h6vqvsbem%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluwdhcuv0005356huwmagc0s%2522%252C%2522activeTabId%2522%253A%2522cluwdhcuv0004356h6vqvsbem%2522%257D%252C%2522cluwdhcuv0003356heen1iwrk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluwdhcuv0003356heen1iwrk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

试试

**Comment by zy-zero** [comment]
> 可以提供一个codesanbox链接吗

![image](https://github.com/VisActor/VTable/assets/23359848/4c92eb45-a9a4-4c27-b2e2-9c8f46329657)
鼠标往table外面拖，就会出现这个错误。
