### ISSUE TITLE
【提问】如何设置 rowTree中的字段，看图中的字段怎么让他根据内容长度完全显示

### ISSUE THREAD

**Issue by YunzhiYike** [VisActor/VTable#1507]
![image](https://github.com/VisActor/VTable/assets/108213897/9ef3adcf-ca32-42e7-9096-aa873a516367)

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/basic_function/row_height_column_width  可阅读教程

**Comment by YunzhiYike** [comment]
明白了感谢
