### ISSUE TITLE
【问题求助】单元格数据填充数据格式需要如何定义，我在records中定义了一个数据没有填充进去

### ISSUE THREAD

**Issue by YunzhiYike** [VisActor/VTable#1515]
![image](https://github.com/VisActor/VTable/assets/108213897/0ee9d96f-8378-4b41-b2e0-bfe03a07eb34)

代码：
      option: {
        records: [
          {
            'xd': '下单销售额',
            'xse': '销售额',
            'ds': '电商销售额',
            'quarter': 'A组',
            'sales': '111222',
          }
        ],
        rows: [
          {
            dimensionKey: 'xjly',
            title: '一级科目',
            style: {
              textAlign: true,
            }
          },
          {
            dimensionKey: 'bdfhj',
            title: '二级科目',
            style: {
              textAlign: true,
            }
          },
          {
            dimensionKey: 'nrscf',
            title: '三级科目',
            style: {
              textAlign: true,
            }
          }
        ],
        columns: [
          {
            "field": "sales",
            "title": "额"
          }
        ],
        rowTree: [
          {
            dimensionKey: 'xse',
            value: '销售额',
            hierarchyState: 'expand',
            children: [
              {
                dimensionKey: 'ds',
                value: '电商销售额',
                children: [
                  {
                    dimensionKey: 'xd',
                    value: '下单销售额',
                  },
                  {
                    dimensionKey: 'xdwzf',
                    value: '下单未支付销售额',
                  },
                  {
                    dimensionKey: 'bd',
                    value: '补单金额',
                  },
                  {
                    dimensionKey: 'tkje',
                    value: '退款金额',
                  }
                ]
              },
              {
                dimensionKey: 'yx',
                value: '有效销售额合计',
              }
            ]
          },
          {
            dimensionKey: 'bdf',
            value: '变动费',
            children: [
              {
                dimensionKey: 'bdcb',
                value: '变动成本',
                children: [
                  {
                    dimensionKey: 'cpcb',
                    value: '产品成本',
                  }
                ]
              },
              {
                dimensionKey: 'qtbdf',
                value: '其它变动费',
                children: [
                  {
                    dimensionKey: 'nrscf',
                    value: '内容素材费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '广告费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: 'CID使用费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '广告费返点',
                    hierarchyState: 'collapse',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '站内运营费用',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '站内推广费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '平台服务费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '佣金返还',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '客服外包',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '推广外包',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '分销推广费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '快递费用',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '私域运营费用',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '税费',
                  },
                  {
                    dimensionKey: 'nrscf',
                    value: '其它费用',
                  }
                ]
              },
              {
                dimensionKey: 'bdfhj',
                value: '变动费合计',
              }
            ]
          },
          {
            dimensionKey: 'xjly',
            value: '限界利益',
          }
        ],
        columnTree: [
          {
            dimensionKey: 'quarter',
            value: 'A组',
            children: [
              {
                indicatorKey: 'sales',
                value: '额'
              },
              {
                indicatorKey: 'profit',
                value: '率'
              }
            ]
          },
          {
            dimensionKey: 'quarter1',
            value: 'B组',
            children: [
              {
                indicatorKey: 'sales',
                value: '额'
              },
              {
                indicatorKey: 'profit',
                value: '率'
              }
            ]
          },
          {
            dimensionKey: 'sum',
            value: '合计',
            children: [
              {
                indicatorKey: 'sales',
                value: '额'
              },
              {
                indicatorKey: 'profit',
                value: '率'
              }
            ]
          }
        ],
        corner: {
          titleOnDimension: "row",
          headerStyle: {
            textStick: true
          }
        },
        rowHierarchyIndent: 20,
        widthMode: 'autoWidth'
      }

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/55eb7250-8696-499d-a1b8-daef88e29aac)
同一层请确保key一致
#1513 已作答
