### ISSUE TITLE
使用了VUE UI框架，会导致编辑模式，样式叠加不正常。

### ISSUE THREAD

**Issue by cwwjsyc** [VisActor/VTable#1518]
![Err](https://github.com/VisActor/VTable/assets/26668815/e76167e4-aade-4a6a-be3a-1a2d01729030)

如上图，无论是用vuetify 还是ArcoDesign 框架，都会导致 editor.input样式异常。
有什么解决办法？

**Comment by martesi** [comment]
是不是 UI 框架带的样式重置把输入框的背景色弄没了

**Comment by cwwjsyc** [comment]
设置父元素样式 不继承也没用。{all:initial}

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/edit/edit_cell  这个是引入其他框架导致的话 我这块也没有什么好的方式。看看自定义编辑器   看看是否可以解决掉问题。

**Comment by cwwjsyc** [comment]
从产品角度看，应该想办法支持使用框架，起码自家的框架ArcoDesign 要100%兼容。ag-grid就没有这个问题，说明技术上是行得通的。没有对UI 框架的支持，就面临2选1的结果，对使用者来说代价太大了

**Comment by fangsmile** [comment]
你可以给个demo吗 看看具体是什么样式冲突的问题

**Comment by fangsmile** [comment]
你好 在吗 @cwwjsyc

**Comment by fangsmile** [comment]
您好 如果还有问题可以加入微信群或者飞书群联系我们
订阅号：
![image](https://github.com/VisActor/VTable/assets/3468473/e6fd1bae-bd6b-4342-8998-bc44dbaf1e04)
