### ISSUE TITLE
可编辑表格能否支持初始就直接全表格展示可编辑状态的单元格，而不是双击某一个单元格后才能进行可编辑

### ISSUE THREAD

**Issue by xinbo97** [VisActor/VTable#1519]
当前案例中，可编辑表格只有在双击某一个单元格后才能进行可编辑。能否支持直接展示单元格的可编辑状态不用进行双击操作。且支持单元格校验功能

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/edit/edit_cell  有个编辑触发时机的配置  可以看看

**Comment by fangsmile** [comment]
解决方案 
可在表格初始化的option中配置editCellTrigger为click。该配置项定义如下：
/** 编辑触发时机:双击事件 | 单击事件 | api手动开启编辑。默认为双击'doubleclick' */
editCellTrigger?: 'doubleclick' | 'click' | 'api';

代码示例  
  const option = {
    records,
    columns,
    autoWrapText: true,
    limitMaxAutoWidth: 600,
    heightMode: 'autoHeight',
    editCellTrigger: 'click' // 设置编辑触发时机
  };
  const tableInstance = new VTable.ListTable(container, option);

**Comment by Yang-yibu** [comment]
可以吧这个看成 Excel，而且如果全部进入编辑状态的话性能也不会好；如果你想标记编辑状态让用户知道那些单元格可以编辑的话，可以添加 svg icon 或者特殊样式实现吧
