### ISSUE TITLE
ListTable配置表头高度无效；

### ISSUE THREAD

**Issue by cwwjsyc** [VisActor/VTable#1520]
配置项目：
`
{
widthMode: 'standard',
  standard: 'standard',
  autoWrapText: false,
  defaultHeaderRowHeight: 50,
  defaultRowHeight: 28,
……
}
`
没有效果

**Comment by cwwjsyc** [comment]
查到 是因为设置了rowSeriesNumber，但是rowSeriesNumber 的配置项中没有高度选项。

**Comment by fangsmile** [comment]
我看下
