### ISSUE TITLE
[Bug] customMergeCell合并后内容显示不全

### ISSUE THREAD

**Issue by yuzhanyin** [VisActor/VTable#1543]
### Version

0.23.3

### Link to Minimal Reproduction

如下

### Steps to Reproduce

`let  tableInstance;

const generatePersons = count => {
  return Array.from(new Array(count)).map((_, i) => ({
    id: i + 1,
    email1: `${i + 1}@xxx.com`,
    name: `name${i + 1}`,
    date1: '2022-9-1日',
    tel: '000-0000-0000',
    sex: i % 2 === 0 ? 'boy' : 'girl',
    work: i % 2 === 0 ? 'back-end engineer' : 'front-end engineer',
    city: 'beijing'
  }));
};
const records = generatePersons(10);

const columns = [
    {
      field: 'id',
      title: 'ID ff',
      width: '1%',
      minWidth: 200,
      sort: true
    },
    {
      field: 'email1',
      title: 'email',
      width: 200,
      sort: true
    },
    {
      title: 'full name',
      columns: [
        {
          field: 'name',
          title: 'First Name',
          width: 200
        },
        {
          field: 'name',
          title: 'Last Name',
          width: 200
        }
      ]
    },
    {
      field: 'date1',
      title: 'birthday',
      width: 200
    },
    {
      field: 'sex',
      title: 'sex',
      width: 100
    },
    {
      field: 'tel',
      title: 'telephone',
      width: 150
    },
    {
      field: 'work',
      title: 'job',
      width: 200
    },
    {
      field: 'city',
      title: 'city',
      width: 150
    }
  ];

const option = {
  records,
  columns,
  widthMode:'standard',
  bottomFrozenRowCount:1,
  customMergeCell: (col, row, table) => {
    if (col ==0 && row % 2 == 0 && row > 3) {
      return {
        text: '总结栏：此数据为一份人员基本信息',
        range: {
          start: {
            col: 0,
            row: row - 1
          },
          end: {
            col: 0,
            row: row
          }
        },
        style:{
          borderLineWidth:[6,1,1,1],
          borderColor:['gray']
        }
      };
    }
  }
};
tableInstance = new VTable.ListTable(document.getElementById(CONTAINER_ID),option);
window['tableInstance'] = tableInstance;`
![bug](https://github.com/VisActor/VTable/assets/33897815/db3bb455-4ff2-4f30-af26-27a539a06d55)

### Current Behavior

合并后内容显示错误

### Expected Behavior

期望合并后内容正常显示

### Environment

```markdown
- OS:win10
- Browser:chrome 123.0.6312.123
- Framework:
```

**Comment by yuzhanyin** [comment]
还有customMergeCell: (col, row, table) => {
    //console.log(table.getCellValue(col,row)) // 会报错，
![bug2](https://github.com/VisActor/VTable/assets/33897815/6623356e-c693-4db1-b3d4-ae16f66a9b6a)
    // console.log(table.getCellRawValue(col,row)) 这样又是正常打印出内容的
    }
  }

**Comment by Rui-Sun** [comment]
这里的合并规则写的有问题，规则需要应用到所有单元格
```
    customMergeCell: (col, row, table) => {
      if (col == 0 && row > 2) {
        if (row % 2 == 0) {
          return {
            text: '总结栏：此数据为一份人员基本信息',
            range: {
              start: {
                col: 0,
                row: row - 1
              },
              end: {
                col: 0,
                row: row
              }
            },
            style: {
              borderLineWidth: [6, 1, 1, 1],
              borderColor: ['gray']
            }
          };
        } else {
          return {
            text: '总结栏：此数据为一份人员基本信息',
            range: {
              start: {
                col: 0,
                row: row
              },
              end: {
                col: 0,
                row: row + 1
              }
            },
            style: {
              borderLineWidth: [6, 1, 1, 1],
              borderColor: ['gray']
            }
          };
        }
      }
    }
```
![image](https://github.com/VisActor/VTable/assets/25134429/e8c1d552-b399-4d89-be6c-c64fd745fb78)

**Comment by Rui-Sun** [comment]
第二个问题，在getCellValue中会判断是否使用的自定义合并，会引起循环调用，getCellRawValue是获取原始数据，不会判断合并，所有不会引起循环调用；后续再getCellValue中加一个skipCustomMerge的参数，提供给合并函数里调用
