### ISSUE TITLE
[Bug] Some Theme extends elements doesn't effect anything?

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1548]
### Version

^0.23.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-simple-demo-forked-7k5zm9?file=%2Fsrc%2Findex.ts%3A9%2C30

### Steps to Reproduce

Some of the item after change doesn't effect the table. Is it a bug?

```ts
const CUSTOM_THEME = VTable.themes.DEFAULT.extends({
    defaultStyle: {
        borderLineWidth: 0, //Doesn't work
        bgColor: "transparent", //Doesn't work
        fontSize: 10, //Doesn't work
        fontWeight: "normal", //Doesn't work
    },
    selectionStyle: {
        cellBorderLineWidth: 1,
    },
    scrollStyle: {
        barToSide: true,
        visible: "always",
        width: 5,
        scrollSliderColor: "rgba(76, 140, 74, 0.7)"
    }
});
```

### Current Behavior

Doesn't effect the table.

### Expected Behavior

Table theme should changed accordingly.

### Environment

```markdown
- OS: Windows 10
- Browser: Webview2
- Framework: Svelte^4
```

**Comment by fangsmile** [comment]
You can see the defined of DEFAULT theme file : https://github.com/VisActor/VTable/blob/develop/packages/vtable/src/themes/DEFAULT.ts
There are defining of bodyStyle and headerStyle so your defaultStyle can not effect.
If you don't use extend just use like this:
```
const CUSTOM_THEME = {
    defaultStyle: {
        borderLineWidth: 0, //Doesn't work
        bgColor: "transparent", //Doesn't work
        fontSize: 10, //Doesn't work
        fontWeight: "normal", //Doesn't work
    },
    selectionStyle: {
        cellBorderLineWidth: 1,
    },
    scrollStyle: {
        barToSide: true,
        visible: "always",
        width: 5,
        scrollSliderColor: "rgba(76, 140, 74, 0.7)"
    }
};
```

It will work!

**Comment by KiddoV** [comment]
Thanks, I just realized that as well. I just gonna use ``bodyStyle`` and ``headerStyle`` then.
