### ISSUE TITLE
[Bug] SVG custom icon with color doesn't work!

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1550]
### Version

^0.23.3

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/custom-render/custom-icon

### Steps to Reproduce

![Untitled](https://github.com/VisActor/VTable/assets/28552977/c0898734-ba38-4d3b-9b99-2ad7ed5fcba2)

### Current Behavior

SVG icon color not change.

### Expected Behavior

SVG icon color should change.

### Environment

```markdown
- OS: Windows 10
- Browser: Webview2
- Framework: Svelte
```

**Comment by fangsmile** [comment]
Sorry，VTable is currently not possible to parse svg to automatically modify color.

**Comment by fangsmile** [comment]
sorry，the example in the website with `color` is a mistick ,i will delete it .
