### ISSUE TITLE
[Bug] Input editor box does not change size according to cell size when enable ``autoFillWidth``

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1559]
### Version

^0.23.3

### Link to Minimal Reproduction

N/A

### Steps to Reproduce

1. Enable the ``autoFillWidth``.
2. Assign input editor.
3. Open editor box and change the window size.

Result:
![no-work](https://github.com/VisActor/VTable/assets/28552977/7eb8f22e-50a4-4b6d-87ba-913cf3790839)

### Current Behavior

Input editor box doesn't update size according to cell.

### Expected Behavior

Input editor box SHOULD update size according to cell.

### Environment

```markdown
- OS: Windows 10
- Browser: Webview2
- Framework: Svelte
```

**Comment by fangsmile** [comment]
To handle this problem, I will complete edit cell and exit edit state.
