### ISSUE TITLE
[Feature] 单元格编辑支持输入多行

### ISSUE THREAD

**Issue by nikoohp** [VisActor/VTable#1616]
### What problem does this feature solve?

一个单元里面可编辑并展示多行内容

### What does the proposed API look like?

.

**Comment by fangsmile** [comment]
这个可以写个自定义编辑器来解决哈  写的通用点的话 可以提pr 集成到编辑器的包里面  @nikoohp

**Comment by LofiSu** [comment]
我可以认领这个issue吗？

**Comment by LofiSu** [comment]
我是社区萌新，对这个issue很感兴趣，刚好我之前用js写过类似的，可以把这个issue指派给我吗？
