### ISSUE TITLE
[Feature] Get the final generated canvas element

### ISSUE THREAD

**Issue by xingorg1** [VisActor/VTable#162]
### What problem does this feature solve?

I hope I can get the final generated canvas element, or I can set the ID attribute of the final generated canvas element. So I can turn the table into a picture.

Demo：line 202 https://codesandbox.io/s/vtable-list-table-forked-kxj2l4?file=/src/index.ts 

### What does the proposed API look like?

const tableInstance = new ListTable(option);
tableInstance.canvas // -> the generated canvas element

**Comment by fangsmile** [comment]
temporary method：
`
tableInstance.canvas.toDataURL()
`
you can reference https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL.

We will add api can export image. you can follow this issue https://github.com/VisActor/VTable/issues/163

**Comment by xuanhun** [comment]
@xingorg1 

> temporary method： `tableInstance.canvas.toDataURL()` you can reference https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL.
> 
> We will add api can export image. you can follow this issue #163
