### ISSUE TITLE
[Feature] 透视表自定义列头对齐s2的功能

### ISSUE THREAD

**Issue by xiaochong444** [VisActor/VTable#1644]
### What problem does this feature solve?

在数据透视分析的过程中有可能透视表只有行和值，当值的字段又非常多的时候，希望通过自定义列头的形式对指标进行分组。
类似如下的一种bi分析形式，实际上列上的表头都是虚拟的，并没有维度字段去绑定，层级数也不确定。使用s2的自定义列头很容易做到，但是用vtable现在无法实现
![image](https://github.com/VisActor/VTable/assets/166355956/fb0550e4-b7e3-4a36-a1d6-402ed01c00df)

### What does the proposed API look like?

功能上和下面s2的例子一样，透视表绑定行和值，列头用自定义树生成，由于整个列都是自定义的，所以列的小计总计问题无须考虑，由用户自己负责
https://s2.antv.antgroup.com/examples/layout/custom-header-group/#custom-pivot-col-header

**Comment by fangsmile** [comment]
数据records那就必须每一列分别对应一个指标字段了吧
![image](https://github.com/VisActor/VTable/assets/3468473/a19ecd33-1a94-404a-8912-e0c433e49ba1)
 @xiaochong444

**Comment by xiaochong444** [comment]
是的，列的叶子节点和指标一一对应，s2也是这样实现的，父节点field就是个虚拟的唯一标识，叶子节点的field对应指标
![image](https://github.com/VisActor/VTable/assets/166355956/fe08eb88-3613-40c1-b77a-1ff49a2eae4a)
