### ISSUE TITLE
[Feature] 表格行序号rowSeriesNumber有问题，应该有个配置禁止列宽调整

### ISSUE THREAD

**Issue by sfeng95** [VisActor/VTable#1649]
### What problem does this feature solve?

表格行序号rowSeriesNumber有问题，应该有个配置禁止列宽调整

### What does the proposed API look like?

表格行序号rowSeriesNumber有问题，应该有个配置禁止列宽调整

**Comment by YELineee** [comment]
I'd like to work on this issue.
