### ISSUE TITLE
[Feature] 自定义表头或自定义单元格里的element.type期望添加一个line

### ISSUE THREAD

**Issue by semmywong** [VisActor/VTable#1650]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/67748948/26c179e1-3c38-4a7f-8106-29657a37a354)
可以自定义对表头单元格画线，并且线有旋转角度

### What does the proposed API look like?

![img_v3_02am_ccf925e5-52d9-4f4f-bcd8-fcabfafafd0g](https://github.com/VisActor/VTable/assets/67748948/8b05902e-33c2-4a31-8467-596422f0ce1e)
图元类型添加一个line

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/52e3d50e-2423-4330-bcac-546c596b108e)
VLine是支持的  教程中有少些一个  我们更新下
