### ISSUE TITLE
单元格编辑：决定是否进入编辑模式

### ISSUE THREAD

**Issue by Yang-yibu** [VisActor/VTable#1659]
给单元格右侧添加了 ICON，开启了双击进入编辑模式。需求：在双击 icon 的时候，不进入编辑模式

**Comment by martesi** [comment]
你可能需要[设置触发方式为 API](https://visactor.com/vtable/option/ListTable#editCellTrigger('doubleclick'%20|%20'click'%20|%20'api')%20=%20'doubleclick')，并为 icon 点击绑定事件[触发编辑](https://visactor.com/vtable/api/Methods#startEditCell)。

**Comment by Yang-yibu** [comment]
可以，我之前想多，通过API方式控制反而灵活一些

**Comment by fangsmile** [comment]
还需要讨论吗 这个。如果没有问题的话 可以关闭这个issue了。
欢迎加入飞书群
![飞书20240509-104434](https://github.com/VisActor/VTable/assets/3468473/19042cc8-0202-4696-9f7e-a71c4097ee03)

**Comment by Yang-yibu** [comment]
有微信QQ么？
