### ISSUE TITLE
合并单元格后，单元格编辑失效 [Bug] 

### ISSUE THREAD

**Issue by lxm-qqbear** [VisActor/VTable#1666]
### Version

0.25.2

### Link to Minimal Reproduction

N/A

### Steps to Reproduce

N/A

### Current Behavior

N/A

### Expected Behavior

N/A

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
我们内部就是针对合并情况做了禁用编辑  请问你是什么场景下需要  是自动合并 还是自定义合并  业务场景也描述下吧

**Comment by lxm-qqbear** [comment]
我现在是把这个表格系统作为excel使用，在自定义合并的时候，需要能够继续编辑

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/7e84de15-7566-4ea9-aeda-f60cbca0fbd7)
这个需求可以单独提一个issue

**Comment by Moon-9552** [comment]
> 我们内部就是针对合并情况做了禁用编辑 请问你是什么场景下需要 是自动合并 还是自定义合并 业务场景也描述下吧

请问是怎么实现对合并单元格的情况做的禁用编辑？
