### ISSUE TITLE
[Bug] 文档错误及缺失

### ISSUE THREAD

**Issue by AlphaYoung111** [VisActor/VTable#1676]
### Version

0.25.2

### Link to Minimal Reproduction

1

### Steps to Reproduce

1. https://www.visactor.io/vtable/demo/basic-functionality/list-table-header-group 文档示例 `caption`属性未修改为`title`
2. https://www.visactor.io/vtable/api/Methods 其中的可参考教程的每个跳转链接都带上了)
3. https://visactor.io/vtable/guide/basic_function/update_option 更新单项配置中的`updateColumns()`方法多了个`
4. https://www.visactor.io/vtable/demo/data-analysis/pivot-analysis-total 示例代码中出现的`enableDataAnalysis`属性未在文档中找到
5. 文档中如果透视表无法使用的属性没有特殊备注说明，如第三点的中的方法

### Current Behavior

文档未正确显示

### Expected Behavior

文档正确显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/fefa2f27-2d60-4f3f-b078-dc5c5947e9fc)
columns需要跟着个中括号

**Comment by fangsmile** [comment]
补充editor包 cnd引用方式的写法


![Image](https://github.com/orgs/VisActor/projects/4/assets/3468473/af04b7dd-ae8f-4f38-9e80-cbca6b88193d)
这里也需要补充写明
![Image](https://github.com/orgs/VisActor/projects/4/assets/3468473/01182928-e697-46c5-8f97-26046a8881c4)

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/150cecf0-ff66-4120-a461-d7ce541c691b)
![image](https://github.com/VisActor/VTable/assets/3468473/150cecf0-ff66-4120-a461-d7ce541c691b)
这几处应该大写
