### ISSUE TITLE
[Feature] 隐藏透视表表头, API命名需要规范

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#1680]
```
"showColumnHeader": false,
"showRowHeader": false,
"hideIndicatorName": true

```

2个show, 1个hide, 才能实现完全的隐藏, 理解起来成本很高, 需要优化一下.

**Comment by fangsmile** [comment]
enableColumnResizeOnAllRows: true, //是否可以在所有行上调整列宽
        disableColumnResize: false, //关闭调整列宽

**Comment by fangsmile** [comment]
基本表格filedFormat和指标的format 
以及两处的headerFormat 命名和参数统一

**Comment by youngwinds** [comment]
no need any more
