### ISSUE TITLE
[Bug] 希望table的边框能够实现圆角 

### ISSUE THREAD

**Issue by liuboying1119** [VisActor/VTable#1696]
### Version

0.23.4

### Link to Minimal Reproduction

https://data.bytedance.net/evals/projects/test/datasets

### Steps to Reproduce

我当前的配置如下
![img_v3_02ar_d07e8d45-9b9f-4a31-be86-7972e46c6c8g](https://github.com/VisActor/VTable/assets/134760419/8a4e41ce-8835-4f23-971f-7a04eb28bc3c)

### Current Behavior

![img_v3_02ar_792ea5b0-faab-4c50-bdb4-2435c5c3949g](https://github.com/VisActor/VTable/assets/134760419/db42319d-99a9-4266-a209-87a5ef79d6d3)

### Expected Behavior

希望上图红色框圈出的部分，能够实现圆角

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
目前配置cornerRadius四边分别设置不同样式（borderLineWidth:[0,1,0,1]），统一样式是可以的
![image](https://github.com/VisActor/VTable/assets/25134429/f1d09236-838e-4e64-95a4-b65d50696e0f)

**Comment by fangsmile** [comment]
配置中有数组的话会拆分四条线绘制  配一个值的话才是绘制矩形才有圆角。
不过linedash是有问题的：
![image](https://github.com/VisActor/VTable/assets/3468473/b9a2a462-fae9-45f6-8077-fc5fe813d6e2)
