### ISSUE TITLE
[Feature] 树形数据中图标的注册，与图标展示位置期望可配置

### ISSUE THREAD

**Issue by liudengyan** [VisActor/VTable#1697]
### What problem does this feature solve?

可以展示一个动态生成的用户文字头像

### What does the proposed API look like?

![image](https://github.com/VisActor/VTable/assets/38559174/0b2bb4e8-4141-4637-b309-60726c452fc2)
1. 期望icon中可自定义回调函数生成，并且可以获取到当前单元格的数据。
2. 期望树形数据中，icon可以跨越展开图标，在左侧紧紧贴合文字。

**Comment by fangsmile** [comment]
第一条中提到的，icon本身就是可以配置函数的吧

**Comment by liudengyan** [comment]
感谢您的回复，第一个确实是可以的，已经完成了，现在只需要让图标与文字贴合了，这个有什么办法吗
