### ISSUE TITLE
[Bug] Cannot apply custom editor on sub-column

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1711]
### Version

^0.25.5

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-simple-demo-forked-hgsqc6?file=%2Fsrc%2Findex.ts%3A31%2C36

### Steps to Reproduce

1. DBClick on the first column (Item Number) => Editor works
2. DBClick on the third column (Sub column - Test Firmware | Version) => Editor not popup

### Current Behavior

Double click on sub-column, the custom editor is not display!
Also I just found out that when dbclick on the sub-column and then edit the first column, the sub-column will get the value instead of the editing column after confirm edit change (see attached gif).

### Expected Behavior

Double click on sub-column, the custom editor SHOULD display!

### Environment

```markdown
Any
```

### Any additional comments?

![bug](https://github.com/VisActor/VTable/assets/28552977/9c484ea7-0c8c-474c-809d-c212373c12de)

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/d1295116-f381-47c8-9e12-d0342517839e)
codesanbox  is not shared

**Comment by KiddoV** [comment]
@fangsmile my bad. I changed to public now.

**Comment by fangsmile** [comment]
If you like you can contribute your edit cell usage with inputmask to VTable's website.
![image](https://github.com/VisActor/VTable/assets/3468473/b4a6ba11-0047-4595-bee8-c11c4a5e9051)

**Comment by KiddoV** [comment]
@fangsmile Thanks! Will contribute when I have time.
