### ISSUE TITLE
[Bug] Instance.arrangeCustomCellStyle(cellPosition, 'a0001') 设置单元格样式报错

### ISSUE THREAD

**Issue by sfeng95** [VisActor/VTable#1729]
### Version

0.24，0.25版本都是

### Link to Minimal Reproduction

设置单元格样式报错

### Steps to Reproduce

Instance.arrangeCustomCellStyle(cellPosition, 'a0001') 设置单元格样式报错

### Current Behavior

Instance.arrangeCustomCellStyle(cellPosition, 'a0001') 设置单元格样式报错

### Expected Behavior

Instance.arrangeCustomCellStyle(cellPosition, 'a0001') 设置单元格样式报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Instance.arrangeCustomCellStyle(cellPosition, 'a0001') 设置单元格样式报错

**Comment by Rui-Sun** [comment]
具体是什么报错呢？能提供一下报错的例子吗？站点的用例好像没复现这个问题 https://www.visactor.io/vtable/demo/custom-render/custom-style

**Comment by sfeng95** [comment]
> 具体是什么报错呢？能提供一下报错的例子吗？站点的用例好像没复现这个问题 https://www.visactor.io/vtable/demo/custom-render/custom-style

不是配置文档，是接口文档，地址：https://www.visactor.io/vtable/api/Methods#registerCustomCellStyleArrangement
`
    let cellPosition: any = { row: 1, column: 1 ,range:{}};    
listTableInstance.registerCustomCellStyleArrangement(cellPosition, 'a0001')
`报错，说函数不存在
![微信图片_20240529170544](https://github.com/VisActor/VTable/assets/21358616/032d7187-9b7e-4adb-bc24-104ce3b1fe2a)
![Uploading 微信图片_20240529170411.png…]()

**Comment by sfeng95** [comment]
很感谢你的帮助！但是依然报错
![捕获](https://github.com/VisActor/VTable/assets/21358616/10c6faa3-1c25-4fac-ba04-c2626380e232)
![捕获2](https://github.com/VisActor/VTable/assets/21358616/9484faf5-3cf4-4a6c-8972-6138d4e91963)
![捕获3](https://github.com/VisActor/VTable/assets/21358616/f512c809-9f13-4c24-8523-93181c71024a)
![捕获4](https://github.com/VisActor/VTable/assets/21358616/7518b20d-3ad6-4517-a92d-78fb9fa8d0a6)

**Comment by Rui-Sun** [comment]
是col，不是column

**Comment by Rui-Sun** [comment]
我们会尽快修复一下文档，非常欢迎一起贡献代码👏🏻👏🏻👏🏻

**Comment by sfeng95** [comment]
好的！谢谢！
