### ISSUE TITLE
vchart 垂直方向不能居中?

### ISSUE THREAD

**Issue by xuyifeiOnly** [VisActor/VTable#1734]
我设置了表格的 defaultRowHeight = 40之后，添加了 vchart 垂直方向不能自动居中，是需要配置啥吗？
<img width="1003" alt="image" src="https://github.com/VisActor/VTable/assets/49358706/e0779427-083f-4243-b858-21c46544d792">

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/473b7508-a15e-4667-8bdc-34a02b745c68)
看下这个示例  @xuyifeiOnly

**Comment by fangsmile** [comment]
好吧 我理解错了  
是vchart的用法是吧 @xile611 看看bar怎么居中配置？

**Comment by xile611** [comment]
@xuyifeiOnly 可以加上 `padding: 0`试试，去除`padding`

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/cell-type/list-table-chart 这个示例也可以参考

**Comment by xuyifeiOnly** [comment]
> @xuyifeiOnly 可以加上 `padding: 0`试试，去除`padding`

padding设置了，不起作用

**Comment by xuyifeiOnly** [comment]
> https://visactor.io/vtable/demo/cell-type/list-table-chart 这个示例也可以参考

<img width="578" alt="image" src="https://github.com/VisActor/VTable/assets/49358706/c852c2d7-df1c-4d73-8a38-74ba0feea309">
你可以更改一下这个高度，然后就会复现，没有办法居中

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/8f41c2d8-e0d2-4459-9b3a-b85a414178cc)
@xuyifeiOnly 加上这个是可以的呀
