### ISSUE TITLE
换行符渲染

### ISSUE THREAD

**Issue by zhuweileo** [VisActor/VTable#1735]
当表格内容中存在换行符时，会渲染成一个空格
<img width="809" alt="image" src="https://github.com/VisActor/VTable/assets/22818403/988fd1c1-e69b-4323-ae42-ff486e32b7e2">

**Comment by Rui-Sun** [comment]
option.enableLineBreak: true可以开启解析换行符

**Comment by zhuweileo** [comment]
@Rui-Sun 我尝试在0.25.2 和 0.25.7 版本上使用这个属性，开启之后渲染效果变成了下面这样
<img width="694" alt="image" src="https://github.com/VisActor/VTable/assets/22818403/dd1801f9-1473-4756-a7ea-eb592795c459">


这里是我的代码
<img width="591" alt="image" src="https://github.com/VisActor/VTable/assets/22818403/e1076416-d806-4067-8e9a-68c6493c9dba">

**Comment by zhuweileo** [comment]
@Rui-Sun 是高通的孙瑞么？

**Comment by Rui-Sun** [comment]
> @Rui-Sun 我尝试在0.25.2 和 0.25.7 版本上使用这个属性，开启之后渲染效果变成了下面这样 <img alt="image" width="694" src="https://private-user-images.githubusercontent.com/22818403/332016735-dd1801f9-1473-4756-a7ea-eb592795c459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MDYsIm5iZiI6MTcxNjIwODMwNiwicGF0aCI6Ii8yMjgxODQwMy8zMzIwMTY3MzUtZGQxODAxZjktMTQ3My00NzU2LWE3ZWEtZWI1OTI3OTVjNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmM3MDBhZDg0ZjY0Yzg4ZDdkM2RiNTczNzA0ZDYwODdmM2JlZmM2M2Q5Y2VjMzI0Njk4ODg0NDVjMTI5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QhR8iTn3untJU_RVvSMGR-ah-ZXXIM5Eu9WAwsOrfi4">
> 
> 这里是我的代码 <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/22818403/332016386-e1076416-d806-4067-8e9a-68c6493c9dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg2MDYsIm5iZiI6MTcxNjIwODMwNiwicGF0aCI6Ii8yMjgxODQwMy8zMzIwMTYzODYtZTEwNzY0MTYtZDgwNi00MDY3LThlOWEtNjhjNjQ5M2M5ZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZjYwMTk5YmEyYmEwZThmOWE1MGU3YjU4ZjUzYjliNzU5MzkxODkyYzQzOGJhNGYwZGNlZTA4YmZlMjRlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ib7cLV4m8FEBGJyFBGzqgOC4iLg57OpOTSP9RA1-gGI">

这个是行号是默认值，显示不下两行，自动省略；可以配置heightMode:'autoHeight' 开启自动行高

**Comment by zhuweileo** [comment]
同时设置option.enableLineBreak: true，option.heightMode:'autoHeight' 达到了想要的效果。
非常酷的开源项目！

**Comment by fangsmile** [comment]
@Rui-Sun 写一个FAQ吧
