### ISSUE TITLE
How to update `rawData`?

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1780]
Related to: https://github.com/VisActor/VTable/discussions/1635

**Comment by KiddoV** [comment]
I don't think this work as expected yet.
The `rawData` should only update after `updateRecords()` method called.
Current behavior after `edit a cell` the `raw record`  also changed even when not calling `updateRecords()`.
So after edit a cell, I call `getCellRawRecord()`, it will return the record with the updated value of the edited cell. THIS IS WRONG!

**Comment by KiddoV** [comment]
Will try my best then...

**Comment by fangsmile** [comment]
You can record in the issues, in case you forget
