### ISSUE TITLE
[Feature] 当编辑状态退出前会validate验证,validate方法能否支持异步;

### ISSUE THREAD

**Issue by creasy2010** [VisActor/VTable#1797]
### What problem does this feature solve?

问题:  
退出编辑前, 会进行数据验证, 但有些逻辑是异步(需要调用后端接口进行验证). 
这样就会导致错误. 

### What does the proposed API look like?

validate 方法支持异步

**Comment by fangsmile** [comment]
收到。
这个需求的话 你要不要尝试帮我们改一下，做个代码贡献呢https://visactor.io/vtable/guide/Contribution_Guide  @creasy2010

**Comment by creasy2010** [comment]
可以. 
只要这个需求跟之前的设计不冲突, 乐意处理

**Comment by fangsmile** [comment]
![飞书20240528-193336](https://github.com/VisActor/VTable/assets/3468473/fce43de4-9026-4ae5-8a9d-271ac73d49ba)
可以加飞书群 加下我

**Comment by creasy2010** [comment]
已修复, 在项目中测试, 测试通过后发去pr

**Comment by fangsmile** [comment]
https://github.com/VisActor/VTable/pull/1844.  为什么关闭了呢 @creasy2010

**Comment by creasy2010** [comment]
提交验证有些问题,周末上线, 线上验证完, 重新发pr
