### ISSUE TITLE
[Feature] 移动表头的前置条件由点击改为鼠标落下

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#1800]
### What problem does this feature solve?

当前移动表头的前置条件是点击选中表头，如果设置了disableSelect则无法移动表头。希望改为鼠标落下后就可以拖动表头。

### What does the proposed API look like?

例如怎加配置 dragMode: 'click' | 'mouse_down'

**Comment by fangsmile** [comment]
我们这块优化了下 如果配置了disableSelect  直接拖拽即可
