### ISSUE TITLE
[Feature] add support for celltype = 'checkbox' and 'radiobutton' in  exportVTableToExcel

### ISSUE THREAD

**Issue by MrFlaro** [VisActor/VTable#1813]
### What problem does this feature solve?

Currently export for checkboxes only works with CSV export.

Also - it would be very usefull to have an option to localize the exported boolean value. Checkbox might make sense in UI, but in Excel some users might prefer seeing "Yes/No" (or whatever other custom value) instead of "True/False".

### What does the proposed API look like?

Export API is fine as it is. 

Localization can be implemented as a general arrow function that takes export-ready cell value and modifies it if neccessary. 

Like: 
```ts
formatExportOutput((cell) => {
 if (cell.cellType === 'checkbox')
 {
 cell.value = cell.value ? 'Yes' : 'No';
 }
 return cell;
});
```

**Comment by Rui-Sun** [comment]
This is a very good suggestion! We will schedule it into our development plan.
