### ISSUE TITLE
[Bug] 移动端冻结列bug

### ISSUE THREAD

**Issue by spirit-lh** [VisActor/VTable#1816]
### Version

VTable 1.0.0

### Link to Minimal Reproduction

https://visactor.com/vtable/demo/basic-functionality/frozen-col

### Steps to Reproduce

在移动端使用冻结列API，冻结非第一列时

### Current Behavior

在移动端冻结列时，如果是第一列没有问题，但是如果是其他列，则冻结失效，如下方式是无效的：
// 手机端冻结列有bug,只能冻结第一列
        // allowFrozenColCount: 3,
        // frozenColCount: 2,

### Expected Behavior

可同时冻结多列

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
这个是一个功能，我们默认如果冻结区域占据了绝大部分画面时，可滚动区域会非常小，影响交互；此时会禁用冻结效果，是表格整体可滚动。这是一个交互优化效果
