### ISSUE TITLE
表格查询后，拖送滚动条后，改变浏览器页面大小或更新数据updateOption，都会导致vtable出现空白区域[Bug] 

### ISSUE THREAD

**Issue by paopaome8933** [VisActor/VTable#1829]
### Version

https://unpkg.com/@visactor/vtable/dist/vtable.min.js

### Link to Minimal Reproduction

1

### Steps to Reproduce

1

### Current Behavior

表格查询后，拖送滚动条后，改变浏览器页面大小或更新数据updateOption，将滚动条移动到初始位置，会出现空白区域。目前我是在触发重新渲染前将滚动条回到初始化状态。

### Expected Behavior

不要出现空白区域bug

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
可以给个复现的例子吗  我这没有复现出来
