### ISSUE TITLE
是否可以优化包体积

### ISSUE THREAD

**Issue by gdnwr** [VisActor/VTable#1857]
简单使用场景下，如仅使用ListTable渲染一个简单表格
一个空的vite创建的vue项目，在引入vtable前后的dist文件体积变化为：57KB->1.39MB

![image](https://github.com/VisActor/VTable/assets/28519600/7250a78a-8d34-41fc-8a17-47c6295f8b80)
![image](https://github.com/VisActor/VTable/assets/28519600/c3c4d5b4-7aca-4f7c-8881-4e5531203134)

**Comment by i7eo** [comment]
ui 相关的组件、图表可以考虑拆出来

**Comment by fangsmile** [comment]
[1.4.2-alpha.3](https://www.npmjs.com/package/@visactor/vtable/v/1.4.2-alpha.3) 可以试一下
教程可以参考：https://github.com/VisActor/VTable/pull/1994/files#diff-fb09b50ef5b83944d197539fadf3f85e8eec90fab844118f60e7b9766472970f  @i7eo @kortin99

**Comment by kortin99** [comment]
@fangsmile 我导入了 `ListTableSimple` 没有注册 `registerTitle` 和 `registerMenu`，但标题和右键菜单依然是可用的。打包后大小也没有变化。
这里是重现链接：[CodeSandBox](https://codesandbox.io/p/devbox/vtable-import-mp8824?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clycgbyct00073b6k3bzv4a91%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clycgbyct00023b6krbomohhp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clycgbyct00043b6kl01l9es3%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clycgbyct00063b6kb34xt9kb%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clycgbyct00023b6krbomohhp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00013b6keyv0jsxt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clycgbyct00023b6krbomohhp%2522%252C%2522activeTabId%2522%253A%2522clycgbyct00013b6keyv0jsxt%2522%257D%252C%2522clycgbyct00063b6kb34xt9kb%2522%253A%257B%2522id%2522%253A%2522clycgbyct00063b6kb34xt9kb%2522%252C%2522activeTabId%2522%253A%2522clycl16ex006e3b6kirsg8wl8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00053b6k9kwil1nk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clycgs37f00a33b6kos5brt66%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clycl16ex006e3b6kirsg8wl8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clycgbyct00043b6kl01l9es3%2522%253A%257B%2522id%2522%253A%2522clycgbyct00043b6kl01l9es3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00033b6kj8gn5wwb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clycgbyct00033b6kj8gn5wwb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Rui-Sun** [comment]
> @fangsmile 我导入了 `ListTableSimple` 没有注册 `registerTitle` 和 `registerMenu`，但标题和右键菜单依然是可用的。打包后大小也没有变化。 这里是重现链接：[CodeSandBox](https://codesandbox.io/p/devbox/vtable-import-mp8824?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clycgbyct00073b6k3bzv4a91%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clycgbyct00023b6krbomohhp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clycgbyct00043b6kl01l9es3%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clycgbyct00063b6kb34xt9kb%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clycgbyct00023b6krbomohhp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00013b6keyv0jsxt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clycgbyct00023b6krbomohhp%2522%252C%2522activeTabId%2522%253A%2522clycgbyct00013b6keyv0jsxt%2522%257D%252C%2522clycgbyct00063b6kb34xt9kb%2522%253A%257B%2522id%2522%253A%2522clycgbyct00063b6kb34xt9kb%2522%252C%2522activeTabId%2522%253A%2522clycl16ex006e3b6kirsg8wl8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00053b6k9kwil1nk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clycgs37f00a33b6kos5brt66%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clycl16ex006e3b6kirsg8wl8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clycgbyct00043b6kl01l9es3%2522%253A%257B%2522id%2522%253A%2522clycgbyct00043b6kl01l9es3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycgbyct00033b6kj8gn5wwb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clycgbyct00033b6kj8gn5wwb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

试了一下打包体积是有差异的，生产环境也是不能使用菜单的，不过开发环境为什么还能用我们需要再看一下
![image](https://github.com/VisActor/VTable/assets/25134429/62270fa4-b713-4bbc-8d94-80a333881aaa)
