### ISSUE TITLE
[Bug] PivotTable透视列表滚动行维度内容不全

### ISSUE THREAD

**Issue by Joeays** [VisActor/VTable#1869]
### Version

0.18.1

### Link to Minimal Reproduction

1

### Steps to Reproduce

内容不全，这是什么情况。
![微信截图_20240606134330](https://github.com/VisActor/VTable/assets/74179094/e3155b7b-9767-44e6-8e08-60c810be4e7c)

### Current Behavior

官网给出的这个方案能解决吗？https://www.visactor.com/vtable/faq/7-How%20to%20improve%20the%20performance%20of%20rendering%20a%20large%20number%20of%20charts%20in%20a%20web%20page

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
你升级到最新版本试试吧

**Comment by Rui-Sun** [comment]
提供一下复现的option吧，我们排查一下

**Comment by Joeays** [comment]
改了下行高的计算模式就好了，autoHeight换成默认standard。

**Comment by Rui-Sun** [comment]
> 改了下行高的计算模式就好了，autoHeight换成默认standard。 @Rui-Sun ，但是通过内容计算行高就行不通，原因未知。

提供一下复现的option吧，我们排查一下

**Comment by Joeays** [comment]
[test.zip](https://github.com/user-attachments/files/15800882/test.zip)
