### ISSUE TITLE
[Bug] 文档部分页面渲染错误

### ISSUE THREAD

**Issue by fourteendp** [VisActor/VTable#1870]
### Version

1.1.1

### Link to Minimal Reproduction

无

### Steps to Reproduce

- https://visactor.io/vtable/demo/export/table-export
- https://visactor.io/vtable/demo/table-type/pivot-table-virtual-header
![image](https://github.com/VisActor/VTable/assets/53899166/d3b5a05c-f748-47c2-9b08-3118e93874a9)

### Current Behavior

文档部分页面渲染错误

### Expected Behavior

正常渲染

### Environment

```markdown
浏览器：Microsoft Edge 版本 123.0.2420.81 (正式版本) (64 位)
操作系统： win11
```

**Comment by fangsmile** [comment]
已修正
