### ISSUE TITLE
内存泄漏[Bug] 

### ISSUE THREAD

**Issue by ahuiiiiiii** [VisActor/VTable#1871]
### Version

0.25.7

### Link to Minimal Reproduction

https://codepen.io/ahuiiiiiii/pen/pomEMxg

### Steps to Reproduce

1.打开最小复现链接、
2.打开谷歌浏览器工具，点击内存，点击开启监控
3.不停点击开启跟关闭按钮
4.过一段时间就点下停止监控
5.重复3，4

### Current Behavior

不断创建表格跟release表格，发现内存线性增长

### Expected Behavior

内存资源能被正确释放，内存能下降到创建之前的容量

### Environment

```markdown
- OS:windows 11
- Browser: 125.0.6422.114（正式版本）
- Framework: 无
```

### Any additional comments?

![Uploading 335441575-eeca4912-7c90-4b1f-a654-ffd0d0094c47.png…]()

**Comment by ahuiiiiiii** [comment]
![335441575-eeca4912-7c90-4b1f-a654-ffd0d0094c47](https://github.com/VisActor/VTable/assets/49714450/47eebfb9-21d8-438d-8f85-a3d8f92c2042)
补充文件，之前好像打不开

**Comment by fangsmile** [comment]
你可以试一下版本 1.2.1-alpha.0  看下是否已经修复 @ahuiiiiiii
