### ISSUE TITLE
[Feature] 表格编辑时，英文单词下面有波浪线，不知怎么设置，取消它，求大佬指教一下！

### ISSUE THREAD

**Issue by sfeng95** [VisActor/VTable#1888]
### What problem does this feature solve?

表格编辑时，英文单词下面有波浪线，不知怎么设置，取消它，求大佬指教一下！
![Uploading 微信截图_20240611173637.png…]()

### What does the proposed API look like?

表格编辑时，英文单词下面有波浪线，不知怎么设置，取消它，求大佬指教一下！

**Comment by sfeng95** [comment]
![Uploading 微信截图_20240611173637.png…]()

**Comment by fangsmile** [comment]
图片没有上传成功。

不过听着感觉是你的浏览器有什么英文纠错的插件

**Comment by sfeng95** [comment]
> 图片没有上传成功。
> 
> 不过听着感觉是你的浏览器有什么英文纠错的插件

我也是这么觉得，在chrome中，input、textarea中英文单词的红色波浪线是浏览器默认开启了语法检查导致的。

只需要在textarea或者input中添加属性spellcheck=“false” 即可去除该波浪线：

<textarea spellcheck="false" autocomplete="off" autocapitalize="off" autocorrect="off"></textarea>

问题是我需要改源码

**Comment by fangsmile** [comment]
那你自定义一个编辑器就可以了 很简单的 你可以继承下textareaEditor那个类

**Comment by sfeng95** [comment]
> 那你自定义一个编辑器就可以了 很简单的 你可以继承下textareaEditor那个类

多谢大佬指教！
