### ISSUE TITLE
[Bug] 透视分析表指标无法展示原始值

### ISSUE THREAD

**Issue by Huangjiahui2233** [VisActor/VTable#1897]
### Version

1.2.0

### Link to Minimal Reproduction

https://github.com/VisActor/VTable/issues/718

### Steps to Reproduce

![image](https://github.com/VisActor/VTable/assets/64945423/0c56dbce-2737-4e2b-a2b4-08f260da8a8a)

### Current Behavior

无法展示原始值，包括format函数和style函数中，也无法获取到原始值，全部都转换为0，部分场景需要原始值.
前面的issue有解决过此问题，目前又重新复现 [ISSUE718](https://github.com/VisActor/VTable/issues/718)

### Expected Behavior

1. 能够将无法转为数字的单元格显示原始值。
2. 在format、style函数中将原始值返回，目前函数式的style参数中的dataValue中也是转换过后的值，前几个版本印象value才是转换后的，dataValue是最原始的值

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
https://visactor.io/vtable/option/PivotTable#dataConfig.aggregationRules

![image](https://github.com/VisActor/VTable/assets/3468473/2e54b46f-5546-428e-a11a-fe4a67ff2d50)
你需要配置下 不做聚合


https://visactor.io/vtable/guide/data_analysis/pivot_table_dataAnalysis

**Comment by Huangjiahui2233** [comment]
> https://visactor.io/vtable/option/PivotTable#dataConfig.aggregationRules
> 
> ![image](https://private-user-images.githubusercontent.com/3468473/338915607-2e54b46f-5546-428e-a11a-fe4a67ff2d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODc0MzEsIm5iZiI6MTcxODE4NzEzMSwicGF0aCI6Ii8zNDY4NDczLzMzODkxNTYwNy0yZTU0YjQ2Zi01NTQ2LTQyOGUtYTExYS1mZTRhNjdmZjJkNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTAxMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI0ODVkMzQ1NTliZDJhZmVhNWI5ZGExOTQ3NzlkNmI3NzMxOWU1ZjFlOWM2ZjhmZWZlYmZkNzBjMjhmMWJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xDrsVkbUV099xV3ltG3UrfJcTS5YLiTNF58qB-M7UgM) 你需要配置下 不做聚合
> 
> https://visactor.io/vtable/guide/data_analysis/pivot_table_dataAnalysis

谢谢，已解决
