### ISSUE TITLE
[Feature] PivotTable's corner can support customRender  customLayout 

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#1907]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/3468473/8cf141fc-3566-4050-85f9-ded02baeed66)
use this feature can write this demo

### What does the proposed API look like?

1

**Comment by LofiSu** [comment]
请问params.disableHeaderSelect在那里呢？

**Comment by LofiSu** [comment]
function cellRenderer(params) {
  if (params.disableHeaderSelect) {
    // 禁用鼠标点击选择
    params.eHeaderCell.addEventListener('click', function(event) {
      event.stopPropagation();
    });

    // 禁用键盘快捷键选择
    document.addEventListener('keydown', function(event) {
      if (event.ctrlKey && event.key === 'a') {
        event.preventDefault();
      }
      // 处理方向键逻辑
      if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) {
        // 检查当前焦点是否在头部，如果是，则取消选择
        if (document.activeElement === params.eHeaderCell) {
          event.preventDefault();
        }
      }这样可行吗

**Comment by ziqiangai** [comment]
Let me try.

**Comment by fangsmile** [comment]
具体需求是给角头增加自定义渲染能力 也就是增加customRender和customLayout的配置到corner  。然后通过自定义能力实现这样一个demo。
![image](https://github.com/user-attachments/assets/e2b52234-8bf1-47e6-bdfb-8ee6179802d4)

需要注意的是：
customRender和customLayout的作用目前是给当前单元格定义自定义渲染，例如角头部分是两个单元格的时候，配置了自定义渲染，和目前其他地方的自定义渲染逻辑一样在两个单元格分别进行自定义绘制
![image](https://github.com/user-attachments/assets/b8a557ec-5685-42bb-b2b5-4f48833eb6cd)
但是我们实现的目前是需要有合并的能力，也就是两个单元格是按一个单元格来渲染自定义内容的。这个开发前需要需要参考学习自定义合并单元格能力：
https://visactor.io/vtable/demo/basic-functionality/custom-merge，
https://visactor.io/vtable/option/ListTable#customMergeCell
以及分组标题的合并及自定义渲染：
https://visactor.io/vtable/demo/table-type/list-table-group
https://visactor.io/vtable/option/ListTable#groupTitleCustomLayout
