### ISSUE TITLE
[Bug] PivotChart indicatorsAsCol为true时数据显示反了

### ISSUE THREAD

**Issue by a1419735487** [VisActor/VTable#1915]
### Version

1.3.0

### Link to Minimal Reproduction

-1

### Steps to Reproduce

![img_v3_02bq_219d941e-7c74-42d2-94d6-f54b9a5bb01g](https://github.com/VisActor/VTable/assets/72694814/935408da-c655-45db-8e50-9fcbb07cc98f)

### Current Behavior

{
        "indicators": [
          {
            "indicatorKey": "indicator_val_0",
            "chartSpec": {
                "series": [
                    {
                        "xField": "indicator_val_0",
                        "data": {
                            "id": "e0045e5fa98d4ba78218743ff90bae34",
                        },
                        "yField": [
                            "region",
                            "indicator_key_0"
                        ],
                        "type": "bar",
                        "direction": "horizontal",
                        "width": "auto",
                        "size": 18,
                    }
                ],
                "type": "common",
                "size": 18,
            },
            "cellType": "chart",
            "chartModule": "vchart",
            "style": {
                "padding": 1
            }
        }
      ],
      "indicatorsAsCol": true,
      "records": [
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "5566",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "华东",
            "indicator_val_0": "5566"
        },
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "2674",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "华北",
            "indicator_val_0": "2674"
        },
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "3246",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "东北",
            "indicator_val_0": "3246"
        },
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "1804",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "西南",
            "indicator_val_0": "1804"
        },
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "4869",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "中南",
            "indicator_val_0": "4869"
        },
        {
            "colorset_2": "数量",
            "indicator_title_0": "数量",
            "color_set_name": "数量",
            "col_fld_tmp_zb_3": "1014",
            "col_fld_tmp_zb_3_title": "数量",
            "indicator_key_0": "数量",
            "segmentation": "消费者",
            "series_field_01": "数量  ",
            "region": "西北",
            "indicator_val_0": "1014"
        }
      ],
      "widthMode": "standard",
      "heightMode": "standard",
      "autoFillWidth": true,
      "autoFillHeight": true,
      "axes": [
          {
              "orient": "left",
              "visible": true,
              "zero": true,
              "sampling": false,
          },
          {
              "orient": "bottom",
              "visible": true,
              "zero": true,
              "nice": true,
              "sampling": false,
          },
      ],
    }

### Expected Behavior

-1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
请将vchart  相关spec配置中的"direction": "horizontal",  设置在series外层
