### ISSUE TITLE
[Feature] 能否支持style函数上的cellHeaderPaths属性也添加到format函数的参数上？

### ISSUE THREAD

**Issue by Huangjiahui2233** [VisActor/VTable#1944]
### What problem does this feature solve?

能够解决在部分行或者部分列的时候，format不同的数据格式

### What does the proposed API look like?

和函数方式的style一致

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/670622d9-1b7f-4edf-b8e7-7ab7f6c85578)
接口中有 直接获取即可，非通用性的参数无需都传递 浪费性能的
