### ISSUE TITLE
[Bug] 鼠标按下后移动鼠标，不触发onMouseMoveCell、onMouseEnterCell

### ISSUE THREAD

**Issue by YUOrz233** [VisActor/VTable#1950]
### Version

1.2.0

### Link to Minimal Reproduction

-

### Steps to Reproduce

按下鼠标后，移动鼠标
```js
onMouseDownCell={(params) => {
  console.log('onMouseDownCell11111', params);
}}
onMouseEnterCell={(params) => {
  console.log('onMouseEnterCell22222', params);
}}
onMouseMoveCell={(params) => {
  console.log('onMouseMoveCell33333', params);
}}
```

### Current Behavior

按下鼠标后，移动鼠标，没有触发onMouseEnterCell、onMouseMoveCell事件

### Expected Behavior

按下鼠标后，移动鼠标，触发onMouseEnterCell、onMouseMoveCell事件

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到 
这个问题是否可以自行来调试找找原因？ 可以贡献代码提pr哈   我们目前手头上任务还是挺多  需要排后解决的话

**Comment by fangsmile** [comment]
这个不是问题吧  html中 鼠标按下也是会触发mousemove事件的  如果需要区分出来的话 可以鼠标按下的时候记录个状态。

**Comment by YUOrz233** [comment]
我需要的就是鼠标按下，然后不松开，移动鼠标，也触发mousemove。问题是鼠标按下后，移动鼠标，没触发mousemove @fangsmile
