### ISSUE TITLE
[Feature] react-vtable实例支持配置emptyTip

### ISSUE THREAD

**Issue by liumengyaoo** [VisActor/VTable#1952]
### What problem does this feature solve?

支持通过以下方式配置emptyTip
```
 <PivotTable
  emptyTip= {{ text: '暂无数据' }}
  />
```

### What does the proposed API look like?

对齐options中的emptyTip

**Comment by Aluomolo** [comment]
认领

**Comment by xuanhun** [comment]
> 认领

Thanks！I  will invite you to the developer group.
