### ISSUE TITLE
[Bug] 透视表拖拽改变指标列宽后点击排序，表格宽度发生变化，并出现空白区域

### ISSUE THREAD

**Issue by liumengyaoo** [VisActor/VTable#1958]
### Version

1.3.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-vvvrjq?file=%2Fsrc%2Findex.ts%3A456%2C17

### Steps to Reproduce

1.拖拽改变指标列宽
2.点击排序

### Current Behavior

 透视表拖拽改变指标列宽后点击排序，表格宽度发生变化，并出现空白区域

### Expected Behavior

拖拽改变指标列宽后点击排序表格列宽不发生变化

### Environment

```markdown
- OS:
- Browser:chrome
- Framework:
```

**Comment by Rui-Sun** [comment]
![image](https://github.com/VisActor/VTable/assets/25134429/d532bb4b-ade0-42ce-9c15-f44e54bfc379)
