### ISSUE TITLE
[Bug] 自定义编辑器validateValue方法返回false时仍能点击选中其他单元格

### ISSUE THREAD

**Issue by CrabSAMA** [VisActor/VTable#1974]
### Version

1.4.0

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/edit/custom-editor

### Steps to Reproduce

https://visactor.io/vtable/demo/edit/custom-editor
在官方示例中，自定义editor实现validateValue方法，此处为了简单演示直接返回false
```typescript
validateValue() {
  return false;
}
```

双击单元格进入编辑状态后，模拟校验不通过的场景（直接返回false），此时用户习惯是直接点击外层取消编辑状态。
![20240624143316_rec_](https://github.com/VisActor/VTable/assets/40541269/6183cb5e-0d0f-4d7c-9cd6-76816e4476e3)

### Current Behavior

现状是：不取消编辑状态，其他单元格被选中

### Expected Behavior

预期是：不取消编辑状态，不选中其他单元格，保留当前编辑状态的单元格选中状态

### Environment

```markdown
- OS:macOS 14.1.1 (23B81)
- Browser: edge 126.0.6478.62
- Framework: Vue@2.6.12 & VTable@1.4.0
```

**Comment by fangsmile** [comment]
看看 是否可以尝试解决这个问题 贡献代码提pr给我们呢？
可以加飞书群如有不清楚的代码逻辑 可以沟通
![image](https://github.com/VisActor/VTable/assets/3468473/eaf5f275-6e32-49c7-87ad-31e42a2007d8)
