### ISSUE TITLE
基础数据表格-树结构-更改hierarchyExpandLevel的值，调用updateOption不生效

### ISSUE THREAD

**Issue by frank-zyb** [VisActor/VTable#1976]
### Version

1.3.0

### Link to Minimal Reproduction

https://visactor.io/vtable/api/Methods#updateOption

### Steps to Reproduce

树结构，默认展开一层，点击按钮一键展开2层，执行以下代码
this.option.hierarchyExpandLevel = 2;
        this.tableInstance.updateOption(this.option);  并未生效

### Current Behavior

updateOption没有生效

### Expected Behavior

updateOption可以生效

### Environment

```markdown
- OS:maxOS
- Browser: chrome
- Framework:"vue": "^2.7.16",   "@visactor/vtable": "^1.3.0",
```

**Comment by Rui-Sun** [comment]
可以重新提一个使用优化issue

**Comment by frank-zyb** [comment]
已经解决了，需要手动删除tree结构中每个节点的hierarchyState属性，让后在执行上述代码
