### ISSUE TITLE
Is whether there exists an API for exporting HTML？

### ISSUE THREAD

**Issue by GuangYiL** [VisActor/VTable#1982]
If I want to export a supported "htmlemail" or "html" format string, can you provide some ideas?

**Comment by fangsmile** [comment]
导出图片 嵌入到html中呢？

**Comment by GuangYiL** [comment]
> 导出图片嵌入到html中呢？

谢谢，因为项目需要表格可编辑，目前我自己根据data数据转换为html的table组件了，邮件支持的html格式太古老了😅。

**Comment by fangsmile** [comment]
好的
