### ISSUE TITLE
导出excel功能优化[Feature] 

### ISSUE THREAD

**Issue by xiaochong444** [VisActor/VTable#1989]
### What problem does this feature solve?

当前导出excel时是直接导出表格的字符，如果表格使用了格工化函数，比如数字加了千分号或者百分比等，导出EXCEL就变成了文本格式，这个时间要进行二次加工就非常的麻烦了。

### What does the proposed API look like?

希望导出的时候可以支持原始值导出，并有选项可以配置每一列的格式化字符，这样可以适配excel里的单元格格式，不影响表格的二次加工。

**Comment by Rui-Sun** [comment]
https://www.visactor.io/vtable/guide/export/excel
![image](https://github.com/VisActor/VTable/assets/25134429/fcfade16-e0ee-46e8-8524-428a73a65778)
目前已经提供了导出格式化接口，调用table.getCellOriginValue(col,row)可获取原始数据；如果需要匹配excel数据，需要返回值符合exceljs value规则 https://github.com/exceljs/exceljs/tree/master?tab=readme-ov-file#value-types

**Comment by xiaochong444** [comment]
@

> https://www.visactor.io/vtable/guide/export/excel ![image](https://private-user-images.githubusercontent.com/25134429/344015934-fcfade16-e0ee-46e8-8524-428a73a65778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjE3OTUsIm5iZiI6MTcxOTgyMTQ5NSwicGF0aCI6Ii8yNTEzNDQyOS8zNDQwMTU5MzQtZmNmYWRlMTYtZTBlZS00NmU4LTg1MjQtNDI4YTczYTY1Nzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGM4NGI1NDQ4ZjY0ZDY2NTljM2U2NDk3ZDQ0ZDFlMzI3MWQzNzNmYjYyZmNlYzRlYzBkMDBlYmE4NWQwMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4dfshe22Oaexd4-olnC83JToeRogTd6lq-dI0QWRkBI) 目前已经提供了导出格式化接口，调用table.getCellOriginValue(col,row)可获取原始数据；如果需要匹配excel数据，需要返回值符合exceljs value规则 https://github.com/exceljs/exceljs/tree/master?tab=readme-ov-file#value-types

现在返回的只是值，格式化需要用到exceljs的numFmt ，感觉现在设计的导出格式化问题有点不对吧，应该是改显示格式，不是改单元格的值
