### ISSUE TITLE
[Bug] 发现个简单的小bug，当columns的所有width为auto时，rowSeriesNumber的width属性会失效

### ISSUE THREAD

**Issue by sfeng95** [VisActor/VTable#1996]
### Version

1.4

### Link to Minimal Reproduction

rowSeriesNumber的width属性失效

### Steps to Reproduce

发现个简单的小bug，当columns的所有width为auto时，rowSeriesNumber的width属性会失效，或者列太少的时候，rowSeriesNumber的width属性也会失效****

### Current Behavior

发现个简单的小bug，当columns的所有width为auto时，rowSeriesNumber的width属性会失效，或者列太少的时候，rowSeriesNumber的width属性也会失效****
![a](https://github.com/VisActor/VTable/assets/21358616/922156f3-0539-4e6d-adc6-ca46d248df27)

![b](https://github.com/VisActor/VTable/assets/21358616/40b0833a-0857-4bd6-9e22-eb559668405e)

### Expected Behavior

发现个简单的小bug，当columns的所有width为auto时，rowSeriesNumber的width属性会失效，或者列太少的时候，rowSeriesNumber的width属性也会失效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by sfeng95** [comment]
即使是设置了disableColumnResize: true,也没有

**Comment by Rui-Sun** [comment]
![image](https://github.com/VisActor/VTable/assets/25134429/6ca2dbb7-3189-44c2-aafc-f4f3941edd0c)
是有设置widthMode: adaptive或者autoFillWidth吗？没能复现这个问题

**Comment by sfeng95** [comment]
的确是因为autoFillWidth:true导致的，但是autoFillWidth开启时候，应该不能改变rowSeriesNumber的宽才对。

**Comment by Rui-Sun** [comment]
这个需求有记载这个issue上 #1917 ，后续会支持，这个bug issue先关闭了
