### ISSUE TITLE
[Bug] 设置了分页属性，但是并没有显示出分页器

### ISSUE THREAD

**Issue by little-yaonv** [VisActor/VTable#2000]
### Version

^0.23.4

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/list-table-data-analysis/list-table-aggregation-multiple

### Steps to Reproduce

需要使用分页功能，在表格的option中设置了分页属性
pagination: {
    perPageCount: 100,
    currentPage: 0
  },

### Current Behavior

并没有显示出分页器

### Expected Behavior

需要显示出分页器

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
分页器是需要自己来做的 上述配置 只是让vtable来展示对应的数据。https://visactor.io/vtable/demo/basic-functionality/pagination 可以参考demo代码 或者使用其他ui组件的翻页器

**Comment by little-yaonv** [comment]
好的，我看这个demo上切换页数使用的是
tableInstance.updatePagination({
        currentPage: i - 1
      });
我们这边是在react环境中使用，用的是@visactor/react-vtable包，并不是通过new VTable.ListTable的方式，所以没有tableInstance，那要如何使用updatePagination这个方法呢

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/a0a4142e-3456-4460-ae43-25bb6813faa8)
@little-yaonv  可多翻阅看看demo

**Comment by little-yaonv** [comment]
好的，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VTable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VTable] [Bug] 设置了分页属性，但是并没有显示出分页器 (Issue #2000)





 
image.png (view on web)
 @little-yaonv  可多翻阅看看demo
