### ISSUE TITLE
[Feature] 能否在选中多个单元格的情况下，保持行高亮的状态？

### ISSUE THREAD

**Issue by mzhang-eric** [VisActor/VTable#2026]
### What problem does this feature solve?

当设置单元格选中响应模式为整行高亮时，选中单个单元格时，所在行会出现高亮样式，但通过Ctrl Shift 快捷键或鼠标框选选中多个单元格，行的高亮状态不存在了，selectionStyle.inlineRowBgColor 没有生效。
```
const option = {
    select: {
        highlightMode: 'row'
    },
   selectionStyle: {
      cellBgColor: 'rgba(0, 174, 199, 0.2)',
      cellBorderLineWidth: 1,
      cellBorderColor: '#3dc1d4',
      inlineRowBgColor: '#86dbeb',
  },
}
```

### What does the proposed API look like?

希望在选中多个单元格的时候，单元格所在的行都能保持高亮状态

**Comment by fangsmile** [comment]
目前的逻辑是只有一个单元格被选中的情况 才会出现整行整列的高亮效果

**Comment by fangsmile** [comment]
我标记了good first issue 看看有没有其他贡献者可以看看这个需求 或者你也可以参与开源共享 提pr

**Comment by taiiiyang** [comment]
这个可以让我尝试下吗

**Comment by taiiiyang** [comment]
> 我标记了good first issue 看看有没有其他贡献者可以看看这个需求 或者你也可以参与开源共享 提pr

这个可以让我尝试下吗
