### ISSUE TITLE
[refactor] indicator 隐藏不完全

### ISSUE THREAD

**Issue by zamhown** [VisActor/VTable#2070]
[option.json](https://github.com/user-attachments/files/16158091/option.json)

在设置`"hideIndicatorName": true`时，不希望出现额外的 indicator 单元格：
![image](https://github.com/VisActor/VTable/assets/15249097/72e6c531-0e26-4617-be7b-9931f5dc5fc4)

**Comment by 1379255913** [comment]
使用最新的1.5.2的版本，问题似乎还存在
![QQ_1721109901100](https://github.com/user-attachments/assets/34c44fd4-b76b-47ad-9dfe-1623ae70846c)
![QQ_1721109974071](https://github.com/user-attachments/assets/ccda1644-a1ad-4682-bd23-c0ebab798400)

**Comment by fangsmile** [comment]
![飞书20240716-140927](https://github.com/user-attachments/assets/e01778a8-b1e4-4432-bae4-a8c19c851891)
你进下群 加我下吧 我跟你说下目前的使用方式   @1379255913 
上面那个问题目前的解决方式不是从源头解决的
