### ISSUE TITLE
[Bug] RESIZE_COLUMN_END 列宽调整结束事件会触发两次

### ISSUE THREAD

**Issue by mzhang-eric** [VisActor/VTable#2101]
复现步骤：

1.打开官方示例：[事件监听](https://visactor.io/vtable/demo-react/event/event)

2.监听 RESIZE_COLUMN_END 事件

```
onResizeColumnEnd={args => {
      alert('onResizeColumnEnd');
 }}
```

3.在表格上随意拖动改变某列宽度，结束后alert会出现两次

**Comment by Rui-Sun** [comment]
事件函数使用useMemo包一下吧

**Comment by Rui-Sun** [comment]
确实不太合理，这个我reopen一下，下周排查修复
