### ISSUE TITLE
[Bug] 当异步加载的条数较少时，表格报错 Cannot read 'camera'

### ISSUE THREAD

**Issue by Lionad-Morotar** [VisActor/VTable#2110]
### Version

1.5.0

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/performance/async-data

### Steps to Reproduce

1. 把分页条数改成 10，会发现表格中多了很多“promise”字样，不会自动加载新数据

![image](https://github.com/user-attachments/assets/6cd196b4-14b1-4133-9de1-9e0c9a38c9ac)

2. 继续滚动页面，会出现报错

![image](https://github.com/user-attachments/assets/6cbc6204-6142-43ba-ba80-094429627e8d)

3. 忽略报错，继续滚动，此时页面 JS 线程会卡死（动画还在动，但是页面不能点击、关闭，性能工具也打不开，内存是正常的）

![image](https://github.com/user-attachments/assets/09a00772-d8df-4d7a-a805-b92a6597c929)

### Current Behavior

目前分页较少时，如果第一页的数量小于屏幕高度（比如屏幕能显示 15 条内容，但分页设置为 14），就会触发一系列错误。

### Expected Behavior

希望能自动加载新数据，填满屏幕高度

### Environment

```markdown
- OS: MacOS 14.5
- Browser: Edge
- Framework: -
```

### Any additional comments?

加大分页数就不会有任何问题，但是在一些页面我需要根据屏幕剩余高度动态调整分页数量，这个时候可能会出现计算出来的分页不够填满表格的问题。

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/495f8a4b-247f-448c-a515-90e918d6e29c)
应该真么写，三个需要保持一致

**Comment by Lionad-Morotar** [comment]
sorry, my problem
