### ISSUE TITLE
[Bug] clearSelected API无法清除ctrl + A. 选中的单元格

### ISSUE THREAD

**Issue by feEden** [VisActor/VTable#2115]
### Version

1.5.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-c33q9r?file=%2Fsrc%2Findex.ts%3A78%2C1

### Steps to Reproduce

如codesandbox所示

### Current Behavior

1. ctrl + a 选中所有单元格，调用clearSelected, 无法取消选中。单击选中或者点击表头选中是可以做到取消的
2. 配置了outsideClickDeselect=true 点击非表格外的区域无法取消选中，只有点击canvas区域才行

### Expected Behavior

1. ctrl + a 选中所有单元格，调用clearSelected, 应该取消选中
2. 配置了outsideClickDeselect=true 点击非表格外的区域应该取消选中

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
![20240723120314_rec_](https://github.com/user-attachments/assets/c6fce459-bddf-4aaf-856b-d69a1ffeabee)
我这试了下outsideClickDeselect  没问题哦

**Comment by feEden** [comment]
> ![20240723120314_rec_](https://private-user-images.githubusercontent.com/3468473/351181493-c6fce459-bddf-4aaf-856b-d69a1ffeabee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkyOTEsIm5iZiI6MTcyNTI1ODk5MSwicGF0aCI6Ii8zNDY4NDczLzM1MTE4MTQ5My1jNmZjZTQ1OS1iZGRmLTRhYWYtODU2Yi1kNjlhMWZmZWFiZWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3ZGIwYWUzOGQ5MzM4MjQ1MzFlMzdlNWM3OGY1NDRmYTJkZDA0MWVjMTI0MzI5ODUwOTI1OTcwMjg3ZDgxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BN8y7WkUgwM5JMRGwpB4usdO5ZbIne6TFdwpmbmUvXU) [ ![20240723120314_rec_](https://private-user-images.githubusercontent.com/3468473/351181493-c6fce459-bddf-4aaf-856b-d69a1ffeabee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkyOTEsIm5iZiI6MTcyNTI1ODk5MSwicGF0aCI6Ii8zNDY4NDczLzM1MTE4MTQ5My1jNmZjZTQ1OS1iZGRmLTRhYWYtODU2Yi1kNjlhMWZmZWFiZWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3ZGIwYWUzOGQ5MzM4MjQ1MzFlMzdlNWM3OGY1NDRmYTJkZDA0MWVjMTI0MzI5ODUwOTI1OTcwMjg3ZDgxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BN8y7WkUgwM5JMRGwpB4usdO5ZbIne6TFdwpmbmUvXU) ](https://private-user-images.githubusercontent.com/3468473/351181493-c6fce459-bddf-4aaf-856b-d69a1ffeabee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkyOTEsIm5iZiI6MTcyNTI1ODk5MSwicGF0aCI6Ii8zNDY4NDczLzM1MTE4MTQ5My1jNmZjZTQ1OS1iZGRmLTRhYWYtODU2Yi1kNjlhMWZmZWFiZWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3ZGIwYWUzOGQ5MzM4MjQ1MzFlMzdlNWM3OGY1NDRmYTJkZDA0MWVjMTI0MzI5ODUwOTI1OTcwMjg3ZDgxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BN8y7WkUgwM5JMRGwpB4usdO5ZbIne6TFdwpmbmUvXU) [ ](https://private-user-images.githubusercontent.com/3468473/351181493-c6fce459-bddf-4aaf-856b-d69a1ffeabee.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTkyOTEsIm5iZiI6MTcyNTI1ODk5MSwicGF0aCI6Ii8zNDY4NDczLzM1MTE4MTQ5My1jNmZjZTQ1OS1iZGRmLTRhYWYtODU2Yi1kNjlhMWZmZWFiZWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3ZGIwYWUzOGQ5MzM4MjQ1MzFlMzdlNWM3OGY1NDRmYTJkZDA0MWVjMTI0MzI5ODUwOTI1OTcwMjg3ZDgxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BN8y7WkUgwM5JMRGwpB4usdO5ZbIne6TFdwpmbmUvXU) 我这试了下outsideClickDeselect 没问题哦

试试多选再点击呢
