### ISSUE TITLE
[Feature] prevent dragging row/column to the front of row header/column header

### ISSUE THREAD

**Issue by purpose233** [VisActor/VTable#2129]
### What problem does this feature solve?

图表助手中透视表的行列头是固定的，拖拽操作希望能够禁止行列拖拽到行头/列头前面：
![img_v3_02d4_e6b3f0f6-a915-4b3e-a6a8-f54270d88f9g](https://github.com/user-attachments/assets/b0a3dbd1-7c43-47be-86bb-e9d3bec613eb)

### What does the proposed API look like?

dragHeaderMode: string

**Comment by skie1997** [comment]
期望8.1之前
