### ISSUE TITLE
[Feature] 实现某一行或者某一区域的单元格禁止编辑

### ISSUE THREAD

**Issue by wangziqi7** [VisActor/VTable#2139]
### What problem does this feature solve?

通过树形结构实现了类似于分组的功能，分组条件作为父级合并了当前行的单元格，为此实现某一行或者某一区域的单元格禁止编辑

### What does the proposed API look like?

开放一个禁止编辑的方法，入参为row和col

**Comment by fangsmile** [comment]
editor可以配置函数的，不需要编辑的情况返回个空就行

**Comment by wangziqi7** [comment]
editor现在可以在全局或者某一列设置，无法通过rows设置，而我想实现的效果是这一列某几个单元格不能编辑，其他单元格需要编辑

**Comment by fangsmile** [comment]
![20240730104641_rec_](https://github.com/user-attachments/assets/28cb0071-a1e9-40ab-97c7-315473fcdc41)
利用函数呀

**Comment by wangziqi7** [comment]
![image](https://github.com/user-attachments/assets/ae261c15-0ba9-4d5e-b51c-296a5e4c7ed9)
谢谢。。。这里没看懂能这么写

**Comment by wangziqi7** [comment]
![image](https://github.com/user-attachments/assets/5be8fdb8-28b3-4126-9774-1ee32d49847e)
谢谢。。。刚看到这里有args的参数。。。
