### ISSUE TITLE
[Bug] 使用VText自定义渲染，tooltip 显示错位

### ISSUE THREAD

**Issue by QaQ-top** [VisActor/VTable#2140]
### Version

1.5.3

### Link to Minimal Reproduction

[示例](https://codesandbox.io/p/sandbox/vtable-custom-rendering-sgtqj8?file=%2Fsrc%2Fapp.ts)

### Steps to Reproduce

```tsx
{
    field: '230517143221027',
    title: 'Order ID',
    width: 'auto',
    render: (params, { VGroup, VText, VTag }) => {
      return {
        rootContainer: (
          <VGroup
            attribute={{
              width: params.rect?.width,
              height: params.rect?.height,
              fill: '#000',
              opacity: 0.1,
            }}
          >
            <VText
              attribute={{
                text: params.value,
                fontSize: 16,
                textBaseline: 'top',
                fontWeight: 600,
                lineHeight: params.rect?.height,
                maxLineWidth: params.rect?.width,
                ellipsis: true,
                fill: '#000',
                cellInfo: params,
              }}
              stateProxy={(stateName) => {
                if (stateName == 'hover') {
                  return {
                    fill: '#0568b9',
                    cursor: 'pointer',
                  };
                } else {
                  return {};
                }
              }}
              onMouseEnter={({ currentTarget }) => {
                currentTarget.addState('hover', true, false);
                currentTarget.stage?.renderNextFrame();
              }}
              onMouseLeave={function (params) {
                const { currentTarget } = params;
                console.log(event);
                currentTarget.removeState('hover', false);
                console.log(this.attribute.cellInfo, params, 'FFF');
                currentTarget.stage?.renderNextFrame();
              }}
            ></VText>
          </VGroup>
        ),
      };
    },
    sort: true,
    dropDownMenu: [
      {
        text: 'ere',
        menuKey: 'aki',
      },
      {
        text: 'FSZdz',
        menuKey: 'zdz',
      },
    ],
    editor: EditorSymbol.Input,
  }
```

### Current Behavior

![QQ_1722248729008](https://github.com/user-attachments/assets/6a3276d8-93d9-4a09-bf52-3db916f0ce22)

### Expected Behavior

正常显示如下
![QQ_1722248901331](https://github.com/user-attachments/assets/144af6b4-34b5-4193-ba35-7e1329a98329)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by QaQ-top** [comment]
@fangsmile 
![QQ_1722308290753](https://github.com/user-attachments/assets/6ad335ae-642f-4066-bde4-cb6e27cf39f3)
我在使用自定义 tooltip 时出现了两个，一个是html渲染，一个是canvas渲染，我又想用VText的`ellipsis`，有没有方法解决这个问题；
```tsx
          table.on('mouseenter_cell', (args) => {
            const { col, row } = args;
            console.log(args, "args")
            if (row >= 1) {
              const value = table.getCellValue(col,row);
              const rect = table.getVisibleCellRangeRelativeRect({ col, row });
              table.showTooltip(col, row, {
                content: value,
                referencePosition: { rect, placement: Placement.bottom },
                className: 'defineTooltip',
                style: {
                  bgColor: 'black',
                  color: 'white',
                  arrowMark: true,
                },
              });
            }
          });
```
我在使用`showTooltip`方法时候，是否能知道我文本内容是否超出，然后我选择性的执行？

**Comment by Rui-Sun** [comment]
可以用事件参数中的的target，移动到文字的时候，target为text图元，其中有clip属性，为true时表示该图元文字被截断

```
  const { MOUSEMOVE_CELL } = VTable.ListTable.EVENT_TYPE;
  instance.addEventListener(MOUSEMOVE_CELL, (...args) => {
    console.log('MOUSEMOVE_CELL', args[0]?.target);
  });
```
![image](https://github.com/user-attachments/assets/913d1c3e-46a2-4219-835f-48d0a9c4479b)

**Comment by QaQ-top** [comment]
> 可以用事件参数中的的target，移动到文字的时候，target为text图元，其中有clip属性，为true时表示该图元文字被截断
> 
> ```
>   const { MOUSEMOVE_CELL } = VTable.ListTable.EVENT_TYPE;
>   instance.addEventListener(MOUSEMOVE_CELL, (...args) => {
>     console.log('MOUSEMOVE_CELL', args[0]?.target);
>   });
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/25134429/353391633-913d1c3e-46a2-4219-835f-48d0a9c4479b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzAyNzksIm5iZiI6MTcyMjMyOTk3OSwicGF0aCI6Ii8yNTEzNDQyOS8zNTMzOTE2MzMtOTEzZDFjM2UtNDZhMi00MjE5LTgzNWYtNDhkMGE5YzQ0NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4NTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDI0OTg3YWY4N2FjYzNhNmE3MjJkN2JlZWQ1MTgzMmZiOWMyMWY5NTMwNWJjZmQzMmE2NmViNzA5MzVjYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnCb9jrX6YvKemRp3YtW8emU5StnbW_x1pwPB1uha-4)

👍可以，感谢
