### ISSUE TITLE
如何设置全局主题和样式

### ISSUE THREAD

**Issue by liuhuan1011** [VisActor/VTable#2150]
如何在react脚手架全局设置主题和样式呢

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/96e9f62b-7c5b-47e1-9e28-a2a4dc3cbd4b)

**Comment by tylerrrkd** [comment]
大佬你好，为啥我设置主题无效呢？ @Rui-Sun 

```tsx
import { ListTableSimple } from '@visactor/react-vtable';
import { themes } from '@visactor/vtable';

...

<ListTableSimple
  theme={themes.DARK}
/>

```

也尝试过自己手动设置，均无效，是我的姿势不对吗？

```tsx
<ListTableSimple
   theme={{
      headerStyle: {
        fontSize: 12,
      },
    }}
/>
```

**Comment by tylerrrkd** [comment]
> 大佬你好，为啥我设置主题无效呢？ [@Rui-Sun](https://github.com/Rui-Sun)
> 
> import { ListTableSimple } from '@visactor/react-vtable';
> import { themes } from '@visactor/vtable';
> 
> ...
> 
> <ListTableSimple
>   theme={themes.DARK}
> />
> 也尝试过自己手动设置，均无效，是我的姿势不对吗？
> 
> <ListTableSimple
>    theme={{
>       headerStyle: {
>         fontSize: 12,
>       },
>     }}
> />

因为 传递了  `option` 时需要在 `option` 内声明 `theme`
