### ISSUE TITLE
[Feature] 单元格绘制 chart 支持数据源为二维数组

### ISSUE THREAD

**Issue by huxiaoyun** [VisActor/VTable#2153]
### What problem does this feature solve?

单元格绘制 chart 支持数据源为二维数组

### What does the proposed API look like?

VTable.register.chartModule('vchart', VChart);
  const columns = [
    {
      field: '0',
      title: 'multiple vchart type',
      width: '320',
      cellType: 'chart',
      chartModule: 'vchart',
      chartSpec(args) {
        return {
          type: 'common',
          series: [
            {
              type: 'line',
              data: {
                id: 'data'
              },
              xField: 'x',
              yField: 'y',
              seriesField: 'type',
              line: {
                state: {
                  hover: {
                    strokeWidth: 4
                  },
                  selected: {
                    stroke: 'red'
                  },
                  hover_reverse: {
                    stroke: '#ddd'
                  }
                }
              },
              point: {
                state: {
                  hover: {
                    fill: 'red'
                  },
                  selected: {
                    fill: 'yellow'
                  },
                  hover_reverse: {
                    fill: '#ddd'
                  }
                }
              },
              legends: [
                {
                  visible: true,
                  orient: 'bottom'
                }
              ]
            }
          ],
          axes: [
            {
              orient: 'left',
              range: {
                min: 0
              }
            },
            {
              orient: 'bottom',
              label: {
                visible: true
              },
              type: 'band'
            }
          ],
          legends: [
            {
              visible: true,
              orient: 'bottom'
            }
          ]
        };
      }
    },
  ];
  const records = [
    [
      { x: '0', type: 'A', y: '100' },
      { x: '1', type: 'A', y: '707' },
      { x: '2', type: 'A', y: '832' },
      { x: '3', type: 'A', y: '726' },
      { x: '4', type: 'A', y: '756' },
    ]
  ]; 
  const option = {
    records,
    columns,
    transpose: false,
    defaultColWidth: 200,
    defaultRowHeight: 200,
    defaultHeaderRowHeight: 50
  };

const tableInstance = new VTable.ListTable(document.getElementById(CONTAINER_ID),option);
window['tableInstance'] = tableInstance;

**Comment by fangsmile** [comment]
配置问题 records少了一层括号
