### ISSUE TITLE
问题：rowtree中的三级支小再贷款不显示数据

### ISSUE THREAD

**Issue by siyueye** [VisActor/VTable#2157]
代码如下：
`<template>
  <div ref="pivotTableRef" id="pivotTableRef" style="width: 1580px; height: 800px"></div>
</template>

<script setup>
  import { onMounted, ref, shallowRef } from "vue";
  import { PivotTable } from "@visactor/vtable";

const pivotTableRef = ref();
const tableInstance = shallowRef();
const records = [
    {
        "S_NORMITEM1": "河北银行",
        "S_NORMITEM2": "",
        "S_NORMITEM3": "支小再贷款",
        "S_LAYERITEM1": "利息",
        "S_LAYERITEM2": "应计单利",
        "F_AMT": 33564165.63
    },
    {
        "S_NORMITEM1": "河北银行",
        "S_NORMITEM2": "",
        "S_NORMITEM3": "支小再贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期末数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "河北银行",
        "S_NORMITEM2": "",
        "S_NORMITEM3": "支小再贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期末数",
        "F_AMT": 3150680000
    },
    {
        "S_NORMITEM1": "河北银行",
        "S_NORMITEM2": "",
        "S_NORMITEM3": "支小再贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期初数",
        "F_AMT": 3150680000
    },
    {
        "S_NORMITEM1": "河北银行",
        "S_NORMITEM2": "",
        "S_NORMITEM3": "支小再贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期初数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "其他农村信用社",
        "S_NORMITEM3": "支农再贷款",
        "S_LAYERITEM1": "利息",
        "S_LAYERITEM2": "应计单利",
        "F_AMT": 59017476.94
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "其他农村信用社",
        "S_NORMITEM3": "支农再贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期末数",
        "F_AMT": 255704000
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "其他农村信用社",
        "S_NORMITEM3": "支农再贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期初数",
        "F_AMT": 255704000
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "流动性贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期末数",
        "F_AMT": 25485353.69
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "流动性贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期初数",
        "F_AMT": 25485353.69
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "金融稳定贷款",
        "S_LAYERITEM1": "利息",
        "S_LAYERITEM2": "应计单利",
        "F_AMT": 493161.67
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "金融稳定贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期末数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "金融稳定贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期初数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "流动性贷款",
        "S_LAYERITEM1": "利息",
        "S_LAYERITEM2": "应计单利",
        "F_AMT": 662619.19
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "流动性贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期末数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "其他农村信用社",
        "S_NORMITEM3": "支农再贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期末数",
        "F_AMT": 6039112400
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "流动性贷款",
        "S_LAYERITEM1": "展期",
        "S_LAYERITEM2": "期初数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "其他农村信用社",
        "S_NORMITEM3": "支农再贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期初数",
        "F_AMT": 6039112400
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "金融稳定贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期末数",
        "F_AMT": ""
    },
    {
        "S_NORMITEM1": "信用社",
        "S_NORMITEM2": "城市信用社",
        "S_NORMITEM3": "金融稳定贷款",
        "S_LAYERITEM1": "账户余额",
        "S_LAYERITEM2": "期初数",
        "F_AMT": ""
    }
];
const rowTree =  [
      {
        dimensionKey: 'S_NORMITEM1',
        value: '河北银行',
        hierarchyState: 'expand',
        children: [
          {
            dimensionKey: 'S_NORMITEM3',
            value: '支小再贷款',
          }
        ]
      },
      {
        dimensionKey: 'S_NORMITEM1',
        value: '信用社',
        hierarchyState: 'expand',
        children: [
          {
            dimensionKey: 'S_NORMITEM2',
            value: '城市信用社',
            hierarchyState: 'expand',
            children: [
              {
                dimensionKey: 'S_NORMITEM3',
                value: '流动性贷款',
                hierarchyState: 'expand',
              },
              {
                dimensionKey: 'S_NORMITEM3',
                value: '金融稳定贷款',
                hierarchyState: 'expand',
              }
            ]
          },
          {
            dimensionKey: 'S_NORMITEM2',
            value: '其他农村信用社',
            hierarchyState: 'expand',
            children: [
              {
                dimensionKey: 'S_NORMITEM2',
                value: '支农再贷款',
                hierarchyState: 'expand',
              }
            ]
          }
        ]
      },
    ];
const option = {
    records: records,
    rowTree:rowTree,
    rowExpandLevel:3,
    rows: ["S_NORMITEM1","S_NORMITEM2","S_NORMITEM3"],
    columns: [
      {
        dimensionKey: 'S_LAYERITEM1',
        title: 'S_LAYERITEM1',
        headerStyle: {
          textStick: true
        },
        width: 'auto'
      },
      {
        dimensionKey: 'S_LAYERITEM2',
        title: 'S_LAYERITEM2',
        headerStyle: {
          textStick: true
        },
        width: 'auto'
      }
    ],
    indicators: [
      {
        indicatorKey: 'F_AMT',
        width: 'auto',
        showSort: false,
        headerStyle: {
          fontWeight: 'normal'
        },
        format: rec => {
          return  Number(rec).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,'); //千位分隔符并强制保留两位小数
        },
        style: {
          padding: [16, 28, 16, 28],
          color(args) {
            if (args.dataValue >= 0) return 'black';
            return 'red';
          }
        }
      },

    ],
    corner: {
      titleOnDimension: 'row',
      headerStyle: {
        textStick: true
      }
    },
    dataConfig: {
      sortRules:[
        {
          sortField: 'S_LAYERITEM1',
          sortBy: ['账户余额','本期发生额','展期','逾期','停息挂账','利息','调整金额'],
         },
         {
          sortField: 'S_NORMITEM1',
          sortBy: ['河北银行','信用社'],
         }
      ],
      totals: {
        row: {
          showGrandTotals: true,
          showSubTotals: true,
          subTotalsDimensions: ['S_NORMITEM1','S_NORMITEM2','S_NORMITEM3'],
          subTotalLabel: '',
          showGrandTotalsonTop:false //汇总值显示在上
        }
      }
    },
    rowHierarchyType: 'tree',
    widthMode: 'standard'
  };

onMounted(() => {
  tableInstance.value = new PivotTable(pivotTableRef.value, option);

  tableInstance.value.on("click_cell", (params) => {
    console.log(params);
  });
});
</script>

<style scoped></style>
`
![Uploading img_v3_02dc_ade9a9d2-361b-4692-8dc1-1775a838caag.jpg…]()

**Comment by siyueye** [comment]
1. 当注释掉   rowTree:rowTree,时，如下图：可以展示数据河北银行下的支小再贷款的数据
2. 当把rowTree中的信用社部分注释掉时，数据也可以展示河北银行下的支小再贷款的数据。

**Comment by fangsmile** [comment]
请使用最新版本吧 应该已经可以显示了，有问题可以再提个新的issue沟通
