### ISSUE TITLE
如何给多维表格的行头标题添加自定义图标

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2175]
请问多维表的行头可以支持自定义指标吗，我在rows里设置之后发现是在每一行里添加了，但是我只想在行头的头标处添加一个自定义图标，并通过该自定义图标实现筛选哪些行显示或隐藏。

**普通表**
![image](https://github.com/user-attachments/assets/74375471-c3f3-4ec6-9d74-aabda2475e81)

**多维表**
![image](https://github.com/user-attachments/assets/410c4335-10f1-425a-bcf9-85d5e933d3e7)

**Comment by fangsmile** [comment]
https://visactor.io/vtable/option/PivotTable-columns-text#cornerHeaderIcon
用这个哦

**Comment by blngblng** [comment]
> https://visactor.io/vtable/option/PivotTable-columns-text#cornerHeaderIcon 用这个哦


你好，我试了一下，发现在demo里不同版本好像会不一样，1.5.4版本的columns可以设置，但是1.5.3版本的不行。我自己本地使用的是1.5.3版本的CDN包，直接下载之后引入使用的，也是不生效。

[vtable@1.5.3.min.zip](https://github.com/user-attachments/files/16505906/vtable%401.5.3.min.zip)

### 1.5.4版本
![AkZEkZFFul](https://github.com/user-attachments/assets/f7f857e5-39e1-49fc-8750-8ef5e7173f52)


### 1.5.3版本
![image](https://github.com/user-attachments/assets/1a4ea3e0-7445-4140-87c3-ac3c24656476)

**Comment by fangsmile** [comment]
新加的配置 @blngblng

**Comment by blngblng** [comment]
好的，谢谢解答 @fangsmile
