### ISSUE TITLE
Ability to keep whitespace/backspace '\n'

### ISSUE THREAD

**Issue by Bujupah** [VisActor/VTable#2181]
### What problem does this feature solve?

I want to maintain my data/text format in the cell as it is, meaning that if I have multiple rows, VTable should preserve the line breaks...
for eg.
|ID | content                                     |
|---|---------------------------------------------|
| 1 | ID: 123<br>Github: Bujupah<br>Verified: Yes |
| 2 | ID: 321<br>Github: Other<br>Verified: No |

Translated to CN: (Sorry for translation)
我想保持单元格中的数据/文本格式不变，这意味着如果我有多行内容，VTable 应该保留换行符。

### What does the proposed API look like?

Style options should have something like this
`whiteSpace: 'pre'` maybe?

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by fangsmile** [comment]
https://visactor.io/vtable/faq/22-How%20to%20deal%20with%20line-break
https://visactor.io/vtable/option/ListTable#enableLineBreak
应该是这个配置吧

**Comment by hzl123456** [comment]
enableLineBreak 对 customLayout 中的 VText 不生效呢，如何让VText 支持换行符呢？
