### ISSUE TITLE
设置columns数量超过一两百个，表头不能正常显示

### ISSUE THREAD

**Issue by ooxx** [VisActor/VTable#220]
设置columns数量超过一两百个，表头不能正常显示

![vtable1](https://github.com/VisActor/VTable/assets/16346254/8385cf1f-932c-4911-a323-449b048c5ed1)

![vtable](https://github.com/VisActor/VTable/assets/16346254/2ef3a2ad-80a2-49d4-9d96-4f2d3642bdc0)

表头只能正常显示前几十个（适口宽度不同显示数量不同），后面的表头为空白。但是对应的records数据能显示。如上图所示。复现方式：复制columns到达100以上的数量。

_Originally posted by @ooxx in https://github.com/VisActor/VTable/discussions/219_

**Comment by fangsmile** [comment]
fixed version 0.10.0
