### ISSUE TITLE
[Bug] 使用异步懒加载数据源、监听排序点击事件切换图标回调中使用updateRecords导致请求全部数据

### ISSUE THREAD

**Issue by voidman2017** [VisActor/VTable#2201]
### Version

1.5.2

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/performance/async-data

### Steps to Reproduce

```
const generatePersons = i => {
  return {
    id: i + 1,
    email1: `${i + 1}@xxx.com`,
    name: `小明${i + 1}`,
    lastName: '王',
    date1: '2022年9月1日',
    tel: '000-0000-0000',
    sex: i % 2 === 0 ? 'boy' : 'girl',
    work: i % 2 === 0 ? 'back-end engineer' : 'front-end engineer',
    city: 'beijing'
  };
};

const getNextState = (state) => {
  const states = ['normal', 'asc', 'desc']
  let currentIndex = states.indexOf(state)
  return states[currentIndex++ % 3]
}

/**
 * 模拟接口请求数据
 * @param startIndex
 * @param num
 * @returns
 */
const getRecordsWithAjax = (startIndex, num) => {
  // console.log('getRecordsWithAjax', startIndex, num);
  return new Promise(resolve => {
    setTimeout(() => {
      console.log('getRecordsWithAjax', startIndex, num);
      const records = [];
      for (let i = 0; i < num; i++) {
        records.push(generatePersons(startIndex + i));
      }
      resolve(records);
    }, 500);
  });
};

// create DataSource
const loadedData = {};
const dataSource = new VTable.data.CachedDataSource({
  get(index) {
    // 每一批次请求100条数据 0-99 100-199 200-299
    const loadStartIndex = Math.floor(index / 100) * 100;
    // 判断是否已请求过？
    if (!loadedData[loadStartIndex]) {
      const promiseObject = getRecordsWithAjax(loadStartIndex, 100); // return Promise Object
      loadedData[loadStartIndex] = promiseObject;
    }
    return loadedData[loadStartIndex].then((data) => {
      return data[index - loadStartIndex]; //获取批次数据列表中的index对应数据
    });
  },
  length: 10000 //all records count
});
const columns = [
  {
    field: 'id',
    title: 'ID',
    width: 120
    // sort: true
  },
  {
    field: 'email1',
    title: 'email',
    width: 200,
    sort: true
  },
  {
    title: 'full name',
    columns: [
      {
        field: 'name',
        title: 'First Name',
        width: 200
      },
      {
        field: 'name',
        title: 'Last Name',
        width: 200
      }
    ]
  },
  {
    field: 'date1',
    title: 'birthday',
    width: 200
  },
  {
    field: 'sex',
    title: 'sex',
    width: 100
  },
  {
    field: 'tel',
    title: 'telephone',
    width: 150
  },
  {
    field: 'work',
    title: 'job',
    width: 200
  },
  {
    field: 'city',
    title: 'city',
    width: 150
  }
];
const option = {
  columns
};
const tableInstance = new VTable.ListTable(document.getElementById(CONTAINER_ID), option);
tableInstance.dataSource = dataSource;
tableInstance.on('sort_click', (args) => {
  const sortState = getNextState(args.order)
    tableInstance.updateSortState({
      field: args.field,
      order: sortState
    },
      false
    );
  tableInstance.updateRecords(
    [
      generatePersons(Math.random()),
      generatePersons(Math.random()),
      generatePersons(Math.random())
    ],
    [1, 2, 3]
  )

  return false
})
window['tableInstance'] = tableInstance;
```

使用以上代码，点击排序按钮，会导致请求全量数据：
![image](https://github.com/user-attachments/assets/f2f9c24b-e9bf-4e3c-9f47-84122a592fea)

### Current Behavior

-

### Expected Behavior

能够提供异步懒加载数据源的情况下，支持排序功能

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
这个逻辑看起来是符合预期的，对应列排序是需要全部数据排序的；如果只排序已加载数据，滚动加载新数据的话，可能出现错乱，或者需要全量重拍之前的数据；所有懒加载的顺序只支持数据的顺序，如果需要排序的话，会请求所有数据

**Comment by voidman2017** [comment]
> 这个逻辑看起来是符合预期的，对应列排序是需要全部数据排序的；如果只排序已加载数据，滚动加载新数据的话，可能出现错乱，或者需要全量重拍之前的数据；所有懒加载的顺序只支持数据的顺序，如果需要排序的话，会请求所有数据

但是如果这样，请求全量数据就失去了内存懒加载的初衷，使用懒加载目的为了降低页面内存。有没有办法，在既保证懒加载可用的情况下，局部更新数据。这样就可以在点击排序之后，将排序参数告知后端来获取后端处理后的排序数据，进行局部更新

**Comment by Rui-Sun** [comment]
> tableInstance.on('sort_click', (args) => {
>   const sortState = getNextState(args.order)
>     tableInstance.updateSortState({
>       field: args.field,
>       order: sortState
>     },
>       false
>     );
>   tableInstance.updateRecords(
>     [
>       generatePersons(Math.random()),
>       generatePersons(Math.random()),
>       generatePersons(Math.random())
>     ],
>     [1, 2, 3]
>   )
> 
>   return false
> })

我明白你的需求了，这样的话，可以先这么处理一下
![image](https://github.com/user-attachments/assets/5233e88c-8e4b-4a58-8803-a64a8a7e76c9)

updateRecords执行时，如果有排序状态，会进行完全排序；这里每次更新排序状态时，可以先清除表格排序信息，再更新数据，这样就不会请求完整数据，最后更新图标状态

**Comment by voidman2017** [comment]
> > tableInstance.on('sort_click', (args) => {
> > const sortState = getNextState(args.order)
> > tableInstance.updateSortState({
> > field: args.field,
> > order: sortState
> > },
> > false
> > );
> > tableInstance.updateRecords(
> > [
> > generatePersons(Math.random()),
> > generatePersons(Math.random()),
> > generatePersons(Math.random())
> > ],
> > [1, 2, 3]
> > )
> > return false
> > })
> 
> 我明白你的需求了，这样的话，可以先这么处理一下 ![image](https://private-user-images.githubusercontent.com/25134429/356517930-5233e88c-8e4b-4a58-8803-a64a8a7e76c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTE1MzgsIm5iZiI6MTcyMzE5MTIzOCwicGF0aCI6Ii8yNTEzNDQyOS8zNTY1MTc5MzAtNTIzM2U4OGMtOGU0Yi00YTU4LTg4MDMtYTY0YThhN2U3NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjVkY2RjY2NmOTNhMGNiMTk5YzQyMzBlMWI1MWE3YTViM2FjZDQzM2MyODljOGQxNDA5MTJhNGM1MWFjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_FJ5gJsuKECVz62ZXf4ha4Cgep74EDkU0zcsE-LDBo)
> 
> updateRecords执行时，如果有排序状态，会进行完全排序；这里每次更新排序状态时，可以先清除表格排序信息，再更新数据，这样就不会请求完整数据，最后更新图标状态

测试了一下，是可以的。只是目前编码不够优雅，后续是否有计划通过框架侧调整api覆盖该场景。
另外https://visactor.io/vtable/demo/performance/async-data可以提供有关「建议后端实现排序逻辑，前端仅展示排序图标」的完整demo

**Comment by Rui-Sun** [comment]
> > > tableInstance.on('sort_click', (args) => {
> > > const sortState = getNextState(args.order)
> > > tableInstance.updateSortState({
> > > field: args.field,
> > > order: sortState
> > > },
> > > false
> > > );
> > > tableInstance.updateRecords(
> > > [
> > > generatePersons(Math.random()),
> > > generatePersons(Math.random()),
> > > generatePersons(Math.random())
> > > ],
> > > [1, 2, 3]
> > > )
> > > return false
> > > })
> > 
> > 
> > 我明白你的需求了，这样的话，可以先这么处理一下 ![image](https://private-user-images.githubusercontent.com/25134429/356517930-5233e88c-8e4b-4a58-8803-a64a8a7e76c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTE1MzgsIm5iZiI6MTcyMzE5MTIzOCwicGF0aCI6Ii8yNTEzNDQyOS8zNTY1MTc5MzAtNTIzM2U4OGMtOGU0Yi00YTU4LTg4MDMtYTY0YThhN2U3NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjVkY2RjY2NmOTNhMGNiMTk5YzQyMzBlMWI1MWE3YTViM2FjZDQzM2MyODljOGQxNDA5MTJhNGM1MWFjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_FJ5gJsuKECVz62ZXf4ha4Cgep74EDkU0zcsE-LDBo)
> > updateRecords执行时，如果有排序状态，会进行完全排序；这里每次更新排序状态时，可以先清除表格排序信息，再更新数据，这样就不会请求完整数据，最后更新图标状态
> 
> 测试了一下，是可以的。只是目前编码不够优雅，后续是否有计划通过框架侧调整api覆盖该场景。 另外[https://visactor.io/vtable/demo/performance/async-data可以提供有关「建议后端实现排序逻辑，前端仅展示排序图标」的完整demo](https://visactor.io/vtable/demo/performance/async-data%E5%8F%AF%E4%BB%A5%E6%8F%90%E4%BE%9B%E6%9C%89%E5%85%B3%E3%80%8C%E5%BB%BA%E8%AE%AE%E5%90%8E%E7%AB%AF%E5%AE%9E%E7%8E%B0%E6%8E%92%E5%BA%8F%E9%80%BB%E8%BE%91%EF%BC%8C%E5%89%8D%E7%AB%AF%E4%BB%85%E5%B1%95%E7%A4%BA%E6%8E%92%E5%BA%8F%E5%9B%BE%E6%A0%87%E3%80%8D%E7%9A%84%E5%AE%8C%E6%95%B4demo)

我们后面考虑一下类似的需求什么更好实现，如果有好的实现方案也欢迎一起参与开源项目的开发

**Comment by voidman2017** [comment]
> > > > tableInstance.on('sort_click', (args) => {
> > > > const sortState = getNextState(args.order)
> > > > tableInstance.updateSortState({
> > > > field: args.field,
> > > > order: sortState
> > > > },
> > > > false
> > > > );
> > > > tableInstance.updateRecords(
> > > > [
> > > > generatePersons(Math.random()),
> > > > generatePersons(Math.random()),
> > > > generatePersons(Math.random())
> > > > ],
> > > > [1, 2, 3]
> > > > )
> > > > return false
> > > > })
> > > 
> > > 
> > > 我明白你的需求了，这样的话，可以先这么处理一下 ![image](https://private-user-images.githubusercontent.com/25134429/356517930-5233e88c-8e4b-4a58-8803-a64a8a7e76c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTE1MzgsIm5iZiI6MTcyMzE5MTIzOCwicGF0aCI6Ii8yNTEzNDQyOS8zNTY1MTc5MzAtNTIzM2U4OGMtOGU0Yi00YTU4LTg4MDMtYTY0YThhN2U3NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjVkY2RjY2NmOTNhMGNiMTk5YzQyMzBlMWI1MWE3YTViM2FjZDQzM2MyODljOGQxNDA5MTJhNGM1MWFjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_FJ5gJsuKECVz62ZXf4ha4Cgep74EDkU0zcsE-LDBo)
> > > updateRecords执行时，如果有排序状态，会进行完全排序；这里每次更新排序状态时，可以先清除表格排序信息，再更新数据，这样就不会请求完整数据，最后更新图标状态
> > 
> > 
> > 测试了一下，是可以的。只是目前编码不够优雅，后续是否有计划通过框架侧调整api覆盖该场景。 另外[https://visactor.io/vtable/demo/performance/async-data可以提供有关「建议后端实现排序逻辑，前端仅展示排序图标」的完整demo](https://visactor.io/vtable/demo/performance/async-data%E5%8F%AF%E4%BB%A5%E6%8F%90%E4%BE%9B%E6%9C%89%E5%85%B3%E3%80%8C%E5%BB%BA%E8%AE%AE%E5%90%8E%E7%AB%AF%E5%AE%9E%E7%8E%B0%E6%8E%92%E5%BA%8F%E9%80%BB%E8%BE%91%EF%BC%8C%E5%89%8D%E7%AB%AF%E4%BB%85%E5%B1%95%E7%A4%BA%E6%8E%92%E5%BA%8F%E5%9B%BE%E6%A0%87%E3%80%8D%E7%9A%84%E5%AE%8C%E6%95%B4demo)
> 
> 我们后面考虑一下类似的需求什么更好实现，如果有好的实现方案也欢迎一起参与开源项目的开发

👌有交流渠道么

**Comment by Rui-Sun** [comment]
![飞书20240625-163310](https://github.com/user-attachments/assets/dca74a5f-d53f-42c1-83f3-d8d300f37869)
可以加飞书群讨论

**Comment by voidman2017** [comment]
不好意思，之前的图标更新和更新局部数据可以了。但是当滚动至已请求过的数据区域时，没有出发get方法，重新请求数据。是否有办法实现。或者能够提供完整的异步懒加载数据结合后端实现排序的demo吗
