### ISSUE TITLE
autoWrapText: false 和 enableLineBreak: true 有点冲突

### ISSUE THREAD

**Issue by fuxingjun** [VisActor/VTable#2202]
### Version

*

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-vl6scd?file=%2Fsrc%2Findex.ts%3A20%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxye8r0c0007356empkk9gxz%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxye8r0c0003356e342tutwc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxye8r0c0004356e12tny81s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxye8r0c0006356eyyh8tuiv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.87263846%252C47.12736154%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxye8r0c0003356e342tutwc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxye8r0c0002356ex4tnac9o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxye8r0c0003356e342tutwc%2522%252C%2522activeTabId%2522%253A%2522clxye8r0c0002356ex4tnac9o%2522%257D%252C%2522clxye8r0c0006356eyyh8tuiv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxye8r0c0005356e283rca2d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxye8r0c0006356eyyh8tuiv%2522%252C%2522activeTabId%2522%253A%2522clxye8r0c0005356e283rca2d%2522%257D%252C%2522clxye8r0c0004356e12tny81s%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxye8r0c0004356e12tny81s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

```
...
autoWrapText: false,
heightMode: "autoHeight",
enableLineBreak: true,
autoFillWidth: true,
...
```

### Current Behavior

目前的表现是enableLineBreak为true是会自动换行, 但是自动计算的高度太小导致内容显示不全

### Expected Behavior

1. 自动换行, 但是计算的高度需要对应上,
2. 不自动换行, 每行的内容超出宽度隐藏

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
autoWrapText 这个是为了自动换位的 没有换行符的话 文字宽度超过容器也会换行 行高度也不会自动撑开
enableLineBreak 是为了将文字中的换行符\n 生效  行高度也不会自动撑开

需要行高自动撑开 需要配置heightMode为autoHeight https://visactor.io/vtable/guide/basic_function/row_height_column_width
