### ISSUE TITLE
[Bug] vtable仅渲染一个分组堆叠玫瑰图时，点击图例后鼠标悬浮轴线消失

### ISSUE THREAD

**Issue by a1419735487** [VisActor/VTable#2209]
### Version

1.5.4

### Link to Minimal Reproduction

-1

### Steps to Reproduce

![img_v3_02di_83e94887-b5f0-4c6b-931c-b12bf7f9d1eg](https://github.com/user-attachments/assets/710794b7-6007-4eca-8a2d-fe50ffe9e69c)
![img_v3_02di_88a1f54b-2bb0-4e6f-ae8f-aacb553a0e6g](https://github.com/user-attachments/assets/b82cd465-a4fc-4f55-84d5-d670f561d6d4)

### Current Behavior

      const option = {
    "indicators": [
        {
            "indicatorKey": "col_fld_tmp_zb_2",
            "chartSpec": {
                "categoryField": "subcategory",
                "data": {
                    "id": "9f9f482542764dc1aed841eafd768116",
                    "fields": {
                        "subcategory": {
                            "sortIndex": 1,
                            "domain": [
                                "桌子",
                                "椅子",
                                "用具",
                                "书架"
                            ]
                        }
                    }
                },
                "scales": [
                    {
                        "domain": [
                            "桌子",
                            "椅子",
                            "用具",
                            "书架"
                        ],
                        "id": "color",
                        "type": "ordinal",
                        "range": [
                            "#1664FF",
                            "#1AC6FF",
                            "#FF8A00",
                            "#3CC780"
                        ]
                    }
                ],
                "seriesField": "subcategory",
                "type": "rose",
                "valueField": "col_fld_tmp_zb_2",
                "axes": [
                    {
                        "orient": "angle",
                        "domainLine": {
                            "visible": true,
                            "smooth": true
                        },
                        "label": {
                            "visible": true
                        },
                        "tick": {
                            "visible": true
                        },
                        "grid": {
                            "visible": true,
                            "alignWithLabel": false
                        },
                        "bandPadding": 0.05
                    },
                    {
                        "orient": "radius",
                        "label": {
                            "visible": true
                        },
                        "grid": {
                            "visible": true,
                            "smooth": true
                        }
                    }
                ]
            },
            "cellType": "chart",
            "chartModule": "vchart",
        }
    ],
    "records": [
        {
            "col_fld_tmp_zb_2": "619",
            "col_fld_tmp_zb_2_title": "数量",
            "col_fld_tmp_zb_2_rate": "7.28%",
            "category": "家具",
            "subcategory": "桌子",
            "col_fld_tmp_zb_2_total": 8505
        },
        {
            "col_fld_tmp_zb_2": "3182",
            "col_fld_tmp_zb_2_title": "数量",
            "col_fld_tmp_zb_2_rate": "37.41%",
            "category": "家具",
            "subcategory": "椅子",
            "col_fld_tmp_zb_2_total": 8505
        },
        {
            "col_fld_tmp_zb_2": "2308",
            "col_fld_tmp_zb_2_title": "数量",
            "col_fld_tmp_zb_2_rate": "27.14%",
            "category": "家具",
            "subcategory": "用具",
            "col_fld_tmp_zb_2_total": 8505
        },
        {
            "col_fld_tmp_zb_2": "2396",
            "col_fld_tmp_zb_2_title": "数量",
            "col_fld_tmp_zb_2_rate": "28.17%",
            "category": "家具",
            "subcategory": "书架",
            "col_fld_tmp_zb_2_total": 8505
        }
    ],
    "corner": {
        "titleOnDimension": "row"
    },
    "autoWrapText": true,
    "widthMode": "standard",
    "heightMode": "standard",
    "autoFillWidth": true,
    "autoFillHeight": true,
    "axes": [
        {
            "orient": "left",
            "visible": true,
            "zero": true,
            "nice": true,
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12
                }
            },
            "title": {
                "angle": 0,
                "style": {
                    "fontSize": 12,
                    "direction": "vertical"
                }
            }
        },
        {
            "orient": "right",
            "visible": true,
            "zero": true,
            "nice": true,
            "label": {
                "visible": true,
                "style": {
                    "fontSize": 12
                }
            },
            "title": {
                "angle": 0,
                "style": {
                    "fontSize": 12,
                    "direction": "vertical"
                }
            }
        },
        {
            "orient": "bottom",
            "visible": true,
            "zero": true,
            "nice": true,
            "label": {
                "style": {
                    "fontSize": 12
                }
            },
            "title": {
                "style": {
                    "fontSize": 12
                }
            }
        },
        {
            "orient": "top",
            "visible": true,
            "zero": true,
            "nice": true,
            "label": {
                "style": {
                    "fontSize": 12
                }
            },
            "title": {
                "style": {
                    "fontSize": 12
                }
            }
        }
    ],
    "legends": {
        "orient": "right",
        "type": "discrete",
        "allowAllCanceled": false,
        "data": [
            {
                "label": "桌子",
                "shape": {
                    "fill": "#1664FF",
                    "symbolType": "square"
                }
            },
            {
                "label": "椅子",
                "shape": {
                    "fill": "#1AC6FF",
                    "symbolType": "square"
                }
            },
            {
                "label": "用具",
                "shape": {
                    "fill": "#FF8A00",
                    "symbolType": "square"
                }
            },
            {
                "label": "书架",
                "shape": {
                    "fill": "#3CC780",
                    "symbolType": "square"
                }
            }
        ],
    },
}

### Expected Behavior

      tableInstance.on(LEGEND_ITEM_CLICK, args => {
        console.log('LEGEND_ITEM_CLICK', args);
        tableInstance.updateFilterRules([
          {
              filterKey: option.indicators[0].chartSpec.categoryField,
              filteredValues: args.value,
          }
        ]);
      });

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
复现demo没有完全贴进来 @a1419735487
