### ISSUE TITLE
透视表如何显示字符串的内容而不是显示数值

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2218]
**虽然透视表是用来做数据分析的，但有时会有单纯的数据展示需求，然后用透视表的话方便设置表头和行头，想知道是否支持正常显示字符串，目前看起来字符串好像会被默认为0。**

有尝试设置cellType，但是好像不生效

![image](https://github.com/user-attachments/assets/5e105d91-fbf3-4eab-b2aa-5b1affde4811)

![image](https://github.com/user-attachments/assets/7595c26f-301c-4a78-bbc6-0f52a49c2721)

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/data_analysis/pivot_table_dataAnalysis  聚合类型可以设置
