### ISSUE TITLE
[Bug] 设置自动高度后，使用自定义渲染方式导致内容行不展示

### ISSUE THREAD

**Issue by noxxxxxxxx** [VisActor/VTable#2220]
### Version

1.5.6

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-custom-rendering-forked-78nszz?file=%2Fsrc%2Fapp.ts%3A112%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzr0ynix00073b6ipkf04suo%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzr0ynix00033b6iebvnikrr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzr0ynix00043b6i4r5cyyes%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzr0ynix00063b6ieggeeago%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzr0ynix00033b6iebvnikrr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzr0ynix00023b6it7wegc66%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A112%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A112%252C%2522endColumn%2522%253A30%257D%255D%257D%255D%252C%2522id%2522%253A%2522clzr0ynix00033b6iebvnikrr%2522%252C%2522activeTabId%2522%253A%2522clzr0ynix00023b6it7wegc66%2522%257D%252C%2522clzr0ynix00063b6ieggeeago%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzr0ynix00053b6inxyk39h5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzr0ynix00063b6ieggeeago%2522%252C%2522activeTabId%2522%253A%2522clzr0ynix00053b6inxyk39h5%2522%257D%252C%2522clzr0ynix00043b6i4r5cyyes%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzr0ynix00043b6i4r5cyyes%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

 1. 设置 heightMode: 'autoHeight' 即可复现

### Current Behavior

![image](https://github.com/user-attachments/assets/8318dd71-b16f-4015-b470-0b0744214fe1)

### Expected Behavior

![image](https://github.com/user-attachments/assets/d82d0e02-edc4-487f-8184-4f32e23fe7bb)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed by https://github.com/VisActor/VTable/pull/2199
