### ISSUE TITLE
rowTree和columnTree支持设置link模式吗

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2227]
请问有类似cellType和headerType的属性可以设置给rowTree和columnTree吗

![image](https://github.com/user-attachments/assets/d6704237-9f62-42b9-b373-c32055039d96)

**Comment by fangsmile** [comment]
rows或者columns中 可以设置headerCellType吧

**Comment by blngblng** [comment]
> rows或者columns中 可以设置headerCellType吧

文档里好像没有headerCellType，rows或者columns是设置headerType，但是headerType是直接统一设置类型，不支持函数，有时候只想对某几个设置link或某些虚拟节点设置。
@fangsmile

**Comment by fangsmile** [comment]
那就改成提个需求吧 Feature
headerType支持函数写法

**Comment by blngblng** [comment]
好的
