### ISSUE TITLE
[Feature] react 中绑定onDropdownMenuClick 事件 无法完成复制内容操作

### ISSUE THREAD

**Issue by xiaoshengwpp** [VisActor/VTable#2228]
### What problem does this feature solve?

function App() {
  const option = {
    // ......
  };
  return (
    <ListTable
      option={option}
      onDropdownMenuClick={(...arg: any) => {
        console.log('onDropdownMenuClick', ...arg);//没有 已选区域 内容
      }}
    />
  );
}

//打印出来的内容
{
    "col": 3,
    "row": 2,
    "field": "0",
    "menuKey": "复制",
    "text": "复制",
    "highlight": false,
    "cellLocation": "body",
    "event": {
        "isTrusted": true
    }
}

### What does the proposed API look like?

期望 react 中 直接绑定事件 来 写入 右键点击复制功能

**Comment by Rui-Sun** [comment]
可以在ref中存一下tableIntance，在函数中使用
![image](https://github.com/user-attachments/assets/044b7d6f-28dd-454b-8841-bda5a7c6492d)
