### ISSUE TITLE
[Bug] emptyTip开启后,父容器缩放导致emptyTip位置异常

### ISSUE THREAD

**Issue by li936393** [VisActor/VTable#2231]
### Version

1.5.4

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/component/empty-tip

### Steps to Reproduce

1、设置emptyTip: {text: 'no data records'},
2、vtable这是自使用父容器

### Current Behavior

缩放浏览器，父容器跟随一起缩放，emptyTip位置会偶发出现异常(不是居中显示)
![Uploading 1.jpg…]()

### Expected Behavior

父容器缩放时emptyTip位置一直居中显示，同时当浏览器缩小时emptyIcon能否也能跟随一起进行适量缩放

### Environment

```markdown
- OS:Windows NT 10.0
- Browser:Chrome/127.0.0.0
- Framework:
```

**Comment by li936393** [comment]
![1](https://github.com/user-attachments/assets/a9ac7b38-7426-4558-b025-9ba12055c6eb)
![2](https://github.com/user-attachments/assets/7c8d0a2d-8864-4723-a85f-bf530e246421)
![3](https://github.com/user-attachments/assets/1c7edf2e-f6f8-4b7f-84dd-420bbc04b7b1)

**Comment by tangerball** [comment]
@fangsmile 以及当前列不够多的情况下设置widthMode="adaptive"也会empty出现错位

**Comment by fangsmile** [comment]
@tangerball 你是设置里点击的缩放 还是触控板双指缩放

**Comment by fangsmile** [comment]
> @fangsmile 以及当前列不够多的情况下设置widthMode="adaptive"也会empty出现错位

这个我没有复现出来哦
![image](https://github.com/user-attachments/assets/8aabe9ef-6208-4249-b842-5318afe9636f)
