### ISSUE TITLE
[Bug] react-table 中，当 listColumn 里渲染了自定义组件后，全局定义的 Aggregation 被覆盖

### ISSUE THREAD

**Issue by nikoohp** [VisActor/VTable#2253]
### Version

latest

### Link to Minimal Reproduction

.

### Steps to Reproduce

![img_v3_02dq_bbcc25a4-649d-466f-aef6-d170d3ad774g](https://github.com/user-attachments/assets/5fccb672-62e4-4f3d-a4ce-0d09c40642f0)
红框的那里本来也是应该显示的是唯一值的聚合栏，但是这一列用了react自定义组件渲染后就去渲染自定义组件了，而不是渲染的聚合栏

### Current Behavior

聚合栏被自定义组件内容覆盖

### Expected Behavior

有聚合栏的显示聚合栏内容

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
https://github.com/VisActor/VTable/issues/2177  重复issue
