### ISSUE TITLE
透视表存在筛选条件或排序条件的情况下，支持获取筛选排序后的表格数据吗

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2255]
目前records属性只能获取到当前表格的所有数据，如果存在筛选规则和排序规则，有办法获取到筛选或排序后的表格数据吗，还是需要自己对表格数据重新筛选排序获取。

**Comment by fangsmile** [comment]
这个我们转成个需求 后面加接口可以获取吧

**Comment by fangsmile** [comment]
我之前以为是基本表格ListTable的需求呢，透视表的话 是不存在排序后的数据的，因为是针对的维度值排的序 而不是针对records。https://visactor.io/vtable/api/Methods#getLayoutRowTree 这个接口 可以获取到当前展示的行表头的维度树

**Comment by blngblng** [comment]
> 我之前以为是基本表格ListTable的需求呢，透视表的话 是不存在排序后的数据的，因为是针对的维度值排的序 而不是针对records。https://visactor.io/vtable/api/Methods#getLayoutRowTree 这个接口 可以获取到当前展示的行表头的维度树

排序后的数据获取不到的话，筛选的数据可以获取的到吗，通过filterRules配置之后筛选显示的数据。 @fangsmile
