### ISSUE TITLE
[Feat] when has columnTree can aggregator records by tree path 

### ISSUE THREAD

**Issue by lucky-LuSir** [VisActor/VTable#2279]
### Version

1.0.0

### Link to Minimal Reproduction

以下配置

### Steps to Reproduce

		const option = {
			columnTree: [
				{
					dimensionKey: 'Segment-1',
					value: 'Segment-1 (virtual-node)',
					virtual: true,
					children: [
						{
							dimensionKey: 'Segment',
							value: 'Consumer',
							children: [
								{
									indicatorKey: 'Quantity',
									value: 'Quantity',
								},
							],
						},
					],
				},
				{
					dimensionKey: 'descc',
					value: 'descc',
					virtual: true,
					children: [
						{
							indicatorKey: 'desc',
							value: 'desc',
						},
					],
				},
			],
			indicators: [
				{
					indicatorKey: 'Quantity',
					title: 'Quantity',
					width: 'auto',
					showSort: false,
				},
				{
					indicatorKey: 'desc',
					title: 'desc',
					width: 'auto',
					showSort: false,
				},
			],
			supplementxndicatorNodes: false,
		};

### Current Behavior

<template>
	<div ref="listTableRef" style="height: 100%"></div>
</template>
<script setup>
import * as VTable from '@visactor/vtable';
let tableInstance;
const listTableRef = ref();
fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/VTable/North_American_Superstore_Pivot_Chart_data.json')
	.then((res) => res.json())
	.then((data) => {
		const newData = [];
		data.forEach((v) => {
			v['descD'] = Math.floor(Math.random() * 1000) + 1;
			v['desc'] = Math.floor(Math.random() * 1000) + 1;
			v['descc'] = 'descc';
			newData.push(v);
		});
		newData.push({
			Region: 'Central',
			Category: 'Furniture',
			descc: '111',
			desc: 'descD',
			descD: '222',
			'Sub-Category': 'Chairs',
			'Order Year': '2015',
			Segment: 'Consumer',
			'Ship Mode': 'First Class',
		});
		const option = {
			records: newData,
			rows: [
				{
					dimensionKey: 'Category',
					title: 'Category',
					headerStyle: {
						textStick: true,
						bgColor(arg) {
							if (arg.dataValue === 'Row Totals') {
								return '#a5b7fc';
							}
							return '#ECF1F5';
						},
					},
					width: 'auto',
				},
				{
					dimensionKey: 'Sub-Category',
					title: 'Sub-Catogery',
					headerStyle: {
						textStick: true,
						bgColor(arg) {
							if (arg.dataValue === 'Sub Totals') {
								return '#d2dcff';
							}
							return '#ECF1F5';
						},
					},
					width: 'auto',
				},
			],
			columnTree: [
				{
					dimensionKey: 'Segment-1',
					value: 'Segment-1 (virtual-node)',
					virtual: true,
					children: [
						{
							dimensionKey: 'Segment',
							value: 'Consumer',
							children: [
								{
									indicatorKey: 'Quantity',
									value: 'Quantity',
								},
							],
						},
					],
				},
				{
					dimensionKey: 'descc',
					value: 'descc',
					virtual: true,
					children: [
						{
							indicatorKey: 'desc',
							value: 'desc',
						},
					],
				},
			],
			indicators: [
				{
					indicatorKey: 'Quantity',
					title: 'Quantity',
					width: 'auto',
					showSort: false,
				},
				{
					indicatorKey: 'desc',
					title: 'desc',
					width: 'auto',
					showSort: false,
				},
			],
			corner: {
				titleOnDimension: 'row',
			},
			theme: VTable.themes.DEFAULT.extends({
				headerStyle: {
					bgColor: '#5071f9',
					color(args) {
						if (
							(args.cellHeaderPaths.colHeaderPaths?.length === 1 && args.cellHeaderPaths.colHeaderPaths[0].virtual) ||
							(args.cellHeaderPaths.colHeaderPaths?.length === 2 && args.cellHeaderPaths.colHeaderPaths[1].virtual)
						) {
							return 'red';
						}
						return '#fff';
					},
				},
				cornerHeaderStyle: {
					bgColor: '#5071f9',
					color: '#fff',
				},
			}),
			supplementIndicatorNodes: false,
			widthMode: 'standard',
		};
		console.log('xxx-option', option);
		tableInstance = new VTable.PivotTable(listTableRef.value, option);
		window.tableInstance = tableInstance;
	});
</script>

<style lang="scss" scoped>
.pageView :deep(.el-card__body) {
	height: 100%;
}
</style>

### Expected Behavior

![image](https://github.com/user-attachments/assets/b90ee5cf-99f9-4139-9900-6a999bd21ab8)

期望:
需要有一列拓展属性, 比如备注, 描述,  独占一列然后展示
以上代码通过columnTree展示了拓展属性, 但是desc数据没展示, 期望desc下面数据能出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
请把复现代码给一份 可以直接粘贴到官网demo编辑器中能复现出来的代码吧 @lucky-LuSir

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/3284d012-e457-4649-bce5-5cbe0d3fbce7)
这个是目标效果吗  @lucky-LuSir
