### ISSUE TITLE
[Bug] ListTable 使用树结构数据，配置 menu.defaultHeaderMenuItems 会报错

### ISSUE THREAD

**Issue by QaQ-top** [VisActor/VTable#2289]
### Version

1.5.3

### Link to Minimal Reproduction

无

### Steps to Reproduce

树结构数据配置 menu.defaultHeaderMenuItems 

### Current Behavior

![image](https://github.com/user-attachments/assets/fd20fa73-7594-41d1-8857-475562b2fa3e)
![image](https://github.com/user-attachments/assets/480a8b4f-9833-41e5-b5ee-f1fed99ec274)

### Expected Behavior

正常执行

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by QaQ-top** [comment]
contextMenuItems  右键菜单也会相同的问题

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/f830f25a-aa4c-4e84-bb9b-6320e0fb2339)

menu功能测试了一下应该是正常的，估计看调用栈分析，问题可能是highlight中配置的field，没有能匹配上任何列；这里我们在查询列上加一个判断，避免逻辑报错
