### ISSUE TITLE
[Bug] @visactor/react-vtable 在1.6.2移除了VTable的导出

### ISSUE THREAD

**Issue by kapeter** [VisActor/VTable#2293]
### Version

1.6.2

### Link to Minimal Reproduction

@visactor/react-vtable 在1.6.2移除了VTable的导出

### Steps to Reproduce

@visactor/react-vtable 在1.6.2移除了VTable的导出，这个是否是break change。

### Current Behavior

import {  Vatble } from '@apaas-core/react-vtable' 报错

### Expected Behavior

小版本尽量保持API稳定。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
为了保证包大小，react-vtable不再提供VTable，需要的话请安装对应版本的VTable引入相应模块

**Comment by kapeter** [comment]
想讨论一下这个移除的时机。API移除算是break change，是不是在大版本更新时做更合适

**Comment by Rui-Sun** [comment]
非常抱歉，预计在1.6.0版本移出，版本发布有问题；我们再站点中补充相关说明
