### ISSUE TITLE
[Bug] ```PivotTable```使用`Editor`编辑数据后，获取更新后的数据失败

### ISSUE THREAD

**Issue by zzjjbbaa** [VisActor/VTable#2305]
### Version

1.6.1

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/edit/pivot-table-editor

### Steps to Reproduce

[1.版本1.6.1；官网链接](https://visactor.io/vtable/demo/edit/pivot-table-editor)

### Current Behavior

无

### Expected Behavior

可以获取到更改后的数据

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

无

**Comment by zzjjbbaa** [comment]
https://github.com/user-attachments/assets/9c762b91-eb92-456f-8508-52d1721d439f

**Comment by fangsmile** [comment]
已修复，当一个单元格对应的源数据只有一条的时候可以做对应修改。但是当单元格对应聚合了多条records数据的指标值时，是不支持对应修改到源数据的

**Comment by zzjjbbaa** [comment]
> 已修复，当一个单元格对应的源数据只有一条的时候可以做对应修改。但是当单元格对应聚合了多条records数据的指标值时，是不支持对应修改到源数据的

**疯狂比心，果然比antv/s2响应快**
1. 只有一条records,意思是`records.length === 0`？
2. 单元格对应聚合了多条records数据的指标值,怎么理解呢？
3. 什么时候发版呢，我再测测
