### ISSUE TITLE
[Bug] 配置headerCustomRender，改变列宽报错

### ISSUE THREAD

**Issue by kapeter** [VisActor/VTable#2329]
### Version

1.6.2

### Link to Minimal Reproduction

配置headerCustomRender，改变列宽报错

### Steps to Reproduce

1、配置headerCustomHeader
2、拖动列宽

### Current Behavior

单元格白屏：

报错位置：  const { vTableMerge } = scene.table.getCellRawRecord(col, row);

### Expected Behavior

不报错：

修改如下：  const { vTableMerge } = scene?.table?.getCellRawRecord?.(col, row) || {};

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
需要给个复现demo @kapeter 
或者复现option直接粘贴到官网编辑器能复现出来的
