### ISSUE TITLE
[Feature] 排序功能调整

### ISSUE THREAD

**Issue by lzwx** [VisActor/VTable#2342]
### What problem does this feature solve?

1.可以自定义按钮宽高,颜色,图标等
2.按住CTRL(或SHIFT)时,支持多字段排序

### What does the proposed API look like?

1.可以自定义按钮宽高,颜色,图标等
2.按住CTRL(或SHIFT)时,支持多字段排序

**Comment by fangsmile** [comment]
多排序状态已经开发了。
另外一个颜色 宽高 可以通过自定义图标来实现  官网的自定义图标教程中有提到重置内部图标的方式

**Comment by lzwx** [comment]
OK, @fangsmile 最帅了!
