### ISSUE TITLE
[Bug] 树形表格无法显示前方展开图标

### ISSUE THREAD

**Issue by a552966346** [VisActor/VTable#2395]
### Version

1.7.3

### Link to Minimal Reproduction

123

### Steps to Reproduce

<script setup lang="ts">
import * as VTable_editors from '@visactor/vtable-editors';
import * as VTable from '@visactor/vtable';
let tableInstance;
const data = [
  {
    类别: '办公用品',
    销售额: '129.696',
    数量: '2',
    利润: '-60.704',
    children: [
      {
        类别: '信封', // 对应原子类别
        销售额: '125.44',
        数量: '2',
        利润: '42.56',
        children: [
          {
            类别: '黄色信封',
            销售额: '125.44',
            数量: '2',
            利润: '42.56'
          },
          {
            类别: '白色信封',
            销售额: '1375.92',
            数量: '3',
            利润: '550.2'
          }
        ]
      },
      {
        类别: '器具', // 对应原子类别
        销售额: '1375.92',
        数量: '3',
        利润: '550.2',
        children: [
          {
            类别: '订书机',
            销售额: '125.44',
            数量: '2',
            利润: '42.56'
          },
          {
            类别: '计算器',
            销售额: '1375.92',
            数量: '3',
            利润: '550.2'
          }
        ]
      }
    ]
  },
  {
    类别: '技术',
    销售额: '229.696',
    数量: '20',
    利润: '90.704',
    children: [
      {
        类别: '设备', // 对应原子类别
        销售额: '225.44',
        数量: '5',
        利润: '462.56'
      },
      {
        类别: '配件', // 对应原子类别
        销售额: '375.92',
        数量: '8',
        利润: '550.2'
      },
      {
        类别: '复印机', // 对应原子类别
        销售额: '425.44',
        数量: '7',
        利润: '342.56'
      },
      {
        类别: '电话', // 对应原子类别
        销售额: '175.92',
        数量: '6',
        利润: '750.2'
      }
    ]
  },
  {
    类别: '家具',
    销售额: '129.696',
    数量: '2',
    利润: '-60.704',
    children: [
      {
        类别: '桌子', // 对应原子类别
        销售额: '125.44',
        数量: '2',
        利润: '42.56',
        children: [
          {
            类别: '黄色桌子',
            销售额: '125.44',
            数量: '2',
            利润: '42.56'
          },
          {
            类别: '白色桌子',
            销售额: '1375.92',
            数量: '3',
            利润: '550.2'
          }
        ]
      },
      {
        类别: '椅子', // 对应原子类别
        销售额: '1375.92',
        数量: '3',
        利润: '550.2',
        children: [
          {
            类别: '老板椅',
            销售额: '125.44',
            数量: '2',
            利润: '42.56'
          },
          {
            类别: '沙发椅',
            销售额: '1375.92',
            数量: '3',
            利润: '550.2'
          }
        ]
      }
    ]
  },
  {
    类别: '生活家电（懒加载）',
    销售额: '229.696',
    数量: '20',
    利润: '90.704',
    children: true
  }
];
const tableContainer = ref(null)
let instance

onMounted(()=>{
    let option = {
        container:null,
        columns: [
            {
            field: '类别',
            tree: true,
            title: '类别',
            width: 'auto',
            sort: true
            },
            {
            field: '销售额',
            title: '销售额',
            width: 'auto',
            sort: true
            // tree: true,
            },
            {
            field: '利润',
            title: '利润',
            width: 'auto',
            sort: true
            }
        ],
        showPin: true, //显示VTable内置冻结列图标
        widthMode: 'standard',
        allowFrozenColCount: 2,
        records: data,

        hierarchyIndent: 20,
        hierarchyExpandLevel: 2,
        hierarchyTextStartAlignment: true,
        sortState: {
            field: '销售额',
            order: 'asc'
        },
        theme: VTable.themes.BRIGHT,
        defaultRowHeight: 32
    };
    option.container = tableContainer.value,
    instance = new VTable.ListTable(option);
    const { TREE_HIERARCHY_STATE_CHANGE } = VTable.ListTable.EVENT_TYPE;
    instance.on(TREE_HIERARCHY_STATE_CHANGE, args => {
    // TODO 调用接口插入设置子节点的数据
    if (args.hierarchyState === VTable.TYPES.HierarchyState.expand && !Array.isArray(args.originData.children)) {
        const record = args.originData;
        setTimeout(() => {
        const children = [
            {
            类别: record['类别'] + ' - 分类1', // 对应原子类别
            销售额: 2,
            数量: 5,
            利润: 4
            },
            {
            类别: record['类别'] + ' - 分类2', // 对应原子类别
            销售额: 3,
            数量: 8,
            利润: 5
            },
            {
            类别: record['类别'] + ' - 分类3（懒加载）',
            销售额: 4,
            数量: 20,
            利润: 90.704,
            children: true
            },
            {
            类别: record['类别'] + ' - 分类4', // 对应原子类别
            销售额: 5,
            数量: 6,
            利润: 7
            }
        ];
        instance.setRecordChildren(children, args.col, args.row);
        }, 200);
    }
    });
    window['tableInstance'] = tableInstance;
})
</script>
<template>
    <div style="width: 100%;height:100%;">
        <div id="tableContainer" ref="tableContainer" style="width: 100%;height:100%;"></div>
    </div>
</template>
<style scoped lang="scss">
</style>
![20240909-095137](https://github.com/user-attachments/assets/51caaeab-bbe9-4b32-be3c-0bcf51f5941c)

### Current Behavior

使用的eletron框架出现的问题

### Expected Behavior

正产显示前方展开图标

### Environment

```markdown
"electron": "^31.0.2",
"vite": "^5.4.3",
"vue": "^3.5.0",
```

**Comment by fangsmile** [comment]
页面安全限制导致的：
![Uploading img_v3_02ei_b94f28fe-3a05-4eb3-bc55-6017cd0bb08g.jpg…]()

**Comment by a552966346** [comment]
可以再问一下&nbsp;https://visactor.io/vtable/demo-react/functional-components/arco-select-editor&nbsp; 这个的vue 写法是什么样子的 我这边用的是vue3&nbsp; 可是这边是react的 请教一下




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisActor/VTable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月9日(星期一) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VisActor/VTable] [Bug] 树形表格无法显示前方展开图标 (Issue #2395)





 
页面安全限制导致的：
