### ISSUE TITLE
[Bug] InputEditor 启用时，选中input框中的内容后，再点击表格外的空白处，inputEditor编辑器不会自动移除，点击表格内部可以移除，官网示例一样存在这个问题。

### ISSUE THREAD

**Issue by chency7** [VisActor/VTable#2407]
### Version

1.7.4

### Link to Minimal Reproduction

none

### Steps to Reproduce

1. 对cellType 为 InputEdtior的单元格 双击启用编辑器。
2. 选中Input框中的文字
3. 然后点击表格外的空白处
4. 编辑器不会自动移除

### Current Behavior
![微信图片_20240910001503](https://github.com/user-attachments/assets/57842868-193e-45a0-bede-250a6683c635)

[Bug] InputEditor 启用时，选中input框中的内容后，再点击表格外的空白处，inputEditor编辑器不会自动移除，点击表单内部可以移除，官网示例一样存在这个问题。

### Expected Behavior

编辑器在鼠标点击其他地方会自动移除

### Environment

```markdown
- OS:window 10
- Browser: Chrome 128.0.6613.120
- Framework: vue@3.5
```

**Comment by chency7** [comment]
可以在官网示例上测试复现，另外多问一句，后续会支持 自定义单元格 通过dom元素的渲染吗？

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo-react/custom-layout/cell-custom-dom
react 版本是支持dom组件的 @chency7

**Comment by chency7** [comment]
> https://visactor.io/vtable/demo-react/custom-layout/cell-custom-dom react 版本是支持dom组件的 @chency7

后续会支持js版本吗？ @fangsmile
