### ISSUE TITLE
透视表的单元格编辑，默认编辑器如何设置校验

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2446]
问题：**目前默认的4种编辑器里，想对InputEditor设置校验规则来防止用户输入一些不适用的内容，在手册里只找到自定义编辑器的规则设置，默认的编辑器允许设置规则校验吗。**

![image](https://github.com/user-attachments/assets/15e55c5f-d500-44fc-ae04-aff3a5cc07e5)

![image](https://github.com/user-attachments/assets/6154090d-f9ee-4b64-bbf4-689216929050)

**Comment by fangsmile** [comment]
比较直接的方式  挂上这个方法
![image](https://github.com/user-attachments/assets/16e572b7-5541-43a6-9c7f-0270d67ccef0)

**Comment by blngblng** [comment]
> 比较直接的方式 挂上这个方法 ![image](https://private-user-images.githubusercontent.com/3468473/369358220-16e572b7-5541-43a6-9c7f-0270d67ccef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk0ODAsIm5iZiI6MTcyNzA1OTE4MCwicGF0aCI6Ii8zNDY4NDczLzM2OTM1ODIyMC0xNmU1NzJiNy01NTQxLTQzYTYtOWM3Zi0wMjcwZDY3Y2NlZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDIzOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAzMDM5ZDA4MzRiMzc5M2UxYjMwNWU5ZTRkZDEwYTBkY2U2MmFhODEyODg4MGY3MmZlZDdjMWVhOWE3Y2Y1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Vv0b08gjX05SAC3lyqBaBiZWrwPtFwhcBYN45APIwYY)

@fangsmile  这个检验函数好像没有返回的参数，args是undefined，获取不到修改后的值来进行校验，‘change_cell_value’是在校验事件触发之后的，所以也无法通过‘change_cell_value’获取修改之后的值再进行校验。

**Comment by blngblng** [comment]
找到原因了，input_editor的校验参数返回值是空的，textArea_editor的校验函数参数能正常返回值 @fangsmile 
![image](https://github.com/user-attachments/assets/1075c037-88c9-4446-b0a0-47eed5c7a8c4)
