### ISSUE TITLE
[Bug] 表格排序的点击事件，返回的图标类型和实际点击不同问题

### ISSUE THREAD

**Issue by blngblng** [VisActor/VTable#2465]
### Version

1.7.4

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/basic-functionality/sort?version=1.7.4

### Steps to Reproduce

1. 在官网的排序示例里增加事件绑定代码

`window['tableInstance'].on("click_cell", (args) => {
      const { targetIcon } = args;
      console.log(targetIcon)
    })`

2. 在控制台查看输出

### Current Behavior

![image](https://github.com/user-attachments/assets/b831fb06-687e-4312-a9eb-3fb01da9a606)
![image](https://github.com/user-attachments/assets/c5493289-9547-4141-9403-48bcb0ac7132)

### Expected Behavior

**应用场景：** 给透视维度表的**指标**设置sort: true，显示排序图标但是实际排序不生效，于是想通过点击事件来调整排序事件来控制表格刷新，从而达到排序的目的。

**问题：** 目前点击事件返回图标类型跟当前高亮的状态不一致，导致不能准确获取用户需要的排序状态。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
你最好用事件`sort_click`。
`给透视维度表的指标设置sort: true，显示排序图标但是实际排序不生效，`  这个是怎么配置的呢 可以复现吗 @blngblng
