### ISSUE TITLE
[Bug] 文本不会自动换行

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#2466]
### Version

1.7.4

### Link to Minimal Reproduction

no link

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/c6f763ce-447f-4bd6-bbab-f74bf8c9b50f)
看官网上的设置 

### Current Behavior

并不能换行

### Expected Behavior

自动换行

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/a648dc45-6cb6-4342-8899-40f1d661d0d1)
高度需要设置自动或者大于一行的像素高度，才能展示出多行内容；默认的高度只能放下一行，折行后下面行的内容也无法展示
