### ISSUE TITLE
[Bug] CustomLayout.Text 计算文本包含“——”时，宽度计算有误

### ISSUE THREAD

**Issue by slipperpeng** [VisActor/VTable#2470]
### Version

1.7.2

### Link to Minimal Reproduction

暂无

### Steps to Reproduce

![bug](https://github.com/user-attachments/assets/7df8ef68-beb7-41e7-8c26-4b9add1e72ef)
https://visactor.io/vtable/demo/custom-render/custom-cell-layout  在该实例第352行修改为   bloggerName: 'Virtual anchor little w———olf',即可复现

### Current Behavior

含有 ”——“ 字符时，宽度展示不正常

### Expected Behavior

期望正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/5da63c49-696a-44fa-9dff-448989c1c79c)
快速测量方案中，可能有部分特殊字符没有办法正常测量，可以先使用setCustomAlphabetCharSet补充自定义字符，我们后面补充一下
