### ISSUE TITLE
[Bug] 在文本图元中的部分配置无效

### ISSUE THREAD

**Issue by huhaosanxiong** [VisActor/VTable#2513]
### Version

1.7.8

### Link to Minimal Reproduction

无

### Steps to Reproduce

```
const text = new VTable.CustomLayout.Text({
        text: resValue[i],
        fill: '#1D1D1D',
        boundsPadding: [0, 16, 0, 16],
        fontSize: 13,
        fontWeight: 400,
        lineHeight: 18,
        textOverflow: 'ellipsis',
        maxLineWidth: width - 32,
        lineClamp: 2,
        autoWrapText: true,
        poptip: {
          position: 'tl',
          maxWidth: 320,
          padding: 16,
          contentStyle: {
            fontSize: 12,
            lineHeight: 18,
          },
        }
```
这个文本设置为最大两行，但是实际效果不生效。

### Current Behavior

显示一行文本

### Expected Behavior

显示两行行文本

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by huhaosanxiong** [comment]
![image](https://github.com/user-attachments/assets/f36b010f-f37f-480f-8dd4-00dc678a375e)

**Comment by Rui-Sun** [comment]
![image](https://github.com/user-attachments/assets/8d20c4f7-e9a3-4abb-8103-deaae583db18)
文本正确配置请参考 https://www.visactor.io/vrender/option/Text#attribute

**Comment by huhaosanxiong** [comment]
有用，感谢
