### ISSUE TITLE
[Bug] 使用updateColumns方法更新字段配置后底部聚合栏会变成空白（官例复现），这个表格BUG太多了，我只简单的使用都找出好几个BUG了，哎

### ISSUE THREAD

**Issue by xjcallen** [VisActor/VTable#2519]
### Version

所有版本

### Link to Minimal Reproduction

bug

### Steps to Reproduce

看图
![1](https://github.com/user-attachments/assets/4a0e0699-4a35-4b63-9ee2-f76fe53d8437)

### Current Behavior

bug

### Expected Behavior

bug

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
可以加入开源贡献 一起维护组件稳定性。 @xjcallen 
目前人力有限 同时又在研发新功能，各种配置的交叉使用测试 确实很难覆盖全
