### ISSUE TITLE
[Bug] 框选带有合并单元格的情况下，调用删除方法会删除不干净，复制合并单元格的情况下粘贴会粘贴不全

### ISSUE THREAD

**Issue by shen830** [VisActor/VTable#2521]
### Version

1.7.8

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/interaction/context-menu

### Steps to Reproduce

删除
1.在官方右键菜单示例基础上，在columns下的field: 'Order ID'同级添加mergeCell: true，也就是这样{field: 'Order ID',title: 'Order ID',width: 'auto',mergeCell: true},
2.按照图中框选和指定鼠标触发右键的位置，从第三个PO-19195处按住鼠标，一直移动鼠标到CA-2015的左上角，再移动鼠标到CA-2015的中间或最下面一格位置，此时松开鼠标，右键delete
![cfdf54d1ce0c35be1bfbe78ba40ccdb](https://github.com/user-attachments/assets/5414cad5-287a-4181-a76b-9cd26343bca3)
3.原因是tableInstance.getSelectedCellInfos()得到的值和框选框住的数据不对应导致
复制粘贴
1.复制合并单元格CA-2015，随意粘贴在一个位置，单元格会被解散
![image](https://github.com/user-attachments/assets/85321cdf-dce6-4b0e-bf35-effb22697687)

### Current Behavior

删除
1.如果鼠标触发位置是在左侧合并单元格的中间位置时结果是这样
![image](https://github.com/user-attachments/assets/7b9e8627-b627-420b-96f9-fbd2f970c8b9)
2.最下面一格的位置时结果是这样
![image](https://github.com/user-attachments/assets/1bea2ee8-4216-429d-bdb5-c3a1b5f223c0)
复制粘贴
单元格会被解散，粘贴的结果不是一个完整的合并后的单元格
![image](https://github.com/user-attachments/assets/85321cdf-dce6-4b0e-bf35-effb22697687)

### Expected Behavior

删除结果保持和框选住显示的数据一致
复制完整的是完整合并后的单元格，粘贴的时候也是完整合并后的单元格

**Comment by dcdy** [comment]
还是有一些问题，1.目前鼠标最后移动到合并单元格里是正常删除了。但同样的问题，左侧合并单元格，右侧正常单元格，同样鼠标按住像下图这样操作，还是会删除不干净。2.复制粘贴单元格的问题还没有解决，复制的是合并单元格，但是粘贴时却是一个单元格，希望有时间解决一下
![image](https://github.com/user-attachments/assets/9170be82-b0c5-43bd-9543-e73ab13d89dc)
![image](https://github.com/user-attachments/assets/041569e3-cbb7-475d-a56d-91cfae3832de)
