### ISSUE TITLE
[Bug] updateColumns方法的性能问题

### ISSUE THREAD

**Issue by fochx** [VisActor/VTable#2552]
### Version

1.7.7

### Link to Minimal Reproduction

无

### Steps to Reproduce

1、构建一个columns长度为10000的，records长度为1的表格，构建过程约为5s
2、使用updateColumns方法更新它的columns的部分值，records长度不变，更新过程约25s

### Current Behavior

1、更新过程的时间比创建过程要慢很多

### Expected Behavior

1、更新过程的时间不高于创建过程

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/73e8cc38-1b33-4482-9be6-e7512b6fe68b)
我这试的没有像你说的一样。12500列 1条数据

可以把你测试的数据发我下


这是我的是测试
```
const generatePersons = count => {
  return Array.from(new Array(count)).map((_, i) => ({
    id: i + 1,
    email1: `${i + 1}@xxx.com`,
    name: `小明${i + 1}`,
    lastName: '王',
    date1: '2022年9月1日',
    tel: '000-0000-0000',
    sex: i % 2 === 0 ? 'boy' : 'girl',
    work: i % 2 === 0 ? 'back-end engineer' + (i + 1) : 'front-end engineer' + (i + 1),
    city: 'beijing'
  }));
};
  const records = generatePersons(1);
  const columns: VTable.ColumnsDefine = [
    {
      field: '',
      title: '行号',
      width: 80,
      fieldFormat(data, col, row, table) {
        return row - 1;
      },
      style: {
        underline: true,
        underlineDash: [2, 0],
        underlineOffset: 3
      }
    },
    {
      field: 'id',
      title: 'ID',
      width: 'auto',
      minWidth: 50,
      sort: true
    },
    {
      field: 'email1',
      title: 'email',
      width: 200,
      sort: true,
      style: {
        underline: true,
        underlineDash: [2, 0],
        underlineOffset: 3
      }
    },
    {
      title: 'full name',
      columns: [
        {
          field: 'name',
          title: 'First Name',
          width: 200
        },
        {
          field: 'name',
          title: 'Last Name',
          width: 200
        }
      ]
    },
    {
      field: 'date1',
      title: 'birthday',
      width: 200
    },
    {
      field: 'sex',
      title: 'sex',
      width: 100
    },
    {
      field: 'tel',
      title: 'telephone',
      width: 150
    },
    {
      field: 'work',
      title: 'job',
      width: 200
    },
    {
      field: 'city',
      title: 'city',
      width: 150
    },
    {
      field: 'date1',
      title: 'birthday',
      width: 200
    },
    {
      field: 'sex',
      title: 'sex',
      width: 100
    },
    {
      field: 'tel',
      title: 'telephone',
      width: 150
    },
    {
      field: 'work',
      title: 'job',
      width: 200
    },
    {
      field: 'city',
      title: 'city',
      width: 150
    },
    {
      field: 'date1',
      title: 'birthday',
      width: 200
    },
    {
      field: 'sex',
      title: 'sex',
      width: 100
    },
    {
      field: 'tel',
      title: 'telephone',
      width: 150
    },
    {
      field: 'work',
      title: 'job',
      width: 200
    },
    {
      field: 'city',
      title: 'city',
      width: 150
    },
    {
      field: 'date1',
      title: 'birthday',
      width: 200
    },
    {
      field: 'sex',
      title: 'sex',
      width: 100
    },
    {
      field: 'tel',
      title: 'telephone',
      width: 150
    },
    {
      field: 'work',
      title: 'job',
      width: 200
    },
    {
      field: 'city',
      title: 'city',
      width: 150
    }
  ];
  let tableColumns = [];
  for (let i = 0; i < 500; i++) {
    tableColumns = tableColumns.concat(columns);
  }
  const option: VTable.ListTableConstructorOptions = {
    container: document.getElementById(CONTAINER_ID),
    emptyTip: true,
    records,
    columns: tableColumns,
    tooltip: {
      isShowOverflowTextTooltip: true
    },
    frozenColCount: 1,
    bottomFrozenRowCount: 2,
    rightFrozenColCount: 2,
    overscrollBehavior: 'none',
    dragHeaderMode: 'all',
    keyboardOptions: {
      pasteValueToCell: true,
      copySelected: true,
      selectAllOnCtrlA: true
    },
    eventOptions: {
      preventDefaultContextMenu: false
    },
    autoWrapText: true,
    editor: '',
    // theme: VTable.themes.ARCO,
    // hover: {
    //   highlightMode: 'cross'
    // },
    // select: {
    //   headerSelectMode: 'cell',
    //   highlightMode: 'cross'
    // },
    theme: {
      frameStyle: {
        cornerRadius: [10, 0, 0, 10],
        // cornerRadius: 10,
        borderLineWidth: [10, 0, 10, 10],
        // borderLineWidth: 10,
        borderColor: 'red',
        shadowBlur: 0
      }
    },
    excelOptions: {
      fillHandle: true
    }
    // widthMode: 'adaptive'
  };
  const t0 = performance.now();
  const tableInstance = new VTable.ListTable(option);
  console.log('new table', performance.now() - t0);
  window.tableInstance = tableInstance;

  const t1 = performance.now();
  tableInstance.updateColumns(tableColumns);
  console.log('updateColumns', performance.now() - t1);
```

**Comment by fochx** [comment]
![image](https://github.com/user-attachments/assets/8290c826-89de-40ea-83ef-b8ca4fdd0ed4)
这是我的测试结果，代码如下：

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../libs/vue-vxe/vxe-table-3.6.13/vxe-table-3.6.13.css">
    <style>
        html,
        body,
        #app {
            height: 100%;
        }

        body {
            position: relative;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
    </style>
</head>

<body>
    <script src="../libs/vue-vxe/vue.js"></script>
    <script src="./vtable.min.js"></script>
    <script src="./vtable-editors.min.js"></script>

    <div id="app" class="container-fluid">
        <p v-if="loading">
            
            <button @click="updateColumns()">更新Columns</button>
        </p>
        <div id="tableContainer" style="width: 100%;height:600px;"></div>
    </div>
    <script>
        const generatePersons = (i, columns) => {
            const obj = {};
            columns.forEach(column => {
                obj[column.field] = i;
            })
            obj.seq = i + 1;
            return obj;
        };

        /**
         * 模拟接口请求数据
         * @param startIndex
         * @param num
         * @returns
         */
        const getRecordsWithAjax = (startIndex, num, columns) => {
            // console.log('getRecordsWithAjax', startIndex, num);
            return new Promise(resolve => {
                setTimeout(() => {
                    console.log('getRecordsWithAjax', startIndex, num);
                    const records = [];
                    for (let i = 0; i < num; i++) {
                        records.push(generatePersons(startIndex + i, columns));
                    }
                    resolve(records);
                }, 300);
            });
        };

        /**
         * 获取列数
         * @param startIndex
         * @param num
         * @returns
         */
        const getColumns = (num, isTranspose) => {
            const columns = [];
            if (isTranspose) {
                columns.push({
                    field: 'seq',
                    title: '',
                    width: 70,
                    // headerStyle: {
                    //     bgColor: '#f1f2f4'
                    // },
                    style: {
                        bgColor: '#f1f2f4'
                    },
                    // customRender(args) {
                    //     const { width, height } = args.rect;
                    //     const { dataValue, table, row, col } = args;
                    //     const elements = [];
                    //     let top = 30;
                    //     const left = 15;
                    //     let maxWidth = 0;
                    //     elements.push({
                    //         type: 'text',
                    //         fill: 'black',
                    //         fontSize: 12,
                    //         fontWeight: 500,
                    //         textBaseline: 'middle',
                    //         text: (isTranspose ? col : row).toString(),
                    //         x: 15,
                    //         y: 15,
                    //     });
                    //     return {
                    //         elements
                    //     }
                    // }
                })
            }
            for (let i = 0; i < num; i++) {
                columns.push({
                    field: `${i + 1}`,
                    title: `${i + 1}`,
                    width: 70,
                    editor: 'input-editor'
                });
            }
            return columns;
        };
        (function () {
            new Vue({
                data() {
                    return {
                        loading: false,
                        tableInstance: null,
                        theme: {
                            defaultStyle: {
                                fontSize: 12,
                                textAlign: 'center',
                                textBaseline: 'bottom',
                                borderColor: '#dddddd',
                                fontFamily: '-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol',
                                frameStyle: {
                                    borderColor: '#ddd',
                                    borderLineWidth: [1, 1, 1, 1]
                                }
                            },
                            bodyStyle: {
                                // bgColor: (args) => {
                                //     return args.row % 2 ? '#efefef80' : 'white'
                                // },
                                bgColor: 'white',
                                textAlign: 'left',
                                padding: [2, 1, 2, 2]
                            },
                            headerStyle: {
                                bgColor: '#f1f2f4',
                                textBaseline: 'middle'
                            },
                            frameStyle: {
                                borderColor: '#dddddd',
                                borderLineWidth: [0, 1, 1, 0]
                            },
                            selectionStyle: {
                                cellBorderColor: '#007ACC',
                                cellBgColor: '#eaeaea80',
                                selectionFillMode: 'replace'
                            },
                            scrollStyle: {
                                scrollSliderCornerRadius: 0,
                                width: 8,
                                visible: 'always'
                            }
                        }
                    };
                },
                mounted() {
                    this.loadData(1, 10000)
                },
                methods: {
                    loadData(rows, cols) {
                        this.loading = true;
                        let tmp;
                        if (cols > 10000) {
                            tmp = cols;
                            cols = rows;
                            rows = tmp;
                        }
                        if (this.tableInstance) {
                            this.tableInstance.release();
                            this.tableInstance = null;
                        }
                        // create DataSource
                        const columns = getColumns(cols, !!tmp);
                        const loadedData = {};
                        const option = {
                            columns,
                            canvasWidth: 1000,
                            canvasHeight: 500,
                            colsCount: columns.length,
                            rowsCount: rows,
                            transpose: !!tmp,
                            // records: Array.from({length: rows}, (_, i) => ({})),
                            defaultColWidth: 70,
                            defaultHeaderColWidth: 70,
                            defaultRowHeight: 22,
                            widthMode: 'standard',
                            columnResizeMode: 'body',
                            editCellTrigger: 'doubleclick',
                            keyboardOptions: {
                                copySelected: false,
                                pasteValueToCell: false,
                                selectAllOnCtrlA: false
                            },
                            menu: {
                                contextMenuItems: ['复制', '粘贴', '删除', '...']
                            },
                            theme: this.theme,
                            frozenColCount: 1,
                            frozenRowCount: 1
                        };
                        if (!tmp) {
                            option.rowSeriesNumber = {
                                title: '',
                                width: 50,
                                headerStyle: {
                                    color: 'black',
                                    bgColor: '#f1f2f4',
                                    textAlign: 'center'
                                },
                                style: {
                                    bgColor: '#f1f2f4',
                                    textAlign: 'center'
                                }
                            };
                        }
                        const inputEditor = new VTable.editors.InputEditor();
                        VTable.register.editor('input-editor', inputEditor);
                        const dataSource = new VTable.data.CachedDataSource({
                            get(index) {
                                // return {}
                                // 每一批次请求100条数据 0-99 100-199 200-299
                                const loadStartIndex = Math.floor(index / 100) * 100;
                                // 判断是否已请求过？
                                if (!loadedData[loadStartIndex]) {
                                    // console.log("startRender", new Date().getTime())
                                    const promiseObject = getRecordsWithAjax(loadStartIndex, 100, columns); // return Promise Object
                                    loadedData[loadStartIndex] = promiseObject;
                                }
                                return loadedData[loadStartIndex].then((data) => {
                                    return data[index - loadStartIndex]; //获取批次数据列表中的index对应数据
                                });
                            },
                            length: rows //all records count
                        });
                        const t0 = Date.now();
                        console.log('开始创建：', t0);
                        this.tableInstance = new VTable.ListTable(document.getElementById('tableContainer'), option);
                        console.log('结束创建：', Date.now() - t0);
                        this.tableInstance.dataSource = dataSource;
                        window['tableInstance'] = this.tableInstance;
                    },
                    updateColumns() {
                        const columns = getColumns(9999, false);
                        const t0 = Date.now();
                        console.log('开始更新：', t0);
                        this.tableInstance.updateColumns(columns);
                        console.log('结束更新：', Date.now() - t0);
                    },
                }
            }).$mount("#app");
        })()
    </script>
</body>

</html>

**Comment by fangsmile** [comment]
你用了懒加载，同时有设置width:'auto'.这样用回导致懒加载无效。因为需要获取全部数据才能计算整列单元格的列宽。初始化是有个局部计算逻辑为了减少白屏时间。updateColumns等其他接口没有做这个局部计算。建议你把auto去掉

**Comment by fochx** [comment]
> 你用了懒加载，同时有设置width:'auto'.这样用回导致懒加载无效。因为需要获取全部数据才能计算整列单元格的列宽。初始化是有个局部计算逻辑为了减少白屏时间。updateColumns等其他接口没有做这个局部计算。建议你把auto去掉

我的columns里的width的值是设置的固定值70，没有设置auto呀 @fangsmile

**Comment by HyokaChen** [comment]
@fangsmile 我这边使用的时候也遇到了，当然是为了隐藏列头，看了下 columns 里面可以配置 hide 属性，但是还是得调用 updatecolumns 才能生效，整体响应就会变慢🤣
