### ISSUE TITLE
[Feature] 点击外部区域是否取消选中

### ISSUE THREAD

**Issue by xiaoshengwpp** [VisActor/VTable#2553]
### What problem does this feature solve?

select-outsideClickDeselect: true
开启后  鼠标选择区域 向上 或向下滑动选择后 松开鼠标左键 会触发取消选中；是不是把抬起事件触发取消选择取消掉更合理点？

### What does the proposed API look like?

-

**Comment by fangsmile** [comment]
现在就是鼠标抬起的判断  那我们看看鼠标按下时取消是否合理
