### ISSUE TITLE
[Bug] 行序号 加排序 点击就报错  Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by zhangchenna** [VisActor/VTable#2558]
### Version

1.8.2

### Link to Minimal Reproduction

[Bug] 行序号 加排序 点击就报错  Cannot read properties of undefined (reading 'id')

### Steps to Reproduce

[Bug] 行序号 加排序 点击就报错  Cannot read properties of undefined (reading 'id')

### Current Behavior

[Bug] 行序号 加排序 点击就报错  Cannot read properties of undefined (reading 'id')

### Expected Behavior

[Bug] 行序号 加排序 点击就报错  Cannot read properties of undefined (reading 'id')

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xjcallen** [comment]
和这个问题重复了吧
https://github.com/VisActor/VTable/issues/2488

**Comment by zhangchenna** [comment]
> 和这个问题重复了吧 #2488

是的，以为修复了，发现最新版还是有这个问题
