### ISSUE TITLE
请问实现自定义 React 编辑器的时候如何使用 Context

### ISSUE THREAD

**Issue by moonsky-all** [VisActor/VTable#2567]
我参考这里实现了一个自定义 React 下拉框：

[https://visactor.io/vtable/demo-react/functional-components/arco-select-editor](https://visactor.io/vtable/demo-react/functional-components/arco-select-editor)

但是下拉框选项来自应用的 Context ，不能在 Select 外面再包一层 Context 吧？不太合理

所以想请教一下，这种情况我该如何实现呢？

**Comment by fangsmile** [comment]
需要在自定义编辑器中通过参数来确定选项吗？ 那就得自己写逻辑的
![image](https://github.com/user-attachments/assets/ad1f5388-6d5d-4c70-8e98-a079cf67244f)

**Comment by moonsky-all** [comment]
是自己写逻辑，参数 editorContext 能访问的东西太少了，只能访问单元格的数据、位置信息。

但是实际中自定义下拉框选项并不像示例那样是写死的，通常来自 store、context、后端接口等，这些好像都访问不了（或者只能通过全局变量传递，但是太不优雅了）；

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/fe7f3683-46e1-4242-8bfb-7eb983aa3f43)
这个 col 和row 的参数很有用的。可以通过tableInstance.接口  获取到你想要的信息，例如：https://visactor.io/vtable/api/Methods#getRecordByCell
