### ISSUE TITLE
[Bug] 冻结列 勾选复选框会导致重新渲染

### ISSUE THREAD

**Issue by xiaoshengwpp** [VisActor/VTable#2568]
### Version

1.8.0

### Link to Minimal Reproduction

-

### Steps to Reproduce

貌似是从 1.8 版本开始 目前最新版本 
开启 rightFrozenColCount 后  勾选复选框 会导致这一列内容重新渲染（这一列使用了自定义组件）
已知：
复选框勾选取消 必重新绘制
没开启的冻结的列 无影响

### Current Behavior

貌似是从 1.8 版本开始 目前最新版本 
开启 rightFrozenColCount 后  勾选复选框 会导致这一列内容重新渲染（这一列使用了自定义组件）
已知：
复选框勾选取消 必重新绘制
没开启的冻结的列 无影响

### Expected Behavior

貌似是从 1.8 版本开始 目前最新版本 
开启 rightFrozenColCount 后  勾选复选框 会导致这一列内容重新渲染（这一列使用了自定义组件）
已知：
复选框勾选取消 必重新绘制
没开启的冻结的列 无影响

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoshengwpp** [comment]
没开启冻结的列 无影响

**Comment by Rui-Sun** [comment]
提供一个复现环境吧，没有能够复现这个问题

**Comment by xiaoshengwpp** [comment]
> 提供一个复现环境吧，没有能够复现这个问题

稍等 我这里尝试最小代码也没有复现出来；可能跟onCheckboxStateChange 内部分代码有关   这个注释掉 问题也不会出现，
或者关闭冻结 问题不会出现
我再排查下

**Comment by xiaoshengwpp** [comment]
https://codesandbox.io/p/sandbox/stoic-https-xwdhhl
@Rui-Sun

**Comment by xiaoshengwpp** [comment]
貌似还是有问题 而且会导致复选框无法勾选
