### ISSUE TITLE
[Feature] 点击某行高亮 和 点击表头清空高亮 

### ISSUE THREAD

**Issue by skie1997** [VisActor/VTable#2573]
### What problem does this feature solve?

1. 点击某行数据，某行数据高亮
![20241009144042_rec_](https://github.com/user-attachments/assets/2ebb8654-c184-43b7-b218-779dca5a94be)

2. 单击表头，高亮被清空
![20241009144129_rec_](https://github.com/user-attachments/assets/bed6e7df-2afc-4cca-8d35-88953ce5ceea)

3. 滚动时，高亮数据保持不变
![img_v3_02fg_6965ac3a-662a-4fe2-923a-3efc28ca90cg](https://github.com/user-attachments/assets/0d78da42-5b91-4148-9755-4753457d7488)

### What does the proposed API look like?

null

**Comment by skie1997** [comment]
预计接入时间：2024.10.25之前

**Comment by li936393** [comment]
建议
第1点，高亮的样式，可以通过自定义样式来进行个性化修改
第2点，"单击表头，高亮被清空" 这个行为是可配的，如操作员点击了表格外的区域，此时表格还是可以保持选中状态
第3点，“滚动时，高亮数据保持不变“这个行为是可配置的，某些业务场景下可能并不需要保持不变，只是想要反选的效果
