### ISSUE TITLE
[FAQ]How to implement multi-level headers in a basic table (ListTable)?

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#258]
How to construct such hierarchical structure to display in table header cells like: Department (Finance, Technology), Name (First Name, Last Name)?
![image](https://github.com/VisActor/VTable/assets/3468473/15dde1a5-8823-4e6d-9523-49bfc4a3f045)

**Comment by xuanhun** [comment]
In VTable, the configuration option "columns" can be used to configure sub-items under "columns".
Code Example
```
{
      field: 'full name',
      caption: 'Full name',
      columns: [
        {
          field: 'name',
          caption: 'First Name',
          width: 120
        },
        {
          field: 'lastName',
          caption: 'Last Name',
          width: 100
        }
      ]
    },
```
### Results

Online demo：[https://codesandbox.io/s/vtable-columns-nested-structure-4zwk43](https://codesandbox.io/s/vtable-columns-nested-structure-4zwk43)
![image](https://github.com/VisActor/VTable/assets/2384516/623f9629-5404-4a33-8aa1-a7a8cfaa319b)

### Related Documentation

List Table Demo：[https://visactor.bytedance.net/vtable/demo/table-type/list-table](https://visactor.bytedance.net/vtable/demo/table-type/list-table)

List Table Tutorial：[https://visactor.bytedance.net/vtable/guide/table_type/List_table/list_table_define_and_generate](https://visactor.bytedance.net/vtable/guide/table_type/List_table/list_table_define_and_generate)

Related api：[https://visactor.bytedance.net/vtable/option/ListTable-columns-text#columns](https://visactor.bytedance.net/vtable/option/ListTable-columns-text#columns)

github：[https://github.com/VisActor/VTable](https://github.com/VisActor/VTable)
