### ISSUE TITLE
[Bug] 自定义单元格的内容复制时内容错误

### ISSUE THREAD

**Issue by noxxxxxxxx** [VisActor/VTable#2583]
### Version

1.8.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/competent-engelbart-g5tn75

### Steps to Reproduce

1. 设置自定义的单元格元素 vText，值为格式化后的字符串，例如 123,456.00
2. 鼠标选中单元格复制

### Current Behavior

复制结果是 123

### Expected Behavior

复制结果是 123,456.00

### Environment

```markdown
- OS: MAC
- Browser: Chrom
- Framework:
```

**Comment by fangsmile** [comment]
指标值你这里是个字符串 vtable内部不会自动识别`123,456` 带有千分位逗号形式的数字的。
请将其转为number
![image](https://github.com/user-attachments/assets/2b5607a6-dcca-4edc-98b1-6b5d3ee6d8cb)

**Comment by noxxxxxxxx** [comment]
> 指标值你这里是个字符串 vtable内部不会自动识别`’123,456‘` 带有千分位逗号形式的数字的。 请将其转为number ![image](https://private-user-images.githubusercontent.com/3468473/375604522-2b5607a6-dcca-4edc-98b1-6b5d3ee6d8cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTYzMzgsIm5iZiI6MTcyODYxNjAzOCwicGF0aCI6Ii8zNDY4NDczLzM3NTYwNDUyMi0yYjU2MDdhNi1kY2NhLTRlZGMtOThiMS02YjVkM2VlNmQ4Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDMwNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk0NjgzYjE2OGUxNDQzMmJlOTM5MjY3M2JjNzA2NmUzYjJhZjg2YWNjMDc3MDc5ZWJkY2E0YmFkYmE4ODg1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ypy-sqhwViaEyA3YoUF_pvUeJbAZpcNxnknmT4toxAY)

那金额的格式化呢？展示的内容和复制的内容要保持一致，这种岂不是无法实现了
