### ISSUE TITLE
[Bug] 同时开启分组和列求和的时候ListTable表格会报错

### ISSUE THREAD

**Issue by lhyllc** [VisActor/VTable#2600]
### Version

1.8.1

### Link to Minimal Reproduction

.

### Steps to Reproduce

Uncaught TypeError: Cannot destructure property 'vtableMerge' of 'table.getCellRawRecord(...)' as it is undefined.
    at ListTableAll.getCellValue (ListTable.ts:248:1)

### Current Behavior

Uncaught TypeError: Cannot destructure property 'vtableMerge' of 'table.getCellRawRecord(...)' as it is undefined.
    at ListTableAll.getCellValue (ListTable.ts:248:1)

### Expected Behavior

Uncaught TypeError: Cannot destructure property 'vtableMerge' of 'table.getCellRawRecord(...)' as it is undefined.
    at ListTableAll.getCellValue (ListTable.ts:248:1)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
把你的demo发下吧  分组是指的group。完整配置发这吧 @lhyllc

**Comment by fangsmile** [comment]
是在折叠节点交互的时候报错的吗  @lhyllc
