### ISSUE TITLE
[Bug] 多列排序时，updateSortState批量更新排序列的icon状态不对

### ISSUE THREAD

**Issue by huhaosanxiong** [VisActor/VTable#2614]
### Version

1.9.1

### Link to Minimal Reproduction

无

### Steps to Reproduce

官方例子可复现。
![WX20241014-175252@2x](https://github.com/user-attachments/assets/8f69076b-3c74-428b-a9a5-840b24baab9b)

```
tableInstance.updateSortState([
      { field:'Order ID', order: 'asc' },
      { field:'Customer ID', order: 'desc' }
      ],
      false)
```

### Current Behavior

只有updateSortState数组中的第一列的icon显示正确，其他列似乎被忽略？

### Expected Behavior

updateSortState所传递的数组中的所有列的状态都正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by huhaosanxiong** [comment]
通过updateOption的API，更新其中的sortState可解决此问题。但最好还是修复下updateSortState 😁
<img width="1736" alt="image" src="https://github.com/user-attachments/assets/272cf9e2-c903-4fca-87ab-effb55045f66">

**Comment by zuoerji** [comment]
tableInstance.updateSortState(
        {
          field: args.field,
          order: 'normal'
        },
        false
      );

先设置 normal 再设置 'desc' 就失效了 ，这个是怎么回事
tableInstance.updateSortState(
    {
      field: args.field,
      order: 'desc'
    },
    false
  )

我想要做就是只是点亮图标，但是我用 updateRecords 去分页面更新的时候，发现哪怕设置了 sortClick 里面 return false ,sort :false 但是 updateRecords 设置进去的索引因为更新的排序，导致数据位置有问题，所以才用这个方式，但是这个方式的问题是，先设置 normal 后面设置就失效了，怎么处理


后面我发现，只能设置一次，第一次设置了什么排序就是什么排序，后面改不了了
