### ISSUE TITLE
vtable结合vchart图表库，vchart无法使用cdn引入吗？

### ISSUE THREAD

**Issue by tufaofu** [VisActor/VTable#2622]
vtable结合vchart图表库绘制透视组合图，如果vchart是通过cdn引入的，会报错
vtable: 1.8.0
vchart: 1.12.7
![image](https://github.com/user-attachments/assets/0fecef8b-b5c4-4a93-a38a-36efdc2ed014)

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/4cc68f41-9d48-43f7-ab49-0b801909fb13)
需要这样引用注册
