### ISSUE TITLE
[Bug] 开启rowSeriesNumber后，排序图标点击后高亮效果消失了。

### ISSUE THREAD

**Issue by ChenErik** [VisActor/VTable#2624]
### Version

1.9.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-r3cq8g

### Steps to Reproduce

同时配置sort和rowSeriesNumber属性

### Current Behavior

sort高亮效果失效

### Expected Behavior

正常高亮

### Environment

```markdown
- OS: window11
- Browser:chrome 127.0.6533.89
- Framework: vue@3.5
```

**Comment by fangsmile** [comment]
可以升级到最新版1.10.0 试下 @ChenErik

**Comment by ChenErik** [comment]
试了1.10.0,没有修复

**Comment by fangsmile** [comment]
1.10.2已修复 @ChenErik
