### ISSUE TITLE
[Feature] 行总计再多个指标的时候无法隐藏排序按钮

### ISSUE THREAD

**Issue by scriptnojava** [VisActor/VTable#2630]
### What problem does this feature solve?

因为大部分使用场景除了总计其他的数据是服务端排序的，因此总计不能支持排序，但是现在无法隐藏排序按钮

### What does the proposed API look like?

showSort可否提供类似于bgColor这种回调，让用户自己决定是否展示排序按钮

**Comment by fangsmile** [comment]
“因为大部分使用场景除了总计其他的数据是服务端排序的，因此总计不能支持排序，但是现在无法隐藏排序按钮”
请问 你的具体配置是什么？请结合图文解释下你的应用场景吧
@scriptnojava

**Comment by scriptnojava** [comment]
![image](https://github.com/user-attachments/assets/99f9d016-be04-4e07-95d5-6f5a7c429ad3)
当我们给指标设置排序按钮的时候，总计下面的指标也会有排序按钮。但是预期是不希望有这个按钮的，总计的这一列的数据不是在服务端生成的

**Comment by fangsmile** [comment]
感谢你的反馈！我们已经收到你的问题，并将在后续进行处理。
如果有开发者对这个 issue 感兴趣，请在issue下方留言“认领该issue”，留言后开始你的创作提pr给我们！
欢迎大家参与开源共建！我们非常感激每一位贡献者，提交pr后我们将为参与共建的开发者准备一份礼品。
参与共建可参考：https://visactor.io/vtable/guide/Contribution_Guide
与官方开发者交流问题可以下载飞书app扫码加入飞书群：
![飞书20241029-170312](https://github.com/user-attachments/assets/f753113a-f466-437d-b6d7-951e70303ae9)
再次感谢你的支持！

Thank you for your feedback! We have received your question and will deal with it later.
If any developer is interested in this issue, please leave a message "claim this issue" below the issue, and then start submitting your creation to us!
Welcome everyone to participate in open source co-construction! We are very grateful to every contributor. After submitting the PR, we will prepare a gift for the developers who participate in the co-construction.
For participation in co-construction, please refer to: https://visactor.io/vtable/guide/Contribution_Guide
To communicate with official developers, you can download the Feishu app and scan the QR code to join the Feishu group！
Thank you again for your support!
