### ISSUE TITLE
[Bug] 开启了行号后，点击排序，图标不会更新

### ISSUE THREAD

**Issue by xjcallen** [VisActor/VTable#2631]
### Version

1.9.1

### Link to Minimal Reproduction

/

### Steps to Reproduce

https://github.com/VisActor/VTable/issues/2488
这前提的这个问题解决了，但是又出了新的问题
启用了行号点排序他不会更新变化图标
![image](https://github.com/user-attachments/assets/0f5ef8ec-a110-4e3e-a6e6-2a1f1e50b9ce)
不启用行号排序就可以更新变化
![image](https://github.com/user-attachments/assets/8ea94797-3aa3-46b0-863a-46c878b5af13)

### Current Behavior

、

### Expected Behavior

/

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
可以升级到最新版1.10.0 试下 @xjcallen
