### ISSUE TITLE
[Bug] 开启行序号自定义排序图标不切换

### ISSUE THREAD

**Issue by Aeiousl** [VisActor/VTable#2643]
### Version

1.9.0

### Link to Minimal Reproduction

-

### Steps to Reproduce

在1.9.0版本修复了开启行序号排序报错的问题，但是如果自定义了排序图标，点击排序图标不会切换

### Current Behavior

。

### Expected Behavior

点击排序图标切换自定义升序、降序图标

### Environment

```markdown
- OS:windows
- Browser:Chrome 122
- Framework:Vue@2
```

**Comment by Aeiousl** [comment]
原生的排序图标在开启行号后点击也不会切换升序、降序图标

**Comment by fangsmile** [comment]
@Aeiousl 可以试一下1.10.0 修复好了吗

**Comment by Aeiousl** [comment]
> @Aeiousl 可以试一下1.10.0 修复好了吗

1.10.0 试了一下，没有修复
