### ISSUE TITLE
[Bug] 横向滚动条不在最左侧时，鼠标拖动框选行序号多选行时，滚动条会自己滑动到最左侧

### ISSUE THREAD

**Issue by ybli0719** [VisActor/VTable#2647]
### Version

1.10.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

横向滚动条不在最左侧时，鼠标拖动框选行序号多选行时，滚动条会自己滑动到最左侧

### Current Behavior

横向滚动条不在最左侧时，鼠标拖动框选行序号多选行时，滚动条会自己滑动到最左侧

### Expected Behavior

滚动条不滚动

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
这是我们的优化，框选时会自动滚动。方便一直往一个方向滚动
你的效果是什么样子啊  可以发个动画看看是不是问题

**Comment by ybli0719** [comment]
@fangsmile 

https://github.com/user-attachments/assets/6be8fa1a-c8a8-4a76-8047-aaa02201bd6a

在序列号上框选  滚动条会移动到左侧 就很怪  正常是不应该滚动的

**Comment by fangsmile** [comment]
很关键的配置是加了冻结  才能复现哈。
我看一下吧
