### ISSUE TITLE
[Bug] 单元格内文字不是上下对齐的，下面比上面多3个像素，默认行高设置为24时明显看出文字靠上

### ISSUE THREAD

**Issue by Tom4Java** [VisActor/VTable#2666]
### Version

1.10.1

### Link to Minimal Reproduction

none

### Steps to Reproduce

defaultRowHeight设置为24,

### Current Behavior

文字与上边框的间距为5，与下边框的间距为8

### Expected Behavior

上下间距一致

### Environment

```markdown
- OS:
win10
- Browser:
Chrome/129.0.0.0
- Framework:
Vue3
```

**Comment by Rui-Sun** [comment]
表格内目前的文字对齐策略，是保证小写英文字母(ae...)居中对齐；这样的策略下，ft等字符会向上占据更多空间，视觉上会偏上；yg等字符会向下占据更多空间，视觉上会偏下；大写字母、数字、汉字都会向上占据更多空间，视觉上会偏上。在表格这样的文字密集场景中（如excel），不太好实现完全的对齐，否则可能出现单元格之间的文字不能对齐的场景
![img_v3_02fl_2965abb3-1aa4-4785-b0a6-b8dc3fd4f9fg](https://github.com/user-attachments/assets/1acef356-607a-48df-97c4-14129b1c056d)

**Comment by Tom4Java** [comment]
谢谢解答，那能否通过配置修改呢，表格数据大多数都是中文，靠上 还是看着挺明显的
![image](https://github.com/user-attachments/assets/699952fe-0ac0-4384-9b95-951fc8198a41)

**Comment by Tom4Java** [comment]
> 表格内目前的文字对齐策略，是保证小写英文字母(ae...)居中对齐；这样的策略下，ft等字符会向上占据更多空间，视觉上会偏上；yg等字符会向下占据更多空间，视觉上会偏下；大写字母、数字、汉字都会向上占据更多空间，视觉上会偏上。在表格这样的文字密集场景中（如excel），不太好实现完全的对齐，否则可能出现单元格之间的文字不能对齐的场景 ![img_v3_02fl_2965abb3-1aa4-4785-b0a6-b8dc3fd4f9fg](https://private-user-images.githubusercontent.com/25134429/379998054-1acef356-607a-48df-97c4-14129b1c056d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTY1MzAsIm5iZiI6MTcyOTg1NjIzMCwicGF0aCI6Ii8yNTEzNDQyOS8zNzk5OTgwNTQtMWFjZWYzNTYtNjA3YS00OGRmLTk3YzQtMTQxMjliMWMwNTZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDExMzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTJjOTllMDQ4NThhZjY1M2RiYzU2MjMwZGQ5ODA3ZTQ5NzE0NDAyYTlhZTdmMmViYzk2MDdiZmM3MDY1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UlzqjjDRRmHcsmBRMDXxAbeJF52LyJInQ64Hbu_1woI)
---------------------------------------------------------------------------------
谢谢解答，那能否通过配置修改呢，表格数据大多数都是中文，靠上 还是看着挺明显的
![image](https://github.com/user-attachments/assets/57d803f8-2205-4729-9706-b901ea9f57d7)

**Comment by Rui-Sun** [comment]
可以试一下padding配置，上下设置不一样的padding

**Comment by Tom4Java** [comment]
padding 设置成上4，下0，看不大出来了，先这样处理下吧

**Comment by coretimes** [comment]
> padding 设置成上4，下0，看不大出来了，先这样处理下吧

这样处理有个问题就是，如果有默认图标比如tree和checkbox就不居中了

**Comment by coretimes** [comment]
> 表格内目前的文字对齐策略，是保证小写英文字母(ae...)居中对齐；这样的策略下，ft等字符会向上占据更多空间，视觉上会偏上；yg等字符会向下占据更多空间，视觉上会偏下；大写字母、数字、汉字都会向上占据更多空间，视觉上会偏上。在表格这样的文字密集场景中（如excel），不太好实现完全的对齐，否则可能出现单元格之间的文字不能对齐的场景 ![img_v3_02fl_2965abb3-1aa4-4785-b0a6-b8dc3fd4f9fg](https://private-user-images.githubusercontent.com/25134429/379998054-1acef356-607a-48df-97c4-14129b1c056d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTAxMDIsIm5iZiI6MTczMjI0OTgwMiwicGF0aCI6Ii8yNTEzNDQyOS8zNzk5OTgwNTQtMWFjZWYzNTYtNjA3YS00OGRmLTk3YzQtMTQxMjliMWMwNTZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA0MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMWIwMmNiNzBjNWY5ZjQ1MTkwOWU3MDk2MmNlZmQ0ODczNjIxMzA1ZDRhYWY3ZThjOGNjZTgzZjVkNDFjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uROMFIzh2k3kKa2W5y6A-kvf3BhrkmuzScMFMN73bbU)

其实完全可以不用考虑大小写居中，就默认字体居中就行了
