### ISSUE TITLE
[Feature] 设置指定的单元格不可编辑

### ISSUE THREAD

**Issue by ghfkui** [VisActor/VTable#2669]
### What problem does this feature solve?

设置指定的单元格不可编辑

### What does the proposed API look like?

在column配置的时候disableSelect提供一个函数可以根据record判断哪些可以单元格可以编辑，哪些不可以

**Comment by fangsmile** [comment]
配置项editor可以配置个函数   函数判断下 返回个不存在的编辑器就不能编辑了
