### ISSUE TITLE
[Feature] 甘特图配置是否可支持一行显示多条数据的效果？

### ISSUE THREAD

**Issue by JACK-ZHANG-coming** [VisActor/VTable#2672]
### What problem does this feature solve?

请问大佬，甘特图配置是否可支持一行显示多条数据的效果？ 因为在实际开发中有需求用到

### What does the proposed API look like?

效果图如下方文件，这是别人家的插件

![企业微信截图_17298177672628](https://github.com/user-attachments/assets/9239f1ab-b91a-47c3-bd36-7230b53633d7)

**Comment by fangsmile** [comment]
@JACK-ZHANG-coming 你这个是哪个组件库的截图
