### ISSUE TITLE
[Feature] 文字超出row height后，期望表头 / 单元格高度不被 撑开/压缩

### ISSUE THREAD

**Issue by skie1997** [VisActor/VTable#2681]
### What problem does this feature solve?

1. 单元格文字过大，单元格高度被撑开 且 表头被压缩
![image](https://github.com/user-attachments/assets/5de4f625-3827-40e7-827a-dfc04834513e)

2. 表头文字过大，表头高度被撑开
![image](https://github.com/user-attachments/assets/6a3ee5cc-4b3f-4b1f-845d-edc50c6f5ef8)

### What does the proposed API look like?

null

**Comment by Rui-Sun** [comment]
增加配置，各行按照defaultRowHeight/defaultHeaderRowHeight进行adaptive均分

**Comment by skie1997** [comment]
@Rui-Sun  预期效果：
![20241030154133_rec_](https://github.com/user-attachments/assets/27c4fd05-101b-4b13-8b49-ee5c6e9cf53b)
