### ISSUE TITLE
[Bug] 甘特图markline给出的日期不在当前范围内，markline会显示在某一个位置上

### ISSUE THREAD

**Issue by majinkai** [VisActor/VTable#2689]
### Version

1.10.1

### Link to Minimal Reproduction

/

### Steps to Reproduce

```
markLine: [
      {
        date: dayjs().format('YYYY-MM-DD'),
        position: 'middle',
        style: {
          lineWidth: 1,
          lineColor: window.$themeVars?.successColor,
          scrollToMarkLine: true,
          lineDash: [8, 4]
        }
      }
    ]
```

### Current Behavior

![image](https://github.com/user-attachments/assets/e941b8f7-f5f0-4f6e-9f93-27ffcf7087d8)

### Expected Behavior

/

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
@majinkai 你设置的日期是什么？现在markline是显示在2025年3月6日 是不对的吗？

**Comment by majinkai** [comment]
> @majinkai 你设置的日期是什么？现在markline是显示在2025年3月6日 是不对的吗？

设置的是dayjs()，也就是今天

**Comment by fangsmile** [comment]
> @fangsmile
> 
> 设置的是`date: dayjs().format('YYYY-MM-DD')`，也就是今天
> 
> 假设整个图中的最小日期是2025-01-01，最大日期是2025-10-01，markline给出一个日期是2024-12-01，就会像上图一样，在甘特图的某个位置上面显示一条线，按理说不应该显示任何线

ok 你这样描述问题 我就知道怎么复现去排查问题了 @majinkai
