### ISSUE TITLE
[Bug] The pivotTable horizontal scroll bar is abnormal when the display area is small

### ISSUE THREAD

**Issue by X-smart** [VisActor/VTable#269]
### Version

0.10.1-alpha.2

### Link to Minimal Reproduction

https://codesandbox.io/s/vtable-columns-nested-structure-forked-23t782?file=/src/index.ts

### Steps to Reproduce

The pivotTable horizontal scroll bar is abnormal when the display area is small

### Current Behavior

The pivotTable horizontal scroll bar is abnormal when the display area is small

### Expected Behavior

PivotTable horizontal scroll bar operation is normal

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
fixed version 0.10.1
