### ISSUE TITLE
[Bug] 单元格编辑，Esc退出编辑后按tab键无法选中下一个单元格

### ISSUE THREAD

**Issue by ghfkui** [VisActor/VTable#2693]
### Version

1.10.0

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/edit/edit-cell

### Steps to Reproduce

1.点击进入单元格编辑状态
2.按Esc键退出编辑状态
3. 按tab键切换

### Current Behavior

下一个单元格没有被选中，table element失去了焦点

### Expected Behavior

下一个单元格选中

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
感谢你的反馈！我们已经收到你的问题，并将在后续进行处理。
如果有开发者对这个 issue 感兴趣，欢迎参与开源共建。
我们非常感激每一位贡献者，提交pr后我们将为参与共建的开发者准备一份礼品。
参与共建可参考：https://visactor.io/vtable/guide/Contribution_Guide
与官方开发者交流问题可以加入飞书群：
![飞书20241029-170312](https://github.com/user-attachments/assets/f753113a-f466-437d-b6d7-951e70303ae9)
再次感谢你的支持！

**Comment by Gijela** [comment]
认领该issue

**Comment by fangsmile** [comment]
> 认领该issue

@Gijela 可以的哦

**Comment by ghfkui** [comment]
@Gijela 谢谢你的认领。
现有的behavior时按Esc键后，table element失去了焦点，按tab键时是在整个document内切换。
解决方案是在取消编辑时重新让table的element获取焦点.类似于如下代码，仅供参考。
`
} else if (e.key === 'Escape') {
      (table as ListTableAPI).editorManager?.cancelEdit();
      table.getElement().focus();
    } else if (e.key === 'Enter') {
`
