### ISSUE TITLE
[Bug] 透视表没有启动聚合功能，但是内部创建了SumAggregator 类

### ISSUE THREAD

**Issue by MadSummer** [VisActor/VTable#2705]
### Version

1.10.1

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/table-type/pivot-table

打开控制台，输入tableInstance.dataset.tree查看这个结构，数据量很多并且同时存在多个表格是会比较占用内存，是否可以优化
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/cc8f17c1-137f-4a2b-90dc-73ed7649ca85">

### Steps to Reproduce

透视表没有启动聚合功能，但是内部创建了SumAggregator 类，如果一个页面多个实例并且数据量都很大时，占用了比较高的内存空间

### Current Behavior

创建了无用的SumAggregator
<img width="443" alt="image" src="https://github.com/user-attachments/assets/9706e37c-5a9f-4da1-8e8f-6282fc355dbc">

### Expected Behavior

如果没有启动聚合能力，不自动创建默认的求和聚合类

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
请提供复现demo
@MadSummer

**Comment by MadSummer** [comment]
> 请提供复现demo @MadSummer

已更新，感谢

**Comment by fangsmile** [comment]
抱歉 这个是基于一系列的需求场景来要维护的，如果不想要sum聚合可以设置：
```
        dataConfig: {
          aggregationRules: [
            {
              indicatorKey: 'Quantity', //指标名称
              field: 'Quantity', //指标依据字段
              aggregationType: VTable.TYPES.AggregationType.NONE //计算类
            },
            {
              indicatorKey: 'Sales', //指标名称
              field: 'Sales', //指标依据字段
              aggregationType: VTable.TYPES.AggregationType.NONE //计算类
            },
            {
              indicatorKey: 'Profit', //指标名称
              field: 'Profit', //指标依据字段
              aggregationType: VTable.TYPES.AggregationType.NONE //计算类
            }
          ]
        }
```
指定NONE的聚合类型。但是聚合器还是会相应创建，这个聚合器会管理format和编辑更新数据的作用。none相比默认的sum会小一点。
如果完全不想要这样的方式 可以将数据records设置为二维数组如：
```
records:[
 [45,67,879]
 [32,658,955]
  ...
]
```
@MadSummer
