### ISSUE TITLE
[FAQ]How to specify the width of a column and enable automatic line wrapping in a table component?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#271]
Specify the width of a column in a table, and enable automatic line wrapping based on the width limit, while allowing the height of the cells to be determined by the actual number of content lines.
![image](https://github.com/VisActor/VTable/assets/25134429/d7cd20cc-184e-4771-ba4d-88df7a5ba54d)
How can I achieve this effect on VTable component?

**Comment by xuanhun** [comment]
## 解决方案 Solution

这里使用开源图表组件VTable来实现这个功能。表格配置中加入以下配置：

```
heightMode: 'autoHeight', // 高度模式：自动高度（每一行的高度由内容撑开）
autoWrapText: true, // 打开自动折行配置
```

In VTable, add the following configuration to the table options.

```
heightMode: 'autoHeight', // the height of each row is determined by the content and will expand accordingly.
autoWrapText: true, // Enable automatic line wrapping.
```

## 代码示例 Code Example

代码参考 Code Example

```
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns,
  heightMode: "autoHeight",
  autoWrapText: true
};
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-autoheight-dktrk4

Online demo：https://codesandbox.io/s/vtable-autoheight-dktrk4
![Sep-01-2023 09-59-27](https://github.com/VisActor/VTable/assets/2384516/e74c4751-001b-4fd8-a383-7a4782c5eade)


## 相关文档 Related Documentation

自动换行demo：https://visactor.io/vtable/demo/basic-functionality/auto-wrap-text

自动换行教程：https://visactor.io/vtable/guide/basic_function/auto_wrap_text

相关api：

https://visactor.io/vtable/option/ListTable#autoWrapText

https://visactor.io/vtable/option/ListTable#heightMode

github：https://github.com/VisActor/VTable

  


Auto wrap Demo：https://visactor.io/vtable/demo/basic-functionality/auto-wrap-text

Auto wrap Tutorial：https://visactor.io/vtable/guide/basic_function/auto_wrap_text

Related api：

https://visactor.io/vtable/option/ListTable#autoWrapText

https://visactor.io/vtable/option/ListTable#heightMode

github：https://github.com/VisActor/VTable
