### ISSUE TITLE
[Bug] 懒加载的demo数据1亿2千条报错

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#2717]
### Version

develop

### Link to Minimal Reproduction

1

### Steps to Reproduce

https://visactor.io/vtable/demo/performance/async-data
![image](https://github.com/user-attachments/assets/5dbdb2e8-65bd-4960-915d-e08bb0225f41)
![image](https://github.com/user-attachments/assets/00bdf58e-280a-41f9-a895-8bf19eafd19a)

### Current Behavior

![image](https://github.com/user-attachments/assets/a03cf0bc-5d4a-4c36-a07f-fe42b04980cc)
目前代码中这里超过112813858 push就会报错  大概是2的26次方 不到32次方的长度。怀疑内存？？

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
求教大佬帮忙调试看看！

**Comment by Rui-Sun** [comment]
https://www.zhihu.com/question/650249886/answer/3448557422
