### ISSUE TITLE
[Bug] legend scrollbar abnormal when layout resize

### ISSUE THREAD

**Issue by hujinliang** [VisActor/VTable#2768]
### Version

1.9.2

### Link to Minimal Reproduction

none

### Steps to Reproduce

layout resize

### Current Behavior

![20241105201338_rec_](https://github.com/user-attachments/assets/44b9d044-0471-4000-a45b-2a63d1afd246)

### Expected Behavior

normal

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
这个是legend的padding引起的问题，可以配置：padding[0,0,0,0]
![img_v3_02gc_a6f0aef6-3b81-49b6-9453-3ffedce91f9g](https://github.com/user-attachments/assets/32e1030c-facf-4214-8d0f-e2712f88ad13)
