### ISSUE TITLE
[Bug] 对于我这种有强迫症的人来说，我还是提个建议吧，万被官方重视了呢

### ISSUE THREAD

**Issue by xjcallen** [VisActor/VTable#2807]
### Version

所有版本

### Link to Minimal Reproduction

/

### Steps to Reproduce

对于我这种有强迫症的人来说，我还是提个建议吧，万被官方重视了呢

在调这个表格主题时，画布可以设置一个边框

如果把画布设置一个像素，那个单元格也是有边框的，那么他靠在一起就会是2个像素。
而右边与下边因为还没有滚动到结尾所以又是1个像素
这样看起来就宽度不一样，感觉就不好了

我也尝试把  frameStyle.borderLineWidth=[0,1,1,0]   这样呢左右滚动呢左边又没了给断了

所以建议这里特殊处理一下，设置了边框那边单元格靠边的那一边的边框就为0
这样无论怎么滚动四周都边框都一样宽岂不完美

这个也是用了N个表格库都没有人注意的细节

看官方的意见了，如果追求极致希望采纳！

![image](https://github.com/user-attachments/assets/ef23d392-331d-4e7d-9fc6-43aab1d3a1cb)
![image](https://github.com/user-attachments/assets/f2b31da9-7de1-4d83-945f-3359c5575c72)

### Current Behavior

。

### Expected Behavior

。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
https://visactor.io/vtable/faq/37-%20What%20should%20I%20do%20if%20the%20bottom%20and%20right%20borders%20of%20VTable%20are%20not%20displayed%20when%20it%20is%20scrolled
看看这个是 你说的问题吗

**Comment by xjcallen** [comment]
> https://visactor.io/vtable/faq/37-%20What%20should%20I%20do%20if%20the%20bottom%20and%20right%20borders%20of%20VTable%20are%20not%20displayed%20when%20it%20is%20scrolled 看看这个是 你说的问题吗

遇到新的BUG吧，按上述方法确实可以但是滚动到200行以后又有边框了

 cellInnerBorder: false,
frameStyle: {
        borderLineWidth: 1,
},

![image](https://github.com/user-attachments/assets/4610ae6a-97e8-4bcf-a5fc-abfce4564461)

**Comment by xjcallen** [comment]
> https://visactor.io/vtable/faq/37-%20What%20should%20I%20do%20if%20the%20bottom%20and%20right%20borders%20of%20VTable%20are%20not%20displayed%20when%20it%20is%20scrolled 看看这个是 你说的问题吗

又遇到新的问题，数据量大了，搞个几千行，各种一顿瞎滚动后，你会发现左，下，右边的框架又出来了，好像是没有重新渲染边框，有bug
左
![image](https://github.com/user-attachments/assets/e59fab11-9b92-42c3-8a85-aaa4f228a233)
下
![image](https://github.com/user-attachments/assets/3861cd85-e880-4b01-b6ab-3a48ebd0b286)
右
![image](https://github.com/user-attachments/assets/ac456a38-4598-4b40-bdbf-3ea2f3e72930)

**Comment by fangsmile** [comment]
bug，我们修复下哈。可以重新提一个issue或者这个标题改下 改成这个bug的描述 和复现步骤

**Comment by xjcallen** [comment]
> cellInnerBorder: false,

已新提BUG
https://github.com/VisActor/VTable/issues/2811
