### ISSUE TITLE
[Bug] PivotChart layout error in combinationChart

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#2824]
### Version

1.9.5 alpha7

### Link to Minimal Reproduction

none

### Steps to Reproduce

bug server case id : 673352a4801d3000b3cd9e33

### Current Behavior

bug server case id : 673352a4801d3000b3cd9e33

### Expected Behavior

bug server case id : 673352a4801d3000b3cd9e33

### Environment

```markdown
bug server case id : 673352a4801d3000b3cd9e33
```

### Any additional comments?

bug server case id : 673352a4801d3000b3cd9e33

**Comment by Rui-Sun** [comment]
符合adaptive的预期效果，暂时关闭，肯能解决方案：
增加VRender文字高度省略效果，如果text 图元的heightLimit属性小于fontSize/bounds-height，显示省略号，避免文字被截断
![image](https://github.com/user-attachments/assets/a5097551-cc79-420d-8601-6b04b24c3372)
