### ISSUE TITLE
[FAQ] In table component, how can the truncated text, which exceeds the width of the cell, be displayed in a popup window to show the complete content?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#284]
In the table component, after using the fixed column width to limit the cell width, some text that exceeds the width will be omitted. How to realize that when the cell content is omitted, hover to the corresponding position, and a prompt box will pop up to display the complete content.

**Comment by xuanhun** [comment]
## 解决方案 Solution

可以使用开源图表组件VTable来实现这个效果。VTable可以通过配置`isShowOverflowTextTooltip`，来实现hover弹出poptip显示被省略的完整文字。

  


You can use the open-source charting component VTable to achieve this effect. VTable can configure `isShowOverflowTextTooltip` to realize hover pop-up poptip to display the complete text that has been omitted.

## 代码示例 Code Example

代码参考 Code Example

```
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns,
  tooltip: {
    isShowOverflowTextTooltip: true
  }
};

// 创建 VTable 实例
const vtableInstance = new VTable.ListTable(
  document.getElementById("container")!,
  option
);
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-showoverflowtexttooltip-qq597m

Online demo：https://codesandbox.io/s/vtable-showoverflowtexttooltip-qq597m
![Sep-05-2023 09-57-48](https://github.com/VisActor/VTable/assets/2384516/9434349b-5fa6-4b49-8c52-1fe63171feae)


## 相关文档 Related Documentation

Tooltip demo：https://visactor.io/vtable/demo/component/tooltip

Tooltip 教程：https://visactor.io/vtable/guide/components/tooltip

相关api：https://visactor.io/vtable/option/ListTable#tooltip.isShowOverflowTextTooltip

github：https://github.com/VisActor/VTable

  


Tooltip Demo：https://visactor.io/vtable/demo/component/tooltip

Tooltip Tutorial：https://visactor.io/vtable/guide/components/tooltip

Related api：https://visactor.io/vtable/option/ListTable#tooltip.isShowOverflowTextTooltip

github：https://github.com/VisActor/VTable
