### ISSUE TITLE
[FAQ]VTable Usage Issue: How to customize the content of a tooltip in a pop-up box?

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#286]
When hovering the mouse over a cell, I want to display contextual information about that cell, and I want the tooltip box to have a completely customized style. How can I achieve this using VTable?

**Comment by xuanhun** [comment]
## 解决方案 Solution

提供一种比较灵活的方式：监听VTable实例的事件`mouseenter_cell`和`mouseleave_cell`事件，将自定义的dom展示和隐藏，并依据VTable事件参数中的cellRange计算展示tooltip的位置。他们官网有这个相应的demo：https://visactor.io/vtable/demo/example/component/tooltip_custom_content

  


One flexible approach is to listen to the `mouseenter_cell` and `mouseleave_cell` events of the VTable instance. Show or hide the custom DOM elements accordingly, and calculate the position to display the tooltip based on the `cellRange` parameter from the VTable event. They have a corresponding demo for this on their official website.https://visactor.io/vtable/demo/example/component/tooltip_custom_content

## 代码示例 Code Example

代码参考 Code Example

```
 tableInstance.on('mouseenter_cell', args => {
        const { cellRange, col, row } = args;
        showTooltip(cellRange);//yourself function
});
tableInstance.on('mouseleave_cell', args => {
        const { cellRange, col, row } = args;
        hideTooltip();//yourself function
});
```

## 结果展示 Results

Online demo：https://visactor.io/vtable/demo/example/component/tooltip_custom_content
![image](https://github.com/VisActor/VTable/assets/2384516/a7c91672-992b-44bf-bb8d-0c03dd550320)

## 相关文档 Related Documentation

表格tooltip demo：https://visactor.io/vtable/demo/example/component/tooltip_custom_content

Tooltip教程：https://visactor.io/vtable/guide/components/tooltip

github：https://github.com/VisActor/VTable

  


Table Tooltip Demo：https://visactor.io/vtable/demo/example/component/tooltip_custom_content

Tooltip Tutorial：https://visactor.io/vtable/guide/components/tooltip

github：https://github.com/VisActor/VTable
