### ISSUE TITLE
[Bug] 冻结行如果有 vchart 类型的指标，调整了行宽度，冻结的表格不会重新渲染，鼠标移入就又自适应了

### ISSUE THREAD

**Issue by MadSummer** [VisActor/VTable#2876]
### Version

1.11.0

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-c8ny5f?workspaceId=71db66b0-9538-43e9-bc5d-80b0fa3345e0

### Steps to Reproduce

1、调整带 vchart 的列宽

### Current Behavior

1. 非冻结的图表大小自适应调整了
2. 冻结的图表没有自适应调整大小
3. 鼠标移入冻结的图表单元格，图表变大自适应
4. 鼠标移出冻结的图表单元格，还原成未自适应大小的图表了

### Expected Behavior

冻结的也正常自适应调整大小

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
codesanbox 权限没给开 @MadSummer
