### ISSUE TITLE
[Bug] 表格文字垂直方向不是完全居中偏上两个像素

### ISSUE THREAD

**Issue by coretimes** [VisActor/VTable#2882]
### Version

1.11.0

### Link to Minimal Reproduction

表格文字垂直方向不是完全居中偏上两个像素

### Steps to Reproduce

表格文字垂直方向不是完全居中偏上两个像素

### Current Behavior

表格文字垂直方向不是完全居中偏上两个像素
![20241120-173309](https://github.com/user-attachments/assets/4cf46b2b-c708-4ee7-a5cf-bc4df44aea9b)

### Expected Behavior

表格文字垂直方向不是完全居中偏上两个像素

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
https://github.com/VisActor/VTable/issues/2666#issuecomment-2436717650

**Comment by coretimes** [comment]
> [#2666 (comment)](https://github.com/VisActor/VTable/issues/2666#issuecomment-2436717650)

@Rui-Sun  希望还原文字居中，不要根据小写或者大写居中，因为小写居中场景太少太少了基本没有这种需求的场景，我们只需要正常文字居中就行了

**Comment by Rui-Sun** [comment]
1.12.0+之后的版本调整了纵向对齐效果
