### ISSUE TITLE
[Bug] 明细表配置radio column 报错

### ISSUE THREAD

**Issue by youhan26** [VisActor/VTable#2909]
### Version

1.11.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-55p5y4?workspaceId=ca8fcece-a151-491b-9e81-01f767ea3eab

### Steps to Reproduce

按照文档配置

### Current Behavior

编译报错
<img width="644" alt="image" src="https://github.com/user-attachments/assets/437ab556-7327-40b5-9fc0-03e5c3bc7819">

### Expected Behavior

-

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
复现链接没有开通权限

**Comment by youhan26** [comment]
> 复现链接没有开通权限

已更新

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/dcab3a29-9b77-4c9d-963a-f463bff13da3)
headerType 不支持radio @youhan26
