### ISSUE TITLE
[Bug] sort_click事件执行频率不稳定，偶尔一次点击会有两次执行

### ISSUE THREAD

**Issue by youhan26** [VisActor/VTable#2910]
### Version

1.11.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-c4cgrp?workspaceId=ca8fcece-a151-491b-9e81-01f767ea3eab

### Steps to Reproduce

按照官方文档例子，点击排序

https://github.com/user-attachments/assets/09be94dd-3f3b-45eb-ba20-75f9c3acf2a7

### Current Behavior

大概四五次点击会有一次点击执行两次回调

### Expected Behavior

一次点击，回调执行一次

### Environment

```markdown
- OS: mac
- Browser: chrome
- Framework: none
```

**Comment by fangsmile** [comment]
@youhan26 点击你的这个例子没有复现问题哈
