### ISSUE TITLE
[Bug] Incorrect indentation of Cyrillic text

### ISSUE THREAD

**Issue by vladpro3** [VisActor/VTable#2915]
### Version

1.11.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-gantt-demo-forked-rj9f4f

### Steps to Reproduce

1. Create any table with cyrillic text

### Current Behavior

Text indentation is calculated incorrectly. Neighboring elements overlap the text.
![image](https://github.com/user-attachments/assets/97ca593a-5352-4276-b5b3-753e6670757c)

### Expected Behavior

Indents are calculated correctly

### Environment

```markdown
- OS: macOS sequoia
- Browser: Chrome 130.0.6723.117
- Framework: any
```

### Any additional comments?

This problem occurs in all places where text is indented. For example, in tags

**Comment by Rui-Sun** [comment]
https://www.visactor.io/vtable/guide/multi_language_support
![image](https://github.com/user-attachments/assets/c58a368a-3023-4be5-801a-35117f46c049)
