### ISSUE TITLE
[Feature]  当record为空时希望添加空提示，也支持外部自定义提示

### ISSUE THREAD

**Issue by yibird** [VisActor/VTable#2925]
### What problem does this feature solve?

当record为空时希望添加空提示，也支持外部自定义提示

### What does the proposed API look like?

当record为空时希望添加空提示，也支持外部自定义提示

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/component/empty-tip  @yibird 这个吗

**Comment by yibird** [comment]
这个能自定义空提示吗? 自定义文本、icon有时候满足不了需求

**Comment by fangsmile** [comment]
看下教程哦，icon可以替换或者加文本的  @yibird
