### ISSUE TITLE
[Feature] 支持任意区域自定义渲染能力

### ISSUE THREAD

**Issue by youhan26** [VisActor/VTable#2934]
### What problem does this feature solve?

背景：
譬如需要做hover单元格然后tooltip的效果
<img width="434" alt="image" src="https://github.com/user-attachments/assets/774e6fda-728c-4d31-b919-8c90453e8383">
参考官网文档提供的自定义例子，在外层实现了一套dom的渲染模式，但是鼠标在canvas/dom 之间切换时，需要进行各种事件边界，比较复杂。

诉求：
Vtable是否可提供脱离单元格的自定义渲染能力？
目前提供的自定义能力主要集中在单元格内，底层依赖的是VRender渲染能力。VRender的渲染能力足够了，这种脱离单元格限制的渲染诉求是否可以支持一下

### What does the proposed API look like?

两种层次都可以：
1. column层次提供类似`onHoverRender`的能力
```
const columns = [{
   filed: 'xx',
   onHoverRender(args){
         return {
            x,y,
            render: <VGroup></Group>
        }
   }
}]
```

2. 从全局的事件层面，提供类似canvas框架的`onUpdate`钩子，在每次canvas执行渲染时，触发
```
const option = {
      onUpdate(args){
           return {
            x,y,
            render: <VGroup></Group>
          }
      }
}
```

**Comment by fangsmile** [comment]
你的截图是tootip效果吗  为什么不用tooltip呢  https://visactor.io/vtable/demo/component/tooltip_custom_content 这种实现 @youhan26

**Comment by youhan26** [comment]
> 你的截图是tootip效果吗 为什么不用tooltip呢 https://visactor.io/vtable/demo/component/tooltip_custom_content 这种实现 @youhan26

因为需要在tooltip上做一些点击等操作，用这种方式会有一些业务上问题：
1. 使用类似antd的tooltip来做canvas上层的dom，鼠标会触发Vtable的 moveleave、这时候还没移动到tooltip的元素上，卸载和显示时机上比较麻烦
2. 自己实现类似tooltips的dom，在配置了高亮 cross 的时候，canvas会失焦，高亮效果就丢掉了。

如果有好的思路，还请指点～
