### ISSUE TITLE
[Bug] 无法动态添加列

### ISSUE THREAD

**Issue by 0000005** [VisActor/VTable#2969]
### Version

1.11.5

### Link to Minimal Reproduction

https://codepen.io/Wenjun-Yin/pen/LEPEOVa

### Steps to Reproduce

复现地址：
https://codepen.io/Wenjun-Yin/pen/LEPEOVa

### Current Behavior

添加列之后，没有反应。控制台里面也没有报错。

### Expected Behavior

我想要动态的添加一列，这一列的数据是随机产生的。

### Environment

```markdown
- OS:windows
- Browser:edge
- Framework:js
```

### Any additional comments?

谢谢

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/b44ee392-d3bd-4d7f-98c6-9394c4cdbf08)
你是不是没有滚动到最右侧  新添加的列在最右侧 需要滚动到边缘呀  @0000005

**Comment by 0000005** [comment]
哈哈，尴尬了
