### ISSUE TITLE
[FAQ] How to sort table contents by data records?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#299]
The table is sorted according to certain column data. How to implement this requirement using VTable?

**Comment by xuanhun** [comment]
## 解决方案 Solution

在VTable中，可以通过三种方式来实现数据排序功能：

1.  通过表格内ui实现

在`columns`中配置`sort`属性，支持配置`true`使用默认排序规则，也可以配置函数来自定义排序规则：

```
// ......
columns: [
    {
      field: 'id',
      title: 'ID',
      width: 120,
      sort: true
    },
    {
      field: 'name',
      title: 'Name',
      width: 120,
      sort: (a, b) => { return a - b }
    }
]
```

此时，对应列的表头上会显示排序按钮：

![image](https://github.com/VisActor/VTable/assets/2384516/c6d12b6c-983b-43c0-9e32-4e187e907e15)


点击排序按钮，就可以在无排序、升序排序和降序排序三种状态中切换。

2.  通过在初始化`option`中配置`sortState`实现

在`columns`中配置`sort`属性后，可以在`option`中配置`sortState`属性：

```
sortState:{
    field: 'Category',
    order: 'asc'
}
```

其中，`field`是排序对应的数据源；`order`是排序规则，支持 `asc` 升序、`desc` 降序 和`normal` 不排序。

3.  通过`updateSortState`api 配置`sortState`

在`columns`中配置`sort`属性后，可以通过表格实例的`updateSortState`方法，随时配置`sortState`，更新排序效果：

```
instance.updateSortState({
  field: 'id',
  order: 'desc',
});
```

  


  


In VTable, sorting function can be realized in three ways:

1.  Implemented through UI in the table

Configure the `sort` attribute in `columns`. It supports configuring `true` to use the default sorting rules. You can also configure a function to customize the sorting rules:

```
// ......
columns: [
    {
      field: 'id',
      title: 'ID',
      width: 120,
      sort: true
    },
    {
      field: 'name',
      title: 'Name',
      width: 120,
      sort: (a, b) => { return a - b }
    }
]
```

At this time, the sort button will be displayed on the header of the corresponding column:

![](https://tech-proxy.bytedance.net/tos/images/1694002121711_165620cfe56363990da9bd4a12132fbf)

Click the sort button to switch among three states: no sorting, ascending sort and descending sort.

2.  By configuring `sortState` in the initialization `option`

After configuring the `sort` attribute in `columns`, you can configure the `sortState` attribute in `option`:

```
sortState:{
    field: 'Category',
    order: 'asc'
}
```

`field` is the data source corresponding to sorting; `order` is the sorting rule, which supports `asc` ascending order, `desc` descending order and `normal` non-sorting.

3.  Configure `sortState` through `updateSortState` api

After configuring the `sort` attribute in `columns`, you can configure `sortState` at any time through the `updateSortState` api of the table instance to update the sorting effect:

```
instance.updateSortState({
  field: 'id',
  order: 'desc',
});
```

## 代码示例 Code Example

代码参考 Code Example

```
const columns = [
  {
    field: "id",
    title: "ID",
    width: 80,
    sort: true
  },
  {
    field: "hobbies",
    title: "hobbies",
    width: 300
  }
];
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns,
  sortState:{
    field: 'id',
    order: 'asc'
  }
};
const instance = new ListTable(document.getElementById("container"), option);

setTimeout(() => {
  instance.updateSortState({
    field: 'id',
    order: 'desc',
  });
}, 3000);
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-sort-w869fk

Online demo：https://codesandbox.io/s/vtable-sort-w869fk
![image](https://github.com/VisActor/VTable/assets/2384516/de369f5d-4f55-4c4d-a6fe-62455a763f37)


## 相关文档 Related Documentation

表格排序 demo：https://visactor.io/vtable/demo/basic-functionality/sort

排序功能教程：https://visactor.io/vtable/guide/basic_function/sort

github：https://github.com/VisActor/VTable

  


Table Sort Demo：https://visactor.io/vtable/demo/basic-functionality/sort

Sort Tutorial：https://visactor.io/vtable/guide/basic_function/sort

github：https://github.com/VisActor/VTable
