### ISSUE TITLE
[Bug] ListTable某列宽度固定，其他列宽度设置为auto，auto字段未自动分布剩余宽度

### ISSUE THREAD

**Issue by li936393** [VisActor/VTable#3016]
### Version

1.12.0

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/cell-type/checkbox

### Steps to Reproduce

ListTable某列宽度固定，其他列宽度auto，auto列未自动分布剩余宽度，配置如下
const records = [
    { productName: 'aaaa', price: 20, check: { text: 'unchecked', checked: false, disable: false } },
    { productName: 'bbbb', price: 18, check: { text: 'checked', checked: true, disable: false } },
    { productName: 'cccc', price: 16, check: { text: 'disable', checked: true, disable: true } },
    { productName: 'cccc', price: 14, check: { text: 'disable', checked: false, disable: true } },
    { productName: 'eeee', price: 12, check: { text: 'checked', checked: false, disable: false } },
    { productName: 'ffff', price: 10, check: { text: 'checked', checked: false, disable: false } },
    { productName: 'gggg', price: 10, check: { text: 'checked', checked: false, disable: false } }
  ];

const columns = [
  {
    field: 'isCheck',
    title: '',
    width: 50,
    headerType: 'checkbox',
    cellType: 'checkbox',
  },
 {
    field: 'productName',
    title: 'productName',
    width: 'auto'
  },
  {
    field: 'price',
    title: 'checkbox',
    width: 'auto',
    cellType: 'checkbox',
    disable: true,
    checked: true
  },
  {
    field: 'check',
    title: 'checkbox',
    width: 'auto',
    cellType: 'checkbox'
    // disable: true
  }
];

### Current Behavior

![111](https://github.com/user-attachments/assets/ded8b7dc-f965-4d09-89cc-1306e685a4d4)

### Expected Behavior

期望productName price check 自动分布剩余宽度

### Environment

```markdown
- OS:Windows NT 10.0; Win64; x64
- Browser:Chrome/122.0.6261.95 Safari/537.36
- Framework:
```

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/basic_function/row_height_column_width 先阅读完这个教程 @li936393 看看widthMode配置了吗

**Comment by li936393** [comment]
autoFillWidth: true 可以解决宽度撑满的问题
