### ISSUE TITLE
[Bug] 甘特图自定义渲染的用法下，调整起始时间的计算有问题

### ISSUE THREAD

**Issue by Dxings** [VisActor/VTable#3031]
### Version

1.11.1

### Link to Minimal Reproduction

--

### Steps to Reproduce

甘特图自定义渲染的用法下，调整起始时间的计算有问题

### Current Behavior

![img_v3_02hd_b20fedf1-654e-4a98-a700-ceed15b6cbeg](https://github.com/user-attachments/assets/71cd4337-b0f3-4ec7-95a0-5221310ab6ba)

### Expected Behavior

跟随鼠标移动

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
1.13.0 已经发布解决
