### ISSUE TITLE
[Feature] VTable-gantt：分组（group）需求

### ISSUE THREAD

**Issue by 1483321023** [VisActor/VTable#3073]
### What problem does this feature solve?

**VTable-gantt：分组（group）需求，以下任意一个实现都能满足需求**
![image](https://github.com/user-attachments/assets/a9b79f5b-0c61-4e28-95b2-9254848563c5)
（或）VTable-gantt：希望甘特图的taskbar有一个分组功能，同一个group的数据**时间互不干扰**，如上图

![image](https://github.com/user-attachments/assets/da31e21c-1f3c-43e7-8d8d-7ed6753c39c0)
（或）VTable-gantt：右侧表格自定义边框，将中间两条线去掉，让这三条数据看起来是在同一组内以达到**分组效果**，如上图

### What does the proposed API look like?

**records:**
![image](https://github.com/user-attachments/assets/4fd04c4c-04ea-4c94-9b42-81b151ab5bc4)
**option.grid:**
![image](https://github.com/user-attachments/assets/3b9ad6f9-5eb1-466a-8c7a-c4aa70ffe66a)

**Comment by fangsmile** [comment]
感谢你的反馈！我们已经收到你的问题，并将在后续进行处理。
如果有开发者对这个 issue 感兴趣，请在issue下方留言“认领该issue”，留言后开始你的创作提pr给我们！
欢迎大家参与开源共建！我们非常感激每一位贡献者，提交pr后我们将为参与共建的开发者准备一份礼品。
参与共建可参考：https://visactor.io/vtable/guide/Contribution_Guide
与官方开发者交流问题可以下载飞书app扫码加入飞书群：
![飞书20241029-170312](https://github.com/user-attachments/assets/f753113a-f466-437d-b6d7-951e70303ae9)
再次感谢你的支持！

Thank you for your feedback! We have received your question and will deal with it later.
If any developer is interested in this issue, please leave a message "claim this issue" below the issue. Welcome to participate in open source co-construction!
We are very grateful to every contributor. After submitting the PR, we will prepare a gift for the developers who participated in the co-construction.
For participation in co-construction, please refer to: https://visactor.io/vtable/guide/Contribution_Guide
To communicate with official developers, you can download the Feishu app and scan the QR code to join the Feishu group！
Thank you again for your support!
