### ISSUE TITLE
[Bug] ipad 上使用笔进行滚动会出现选框重复选中的情况

### ISSUE THREAD

**Issue by zoubinzb** [VisActor/VTable#3090]
### Version

all

### Link to Minimal Reproduction

ipad上使用笔滚动条带滚动条的的vtable或者react vtable都可以复现

### Steps to Reproduce

<img width="177" alt="Snipaste_2024-12-16_12-13-21" src="https://github.com/user-attachments/assets/cef78106-9b4d-4591-85ce-69433fbe2b2f" />

https://github.com/user-attachments/assets/2f8ad6a1-cdd1-4ce9-b27d-6ebe453e147f

### Current Behavior

使用笔在ipad上滑动，想要查看后面的数据，出现重复选中选框的情况

### Expected Behavior

只滚动滚动条

### Environment

```markdown
all ipad
```

**Comment by fangsmile** [comment]
https://applink.larkoffice.com/client/message/link/open?token=AmU%2FQqHXB0ADZ1%2Fne3tTgAM%3D
![image](https://github.com/user-attachments/assets/220b76cb-6b26-4741-b2f8-c87435b32721)
