### ISSUE TITLE
[Bug] 甘特图设置timelineHeader.scales，当scalers中的unit为day，且step为大于等于2时，拖拽甘特图任务条异常

### ISSUE THREAD

**Issue by greaclar** [VisActor/VTable#3109]
### Version

1.13.2

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/gantt/gantt-basic?version=1.13.2

### Steps to Reproduce

将配置项中的timelineHeader.scales设置为一个单元格代表多天（step大于等于2）：

```javascript
scales: [
      {
        unit: 'day',
        step: 2,
        format(date) {
          return date.dateIndex.toString();
        },
        style: {
          fontSize: 20,
          fontWeight: 'bold',
          color: 'white',
          strokeColor: 'black',
          textAlign: 'right',
          textBaseline: 'bottom',
          backgroundColor: '#EEF1F5'
        }
      }
    ]
```

### Current Behavior

当一个单元格代表多天，无法将任务条的开始时间拖动到每个单元格中间位置的时间

![image](https://github.com/user-attachments/assets/ce46f0d8-cab0-4315-bd14-30bdd0be7224)

### Expected Behavior

可以将任务条的开始时间拖动到任意时间

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
这个就是这样设定的，可操作最小粒度就是根据unit和step来定的。你可以把step调成1，觉得网格线太密集的话 可以用grid中的https://visactor.io/vtable/option/Gantt#grid.verticalLine(ILineStyle%20%7C%20Function) 来调整
