### ISSUE TITLE
[Bug] @VisActor/vue-vtable使用语法化标签创建table，设置keyboardOptions.copySelected为true，复制效果没用

### ISSUE THREAD

**Issue by robertyclin** [VisActor/VTable#3118]
### Version

1.13.2

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo-vue/usage/grammatical-tag

### Steps to Reproduce

const app = createApp({
  template: `
    <ListTable :options="tableOptions" >
      <ListColumn v-for="(column, index) in columns" :key="index" :field="column.field" :title="column.title" />
      <ListColumn field="4" title="邮件" maxWidth="300"/>
      <ListColumn field="5" title="地址" dragHeader="true"/>
      <ListColumn field="6" title="手机" dragHeader="true"/>
      <ListColumn field="7" title="状态" dragHeader="true"/>
    </ListTable>
  `,
  data() {
    return {
      keyboardOptions: {
        copySelected: true, // 新添加
      },
      columns: [
        { field: '0', title: '名字' },
        { field: '1', title: '年龄' },
        { field: '2', title: '性别' },
        { field: '3', title: '爱好' }
      ],
      tableOptions: {
        records: new Array(1000).fill(['张三', 18, '男', '🏀', '@example', 'xxx.xxx.xxx.xxx', '12345678901', '正常'])
      }
    };
  }
});

app.component('ListTable', VueVTable.ListTable);
app.component('ListColumn', VueVTable.ListColumn);

app.mount(`#${CONTAINER_ID}`);

// release Vue instance, do not copy
window.customRelease = () => {
  app.unmount();
};

### Current Behavior

快捷键复制无用

### Expected Behavior

快捷键复制有用

### Environment

```markdown
- OS:macOS Monterey
- Browser: Chrome 96.0.4664.55
- Framework: Vue@3
```

**Comment by YELineee** [comment]
您好，为了让 keyboardOptions.copySelected 生效，请确保它包含在 tableOptions 中。可以使用以下是正确的配置示例：

```
const app = createApp({
  template: `
    <ListTable :options="tableOptions">
      <ListColumn v-for="(column, index) in columns" :key="index" :field="column.field" :title="column.title" />
      <ListColumn field="4" title="邮箱" maxWidth="300"/>
      <ListColumn field="5" title="地址" dragHeader="true"/>
      <ListColumn field="6" title="手机" dragHeader="true"/>
      <ListColumn field="7" title="状态" dragHeader="true"/>
    </ListTable>
  `,
  data() {
    return {
      tableOptions: {
        keyboardOptions: {
          copySelected: true, // 更新到tableOptions里面
        },
        records: new Array(1000).fill(['张三', 18, '男', '🏀', '@example', 'xxx.xxx.xxx.xxx', '12345678901', '正常'])
      },
      columns: [
        { field: '0', title: '名字' },
        { field: '1', title: '年龄' },
        { field: '2', title: '性别' },
        { field: '3', title: '爱好' }
      ]
    };
  }
});

app.component('ListTable', VueVTable.ListTable);
app.component('ListColumn', VueVTable.ListColumn);

app.mount(`#${CONTAINER_ID}`);

// release Vue instance, do not copy
window.customRelease = () => {
  app.unmount();
};
```

**Comment by yuzuang** [comment]
这个问题还没有解决吗 ？
<template>
  <ListTable :options="tableOptions">
    <ListColumn
      v-for="(column, index) in columns"
      :key="index"
      :field="column.field"
      :title="column.title"
    />
    <ListColumn field="4" title="邮箱" maxWidth="300" />
    <ListColumn field="5" title="地址" dragHeader="true" />
    <ListColumn field="6" title="手机" dragHeader="true" />
    <ListColumn field="7" title="状态" dragHeader="true" />
  </ListTable>
</template>
const columns = ref([
  { field: "0", title: "名字" },
  { field: "1", title: "年龄" },
  { field: "2", title: "性别" },
  { field: "3", title: "爱好" }
]);
const tableOptions = ref({
  keyboardOptions: {
    copySelected: true // 更新到tableOptions里面
  },
  records: new Array(1000).fill([
    "张三",
    18,
    "男",
    "🏀",
    "@example",
    "xxx.xxx.xxx.xxx",
    "12345678901",
    "正常"
  ])
});

复制无效
