### ISSUE TITLE
[FAQ]How to display user information, such as a combination of "avatar + name," in data analysis reports or tables?

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#312]
I would like to display both an avatar and a name in a single cell of a data report table in a simple manner. Are there any examples I can refer to?
![image](https://github.com/VisActor/VTable/assets/3468473/3162f8d8-68a2-4863-8b63-a7b0f3ef1e24)

**Comment by xuanhun** [comment]
## 解决方案 Solution

推荐使用VTable组件，比较小巧易用，可以很容易的实现头像和姓名的组合显示。在VTable中可以通过两种方式实现：一种是借助icon，也是最省事的一直，icon的来源直接设置为资源field，具体可以参考我给出的demo。另外一种方式是通过自定义渲染，该方式需要熟悉这种写法，但能实现更复杂的效果，具体可以看他们官方教程。
![image](https://github.com/VisActor/VTable/assets/2384516/d2447712-da91-4e27-8485-de04750e8fc9)



I recommend using the VTable component as it is lightweight and easy to use, making it straightforward to achieve the combination display of avatars and names. In VTable, there are two ways to accomplish this. The first and simplest approach is to use icons. You can directly set the icon source as the resource field. For more details, you can refer to the demo I provided. The second approach involves custom rendering, which requires familiarity with the syntax. However, it allows for more complex effects. You can find specific instructions in their official tutorial.

## 代码示例 Code Example

代码参考 Code Example

```
const columns: VTable.ColumnsDefine = [
  {
    field: "name",
    title: "name",
    width: "auto",
    cellType: "link",
    templateLink: "https://www.google.com.hk/search?q={name}",
    linkJump: true,
    icon: {
      type: "image",
      src: "image1",
      name: "Avatar",
      shape: "circle",
      //定义文本内容行内图标，第一个字符展示
      width: 30, // Optional
      height: 30,
      positionType: VTable.TYPES.IconPosition.contentLeft,
      marginRight: 20,
      marginLeft: 0,
      cursor: "pointer"
    }
  },
  ...
  ]
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-photo-username-ypndvm?file=/src/index.ts

Online demo：https://codesandbox.io/s/vtable-photo-username-ypndvm?file=/src/index.ts

![image](https://github.com/VisActor/VTable/assets/2384516/d2447712-da91-4e27-8485-de04750e8fc9)


## 相关文档 Related Documentation

自定义icon教程：https://visactor.io/vtable/guide/custom_define/custom_icon

相关demo：https://visactor.io/vtable/demo/custom-render/custom-cell-layout

相关api：https://visactor.io/vtable/option/ListTable-columns-text#icon.ImageIcon.src

github：https://github.com/VisActor/VTable

  


Define icon Tutorial：https://visactor.io/vtable/guide/custom_define/custom_icon

Custom cell layout demo：https://visactor.io/vtable/demo/custom-render/custom-cell-layout

Related api：https://visactor.io/vtable/option/ListTable-columns-text#icon.ImageIcon.src

github：https://github.com/VisActor/VTable
