### ISSUE TITLE
[Bug] 自定义编辑器调用validateValue返回false点击其他单元格不继续调用validateValue

### ISSUE THREAD

**Issue by Aeiousl** [VisActor/VTable#3144]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/5c4b7fa4-87b2-496b-a28a-abfe55c2bda7)
如图，自定义编辑器调用validateValue返回false值之后不会点击其他单元格或者按enter都不会再调用validateValue

### What does the proposed API look like?

validateValue返回false值后点击其他单元格可以继续调用validateValue

**Comment by fangsmile** [comment]
@Aeiousl 提的这是bug还是需求？？
![image](https://github.com/user-attachments/assets/aa2efe6a-e271-41de-ac94-0f98545c85bc)
这句怎么理解？

**Comment by Aeiousl** [comment]
@fangsmile 应该也算是bug吧，就是说在input框编辑完点击其他单元格或者按enter的时候，会调用一次validateValue方法校验值，不通过返回false之后不会退出编辑状态，然后这个时候继续点击其他单元格或者按enter或者修改值之后再点击都不会再调用validateValue了，就一直处在编辑状态下
