### ISSUE TITLE
[Bug] 甘特图滚动bug

### ISSUE THREAD

**Issue by lwei-jlu** [VisActor/VTable#3157]
### Version

1.13.2

### Link to Minimal Reproduction

1.13.2

### Steps to Reproduce

上下滚动甘特图，会导致列表和甘特图不对齐，实际上是因为列表没同步刷新导致
如果调用setrecods刷新数据也会导致此问题
测试发现如果设定了甘特图的起始时间和终止时间不会产生此问题，但是调用setrecords刷新数据会感觉明显卡顿

### Current Behavior

如上

### Expected Behavior

如上

### Environment

```markdown
- OS:
- Browser:
- Framework:
如上 谷歌100浏览器
```

### Any additional comments?

如上

**Comment by fangsmile** [comment]
@lwei-jlu 麻烦给出复现demo

**Comment by lwei-jlu** [comment]
> @lwei-jlu 麻烦给出复现demo
测试，如果下面两个参数设为false，会复现，1.14.0版本也有此问题
  taskBar: {
    resizable: false,
    moveable:false,

![image](https://github.com/user-attachments/assets/9d691b95-d938-43aa-8694-9ccfc8883d86)

**Comment by lwei-jlu** [comment]
> > @lwei-jlu 麻烦给出复现demo
> > 测试，如果下面两个参数设为false，会复现，1.14.0版本也有此问题
> > taskBar: {
> > resizable: false,
> > moveable:false,
> 
> ![image](https://private-user-images.githubusercontent.com/21038774/397890274-9d691b95-d938-43aa-8694-9ccfc8883d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzgzNDksIm5iZiI6MTczNDczODA0OSwicGF0aCI6Ii8yMTAzODc3NC8zOTc4OTAyNzQtOWQ2OTFiOTUtZDkzOC00M2FhLTg2OTQtOWNjZmM4ODgzZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDIzNDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhM2U4NDBiMmY2MTZiZWYzYmY5ZmYyNmY4OWJjMWIyNThhYTBhNDQ3OWQ0ZWY0MTgwNTQzZmZmMzYzYWJiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t4KhhEjoRjaQ7TicEcfOfQq4ryJv-PDNca0Alu1FOtA)

使用的demo是官网示例https://visactor.com/vtable/demo/gantt/gantt-taskShowMode

**Comment by lwei-jlu** [comment]
> > > @lwei-jlu 麻烦给出复现demo
> > > 测试，如果下面两个参数设为false，会复现，1.14.0版本也有此问题
> > > taskBar: {
> > > resizable: false,
> > > moveable:false,
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/21038774/397890274-9d691b95-d938-43aa-8694-9ccfc8883d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MzgzNDksIm5iZiI6MTczNDczODA0OSwicGF0aCI6Ii8yMTAzODc3NC8zOTc4OTAyNzQtOWQ2OTFiOTUtZDkzOC00M2FhLTg2OTQtOWNjZmM4ODgzZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDIzNDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhM2U4NDBiMmY2MTZiZWYzYmY5ZmYyNmY4OWJjMWIyNThhYTBhNDQ3OWQ0ZWY0MTgwNTQzZmZmMzYzYWJiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t4KhhEjoRjaQ7TicEcfOfQq4ryJv-PDNca0Alu1FOtA)
> 
> 使用的demo是官网示例https://visactor.com/vtable/demo/gantt/gantt-taskShowMode

并且 好像如果设定了startDate和endDate，不会出现活动导致甘特图和列表不对齐问题

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/77c71445-911c-4ad9-917f-3385005fc240)
请给出完整复现的demo代码。我这按你描述的也没复现。你上面截图没上传好

**Comment by lwei-jlu** [comment]
好的 我组织一下 重新开个问题
