### ISSUE TITLE
[Feature] support cellType for each cell

### ISSUE THREAD

**Issue by LiangCY** [VisActor/VTable#320]
### What problem does this feature solve?

In the same column, cells can have different types，some cells maybe link，others maybe image

### What does the proposed API look like?

`cellType: (args) => 'text' | 'image' | 'link' | ...`

**Comment by fangsmile** [comment]
developed  effect：
![image](https://github.com/VisActor/VTable/assets/3468473/3d4117d8-8ad3-4aee-a256-41ebeb05bdaa)
