### ISSUE TITLE
[Bug] 编辑器进入编辑状态时，onStart传入的 EditContext.value 不是正在进入编辑状态的单元格当前值

### ISSUE THREAD

**Issue by nmfloris** [VisActor/VTable#3212]
### Version

@visactor/react-vtable @1.14.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/strange-benji-6gwtmy?file=%2Fsrc%2FApp.js

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/97ddf694-1b1a-415e-a494-27a74bf1b0be)
1. 首先编辑传入editor项的列的任一单元格，编辑后
2. 切换同一列任一其他单元格
3. onStart 方法传入的EditContext.value 不是当前表格的值，不做任何编辑操作
4. 退出编辑状态后，会更改第二次编辑的单元格的值为第一次编辑的值

### Current Behavior

编辑器传入 EditContext.value 的不是当前表格的值，而是上一次输入调用编辑器后输入的值，@visactor/vtable-editors 自带的输入编辑器也会有这个问题

### Expected Behavior

期望是 正在进入编辑状态的单元格当前值 

### Environment

```markdown
- OS:
- Browser:
- Framework:
mac os https://codesandbox.io/p/sandbox/strange-benji-6gwtmy?file=%2Fsrc%2FApp.js
```

### Any additional comments?

@visactor/react-vtable @1.14.1 和@visactor/react-vtable @1.14.2 都有这个问题

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/e97343f4-3a39-4254-86fd-ac9a45075e39)
这样的数据是没有问题的。你的records是引用关系了吗  每条数据

**Comment by nmfloris** [comment]
> ![image](https://private-user-images.githubusercontent.com/3468473/398569335-e97343f4-3a39-4254-86fd-ac9a45075e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTAyMjYsIm5iZiI6MTczNTE4OTkyNiwicGF0aCI6Ii8zNDY4NDczLzM5ODU2OTMzNS1lOTczNDNmNC0zYTM5LTQyNTQtODZmZC1hYzlhNDUwNzVlMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDUxMjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM4MzNiYWI1ZjZmMDU0NWY0YmMyYWFlZWU1MWM5ZDhhM2U0MDMwMGRkOWI2M2Q2MjQ5MzhhZGNiZjgwNDk3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.arO7ZnzGFBlOw2rlXpXAB7MfEZa2Srl9iSh_TF3N0E4) 这样的数据是没有问题的。你的records是引用关系了吗 每条数据

感谢回复，我好像犯了一个低级的错误。🫢
