### ISSUE TITLE
[Documentation] 注册好icon 之后在 customLayout 中使用，这个有具体的demo可以查看的吗？

### ISSUE THREAD

**Issue by robertyclin** [VisActor/VTable#3213]
### Documentation Title or Section

注册好icon 之后在 customLayout 中使用，这个有具体的demo可以查看的吗？

### Issue Description or Suggestion

注册好icon 之后在 customLayout 中使用，这个有具体的demo可以查看的吗？
<img width="545" alt="image" src="https://github.com/user-attachments/assets/51276853-28ba-487f-a116-54ce9b505a8a" />

**Comment by fangsmile** [comment]
@robertyclin  这个文档我们改一下吧。 之前的老的接口是支持的 后面我们customLayout统一到了vrender的图元  把这个能力去掉了

**Comment by robertyclin** [comment]
大佬，我想实现在customLayout上渲染一个支持tooltips的小icon，要咋搞。之所以要用到customLayout是因为这个icon展示与否是有条件判断的
