### ISSUE TITLE
[FAQ] Is support displaying mini-charts within cells?

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#322]
I would like to have a separate column in the sales statistics table to display mini-line charts that reflect the displayed growth trends, similar to the daily candlestick list in stock charts.
![image](https://github.com/VisActor/VTable/assets/3468473/6ada7a42-6ea9-4aca-b4e9-58d18cc784a4)

**Comment by xuanhun** [comment]
## 解决方案 Solution

可以使用VTable组件来配置columnType: "sparkline"，将单元格类型显示成迷你图。设置迷你图的具体样式可以设置**sparklineSpec**来实现。优势是：图和表融为一体没有割裂感，性能上体验感最佳。

![image](https://github.com/VisActor/VTable/assets/2384516/085e463d-015c-40bc-a28d-c75a05d715a1)

  


You can use the VTable component and configure the columnType as "sparkline" to display cells as mini-charts. The specific style of the mini-charts can be set using sparklineSpec. The advantage is that the integration of charts and tables creates a seamless experience without a sense of detachment, providing optimal performance and user experience.

## 代码示例 Code Example

代码参考 Code Example

```
const columns: VTable.ColumnsDefine = [
    {
    field: "trend",
    caption: "bird count",
    columnType: "sparkline" ,
    width: 300,
    sparklineSpec: {
      type: "line",
      xField: "x",
      yField: "y",
      pointShowRule: "none",
      smooth: true,
      line: {
        style: {
          stroke: "#2E62F1",
          strokeWidth: 2
        }
      },
      point: {
        hover: {
          stroke: "blue",
          strokeWidth: 1,
          fill: "red",
          shape: "circle",
          size: 4
        },
        style: {
          stroke: "red",
          strokeWidth: 1,
          fill: "yellow",
          shape: "circle",
          size: 2
        }
      },
      crosshair: {
        style: {
          stroke: "gray",
          strokeWidth: 1
        }
      }
    }
  }
  ...
];
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-list-table-jw8yr8?file=/src/index.ts

Online demo：https://codesandbox.io/s/vtable-list-table-jw8yr8?file=/src/index.ts
![image](https://github.com/VisActor/VTable/assets/2384516/e289c9de-b962-4016-8b75-addd2867a472)

## 相关文档 Related Documentation

迷你图相关教程：https://visactor.io/vtable/guide/cell_type/sparkline

相关demo：https://visactor.io/vtable/demo/cell-type/multi-type

相关api：https://visactor.io/vtable/option/ListTable-columns-sparkline#cellType

github：https://github.com/VisActor/VTable

  


Sparkline Tutorial：https://visactor.io/vtable/guide/cell_type/sparkline

Custom cell layout demo：https://visactor.io/vtable/demo/cell-type/multi-type

Related api：https://visactor.io/vtable/option/ListTable-columns-sparkline#cellType

github：https://github.com/VisActor/VTable
