### ISSUE TITLE
关于 `vTable` 的最佳使用场景

### ISSUE THREAD

**Issue by un4gt** [VisActor/VTable#3231]
我使用场景是能够在线实时处理和展示大量的流式数据。
在使用 `vTable` 之前，我一直在尝试使用 [perspective](https://github.com/finos/perspective), 因为使用它可以很方便的连接数据源，并在前端进行展示。不过它有个不足支持，不支持 `tree` 格式。
巧合之下，我在[该网站](https://jsgrids.statico.io/)看到了`vTable`，因为它支持树形表格，所以我编写了不少demo， 体验了一下.
刚开始时，相关的数据是写死的，但等到需要处理一些流式数据时，我注意到关于数据更新，`vTable` 似乎支持的不是很友好。
比如，我刚开始尝试使用 `changeCellValue` 来更新某个单元格的值，不过因为我需要使用树形表格，所以展开表格时，单元格的值会错位，导致更新的单元格不是预期的。
后来再使用了 `updateRecords`, 不过树形表，完全消失了，无法展开任何行。
我不太确定自己是否用错了还是，毕竟我看相关文档，对于实时更新表数据这样的示例，几乎没看到。
如果有人能帮忙解答一下，那真的太好了。
在能力允许的范围之内，我也想对该项目做一些贡献

**Comment by fangsmile** [comment]
![image](https://github.com/user-attachments/assets/640985d2-4c8b-42cb-9639-0b5d9ba9fcdd)
![image](https://github.com/user-attachments/assets/7ceaa219-e10c-4386-8c97-96c78ac884c9)
https://visactor.io/vtable/guide/data/data_format
 树形结构的增改数据 目前还不支持，一直有计划要支持但还没精力去做。如果可以的话 也期望能帮忙贡献这个能力 @un4gt

**Comment by fangsmile** [comment]
你的场景是实时刷新数据吗 大概多久刷新一次？ 可以加我们的飞书话题群进行具体交流
![永久有效](https://github.com/user-attachments/assets/371ca265-eabf-4dee-a71f-efe04e54c727)

**Comment by un4gt** [comment]
场景偏向于实时刷新的，后端推从数据的频率200ms左右。
我加了飞书群，我搞一个minimal example 再去群里向你们请教 @fangsmile
