### ISSUE TITLE
[FAQ] How to add a progress bar to the table component?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#324]
Specify a column on the table, display the content as a progress bar based on data, and display percentage text. How to achieve this effect on the table component?
![image](https://github.com/VisActor/VTable/assets/25134429/8c96d9dd-3915-4b05-abcd-b1cdf7405297)

**Comment by xuanhun** [comment]
## 解决方案 Solution

这里使用开源表格组件VTable来实现这个功能。可以通过在`columns`中将`cellType`设置为`progressbar`，指定该列为`progressbar`类型（进度图）单元格；通过配置`columns`中的`style`，可以配置进度图的样式：

```
{
    field: "value",
    title: "progress",
    cellType: "progressbar",
    style: {
      barColor: DEFAULT_BAR_COLOR,
      barBgColor: "#ddd",
      barHeight: 30,
      barBottom: 4,
      textAlign: "right"
    },
    fieldFormat: (data: any) => {
      return data.value + "%";
    },
    width: 250
}
```

在`style`中：

-   barColor: 进度条颜色，可以配置为函数来改变不同进度的颜色
-   barBgColor: 进度条背景颜色
-   barHeight: 进度条高度，支持配置百分比
-   barBottom: 进度条距离底部高度，支持配置百分比
-   ......

通过`fieldFormat`，可以修改单元格中的文字内容，显示百分比文字。

通过修改`barType`，可以将进度图改为简单的柱图，可以用来显示同时存在正负数据的内容。

  


The open source table component `VTable` is used here to implement this function. You can specify the column to be progress bar type (progress chart) cell by setting `cellType` to `progressbar` in `columns`; by configuring the `style` in `columns`, you can configure the style of the progress chart:

```
{
    field: "value",
    title: "progress",
    cellType: "progressbar",
    style: {
      barColor: DEFAULT_BAR_COLOR,
      barBgColor: "#ddd",
      barHeight: 30,
      barBottom: 4,
      textAlign: "right"
    },
    fieldFormat: (data: any) => {
      return data.value + "%";
    },
    width: 250
}
```

In style:

-   barColor: progress bar color, which can be configured as a function to change the color of different progresses
-   barBgColor: progress bar background color
-   barHeight: progress bar height, supports configuration percentage
-   barBottom: the height of the progress bar from the bottom, supports configuration percentage
-   ......

Through `fieldFormat`, you can modify the text content in the cell and display percentage text.

By modifying the `barType`, the progress chart can be changed to a simple bar chart, which can be used to display content with both positive and negative data.

## 代码示例 Code Example

代码参考 Code Example

```
const columns = [
  {
    field: "id",
    title: "ID",
    width: 80
  },
  {
    field: "value",
    title: "progress",
    cellType: "progressbar",
    style: {
      barColor: DEFAULT_BAR_COLOR,
      barBgColor: "#ddd",
      barHeight: 30,
      barBottom: 4,
      textAlign: "right"
    },
    fieldFormat: (data: any) => {
      return data.value + "%";
    },
    width: 250
  },
  {
    field: "value1",
    title: "axis",
    cellType: "progressbar",
    barType: "negative",
    min: -50,
    max: 50,
    style: {
      barHeight: 30,
      barBottom: 4,
      textAlign: "right"
    },
    width: 250
  }
];
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns
};
```

  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-progress-bar-l69jtk

Online demo：https://codesandbox.io/s/vtable-progress-bar-l69jtk

![image](https://github.com/VisActor/VTable/assets/2384516/1bef3fee-4bc9-477b-b052-5e55f909b5a3)


  


## 相关文档 Related Documentation

进度图demo：https://visactor.io/vtable/demo/cell-type/progressbar

进度图教程：https://visactor.io/vtable/guide/cell_type/progressbar

github：https://github.com/VisActor/VTable

  


Progress bar Demo：https://visactor.io/vtable/demo/cell-type/progressbar

Progress bar Tutorial：https://visactor.io/vtable/guide/cell_type/progressbar

github：https://github.com/VisActor/VTable
