### ISSUE TITLE
[FAQ] How to achieve color gradient effect on table component?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#327]
The background of the cells on the table is displayed in different colors according to different data, realizing a color scale effect. How to achieve this effect on the table component?
![image](https://github.com/VisActor/VTable/assets/25134429/fc0018c2-4d0f-4498-b274-50862c74b88f)

**Comment by xuanhun** [comment]
## 解决方案 Solution

这里使用开源表格组件VTable来实现这个功能。可以通过在`columns`中将`style`中的`bgColor`设置为函数，按照不同数据，返回不同的颜色值，来实现色阶效果：

```
const BG_COLOR = (args: TYPES.StylePropertyFunctionArg): string => {
  const num = args.value;
  if (Number(num) > 80) {
    return "#6690FF";
  }
  if (Number(num) > 50) {
    return "#84A9FF";
  }
  if (Number(num) > 20) {
    return "#ADC8FF";
  }
  return "#D6E4FF";
};

const columns = [
  {
    style: {
      bgColor: BG_COLOR
    }
  }
];
```

  


The open source table component VTable is used here to implement this function. You can achieve the color scale effect by setting `bgColor` in `style` as a function in `columns` and returning different color values based on different data:

  


## 代码示例 Code Example

代码参考 Code Example

```
const BG_COLOR = (args: TYPES.StylePropertyFunctionArg): string => {
  const num = args.value;
  if (Number(num) > 80) {
    return "#6690FF";
  }
  if (Number(num) > 50) {
    return "#84A9FF";
  }
  if (Number(num) > 20) {
    return "#ADC8FF";
  }
  return "#D6E4FF";
};

const columns = [
  {
    field: "id",
    title: "ID",
    width: 80
  },
  {
    field: "value",
    title: "progress",
    style: {
      bgColor: BG_COLOR
    },
    width: 250
  }
];
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns
};
new ListTable(document.getElementById("container"), option);
```

  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-color-step-n9ngjq

Online demo：https://codesandbox.io/s/vtable-color-step-n9ngjq

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c190908021e443418c5471d4859a2a76~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=666&h=886&s=40262&e=png&b=e6e9f8)

  


## 相关文档 Related Documentation

色阶demo：https://visactor.io/vtable/demo/business/color-level

背景色api：https://visactor.io/vtable/option/ListTable-columns-text#style.bgColor

github：https://github.com/VisActor/VTable

  


Color step Demo：https://visactor.io/vtable/demo/business/color-level

Background Color api：https://visactor.io/vtable/option/ListTable-columns-text#style.bgColor

github：https://github.com/VisActor/VTable
