### ISSUE TITLE
[FAQ] How can the table column width show different effects according to the number of data columns?

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#332]
When using VTable table library to display report data, if the total number of columns is not enough to support the width of the entire container, I think it can automatically widen to adapt to the container size, but when the total width of the column is larger than the container width, you can scroll horizontally. How can this effect be achieved?

**Comment by xuanhun** [comment]
## 解决方案 Solution

根据你的问题，我的理解是你想要根据数据的总列宽来动态调整宽度模式，在VTable中宽度模式widthMode有:

-   `standard` 按with设置来设置每列的宽度
-   `autoWidth` 按单元格内容自动计算列宽
-   `adaptive` 按容器宽度缩放，撑满容器的宽度。

那就是如果列数较少不足以铺满容器的时候，你想要adaptive的效果，如果总列宽超过容器宽度，想要`standard`或者`autoWidth`的效果。有两种方式可以实现：

1.  可以已经VTable实例的接口，getAllColsWidth来获取总列宽和容器的宽度做对比，然后根据情况来改变widthMode。
1.  比较省事的一个方式，VTable提供了一个很优化的配置项`autoFillWidth`，配置这个就能完美做到你想要的效果。另外也有相应的高度设置 `autoFillWidth`。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f5c18cf7f4c84c0c9ffdf8d366ef3664~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=804&h=268&s=49830&e=png&b=f9f8fa)

Based on your question, my understanding is that you want to dynamically adjust the width mode based on the total column width of the data. In VTable, the width mode widthMode has:

- `standard` sets the width of each column according to the with setting

- `autoWidth` automatically calculates column width based on cell content

- `adaptive` scales according to the width of the container to fill the width of the container.

That is, if the number of columns is too small to cover the container, you want the adaptive effect. If the total column width exceeds the container width, you want the `standard` or `autoWidth` effect. There are two ways to do this:

1. You can use the interface of the VTable instance, getAllColsWidth, to get the total column width and the width of the container for comparison, and then change the widthMode according to the situation.

2. A relatively trouble-free way, VTable provides a very optimized configuration item `autoFillWidth`. Configuring this can perfectly achieve the effect you want. There is also a corresponding height setting `autoFillWidth`.代码示例 Code Example

代码参考 Code Example

```
const option = {
  records,
  columns,
  limitMaxAutoWidth: 800,
  autoFillWidth: true,
  // widthMode: "autoWidth",
  // heightMode: "autoHeight"
};
```

## 结果展示 Results

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2c600c2409cf40e882337c7898b5614a~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1342&h=550&s=110055&e=png&b=f9f8fa)

在线效果参考：https://codesandbox.io/s/vtable-autfillwidth-6kz69n

Online demo：https://codesandbox.io/s/vtable-autfillwidth-6kz69n

## 相关文档 Related Documentation

列宽相关教程：https://visactor.io/vtable/guide/basic_function/row_height_column_width

相关api：https://visactor.io/vtable/option/ListTable#autoFillWidth

github：https://github.com/VisActor/VTable

  


Column width Tutorial：https://visactor.io/vtable/guide/basic_function/row_height_column_width

Related api：https://visactor.io/vtable/option/ListTable#autoFillWidth

github：https://github.com/VisActor/VTable
