### ISSUE TITLE
[FAQ] How to merge cells with the same content in table component?

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VTable#336]
If there are multiple consecutive cells of the same data in a certain column of the table, these cells will be automatically merged and the content will be displayed in the center. How to achieve this effect on the table component?
![image](https://github.com/VisActor/VTable/assets/25134429/8b697ac2-bbe1-4043-b473-e68256326b7f)

**Comment by xuanhun** [comment]
## 解决方案 Solution

这里使用开源表格组件VTable来实现这个功能。可以通过在`columns`中将`mergeCell`设置为`true`，该列中前后内容相同的单元格会自动合并：

```
const columns = [
  {
    // ......
    mergeCell: true
  }
];
```

  


The open source table component VTable is used here to implement this function. You can set `mergeCell` to `true` in `columns`, and cells with the same content before and after in the column will be automatically merged:

  


## 代码示例 Code Example

代码参考 Code Example

```
const columns = [
  {
    field: "id",
    title: "ID",
    width: 80
  },
  {
    field: "value",
    title: "number",
    width: 100,
    mergeCell: true
  }
];
const option: TYPES.ListTableConstructorOptions = {
  records,
  columns
};
new ListTable(document.getElementById("container"), option);
```

  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/vtable-merge-cell-23wwmk

Online demo：https://codesandbox.io/s/vtable-merge-cell-23wwmk

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8231a51bd7144167b22718ea9444a65a~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=364&h=884&s=23082&e=png&b=faf9fb)

  


## 相关文档 Related Documentation

合并单元格demo：https://visactor.io/vtable/demo/basic-functionality/merge

mergeCell api：https://visactor.io/vtable/option/ListTable-columns-text#mergeCell

github：https://github.com/VisActor/VTable

  


Merge Cell Demo：https://visactor.io/vtable/demo/basic-functionality/merge

mergeCell api：https://visactor.io/vtable/option/ListTable-columns-text#mergeCell

github：https://github.com/VisActor/VTable
