### ISSUE TITLE
[Bug] The width and height of the container is changed after the perspective chart is finished,  vchart display exception.

### ISSUE THREAD

**Issue by X-smart** [VisActor/VTable#338]
### Version

0.11.0

### Link to Minimal Reproduction

————

### Steps to Reproduce

The width and height of the container is changed after the perspective chart is finished,  vchart display exception.

### Current Behavior

The width and height of the container is changed after the perspective chart is finished,  vchart display exception.

### Expected Behavior

The width and height of the container is changed after the perspective chart is finished,  vchart display right.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
will release 0.11.1 to fix it
