### ISSUE TITLE
[Bug] ListTable widthMode:'adaptive' 容器宽度发生变化时 表格宽度没有一起响应

### ISSUE THREAD

**Issue by van-chin** [VisActor/VTable#374]
### Version

0.11.0

### Link to Minimal Reproduction

/

### Steps to Reproduce

1.设置 widthMode: 'adaptive',
2.调整容器宽度

### Current Behavior

当调整容器宽度时，会有以下两个问题
- vtable 宽度没有和容器一起响应，
- 用鼠标滚轮滚动时，表格内容响应会有延迟，不会滚动到预期位置（或没有展示预期的内容），用鼠标拖动滚动条则是正常的

同时，浏览器发报错

![image](https://github.com/VisActor/VTable/assets/61791214/9ffc7521-753f-45ef-8fea-90743a5baaaf)

### Expected Behavior

可以同时，解决响应和滚动两个问题

### Environment

```markdown
- OS: windows 11
- Browser: Edge Last
- Framework: Vue@3.3.4
```

**Comment by fangsmile** [comment]
感谢反馈问题！0.11.1会解决这个问题，9号或者10号发布版本 @van-chin

**Comment by fangsmile** [comment]
you can try this version of  0.11.1-alpha.10

**Comment by van-chin** [comment]
@fangsmile 更新到 `0.11.1-alpha.10` 
已经没有了 js 报错信息，宽度也可以进行响应了，非常感谢
但会有一点小问题:

- 当设置 `rightFrozenColCount ` 值为 1 时，表头列宽在拉伸时，没有和表的body 同步响应宽度
![image](https://github.com/VisActor/VTable/assets/61791214/ac995780-6095-4c5f-83dd-0c723dc912c4)

- `rightFrozenColCount ` 大于 1 时，也是因为 `表头列宽` 没有响应导致最后一列内容出现表格线对齐错位 
缩小容器宽度时：
![image](https://github.com/VisActor/VTable/assets/61791214/22e8e09a-f32c-41d3-afb9-8f446246983d)

拉伸容器宽度时:
![image](https://github.com/VisActor/VTable/assets/61791214/d000fb81-2e30-4710-97d0-b78dfc3b46a9)

**Comment by van-chin** [comment]
@fangsmile 

ListTable.widthMode 为 adaptive 时，
同时表格 左右两边设置有固定冻结列时，希望能响应容器宽度的同时，表格内部的横向滚动也能存在，
现在是设置 ListTable.widthMode adaptive 表格就没有了横向滚动了

**Comment by fangsmile** [comment]
> @fangsmile
> 
> ListTable.widthMode 为 adaptive 时， 同时表格 左右两边设置有固定冻结列时，希望能响应容器宽度的同时，表格内部的横向滚动也能存在， 现在是设置 ListTable.widthMode adaptive 表格就没有了横向滚动了
> 
> 就不方便展示 列很多的场景了

这个可以设置widthMode为’standard‘或者’autoWidth‘  然后结合autoFillWidth设置为true，可以列少时撑满容器  列多时根据宽度出现滚动条

**Comment by van-chin** [comment]
设置widthMode为’standard‘或者’autoWidth‘ 然后结合autoFillWidth设置为true

可以满足需求，感谢 @fangsmile
