### ISSUE TITLE
[Feature] Click the row to select a row and drag and drop to move

### ISSUE THREAD

**Issue by li936393** [VisActor/VTable#399]
### What problem does this feature solve?

In some scenarios, you need to manually drag rows to change the data order

### What does the proposed API look like?

add DRAG_ROW event

**Comment by Rui-Sun** [comment]
Row Drag function can be used in pivot table row header currently, we plan to add a row drag state to use Row Drag function in list table. We record this requirement in our requirement pool.

**Comment by fangsmile** [comment]
will support this function to drag row order
https://github.com/VisActor/VTable/issues/593
