### ISSUE TITLE
[Feature] 支持配置小计总计数据

### ISSUE THREAD

**Issue by xiaochong44** [VisActor/VTable#400]
### What problem does this feature solve?

希望可以像s2一样，可以在数据源里直接传入小计总计的数据。因为像达成率这样的指标，小计和总计按哪种聚合方式都是不正确的。
比如下像是s2的配置，第二个记录就是总计，第三个记录就是浙江小计。
{
    "province": "吉林",
    "city": "白山",
    "type": "纸张",
    "price": "1"
  },
  {
    "price": "15.5"
  },
  {
    "province": "浙江",
    "price": "5.5"
  },

### What does the proposed API look like?

类似s2直接传入小计总计数据

**Comment by fangsmile** [comment]
ok，我们高优排进去这个需求的

**Comment by fangsmile** [comment]
补充了例子 https://visactor.io/vtable/demo/data-analysis/pivot-analysis-custom-total

**Comment by nikoohp** [comment]
> 补充了例子 https://visactor.io/vtable/demo/data-analysis/pivot-analysis-custom-total

可以让总计行跟表头一样，固定再最下方吗？
