### ISSUE TITLE
[Feature] 支持计算量功能

### ISSUE THREAD

**Issue by xiaochong44** [VisActor/VTable#402]
### What problem does this feature solve?

增加计算量功能，类似EXCEL透视表，可以增加计算字段，取已有的列进行加减乘除运算。这样可以让每一个小计总计都满足运算公式。如下面EXCEL的计算字段，

![image](https://github.com/VisActor/VTable/assets/25057951/6807500e-f4ca-4daa-8757-2d22130125cb)

### What does the proposed API look like?

希望可以在配置项里增加计算字段配置，可以使用加减乘除四则运算来生成计算字段

**Comment by fangsmile** [comment]
收到，我们有个派生字段的设置：
![image](https://github.com/VisActor/VTable/assets/3468473/6c033b07-f8f4-4407-a199-601a37e073f6)
可以试用下是有什么不能满足吗？

**Comment by xiaochong44** [comment]
@fangsmile 好的，我是在官网没看到，目前官网的文档看的不太直观，找api的话不如s2好找

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/data-analysis/pivot-analysis-derivedField  新加了这个示例
