### ISSUE TITLE
[Feature] Add method set some tree nodes to expand or collapse

### ISSUE THREAD

**Issue by li936393** [VisActor/VTable#404]
### What problem does this feature solve?

Add method set some tree nodes to expand or collapse,

### What does the proposed API look like?

setTreeExpand(rows) setTreeCollapse(rows) or setTreeExpand(rows,true) setTreeExpand(rows,false)

**Comment by fangsmile** [comment]
@li936393 您好 目前有一个接口，是切换状态，您提到的指明状态去设置的我们后面考虑下加入。另外如果是初始化的时候需要设置状态 自定义树的透视表是可以在树节点设置状态hierarchyState的

```
  /**
   * 表头切换层级状态
   * @param col
   * @param row
   */
  toggleHierarchyState(col: number, row: number) 


  /**
   * 获取层级节点收起展开的状态
   * @param col
   * @param row
   * @returns
   */
  getHierarchyState(col: number, row: number) 
```
