### ISSUE TITLE
[Bug] 单元格闪烁

### ISSUE THREAD

**Issue by yuki070** [VisActor/VTable#416]
### Version

0.12.1

### Link to Minimal Reproduction

http://localhost:3020/vtable/demo/performance/100W

### Steps to Reproduce

1. rush docs
2. 打开任一demo链接，如：http://localhost:3020/vtable/demo/performance/100W
3. 选中一个单元格
4. 按住鼠标左键，在选中的单元格区域里小幅度移动

### Current Behavior

单元格会随着移动而不断闪烁
![20231018091355_rec_](https://github.com/VisActor/VTable/assets/656768/b54f49aa-e78a-4ef0-8822-75b23a62a3ce)

### Expected Behavior

移动的时候单元格背景色不发生闪烁

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
resolved 0.12.2
