### ISSUE TITLE
[bug] columns exceed 100 scroll error

### ISSUE THREAD

**Issue by sentongxue** [VisActor/VTable#420]
### What problem does this feature solve?

在我的业务中，需要一次性展示100以上的columns，但是在您得框架中似乎限制colLimit为100，超过100的时候，渲染表格就会报错，并且左右拖动表格，表格显示会错乱，还有空白；经过调试源码，发现确实是因为被限制了，希望您可以将colLimit改大一点，canvas来渲染大数据表格确实很快还不卡，您的框架解决了我最近的烦恼，很厉害！
![image](https://github.com/VisActor/VTable/assets/44992285/6edc54f4-8655-4e08-aae2-f1d22fa460fd)
![image](https://github.com/VisActor/VTable/assets/44992285/b8ad4b70-e65b-441b-9526-6a450237b15d)

### What does the proposed API look like?

希望可以提升colLimit值，这样就不会报错了，最近还比较紧急，因为被限制了

**Comment by fangsmile** [comment]
收到  我们高优解决下

**Comment by Rui-Sun** [comment]
方便提供一下出错的完整options吗，我们本地没有复现这个问题

**Comment by sentongxue** [comment]
> 方便提供一下出错的完整options吗，我们本地没有复现这个问题
const columns = [
  {
    field: 'index',
    title: '序号',
    dropDownMenu: [],
    width: 70,
    style: {
      textAlign: 'center'
    }
  },
  {
    field: 'c1',
    title: '企业名称',
    width: 200,
    sort: true,
    style: {
      autoWrapText: true,
      lineClamp: 2,
      color: 'blue',
      cursor: 'pointer'
    }
  },
  {
    field: 'c2',
    title: '村居',
    sort: true
  },
  {
    field: 'c3',
    title: '具体生产地址',
    sort: true
  },
  {
    field: 'c4',
    title: '经度',
    width: 100,
    dropDownMenu: []
  },
  {
    field: 'c5',
    title: '纬度',
    width: 100,
    dropDownMenu: []
  },
  {
    field: 'c6',
    title: '法人',
    sort: true,
    width: 120
  },
  {
    field: 'c7',
    title: '联系电话',
    width: 150
  },
  {
    field: 'c8',
    title: '负责人电话',
    width: 150
  },
  {
    field: 'c9',
    title: '企业类型',
    sort: true
  },
  {
    field: 'c10',
    title: '是否贷款',
    dropDownMenu: [],
    sort: true,
    width: 100,
    style: {
      textAlign: 'center'
    }
  },
  {
    field: 'c11',
    title: '贷款金额',
    sort: true,
    width: 150,
    style: {
      textAlign: 'center'
    }
  },
  {
    field: 'c12',
    title: '建成时间',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c13',
    title: '投运时间',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c14',
    title: '生产酒的类型',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c15',
    title: '生产状态',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c16',
    title: '企业建设情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c17',
    title: '总窖池',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c18',
    title: '捆籽',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c19',
    title: '碎沙',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c20',
    title: '酒甄',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c21',
    title: '捆籽1',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c22',
    title: '碎沙1',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c23',
    title: '工人总数',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c24',
    title: '其中后勤管理人员',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c25',
    title: '技术工人',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c26',
    title: '产业工人',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c27',
    title: '销售公司名称',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c28',
    title: '注册地址',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c29',
    title: '自有品牌',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c30',
    title: '主要市场',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c31',
    title: '贴牌产品',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c32',
    title: '基酒销售',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c33',
    title: '是否代加工',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c34',
    title: '是否代加工_碎沙',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c35',
    title: '基酒库存地点',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c36',
    title: '现有存量',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c37',
    title: '现有存量1',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c38',
    title: '实缴税金',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c39',
    title: '其中生产企业',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c40',
    title: '销售公司',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c41',
    title: '是否外来资本注入',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c42',
    title: '与外资合作形式',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c43',
    title: '独资企业性质',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c44',
    title: '捆籽2',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c45',
    title: '碎沙2',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c46',
    title: '计划酒甄',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c47',
    title: '捆籽3',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c48',
    title: '碎沙3',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c49',
    title: '生产酒的类型1',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c50',
    title: '食品生产许可证号或小作坊登记证号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c51',
    title: '食品卫生许可证号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c52',
    title: '安全生产许可证号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c53',
    title: '消防意见书',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c54',
    title: '土地和规划手续文号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c55',
    title: '取水许可证号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c56',
    title: '营业执照',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c57',
    title: '水土保持方案批复文号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c58',
    title: '环评批复或备案号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c59',
    title: '验收批复或备案号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c60',
    title: '入河排污口设置批复文号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c61',
    title: '排污许可证类型',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c62',
    title: '排污许可证编号',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c63',
    title: '属于排污许可证限期整改',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c64',
    title: '企业占地面',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c65',
    title: '已完善手续',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c66',
    title: '未完善手续',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c67',
    title: '已建成面积',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c68',
    title: '其中生产用房',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c69',
    title: '制曲用房',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c70',
    title: '配套用房',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c71',
    title: '仍需用地',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c72',
    title: '窖泥用量',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c73',
    title: '窖泥来源',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c74',
    title: '窖泥处置情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c75',
    title: '酒糟产生量',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c76',
    title: '酒糟处置去向',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c77',
    title: '主管网覆盖情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c78',
    title: '支管网接入主管网情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c79',
    title: '是否雨污分流',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c80',
    title: '是否有排污口',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c81',
    title: '高浓度废水处理情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c82',
    title: '在线监测设备情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c83',
    title: '锅炉使用情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c84',
    title: '吨位',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c85',
    title: '污水进入连片处理厂情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c86',
    title: '污水管网输送进入其他污水处理厂情况',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c87',
    title: '污水转运运输单位',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c88',
    title: '污水罐车转运处置单位',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c89',
    title: '处理工艺',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c90',
    title: '日处理能力',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c91',
    title: '类型',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c92',
    title: '去向',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c93',
    title: '处理设施',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c94',
    title: '实施改能',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c95',
    title: '实施改窖',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c96',
    title: '实施改池',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c97',
    title: '实施改管',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c98',
    title: '溪沟分布',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c99',
    title: '与受纳水体直线距离',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c100',
    title: '分类处置意见',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c101',
    title: '包保单位',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c102',
    title: '包保责任人',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c103',
    title: '包保责任人联系电话',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c104',
    title: '职务',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c105',
    title: '核查时间',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c106',
    title: '核查地址',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c107',
    title: '备注',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'c108',
    title: '核查状态',
    dropDownMenu: [],
    width: 150,
    sort: true
  },
  {
    field: 'opt',
    title: '操作',
    dropDownMenu: [],
    width: 100,
    icon: [getBtn('print'), getBtn('edit'), getBtn('delete')]
  }
];

const options =  {
    columns,
    records: [],
    frozenColCount: 2, // 序号、企业名称冻结
    rightFrozenColCount: 1, // 操作冻结
    showFrozenIcon: false, // 不显示冻结图标
    theme: VTable.themes.ARCO.extends({
      scrollStyle: {
        visible: 'always',
        width: 8
      }
    }),
    widthMode: 'standard',
    autoWrapText: true,
    heightMode: 'autoHeight',
    // autoWrapText: true,
    defaultColWidth: 200,
    autoFillWidth: true, // 列宽自动充满容器
    menu: {
      defaultHeaderMenuItems: [
        {
          text: '数据项包含...',
          menuKey: 'includes',
          icon: {
            svg: getIcon('includes')
          }
        },
        {
          text: '数据项等于...',
          menuKey: 'equal',
          icon: {
            svg: getIcon('equal')
          }
        },
        {
          text: '清空筛选条件',
          menuKey: 'reset',
          icon: {
            svg: getIcon('reset')
          }
        }
      ]
    }
  },

**Comment by Rui-Sun** [comment]
[0.12.3-alpha.0](https://www.npmjs.com/package/@visactor/vtable/v/0.12.3-alpha.0)

**Comment by sentongxue** [comment]
> 修复了一下，可以测试一下 [0.12.3-alpha.0](https://www.npmjs.com/package/@visactor/vtable/v/0.12.3-alpha.0)

刚刚重新下载测试了，已经被你完美的解决了，非常谢谢你！

**Comment by fangsmile** [comment]
https://github.com/VisActor/VTable/pull/426

**Comment by sentongxue** [comment]
> 修复了一下，可以测试一下 [0.12.3-alpha.0](https://www.npmjs.com/package/@visactor/vtable/v/0.12.3-alpha.0)

今天发现新问题了，就是我数据条数超过100条，滑动的到底部的时候会出现空白，还会报错
![11](https://github.com/VisActor/VTable/assets/44992285/1dea723c-8c2a-4559-b83a-9ba25e135fcd)
![22](https://github.com/VisActor/VTable/assets/44992285/50bf7651-4d7c-4dad-bc2c-b88386160d3d)

**Comment by Rui-Sun** [comment]
> > 修复了一下，可以测试一下 [0.12.3-alpha.0](https://www.npmjs.com/package/@visactor/vtable/v/0.12.3-alpha.0)
> 
> 今天发现新问题了，就是我数据条数超过100条，滑动的到底部的时候会出现空白，还会报错
> ![11](https://github.com/VisActor/VTable/assets/44992285/1dea723c-8c2a-4559-b83a-9ba25e135fcd)
> ![22](https://github.com/VisActor/VTable/assets/44992285/50bf7651-4d7c-4dad-bc2c-b88386160d3d)
> 

修复了一下，可以试一下这个版本 0.13.0-alpha.3
