### ISSUE TITLE
[Feature] 动态添加数据

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#437]
### What problem does this feature solve?

实例化vtable之后向表格添加数据

### What does the proposed API look like?

目前我没有在接口文档中找到添加数据的接口，所以我想问一下目前有这个功能吗？没有的话可以考虑添加一下吗？谢谢

**Comment by fangsmile** [comment]
有setRecords接口哦
![image](https://github.com/VisActor/VTable/assets/3468473/3d878029-f3e1-4028-83d1-a61f003572b8)
@Nyx2022

**Comment by Nyx2022** [comment]
> 有setRecords接口哦 ![image](https://user-images.githubusercontent.com/3468473/277267277-3d878029-f3e1-4028-83d1-a61f003572b8.png) @Nyx2022

setRecords接口是会直接替换原本的Records吗？如果是的话，就不太符合我的需求，还是希望能有动态添加、删除、修改数据的接口，并且修改之后自动引用排序、筛选、规则等，最重要的是可以保持当前的显示数据不变，只是滚动条的变长和变短以及位置的偏移。我知道最后这个修改数据后保持相对数据位置不变可能有点难，但是还是希望vtable能够具备此能力，这样相信能够在一众竞品中遥遥领先

**Comment by fangsmile** [comment]
好的 了解了 我们后面会考虑实现。也欢迎加入微信群 共享共创共建！
![image](https://github.com/VisActor/VTable/assets/3468473/9e2d1419-bd1a-45a1-a142-8175ba60cc44)
