### ISSUE TITLE
[Feature] field获取整个json值

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#444]
### What problem does this feature solve?

我想在columns的定义中，在某个字段中获取整行的数据，即当前行的json或object数据

### What does the proposed API look like?

类似于args.rowDataValue这种

**Comment by fangsmile** [comment]
请问是ListTable类型表格吗@Nyx2022

**Comment by Nyx2022** [comment]
> 请问是ListTable类型表格吗@Nyx2022

是的，我目前正在打算使用ListTable，当然如果能在其他类型表格中也添加此api，可能对其他道友也会有所帮助

**Comment by fangsmile** [comment]
// 获取原始数据
  getCellOriginRecord(col: number, row: number) 
@Nyx2022 试下这个接口  应该是这个需求吧

**Comment by Nyx2022** [comment]
> // 获取原始数据 getCellOriginRecord(col: number, row: number)getCellOriginRecord（col： number， row： number） @Nyx2022 试下这个接口 应该是这个需求吧

确实可以，感谢
