### ISSUE TITLE
[Feature] 透视图表提供返回当前单元格内数据的同一组数据返回格式{key:XXXX,value:XXX} 

### ISSUE THREAD

**Issue by X-smart** [VisActor/VTable#452]
### What problem does this feature solve?

数据添加属性

### What does the proposed API look like?

return [{key:XXXX,value:XXX} ,{key:XXXX,value:XXX} ,{key:XXXX,value:XXX} ]

**Comment by fangsmile** [comment]
getCellOriginRecord 接口即可
