### ISSUE TITLE
[Feature] 现在的表格功能大部分都是展示数据，后续会有编辑和更多的即时交互功能吗？

### ISSUE THREAD

**Issue by ShiXinClearBoth** [VisActor/VTable#453]
### What problem does this feature solve?

目前想要拥有一些表格即时交互和渲染的功能如：
双击单元格编辑修改/并有接口能够即时与后台数据传递
局部渲染：比如只更新基础表格的columns的数据部分，而不重新渲染整个表格

### What does the proposed API look like?

目前想要拥有一些表格即时交互和渲染的功能如：
双击单元格编辑修改/并有接口能够即时与后台数据传递
局部渲染：比如只更新基础表格的columns的数据部分，而不重新渲染整个表格

**Comment by fangsmile** [comment]
编辑功能 这个季度会进行开发哦！
局部渲染这个场景可以更明确一些，我们现在有updateColumns接口 不知道是否满足？
 @ShiXinClearBoth

**Comment by ShiXinClearBoth** [comment]
好的，我继续多看看文档和应用！
持续关注

**Comment by ShiXinClearBoth** [comment]
通过API中的双击事件写了个基础表的编辑功能，大家可以参考和交流一下：

`tableInstance.on("dblclick_cell",(args)=>{
    // 判断div中是否存在Inp
    if(document.querySelector("#editInp")){
      document.getElementById("vSheet").removeChild(document.getElementById("editInp"));
    }
    // js创建input元素和样式
    const input = document.createElement("input");  
    input.id="editInp";
    input.type = "text"; 
    input.value=args.dataValue; 
    input.style.position="absolute";
    input.style.border = "none";  
    input.style.color = "#2d2e32";
    input.style.fontSize = "14px";
    input.style.top = `${args.cellRange.top +1}px`;  
    input.style.left = `${args.cellRange.left +1}px`;
    input.style.width = `${args.target.attribute.width -2}px`;  
    input.style.height = `${args.target.attribute.height -2}px`;
    input.onblur = function(){
      // 移除inp
      document.getElementById("vSheet").removeChild(document.getElementById("editInp"));
    } 
    document.getElementById("vSheet").appendChild(input);
    document.getElementById("editInp").focus();
  })`

**Comment by ShiXinClearBoth** [comment]
用API中的双击事件写了个基本表格的编辑表格功能，大家可以参考和交流一下
`
tableInstance.on("dblclick_cell",(args)=>{

    // 判断div中是否存在Inp
    if(document.querySelector("#editInp")){
      document.getElementById("vSheet").removeChild(document.getElementById("editInp"));
    }
    // js创建input元素和样式
    const input = document.createElement("input");  
    input.id="editInp";
    input.type = "text"; 
    input.value=args.dataValue; 
    input.style.position="absolute";
    input.style.border = "none";  
    input.style.color = "#2d2e32";
    input.style.fontSize = "14px";
    input.style.top = `${args.cellRange.top +1}px`;  
    input.style.left = `${args.cellRange.left +1}px`;
    input.style.width = `${args.target.attribute.width -2}px`;  
    input.style.height = `${args.target.attribute.height -2}px`;
    input.onblur = function(){
      // 移除inp
      document.getElementById("vSheet").removeChild(document.getElementById("editInp"));
    } 
    document.getElementById("vSheet").appendChild(input);
    document.getElementById("editInp").focus();
  })
`

**Comment by fangsmile** [comment]
@ShiXinClearBoth 有兴趣参与开源贡献？

**Comment by fangsmile** [comment]
@ShiXinClearBoth 编辑功能已经开发 0.15.0版本可以试用
