### ISSUE TITLE
[Bug]  移动表头异常，双击表头会触发列互换事件

### ISSUE THREAD

**Issue by DIVADING** [VisActor/VTable#454]
### Version

0.13.0-alpha.5

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/interaction/move-header-position

### Steps to Reproduce

官网示例——移动表头位置

### Current Behavior

在多次操作后某些列的互换会失效，在某个列上双击会触发列互换事件

### Expected Behavior

列互换正常，在某个列上双击不应该触发列互换事件

### Environment

```markdown
- OS: macOS 13.4 (22F66)
- Browser:Chrome
- Framework: react 16
```

**Comment by fangsmile** [comment]
收到  会高优修复
