### ISSUE TITLE
[Feature] 添加手动排序api

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#470]
### What problem does this feature solve?

我不清楚在每次添加数据（目前是使用setRecords）后会不会自动重新应用sortState中指定的排序规则，如果没有的话建议添加一个手动排序的api

### What does the proposed API look like?

添加一个手动排序的api

**Comment by fangsmile** [comment]
设置数据的时候可以同时传排序规则 @Nyx2022 
![image](https://github.com/VisActor/VTable/assets/3468473/42215904-cf17-46f8-bc63-739d5696d637)

![image](https://github.com/VisActor/VTable/assets/3468473/588094b6-f008-422d-ab7e-7f5f8be71728)

**Comment by Nyx2022** [comment]
> 设置数据的时候可以同时传排序规则 @Nyx2022 ![image](https://user-images.githubusercontent.com/3468473/278323432-42215904-cf17-46f8-bc63-739d5696d637.png)
> 
> ![image](https://user-images.githubusercontent.com/3468473/278323471-588094b6-f008-422d-ab7e-7f5f8be71728.png)

好的，谢谢
