### ISSUE TITLE
[Feature] 文档编辑器代码无法复制

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#471]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/51039208/b1504427-9f42-4b3f-9410-7f27aa40e0e9)

右边的编辑器中的代码无法复制，使用起来很不方便

### What does the proposed API look like?

希望可以复制代码

**Comment by fangsmile** [comment]
@Nyx2022  是可以复制的呀

**Comment by Nyx2022** [comment]
> @Nyx2022 是可以复制的呀

不好意思，确实可以，是我浏览器的问题
