### ISSUE TITLE
[Feature] 滚动条滚动时显示可视区域的范围

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#472]
### What problem does this feature solve?

在列表滚动条滚动时，通过tooltip或其他的方式显示当前可是区域的范围，比如1000-1100

### What does the proposed API look like?

添加属性控制

**Comment by Rui-Sun** [comment]
需求收到，我们计划增加一个api，可以获取当前可视区域的行列范围

**Comment by fangsmile** [comment]
@Nyx2022 0.13.4版本 getBodyVisibleCellRange 可以用这个接口获取。目前还不准备在内部支持这个Tooltip，可以结合滚动事件业务方来自定义实现该需求
![image](https://github.com/VisActor/VTable/assets/3468473/9de13df6-a58b-4ea4-b37a-555b1da95b04)
