### ISSUE TITLE
[Feature] listtable添加筛选和搜索api

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#473]
### What problem does this feature solve?

一是希望在listtable中添加filterRule用于筛选显示的数据，而是希望可以提供一个搜索或更新筛选的api修改或追加筛选条件，三是希望新增的数据能够自动应用已有的筛选条件

### What does the proposed API look like?

添加属性filterRules和接口assFilterRules等

**Comment by fangsmile** [comment]
后续会进行考虑增加该功能 谢谢建议

**Comment by fangsmile** [comment]
筛选 0.20.0已支持
搜索 0.21.0 支持上
