### ISSUE TITLE
[Bug] 窗口宽度发生改变之后cellType=“image” 渲染异常

### ISSUE THREAD

**Issue by 18879293979** [VisActor/VTable#474]
### Version

0.13.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

1.在columns 中配置最后一列为 cellType='image'，minWidth=100，maxWidth=100，width=100
2.option.autoFillWidth = true
3.改变窗口宽度

预览：

https://github.com/VisActor/VTable/assets/57932069/6d3cb975-06ad-4bc9-82a4-c58f987a2dbd

![Uploading image.png…]()

### Current Behavior

图片列为固定宽度

### Expected Behavior

窗口宽度发生改变之后cellType=“image”宽度异常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by 18879293979** [comment]
![image](https://github.com/VisActor/VTable/assets/57932069/17cc9967-0aca-4957-b36c-a464c43eec7d)

**Comment by 18879293979** [comment]
![image](https://github.com/VisActor/VTable/assets/57932069/22c88dda-be7f-411b-a73e-d4f06bda6baa)
![image](https://github.com/VisActor/VTable/assets/57932069/990ab8f8-d76f-4f09-81c3-e397e967f170)

**Comment by Rui-Sun** [comment]
预览视频挂了，没有完全理解这个问题的现象；测试了一下，好像效果是符合预期的，能再详细描述一下这个问题吗，具体的渲染异常是指哪里呢？可以使用下面这个codesandbox用例
https://codesandbox.io/s/vtable-image-issue-qjcpl3?file=/src/index.ts

**Comment by 18879293979** [comment]
> autoFillWidth
我在option中加入了autoFillWidth: true 然后再改变窗口大小

**Comment by 18879293979** [comment]
> 预览视频挂了，没有完全理解这个问题的现象；测试了一下，好像效果是符合预期的，能再详细描述一下这个问题吗，具体的渲染异常是指哪里呢？可以使用下面这个codesandbox用例 https://codesandbox.io/s/vtable-image-issue-qjcpl3?file=/src/index.ts
我在option中加入了autoFillWidth: true 然后再改变窗口大小

**Comment by Rui-Sun** [comment]
> > 预览视频挂了，没有完全理解这个问题的现象；测试了一下，好像效果是符合预期的，能再详细描述一下这个问题吗，具体的渲染异常是指哪里呢？可以使用下面这个codesandbox用例 https://codesandbox.io/s/vtable-image-issue-qjcpl3?file=/src/index.ts
> > 我在option中加入了autoFillWidth: true 然后再改变窗口大小

了解了，可以复现，我们尽快修复
