### ISSUE TITLE
[Feature] listtable支持单选禁止选中多个单元格

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#477]
### What problem does this feature solve?

目前listtable是多选模式。希望支持单选，即只允许每次选择一行

### What does the proposed API look like?

添加控制属性

**Comment by fangsmile** [comment]
具体是想关闭ctrl和shift的多选能力吗 @Nyx2022

**Comment by Nyx2022** [comment]
> 具体是想关闭ctrl和shift的多选能力吗 @Nyx2022

也包括鼠标拖拽的多选能力

**Comment by fangsmile** [comment]
相关issue：  #1485

**Comment by fangsmile** [comment]
已经支持配置disableDragSelect
