### ISSUE TITLE
[Bug] MOUSEOVER_CHART_SYMBOL事件监听问题

### ISSUE THREAD

**Issue by wangdaodao** [VisActor/VTable#479]
### Version

0.13.0

### Link to Minimal Reproduction

https://codesandbox.io/s/vtable-simple-demo-forked-nldxlt?file=/src/index.ts

### Steps to Reproduce

1. 绑定MOUSEOVER_CHART_SYMBOL事件
2. 划到表格滚动条后会控制台报`cellGoup is undefined`

### Current Behavior

控制台报错

### Expected Behavior

控制台不报错

### Environment

```markdown
- OS: win10 64位
- Browser: firefox 119.0
- Framework:
```

### Any additional comments?

不清楚自己事件是否用错了，其他的事件都没有报错，唯独这个事件报错。

**Comment by wangdaodao** [comment]
另外想问一下表格有没有销毁事件：）

**Comment by Rui-Sun** [comment]
问题收到，我们尽快修复
