### ISSUE TITLE
[Bug] 拖拽表头换位报错

### ISSUE THREAD

**Issue by imcxx** [VisActor/VTable#480]
### Version

0.13.0

### Link to Minimal Reproduction

https://codesandbox.io/s/elated-butterfly-3q29kq?file=/src/App.vue

### Steps to Reproduce

1.拖动表头
2.控制台报错event-manager.ts: 416 Uncaught TypeError: Cannot read properties of null (reading 'renderCount')

### Current Behavior

拖动表头换位报错
![image](https://github.com/VisActor/VTable/assets/30992969/504e6229-5f43-4b85-9ffd-bc112a90304f)

### Expected Behavior

换位成功

### Environment

```markdown
- OS:win10 64位
- Browser:谷歌
- Framework:vue@2.x
```

**Comment by Rui-Sun** [comment]
'renderCount'这个报错问题我们有记录，计划在下个版本修复；不过'renderCount'这个报错问题应该不会影响拖拽换位的效果，我在您提供的codesandbox也没有复现这个问题。请问报错是有影响到拖拽功能吗？

**Comment by imcxx** [comment]
我把页面报错关闭后确实不影响了，谢谢~

**Comment by fangsmile** [comment]
@imcxx 可以使用最新版本

**Comment by chenwei1109** [comment]
拖拽表头换位 如果出现横向滚动条，滚动条无法自动滚动如何处理？
