### ISSUE TITLE
[Feature] 复制粘贴的问题，需要支持

### ISSUE THREAD

**Issue by dntzhang** [VisActor/VTable#509]
### What problem does this feature solve?

复制粘贴的问题，需要支持

### What does the proposed API look like?

直接开放配置项目。默认打开 ctrl+c 复制到剪切版

非常棒的项目。打算作为默认table了。

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/e3a21aca-ae1a-441d-85b9-a7e9673c94e4)
@dntzhang 可以开启这个
欢迎加入我们微信群交流
![image](https://github.com/VisActor/VTable/assets/3468473/00d2135f-873c-4ee5-b424-67c0f7548393)

**Comment by dntzhang** [comment]
哦。进了。赞

**Comment by lstoryc** [comment]
咨询下，是否支持剪切能力？
