### ISSUE TITLE
[Bug] ListTable.select.disableHeaderSelect bug

### ISSUE THREAD

**Issue by Kento97** [VisActor/VTable#530]
### Version

0.13.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

const table = new VTable.ListTable({
  select: {
    disableHeaderSelect: true
  }
});
鼠标按住并且按照箭头方向移动，然后getSelectedCellInfos，返回的是空数组
![image](https://github.com/VisActor/VTable/assets/55472948/acb42140-bbf5-42bf-b758-e6b7f32d6191)

### Current Behavior

返回空数组

### Expected Behavior

返回所选单元格的数据

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
0.13.4 fixed
