### ISSUE TITLE
[Feature] 建议支持键盘上下左右选中cell

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#548]
### What problem does this feature solve?

建议给listtable添加支持键盘快捷键切换cell的功能

### What does the proposed API look like?

添加一个选项控制 和 切换前、切换后的回调函数

**Comment by fangsmile** [comment]
选中后 使用键盘来切换选中位置吗？
这个我们后期会加，目前需求比较满

**Comment by fangsmile** [comment]
0.17.1 今晚发版
