### ISSUE TITLE
[Bug] 0.14.0调整页面大小时报错

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#555]
### Version

0.14.0

### Link to Minimal Reproduction

no

### Steps to Reproduce

当调整页面大小的时候，vtabel也会调整大小，然后就会爆出如下错误
![image](https://github.com/VisActor/VTable/assets/51039208/c6ceb84a-2cdd-480f-8f73-7ef185b5fec5)

### Current Behavior

报错

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到

**Comment by fangsmile** [comment]
请描述一下必现步骤 @Nyx2022
