### ISSUE TITLE
希望增加导出功能 如导出csv 和 excel 文件

### ISSUE THREAD

**Issue by xiaofeihe** [VisActor/VTable#564]
### What problem does this feature solve?

希望增加导出数据的 接口，能像 ag -grid 一样 提供导出 csv 或 excel 数据表功能。
导出的excel 文件最好是和 VTable 显示格式一样，如 二级表头，合并单元格这些。

如果能带着 字体颜色，单元格颜色导出 excel 那就太好了。

### What does the proposed API look like?

 
![image](https://github.com/VisActor/VTable/assets/1018509/7111e6d0-9413-474c-a3ce-ea11d853105d)
this.gridApi.exportDataAsExcel();

**Comment by fangsmile** [comment]
收到  我们会尽力去做哈 。
欢迎加入我们的微信群交流
![image](https://github.com/VisActor/VTable/assets/3468473/f13ea2e4-2a2a-43d7-9d5b-0bb699c1ecae)

**Comment by 441023065** [comment]
正在找这个功能。用来显示数据的，其中有合并行列的，想要原模原样导出table显示的效果。

**Comment by fangsmile** [comment]
@441023065  @xiaofeihe  实现了一版  0.17.0版本会带上  可以关注下  15号发布
