### ISSUE TITLE
[Feature] 希望ListTable 增加总结栏功能

### ISSUE THREAD

**Issue by nikoohp** [VisActor/VTable#582]
### What problem does this feature solve?

希望ListTable 增加总结栏功能，并固定在表格最下方

### What does the proposed API look like?

希望ListTable 增加总结栏功能，并固定在表格最下方

**Comment by fangsmile** [comment]
你好！很高兴你的建议，可以先参照这个实现一下：
https://codesandbox.io/s/vtable-summary-row-mh3fjg?file=/src/index.ts
利用了customMergeCell 和 bottomFrozenRowCount
欢迎进我们的微信群进行交流
![image](https://github.com/VisActor/VTable/assets/3468473/58878cda-69cd-41f4-aa87-f8035479d5b0)

**Comment by nikoohp** [comment]
> 你好！很高兴你的建议，可以先参照这个实现一下： https://codesandbox.io/s/vtable-summary-row-mh3fjg?file=/src/index.ts 利用了customMergeCell 和 bottomFrozenRowCount 欢迎进我们的微信群进行交流 ![image](https://user-images.githubusercontent.com/3468473/283448056-58878cda-69cd-41f4-aa87-f8035479d5b0.png)

用 `bottomFrozenRowCount` 试过, 数据撑满时效果能行，但是如果数据不足时，效果就不是我想要的效果了。
希望的是不管数据的多少，总结栏都能固定在表格的底部，现在根据 `bottomFrozenRowCount` 模拟时，当数据不足一屏时，总结栏是跟随数据行的。

![Uploading image.png…]()

**Comment by fangsmile** [comment]
@nikoohp 了解了  我们后续优化下这个功能
