### ISSUE TITLE
[Feature] 能否在hover样式存在时执行updateColumns后保留hover样式

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#619]
### What problem does this feature solve?

在hover样式存在时执行updateColumns后保留hover样式

### What does the proposed API look like?

更新配置项后保留hover样式

**Comment by fangsmile** [comment]
0.15.1 优化

**Comment by jickchen34** [comment]
setRecords等操作依然会刷新掉hover的样式
https://visactor.io/vtable/demo/table-type/list-table
let  tableInstance;
  fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/VTable/North_American_Superstore_data.json')
    .then((res) => res.json())
    .then((data) => {

const columns =[
    {
        "field": "Order ID",
        "title": "Order ID",
        "width": "auto"
    },
    {
        "field": "Customer ID",
        "title": "Customer ID",
        "width": "auto"
    },
    {
        "field": "Product Name",
        "title": "Product Name",
        "width": "auto"
    },
    {
        "field": "Category",
        "title": "Category",
        "width": "auto"
    },
    {
        "field": "Sub-Category",
        "title": "Sub-Category",
        "width": "auto"
    },
    {
        "field": "Region",
        "title": "Region",
        "width": "auto"
    },
    {
        "field": "City",
        "title": "City",
        "width": "auto"
    },
    {
        "field": "Order Date",
        "title": "Order Date",
        "width": "auto"
    },
    {
        "field": "Quantity",
        "title": "Quantity",
        "width": "auto"
    },
    {
        "field": "Sales",
        "title": "Sales",
        "width": "auto"
    },
    {
        "field": "Profit",
        "title": "Profit",
        "width": "auto"
    }
];

const option = {
  records:data,
  columns,
  widthMode:'standard'
};
tableInstance = new VTable.ListTable(document.getElementById(CONTAINER_ID),option);
setInterval(()=>{
    tableInstance.setRecords(data)
},1000)
tableInstance.
window['tableInstance'] = tableInstance;
    })
