### ISSUE TITLE
[Feature] StylePropertyFunctionArg能否增加一个oldValue项

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#620]
### What problem does this feature solve?

便于根据数据变化更新表格样式等操作

### What does the proposed API look like?

export interface StylePropertyFunctionArg {
  row: number;
  col: number;
  /** 表格实例 */
  table: BaseTableAPI;
  /**有format的话 格式化后或者计算后的值 */
  value?: FieldData;
/**更新前的值*/
oldValue?:FieldData;
  /**原始值 */
  dataValue?: FieldData;
  /** progressbar类型特有，表示当前数值在总体数据范围的比例 */
  percentile?: number;
  /** 单元格的表头路径信息 */
  cellHeaderPaths: ICellHeaderPaths;
}

**Comment by fangsmile** [comment]
/原始值 /
dataValue?: FieldData;
目前参数中dataValue是不是就是你所希望要的值？ @jickchen34

**Comment by jickchen34** [comment]
> /原始值 / dataValue?: FieldData; 目前参数中dataValue是不是就是你所希望要的值？ @jickchen34

dataValue是cell更新后当前的值，我期望得到cell上一次的值。例如 1->2,dataValue=2,oldValue=1

**Comment by fangsmile** [comment]
@jickchen34 你是使用了editor编辑功能是吧  可以用getCellRawValue(col,row) 接口
![image](https://github.com/VisActor/VTable/assets/3468473/7fa0b8d1-032b-4287-9146-78001a237b3d)
