### ISSUE TITLE
[Bug] 鼠标弹起，滚动条依然随之滚动

### ISSUE THREAD

**Issue by s209392599** [VisActor/VTable#624]
### Version

0.14.3-alpha.1

### Link to Minimal Reproduction

t

### Steps to Reproduce

滚动

### Current Behavior

在windows上，鼠标放在横向滚动条上按下鼠标左键不松手，拖动到其它地方时松开手进行上下左右移动，此时滚动条会随之左右移动

### Expected Behavior

期望：鼠标弹起时解绑与滚动条的移动事件

### Environment

```markdown
- OS: windows
- Browser: chrome 93
- Framework: 浏览器端的min.js文件
```

### Any additional comments?

t

**Comment by Rui-Sun** [comment]
试了一下好像没能复现这个问题，https://codesandbox.io/p/sandbox/vtable-scroll-y2mjt2 这里写了一个滚动的demo，红框区域(canvas)外松开鼠标也可以终止滚动操作。可以提供一下能复现这个问题的环境吗？
