### ISSUE TITLE
[Bug] when mouse leave scorllbar not offer the event

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#626]
### Version

0.15.0

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

单击滚动条 按住 滚动条 鼠标左右拖动 

### Current Behavior

当鼠标超出canvas时 滚动条的事件并没有消失  鼠标已经放开了 还能左右的滚动 体验非常不好

### Expected Behavior

期望 鼠标离开canvas时 offer 滚动事件 

### Environment

```markdown
- OS:
- Browser:Google
- Framework:
```

**Comment by TryChai** [comment]
const tableOptions = ref({
    columns:[
      {
        field: '',
        title: '',
        width: 60,
        headerType: 'checkbox',
        cellType: 'checkbox',
        headerStyle:bgStyle,
        style:textStyle,
      },
      {
        field: 'key',
        title: '#',
        width: 60,
        headerStyle:bgStyle,
        style:textStyle,
      },
                  {
                    "field": "serviceTicketType",
                    "title": t('serviceTicketVo.serviceTicketType'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                      customLayout:dictShow("serviceTicketType",hs_service_ticket__type)
                  },
                  {
                    "field": "serialNo",
                    "title": t('serviceTicketVo.serialNo'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                  },
                  {
                    "field": "title",
                    "title": t('serviceTicketVo.title'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                  },
                  {
                    "field": "nickName",
                    "title": t('serviceTicketVo.nickName'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                  },
                  {
                    "field": "state",
                    "title": t('serviceTicketVo.state'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                      customLayout:dictShow("state",hs_service_ticket__state)
                  },
                  {
                    "field": "degree",
                    "title": t('serviceTicketVo.degree'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                      customLayout:dictShow("degree",hs_service_ticket__degree)
                  },
                  {
                    "field": "serviceTicketHandleType",
                    "title": t('serviceTicketVo.serviceTicketHandleType'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                      customLayout:dictShow("serviceTicketHandleType",hs_service_ticket__handle_type)
                  },
                  {
                    "field": "createTime",
                    "title": t('serviceTicketVo.createTime'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                  },
                  {
                    "field": "solutionTime",
                    "title": t('serviceTicketVo.solutionTime'),
                    "sort": false,
                    "width":'auto',
                    headerStyle:bgStyle,
                    style:textStyle,
                  },
      {
        "field": "operationByYourself",
        "title": '操作',
        "sort": false,
        headerStyle:bgStyle,
        style:textStyle,
        customLayout:(args)=>{
          const {table, row, col, rect} = args;
          const {height, width} = rect || table.getCellRect(col, row);
          const record = table.getRecordByRowCol(col, row);
          const container = new CustomLayout.Group({
            height,
            width:200,
            display: 'flex',
            flexDirection: 'row',
            alignItems:'center',
            flexWrap:'wrap',

          });
          if(isShowExpress(record,`state==1`) && isAuth('core_serviceTicketVo_edit')){
            const edittext = new CustomLayout.Text({
              text: t('serviceTicketVo.tableBtn.edit'),
              fontSize: 14,
              fill: '#2E5CF6',
              boundsPadding:[15,10,5,10],
              cursor: 'pointer',
              key:'serviceTicketVo-edit'
            } as any);
            container.add(edittext)

          }
          if(isShowExpress(record,`state==1`) && isAuth('core_serviceTicketVo_deal')){
            const dealtext = new CustomLayout.Text({
              text: t('serviceTicketVo.tableBtn.deal'),
              fontSize: 14,
              fill: '#2E5CF6',
              boundsPadding:[15,10,5,10],
              cursor: 'pointer',
              key:'serviceTicketVo-deal'
            } as any);
            container.add(dealtext)

          }
          if(isShowExpress(record,'') && isAuth('core_serviceTicketVo_addReview')){
            const addReviewtext = new CustomLayout.Text({
              text: t('serviceTicketVo.tableBtn.addReview'),
              fontSize: 14,
              fill: '#2E5CF6',
              boundsPadding:[15,10,5,10],
              cursor: 'pointer',
              key:'serviceTicketVo-addReview'
            } as any);
            container.add(addReviewtext)

          }
          if(isShowExpress(record,`state==1`) && isAuth('core_serviceTicketVo_sendWxCpApp')){
            const sendWxCpApptext = new CustomLayout.Text({
              text: t('serviceTicketVo.tableBtn.sendWxCpApp'),
              fontSize: 14,
              fill: '#2E5CF6',
              boundsPadding:[15,10,5,10],
              cursor: 'pointer',
              key:'serviceTicketVo-sendWxCpApp'
            } as any);
            container.add(sendWxCpApptext)

          }
          if(isShowExpress(record,`state==2`) && isAuth('core_serviceTicketVo_editTips')){
            const editTipstext = new CustomLayout.Text({
              text: t('serviceTicketVo.tableBtn.editTips'),
              fontSize: 14,
              fill: '#2E5CF6',
              boundsPadding:[15,10,5,10],
              cursor: 'pointer',
              key:'serviceTicketVo-editTips'
            } as any);
            container.add(editTipstext)

          }
          return {
            rootContainer: container,
            renderDefault: false,
          };
        }
      },
    ],
    records: [],
    widthMode: 'autoWidth',
    frozenColCount:1,
    rightFrozenColCount:1,
    autoWrapText:true,
    heightMode:'autoHeight',
    select:{disableSelect:1},
    hover:{highlightMode:'row'},
    allowFrozenColCount: 2,
    showFrozenIcon: false,
    // columnResizeMode:'none',
    autoFillWidth:true,
    autoFillHeight:true,
  })

**Comment by Rui-Sun** [comment]
试了一下好像没能复现这个问题，https://codesandbox.io/p/sandbox/vtable-scroll-y2mjt2 这里写了一个滚动的demo，红框区域(canvas)外松开鼠标也可以终止滚动操作。可以提供一下能复现这个问题的环境吗？

**Comment by fangsmile** [comment]
长时间未回复  后续如果还有问题 请再开启 @TryChai
