### ISSUE TITLE
[Feature] checkbox 的值能不能放到事件里面

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#630]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/30064871/75c212b7-dc25-4f59-915d-5be09d0fd7b3)
为啥不把 值放进 事件里面 像originData 都能拿到当前的列 为啥还要 我再处理筛选一遍 

### What does the proposed API look like?

期待把这些事件属性都放进去 ，能够更方便一点 ，自己处理一遍实属没必要

**Comment by TryChai** [comment]
![image](https://github.com/VisActor/VTable/assets/30064871/dac3f0fa-501b-43b9-bb61-354241b0c74d)
你这个不太合理 怎么把空当key 我要怎么获取 在里面用for of 吗

**Comment by nikoohp** [comment]
`args.target.attribute.checked`  这个也行吧

**Comment by fangsmile** [comment]
@TryChai 可以描述下具体使用场景吗？我们了解下业务场景。
如果需要check的值 我们后面加个接口 getCellCheckboxState(col: number, row: number) 来自行获取吧。
另外checkbox有事件  CHECKBOX_STATE_CHANGE

**Comment by fangsmile** [comment]
@TryChai 那CHECKBOX_STATE_CHANGE比较适合呢 如果其他时机的话 可以使用getCellCheckboxState(col: number, row: number)  下个版本会带上这个接口 本周发

**Comment by TryChai** [comment]
如果是那种 需要勾选了才显示的场景 也要拿到当前的状态吧 你把状态放进事件 也比较好处理吧

**Comment by fangsmile** [comment]
我们目前不倾向往事件中加入太多信息（大家需求不一样 需要的信息各异  我们会提供充分的接口）  用接口按需取吧
