### ISSUE TITLE
[Bug] 使用update 会有很多的问题

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#633]
### Version

0.15.0

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

改变columns，或者records updateOpion

### Current Behavior

目前我发现的问题
1、滚动 会有bug ,滚到底部再往回滚 会卡顿 整个canvas 卡住 只有右边的 边框会动
2、更新数据之后 那些选项 会有问题 比如边框线啥的

### Expected Behavior

希望滚动正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by TryChai** [comment]
左右滑动滚动条的时候 也一卡一卡的，
如果点击了冻结的icon，updateOption 之后 滚动的时候 canvas 就只有部分滚动

**Comment by Rui-Sun** [comment]
能提供一下updateOption前后的option吗？

**Comment by orionna319** [comment]
VTable version: 1.8.4
Chrome version: 120.0.6099.234 (正式版本) (arm64) 
设备：macOS Ventura 13.0.1

我这边也是，updateColumns之后，鼠标滚动很卡，只有拖动滚动条才不卡。尝试了很久在codesandbox复现，复现不出来，以下是我使用vue3的基础代码。
```js
import { onMounted, ref, onUnmounted } from 'vue'

const listTableRef = ref()
const listTable = ref(null)

const option = {
  records: [],
  columns: [],
  widthMode: 'adaptive',
  keyboardOptions: {
    moveEditCellOnArrowKeys: true,
    copySelected: true,
    pasteValueToCell: true
  }
}

const getTableData = async () => {
  const { data, errorCode, header } = await asyncFunc()
  if (errorCode === 0 && Array.isArray(data)) {
    listTable.value.updateColumns(header)
    listTable.value.setRecords(data)
  } else {
    listTable.value.updateColumns([])
    listTable.value.setRecords([])
  }
}

onMounted(() => {
  listTable.value = new ListTable(listTableRef.value, option)
})

onUnmounted(() => {
  listTable.value = null
})
```
