### ISSUE TITLE
[Bug] 右侧固定列后，行 hover 时背景色不一致

### ISSUE THREAD

**Issue by nikoohp** [VisActor/VTable#645]
### Version

 0.15.1

### Link to Minimal Reproduction

.

### Steps to Reproduce

。

### Current Behavior

右侧固定列后，行 hover 时背景色不一致

### Expected Behavior

右侧固定列后，行 hover 时背景色保持一致

### Environment

```markdown
- OS: macOS 14.1.1
- Browser: Chrome 119.0.6045.159
- Framework: React@18.2.0
```

**Comment by Rui-Sun** [comment]
我这边试了一下，好像没有复现这个问题，我写了一个小例子，能参考修改出一个能复现的环境吗

**Comment by Rui-Sun** [comment]
![image](https://github.com/VisActor/VTable/assets/25134429/99127d5d-fa57-4fb6-bb56-cc5797101a0f)
https://codesandbox.io/p/sandbox/vtable-right-frozen-hover-sq8h5r?file=%2Fsrc%2Findex.ts%3A18%2C39

**Comment by nikoohp** [comment]
@Rui-Sun  ` VTable.themes.ARCO `是这个主题的问题
