### ISSUE TITLE
[Feature] 希望编辑表格支持键盘事件上下左右、entry、tab 等方便快速编辑数据

### ISSUE THREAD

**Issue by charlesmiao** [VisActor/VTable#646]
### What problem does this feature solve?

希望编辑表格支持键盘事件上下左右、entry、tab 等方便快速编辑数据，焦点移动到下一个单元格可继续编辑

### What does the proposed API look like?

option中配置一个启用停用事件即可

**Comment by fangsmile** [comment]
0.17.1 ，12/20发布
