### ISSUE TITLE
[Feature] 希望编辑表格支持表格数据复制到剪贴板、excel。从剪贴板、excel中复制数据到编辑表格中，便于批量填报数据

### ISSUE THREAD

**Issue by charlesmiao** [VisActor/VTable#647]
### What problem does this feature solve?

希望编辑表格支持表格数据复制到剪贴板、excel。从剪贴板、excel中复制数据到编辑表格中，便于批量填报数据。 选择区域 右键复制粘贴，或ctrl+c/v。 但只读单元格禁止覆盖数据。

### What does the proposed API look like?

建议设置成组件默认功能，option中可以配置

**Comment by fangsmile** [comment]
已支持复制  如果有其他问题 可以新提个issue
