### ISSUE TITLE
[Feature]  数据汇总小计总计行列位置的配置

### ISSUE THREAD

**Issue by semmywong** [VisActor/VTable#650]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/67748948/16838dc1-8ba6-4ae6-b507-ffdf61f2138d)

数据汇总小计总计，目前是自动放置在最后一行或最后一列，是否可以通过配置参数可以放置到第N行或第N列（常用是第一行或最后一行，第一列或最后一列）

### What does the proposed API look like?

- 新增position配置项
```js
export interface Total {
  // 是否显示总计
  showGrandTotals: boolean;
  // 是否显示小计
  showSubTotals: boolean;
  // 小计汇总维度定义
  subTotalsDimensions?: string[];
  // 默认'总计'
  grandTotalLabel?: string;
  // 默认'小计'
  subTotalLabel?: string;
 // TODO:放置位置
 position?: number | 'first' | 'last';
}
```

**Comment by fangsmile** [comment]
0.17.0 will publish

**Comment by fangsmile** [comment]
showGrandTotalOnTop
showSubTotalOnTop
