### ISSUE TITLE
[Feature] listtable支持数据分组

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#672]
### What problem does this feature solve?

根据某些列队数据进行分组显示

### What does the proposed API look like?

添加类似属性：group

效果类似于下图：
![image](https://github.com/VisActor/VTable/assets/51039208/7ce8e803-9991-4481-b130-a07ddf661cfc)
分组标题是根据第二列把相同的值整合在一起的

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/table-type/list-table-group
分组功能可以参考这个demo。
如果有其他需求 可以提issue
