### ISSUE TITLE
请问progressbar类型的barPositiveColor如何正确配置CanvasGradient颜色让柱图产生渐变效果

### ISSUE THREAD

**Issue by cow-Rong** [VisActor/VTable#673]
请问progressbar类型的barPositiveColor如何正确配置CanvasGradient颜色让柱图产生渐变效果
以下是配置代码片段，但是不生效：
请问有大佬知道如何设置CanvasGradient类型的样式能生效吗？
{
        cellType: 'progressbar',
        min,
        max,
        style: {
          barHeight: '80%',
          textAlign: 'right',
          barPositiveColor(args) {
            const { col, row, percentile, table } = args;
            const { internalProps } = table;
            const { context } = internalProps;
            const { left, top, right, bottom } = listTable.getCellRect(
              col,
              row
            );
              const barPositiveColor = context.createLinearGradient(
                left,
                top,
                right,
                bottom
              );
              barPositiveColor.addColorStop(0, positiveColor);
              barPositiveColor.addColorStop(1, 'white');
              console.log(barPositiveColor);
              return barPositiveColor;
           
          },
          barNegativeColor(args) {
            const { col, row, percentile, table } = args;
            const { internalProps } = table;
            const { context } = internalProps;
            const { left, top, right, bottom } = listTable.getCellRect(
              col,
              row
            );
              const barNegativeColor = context.createLinearGradient(
                left,
                top,
                right,
                bottom
              );
              barNegativeColor.addColorStop(0, negativeColor);
              barNegativeColor.addColorStop(1, 'white');
              return barNegativeColor;
        
          },
          barAxisColor: axisColor,
          barRightToLeft: direction === 'rightToleft',
          barBottom: '10%',
        },
      }

**Comment by fangsmile** [comment]
@cow-Rong 
barColor 写法 参考一下：
```
style: {
      color: 'red',
      barHeight: 6,
      barColor: {
                gradient: 'linear',
                x0: 0,
                y0: 0,
                x1: 1,
                y1: 0,
                stops: [
                  {
                    offset: 0,
                    color: 'red'
                  },
                  {
                    offset: 1,
                    color: 'green'
                  }
                ]
              },
      barRightToLeft: true
    }
```
