### ISSUE TITLE
Vtable渲染数据支持带样式导出到Excel

### ISSUE THREAD

**Issue by JasonZhuAtamation** [VisActor/VTable#682]
### What problem does this feature solve?

由于之前项目中使用了table2Excel，所以现在用VTable渲染表格也希望把table2Excel的功能迁移过来

### What does the proposed API look like?

希望VTable支持相关API可以带样式导出到Excel

**Comment by xiaofeihe** [comment]
这个 需求我 之前提出过，应该还在排队。

**Comment by fangsmile** [comment]
0.17.0将发布支持 12月15日 请关注

**Comment by JasonZhuAtamation** [comment]
好的，非常感谢

**Comment by xc2020-create** [comment]
请问下，vtable导出的树形表格，折叠行是图片以及导出的样式没有中划线这个怎么解决呢
![image](https://github.com/user-attachments/assets/957e84ce-04e7-4a1a-8d17-ebfad1ed2cb2)
