### ISSUE TITLE
theme.headerStyle.padding 不生效

### ISSUE THREAD

**Issue by youngwinds** [VisActor/VTable#684]
![Image](https://github.com/VisActor/VTable/assets/49136199/90a9b65d-3c10-49e0-b88c-13f99ffe5a57)

**Comment by Rui-Sun** [comment]
这里因为没有配置autoHeight，并且默认textBaseline是middle，所以文字在纵向会在单元格的默认高度上居中显示，纵向表现出来是没有padding效果；如果需要纵向padding撑开，可以配置heightMode: 'autoHeight'
