### ISSUE TITLE
[Bug] [0.15.4没彻底解决]div父元素的display:none时渲染出来的canvas只有一行数据

### ISSUE THREAD

**Issue by Nyx2022** [VisActor/VTable#693]
### Version

0.15.4

### Link to Minimal Reproduction

无

### Steps to Reproduce

https://github.com/VisActor/VTable/issues/668
这个只修复了一半
![image](https://github.com/VisActor/VTable/assets/51039208/10ddb8ed-1ebf-4e7b-8637-1ec3568c5d2a)

现在的情况是，canvas确实有div那么大了，但是数据还是只有一行

### Current Behavior

只显示一行数据

### Expected Behavior

canvas中的主体数据铺满整个canvas，而不只是canvas铺满整个div

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
这个问题修复的代码合并时有问题，恢复了一下，可以试一下0.16.1版本
