### ISSUE TITLE
[Feature] 增加对图元本身样式的设置方案

### ISSUE THREAD

**Issue by Kento97** [VisActor/VTable#701]
### What problem does this feature solve?

可以解决目前无法对图元进行样式以及鼠标交互的设置

### What does the proposed API look like?

在图元身上有对应的配置项或者自定义渲染方法

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo/custom-render/custom-cell-layout-jsx
https://visactor.io/vtable/demo-react/custom-layout/cell-custom-component
可以参考示例，如果有其他问题 可以新提个issue
