### ISSUE TITLE
[Bug] react simple example report error

### ISSUE THREAD

**Issue by GoldSubmarine** [VisActor/VTable#707]
### Version

0.16.1

### Link to Minimal Reproduction

[codesandbox](https://codesandbox.io/p/sandbox/react-vtable-wjrvpq?file=%2Fpackage.json%3A11%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq18loz00006356s363r40fa%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq18loz00002356swa93979c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq18loz00003356sxvy2neku%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq18lp2o000i356sq64nk849%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq18loz00005356sdpmlx3nr%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq18loz00002356swa93979c%2522%253A%257B%2522id%2522%253A%2522clq18loz00002356swa93979c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq18na7o006p356swl3p2lf4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq18na7o006p356swl3p2lf4%2522%257D%252C%2522clq18loz00005356sdpmlx3nr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq18loz00004356sca7cqbti%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq18loz00005356sdpmlx3nr%2522%252C%2522activeTabId%2522%253A%2522clq18loz00004356sca7cqbti%2522%257D%252C%2522clq18loz00003356sxvy2neku%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq18loz00003356sxvy2neku%2522%257D%252C%2522clq18lp2o000i356sq64nk849%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clq18lp2o000i356sq64nk849%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

![image](https://github.com/VisActor/VTable/assets/22909744/6e60b10a-9567-456e-bdf6-bbda289653db)

上述codesandbox链接在`0.15.0-alpha.3`版本下可用，升级到0.16.1后报错

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/22909744/1e1f050c-d725-4c21-8f21-1253a10e23ff)

### Expected Behavior

.

### Environment

```markdown
- OS:Windows 11
- Browser: Chrome
- Framework: React
```

**Comment by Rui-Sun** [comment]
这个是我们的用户写的有问题，更新了一下用例就可以了
![image](https://github.com/VisActor/VTable/assets/25134429/95a98a3a-258d-4fca-81e0-932d34419e6f)

**Comment by hungtcs** [comment]
我这里也有这个错误，使用 vite 开发模式下，每次修改代码之后都会有上面的报错，刷新页面又恢复正常。
