### ISSUE TITLE
[Bug] 透视表修改内容 ，失焦后内容未改

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#708]
### Version

0.16.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/test-editor-tz4948?file=%2Fsrc%2FApp.js%3A10%2C22

### Steps to Reproduce

点击 修改内容

### Current Behavior

失焦后内容 恢复原值 再次点击 输入框是改过的值 但是 失焦之后还是原始值 一直未改
![81c38b185018f9068606cf65a307209](https://github.com/VisActor/VTable/assets/30064871/4aa7db57-345a-4741-b2ec-4ce76642146c)

### Expected Behavior

点击之后修改 原始值

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by TryChai** [comment]
是自定义 rowTree 跟format 冲突的问题 记得修复下

**Comment by TryChai** [comment]
![image](https://github.com/VisActor/VTable/assets/30064871/1f7854fd-1589-467f-b648-9c03f4a6f031)
数据好像不准确 这个2次都取最后一个

**Comment by fangsmile** [comment]
0.16.2 will publish
