### ISSUE TITLE
[Bug] 透视表 没有默认数据的时候编辑没生效

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#712]
### Version

0.16.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/test-editor-tz4948?file=%2Fsrc%2FApp.js%3A10%2C22

### Steps to Reproduce

透视表 没有 rowTree 开启了enableDataAnalysis（如果不开启这个 就不渲染）编辑的时候 本身没有数据的时候 

### Current Behavior

失焦 就空白 没有数据 ，拿不到当前行的数据 

### Expected Behavior

这时候 应该怎么处理

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by TryChai** [comment]
![image](https://github.com/VisActor/VTable/assets/30064871/d5f2ca49-4503-4dbf-aec7-157f8274e4c0)
如果不开启 enableDataAnalysis  就报错 ，开启了 就合并了数据 合并了 我又不好修改

**Comment by fangsmile** [comment]
0.16.2 will publish
