### ISSUE TITLE
[Bug] 透视表 使用changeCellValue 更新数据 陷入死循环

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#713]
### Version

0.16.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/test-editor-tz4948?file=%2Fsrc%2FApp.js%3A10%2C22

### Steps to Reproduce

使用changeCellValue 更新 之前没有的数据 

### Current Behavior

会陷入死循环

### Expected Behavior

直接修改 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
changeCellValue这个接口本身就会触发change_cell_value事件
所以事件中不要再调用接口changeCellValue了
