### ISSUE TITLE
[Bug] 行数较多树状表格在画布高度较低时部分行没有渲染出来

### ISSUE THREAD

**Issue by chilen-z** [VisActor/VTable#723]
### Version

0.16.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-renderbug-yt2s98

### Steps to Reproduce

向下滚动竖向滚动条

### Current Behavior

行数较多树状表格在画布高度较低时部分行没有渲染出来

### Expected Behavior

行数较多树状表格在画布高度较低时正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
这如果希望初始展开全部层级，可以使用option中的hierarchyExpandLevel配置；这里手动多次调用toggleHierarchyState可能导致异步任务问题，进而导致没有正确加载，这个问题我们修复一下

**Comment by chilen-z** [comment]
通过一个字段在控制是否展开树，可能不会展开全部层级

**Comment by Rui-Sun** [comment]
`hierarchyExpandLevel: Infinity`可以展开全部层级

> 通过一个字段在控制是否展开树，可能不会展开全部层级
