### ISSUE TITLE
[Bug] 下拉框 聚焦之后 点击外面 （table 以外）不会失焦

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#727]
### Version

0.16.1

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/component/dropdown

### Steps to Reproduce

点击下拉dropdown
再点击table 之外的地方

### Current Behavior

选项还存在

### Expected Behavior

失焦

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
0.17.0
