### ISSUE TITLE
[Feature] 希望拖拽列不能被拖拽到冻结列，或者拖拽到冻结列时冻结列数增多一列

### ISSUE THREAD

**Issue by Jacoulin** [VisActor/VTable#754]
### What problem does this feature solve?

拖动前：
<img width="966" alt="image" src="https://github.com/VisActor/VTable/assets/22957376/e52b028c-00b6-4da5-9d2c-b13d1f3d5cf5">
拖动后：
<img width="941" alt="image" src="https://github.com/VisActor/VTable/assets/22957376/c4cf3d35-89fc-4c48-afc1-0ddb59811a52">

如图，第1列是冻结列，目前的情况是可以拖拽到冻结列，但是冻结列原先的阴影样式没有改变，冻结列原1 -> 原2，冻结列还是只有1列

### What does the proposed API look like?

希望增加配置项：
1.其他列支持表头拖动时，但不能拖拽到冻结列位置
2.其他列支持表头拖动时，允许拖拽到冻结列位置的情况下，冻结列也跟着调整，比如这里应该是，冻结列原1 -> 原2｜原1，冻结列变成2列

**Comment by fangsmile** [comment]
我们考虑下这个

**Comment by fangsmile** [comment]
0.19.0已支持相关配置
