### ISSUE TITLE
[Question] How to add timeline to play a schedule data using vtable

### ISSUE THREAD

**Issue by zairl23** [VisActor/VTable#755]
Just find the schedule example using vtable: https://visactor.io/vtable/demo/business/project-schedule, now i want to add a timeline to play the schedule, and the table can scroll in a certain frequence, how to achieve this target?

**Comment by fangsmile** [comment]
use api:
setScrollLeft
or
scrollToCell(cellAddr: { col?: number; row?: number })=>void
@zairl23

**Comment by zairl23** [comment]
Thank you! Another question: is there the api to draw a vertical red lines in the vtable which can move by following scrollToCell api call。 @fangsmile

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/754b78c2-cb3e-43d6-a0f5-36a93569022b)
可以自定义渲染

args.table.getSelectedCellInfos()  获取选中状态  判断后确定自定义渲染元素应该什么

**Comment by zairl23** [comment]
can draw this vertical line using cusomRenderer ?
![image](https://github.com/VisActor/VTable/assets/542486/644c97b3-a751-42bc-9a91-4e9089fe6895)

**Comment by fangsmile** [comment]
滚动好搞，示例后面加这么一段话：
```
let animationId;
let scrollX=0;
let t = Date.now();
function animate() {
  console.log('animate')
  // 更新动画的逻辑代码
  const t1 = Date.now();
  if (scrollX>=tableInstance.getAllColsWidth()) {
    console.log('cancelAnimationFrame');
    cancelAnimationFrame(animationId);
    return;
  }
  if(t1-t>=30){
    t=t1;
    tableInstance.setScrollLeft(scrollX);
    scrollX+=3;
  }
  // 执行动画播放
  animationId = requestAnimationFrame(animate);
}

// 开始动画播放
animationId = requestAnimationFrame(animate);
```

不过如果支持那条竖线需要写自定义函数了。可以加我们的飞书交流群找我进行具体业务场景的交流
![飞书群](https://github.com/VisActor/VTable/assets/3468473/16193439-8f99-4af3-8d6e-7ff281a4c438)
@zairl23
