### ISSUE TITLE
[Bug] 双击空白的地方报错

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#758]
### Version

0.17.0

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

当列表的高度很高 ，数据没有完全填满的时候

### Current Behavior

双击 canvas 元素 会报错
![image](https://github.com/VisActor/VTable/assets/30064871/3abfba83-c13a-4440-840a-227bce77080c)
![动画](https://github.com/VisActor/VTable/assets/30064871/847f1c02-9a9a-4d0d-b2cf-be9464ed5978)

### Expected Behavior

希望 双击不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
ok  我们尽快修下

**Comment by fangsmile** [comment]
fix 0.17.1 今晚发
