### ISSUE TITLE
[Bug] 升级到0.17.0 之后 监听不到dropdown_menu_click事件

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#760]
### Version

0.17.0

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

点击 dropdown_menu_click 

### Current Behavior

没有打印 没有效果
![image](https://github.com/VisActor/VTable/assets/30064871/94326e9e-4f33-49ba-87be-81ea34ad21b0)
![动画](https://github.com/VisActor/VTable/assets/30064871/8edc9192-5f47-4eae-a813-6745dfcf5138)

### Expected Behavior

正常使用

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by TryChai** [comment]
![image](https://github.com/VisActor/VTable/assets/30064871/75a144c2-c02f-4a13-b2f8-6df4506358e7)

**Comment by TryChai** [comment]
![动画](https://github.com/VisActor/VTable/assets/30064871/1bd5ab18-83c6-46db-895d-f043d0be6e1f)
改到0.16.1功能是正常的 
说明 0.17.0 这个版本 有问题

**Comment by fangsmile** [comment]
fix 0.17.1 今晚发
