### ISSUE TITLE
[Bug] PivotChart在拖拽画布大小时，卡顿问题

### ISSUE THREAD

**Issue by zzsssssss** [VisActor/VTable#768]
### Version

0.16.4-alpha.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-bug-report-forked-4vwlly?file=%2Fsrc%2Findex.ts

### Steps to Reproduce

1.数据量8800条情况下，拖拽画布大小 ，或窗口大小

### Current Behavior

页面卡顿 

### Expected Behavior

页面不卡顿，拖拽大小时 不卡顿

### Environment

```markdown
- OS:window
- Browser: Chrome 120.0.6099.110（正式版本）
- Framework: Vue@3
```

**Comment by Rui-Sun** [comment]
fixed by 0.17.9-alpha.8
