### ISSUE TITLE
[Bug] 数据量大滚动会卡顿

### ISSUE THREAD

**Issue by since911** [VisActor/VTable#772]
### Version

0.16.0

### Link to Minimal Reproduction

暂无

### Steps to Reproduce

数据量超过1000条，列字段超过80个，包含多级表头

### Current Behavior

数据量大滚动会卡顿，mac上快速滑动鼠标后停止滚动，页面滚动未立即停止

### Expected Behavior

希望能优化大数据量 滚动卡顿问题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
能提供一下复现环境吗？
