### ISSUE TITLE
[Bug] frozenColCount 从 0 改变为 1 时，column 的选中状态未清除彻底

### ISSUE THREAD

**Issue by aMoonkin** [VisActor/VTable#777]
### Version

0.17.1

### Link to Minimal Reproduction
https://codesandbox.io/p/sandbox/vtable-simple-demo-forked-lm25ny?file=%2Fsrc%2Findex.ts

### Steps to Reproduce

1. 点击表格头，选中第一列
![image](https://github.com/VisActor/VTable/assets/35296199/9441e6a9-accd-4434-ab4f-406f2197c239)
2. 点击 Click Me!，修改 frozenColCount

### Current Behavior

有竖线残留
![image](https://github.com/VisActor/VTable/assets/35296199/3fe8d9ac-2361-4019-8b1c-afc7a4332777)

### Expected Behavior

1. 没有竖线，如果选中列已经变化为其他列
2. 该列被选中，如果选中列依然为原列

**Comment by fangsmile** [comment]
收到
