### ISSUE TITLE
[Feature] columnResize旁边的小tip可以设置color和bgColor

### ISSUE THREAD

**Issue by semmywong** [VisActor/VTable#781]
### What problem does this feature solve?

期望，columnResize旁边的宽度小tip可以设置color和bgColor，如图
![img_v3_026b_eda03cdc-914d-4edd-b583-fd730d866b9g](https://github.com/VisActor/VTable/assets/67748948/9b457bd9-65a6-41cf-a9df-fd73511252cc)

### What does the proposed API look like?

期望增加两个属性配置：
ListTable.theme.columnResize.tip.color
ListTable.theme.columnResize.tip.bgColor

**Comment by fangsmile** [comment]
收到
