### ISSUE TITLE
[Bug] 透视表没数据的时候跟有数据的时候表头表现不一致 贼丑

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#782]
### Version

0.16.1

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

透视表

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/30064871/c330231d-e7f6-4187-87fc-7b71cdf86262)
有数据看着还行 
没数据 就很丑
![image](https://github.com/VisActor/VTable/assets/30064871/3251618f-f6b9-4354-9499-c9dfc36e2412)

### Expected Behavior

表头一致 不要出现 只有一部分表头 
body 部分没有就空着

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
把具体option贴一下  还有records

**Comment by TryChai** [comment]
`{
    "rows": [
        {
            "dimensionKey": "Time",
            "title": "时间段",
            "headerStyle": {
                "textStick": true,
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "textStyle": {
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "width": "auto"
        },
        {
            "dimensionKey": "taskCount",
            "title": "任务数",
            "headerStyle": {
                "textStick": true,
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "textStyle": {
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "width": "auto"
        },
        {
            "dimensionKey": "complateCount",
            "title": "完成数",
            "headerStyle": {
                "textStick": true,
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "textStyle": {
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            },
            "width": "auto"
        }
    ],
    "columns": [
        {
            "dimensionKey": "Group",
            "title": "Group",
            "headerStyle": {
                "textStick": true,
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 13,
                "borderColor": "#ebeef5"
            },
            "width": "auto"
        }
    ],
    "corner": {
        "titleOnDimension": "row",
        "headerStyle": {
            "textStick": true,
            "bgColor": "#fff",
            "color": "#606266",
            "fontSize": 14,
            "borderColor": "#ebeef5",
            "autoWrapText": true
        },
        "textStyle": {
            "bgColor": "#fff",
            "color": "#606266",
            "fontSize": 14,
            "borderColor": "#ebeef5"
        }
    },
    "indicators": [
        {
            "indicatorKey": "coefficient",
            "title": "系数",
            "sort": false,
            "maxWidth": "450",
            "width": "auto",
            "headerStyle": {
                "bgColor": "#f5f7fa",
                "color": "#909399",
                "fontSize": 14,
                "fontWeight": 900,
                "borderColor": "#ebeef5"
            },
            "style": {
                "bgColor": "#fff",
                "color": "#606266",
                "fontSize": 14,
                "borderColor": "#ebeef5"
            }
        }
    ],
    "records": [
        {
            "adjustPricePlanId": "1730110490888118277",
            "campId": "17",
            "roomCategoryClusterId": "1725420560616787970",
            "planDate": "2023-11-30",
            "planTime": "2023-11-30 14:20:00",
            "coefficient": 70,
            "day": 0,
            "state": 2,
            "taskCount": 20,
            "complateCount": 20,
            "adjustPriceTemplateId": "0",
            "Group": "测试房源分组1",
            "Time": " 14:20"
        },
        {
            "adjustPricePlanId": "1730110490888118278",
            "campId": "17",
            "roomCategoryClusterId": "1725421011508662274",
            "planDate": "2023-11-30",
            "planTime": "2023-11-30 14:20:00",
            "coefficient": 75,
            "day": 0,
            "state": 2,
            "taskCount": 20,
            "complateCount": 20,
            "adjustPriceTemplateId": "0",
            "Group": "测试房源分组2",
            "Time": " 14:20"
        },
        {
            "adjustPricePlanId": "1730110490888118273",
            "campId": "17",
            "roomCategoryClusterId": "1725420560616787970",
            "planDate": "2023-11-30",
            "planTime": "2023-11-30 16:30:00",
            "coefficient": 90,
            "day": 0,
            "state": 2,
            "taskCount": 20,
            "complateCount": 20,
            "adjustPriceTemplateId": "0",
            "Group": "测试房源分组1",
            "Time": " 16:30"
        },
        {
            "adjustPricePlanId": "1730110490888118274",
            "campId": "17",
            "roomCategoryClusterId": "1725421011508662274",
            "planDate": "2023-11-30",
            "planTime": "2023-11-30 16:30:00",
            "coefficient": 90,
            "day": 0,
            "state": 2,
            "taskCount": 20,
            "complateCount": 20,
            "adjustPriceTemplateId": "0",
            "Group": "测试房源分组2",
            "Time": " 16:30"
        }
    ],
    "widthMode": "autoWidth",
    "frozenColCount": 3,
    "rightFrozenColCount": 0,
    "autoWrapText": true,
    "heightMode": "autoHeight",
    "select": {
        "disableSelect": 1
    },
    "hover": {
        "highlightMode": "row"
    },
    "allowFrozenColCount": 3,
    "showFrozenIcon": false,
    "columnResizeMode": "none",
    "autoFillWidth": true,
    "theme": {
        "_defaultStyle": {
            "fontSize": 16,
            "fontFamily": "Arial,sans-serif",
            "bgColor": "#ECF1F5",
            "color": "#000",
            "borderColor": "#E1E4E8",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "padding": [
                10,
                16,
                10,
                16
            ],
            "textAlign": "left",
            "textBaseline": "middle",
            "textOverflow": "ellipsis",
            "autoWrapText": false,
            "lineClamp": "auto",
            "linkColor": "#3772ff",
            "cursor": "auto",
            "marked": false,
            "underline": false,
            "lineThrough": false
        },
        "_header": {
            "fontSize": 16,
            "fontFamily": "Arial,sans-serif",
            "fontWeight": "bold",
            "bgColor": "#ECF1F5",
            "color": "#000",
            "borderColor": "#E1E4E8",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "hover": {
                "cellBgColor": "#CCE0FF",
                "inlineColumnBgColor": "#F3F8FF",
                "inlineRowBgColor": "#F3F8FF"
            },
            "padding": [
                10,
                16,
                10,
                16
            ],
            "textAlign": "left",
            "textBaseline": "middle",
            "textOverflow": "ellipsis",
            "autoWrapText": false,
            "lineClamp": "auto",
            "linkColor": "#3772ff",
            "cursor": "auto",
            "marked": false,
            "underline": false,
            "lineThrough": false
        },
        "_cornerHeader": {
            "fontSize": 16,
            "fontFamily": "Arial,sans-serif",
            "fontWeight": "bold",
            "bgColor": "#ECF1F5",
            "color": "#000",
            "borderColor": "#E1E4E8",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "padding": [
                10,
                16,
                10,
                16
            ],
            "textAlign": "left",
            "textBaseline": "middle",
            "textOverflow": "ellipsis",
            "autoWrapText": false,
            "lineClamp": "auto",
            "linkColor": "#3772ff",
            "cursor": "auto",
            "marked": false,
            "underline": false,
            "lineThrough": false
        },
        "_cornerRightTopCell": null,
        "_cornerLeftBottomCell": null,
        "_cornerRightBottomCell": null,
        "_rightFrozen": null,
        "_bottomFrozen": null,
        "_rowHeader": {
            "fontSize": 16,
            "fontFamily": "Arial,sans-serif",
            "fontWeight": "bold",
            "bgColor": "#ECF1F5",
            "color": "#000",
            "borderColor": "#E1E4E8",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "hover": {
                "cellBgColor": "#CCE0FF",
                "inlineColumnBgColor": "#F3F8FF",
                "inlineRowBgColor": "#F3F8FF"
            },
            "padding": [
                10,
                16,
                10,
                16
            ],
            "textAlign": "left",
            "textBaseline": "middle",
            "textOverflow": "ellipsis",
            "autoWrapText": false,
            "lineClamp": "auto",
            "linkColor": "#3772ff",
            "cursor": "auto",
            "marked": false,
            "underline": false,
            "lineThrough": false
        },
        "_body": {
            "fontSize": 14,
            "fontFamily": "Arial,sans-serif",
            "color": "#000",
            "borderColor": "#E1E4E8",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "hover": {
                "cellBgColor": "#CCE0FF",
                "inlineColumnBgColor": "#F3F8FF",
                "inlineRowBgColor": "#F3F8FF"
            },
            "padding": [
                10,
                16,
                10,
                16
            ],
            "textAlign": "left",
            "textBaseline": "middle",
            "textOverflow": "ellipsis",
            "autoWrapText": false,
            "lineClamp": "auto",
            "linkColor": "#3772ff",
            "cursor": "auto",
            "marked": false,
            "underline": false,
            "lineThrough": false
        },
        "_scroll": {
            "scrollSliderColor": "#C0C0C0",
            "visible": "scrolling",
            "width": 7,
            "hoverOn": true
        },
        "_tooltip": null,
        "_frameStyle": {
            "borderColor": "#ebeef5",
            "borderLineWidth": 1,
            "borderLineDash": [],
            "shadowBlur": 0,
            "shadowColor": "black",
            "shadowOffsetX": 0,
            "shadowOffsetY": 0,
            "cornerRadius": 0
        },
        "_columnResize": {
            "lineColor": "#416EFF",
            "bgColor": "#D9E2FF",
            "lineWidth": 1,
            "width": 3
        },
        "_dragHeaderSplitLine": {
            "lineColor": "blue",
            "lineWidth": 2,
            "shadowBlockColor": "rgba(204,204,204,0.3)"
        },
        "_frozenColumnLine": {
            "shadow": {
                "width": 3,
                "startColor": "rgba(225, 228, 232, 0.6)",
                "endColor": "rgba(225, 228, 232, 0.6)"
            }
        },
        "_selectionStyle": null,
        "_axisStyle": null,
        "internalTheme": {
            "obj": {
                "frameStyle": {
                    "borderColor": "#ebeef5"
                }
            },
            "superTheme": {
                "_defaultStyle": {
                    "fontSize": 16,
                    "fontFamily": "Arial,sans-serif",
                    "bgColor": "#ECF1F5",
                    "color": "#000",
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "padding": [
                        10,
                        16,
                        10,
                        16
                    ],
                    "textAlign": "left",
                    "textBaseline": "middle",
                    "textOverflow": "ellipsis",
                    "autoWrapText": false,
                    "lineClamp": "auto",
                    "linkColor": "#3772ff",
                    "cursor": "auto",
                    "marked": false,
                    "underline": false,
                    "lineThrough": false
                },
                "_header": {
                    "fontSize": 16,
                    "fontFamily": "Arial,sans-serif",
                    "fontWeight": "bold",
                    "bgColor": "#ECF1F5",
                    "color": "#000",
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "hover": {
                        "cellBgColor": "#CCE0FF",
                        "inlineColumnBgColor": "#F3F8FF",
                        "inlineRowBgColor": "#F3F8FF"
                    },
                    "padding": [
                        10,
                        16,
                        10,
                        16
                    ],
                    "textAlign": "left",
                    "textBaseline": "middle",
                    "textOverflow": "ellipsis",
                    "autoWrapText": false,
                    "lineClamp": "auto",
                    "linkColor": "#3772ff",
                    "cursor": "auto",
                    "marked": false,
                    "underline": false,
                    "lineThrough": false
                },
                "_cornerHeader": {
                    "fontSize": 16,
                    "fontFamily": "Arial,sans-serif",
                    "fontWeight": "bold",
                    "bgColor": "#ECF1F5",
                    "color": "#000",
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "padding": [
                        10,
                        16,
                        10,
                        16
                    ],
                    "textAlign": "left",
                    "textBaseline": "middle",
                    "textOverflow": "ellipsis",
                    "autoWrapText": false,
                    "lineClamp": "auto",
                    "linkColor": "#3772ff",
                    "cursor": "auto",
                    "marked": false,
                    "underline": false,
                    "lineThrough": false
                },
                "_cornerRightTopCell": null,
                "_cornerLeftBottomCell": null,
                "_cornerRightBottomCell": null,
                "_rightFrozen": null,
                "_bottomFrozen": null,
                "_rowHeader": {
                    "fontSize": 16,
                    "fontFamily": "Arial,sans-serif",
                    "fontWeight": "bold",
                    "bgColor": "#ECF1F5",
                    "color": "#000",
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "hover": {
                        "cellBgColor": "#CCE0FF",
                        "inlineColumnBgColor": "#F3F8FF",
                        "inlineRowBgColor": "#F3F8FF"
                    },
                    "padding": [
                        10,
                        16,
                        10,
                        16
                    ],
                    "textAlign": "left",
                    "textBaseline": "middle",
                    "textOverflow": "ellipsis",
                    "autoWrapText": false,
                    "lineClamp": "auto",
                    "linkColor": "#3772ff",
                    "cursor": "auto",
                    "marked": false,
                    "underline": false,
                    "lineThrough": false
                },
                "_body": {
                    "fontSize": 14,
                    "fontFamily": "Arial,sans-serif",
                    "color": "#000",
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "hover": {
                        "cellBgColor": "#CCE0FF",
                        "inlineColumnBgColor": "#F3F8FF",
                        "inlineRowBgColor": "#F3F8FF"
                    },
                    "padding": [
                        10,
                        16,
                        10,
                        16
                    ],
                    "textAlign": "left",
                    "textBaseline": "middle",
                    "textOverflow": "ellipsis",
                    "autoWrapText": false,
                    "lineClamp": "auto",
                    "linkColor": "#3772ff",
                    "cursor": "auto",
                    "marked": false,
                    "underline": false,
                    "lineThrough": false
                },
                "_scroll": {
                    "scrollSliderColor": "#C0C0C0",
                    "visible": "scrolling",
                    "width": 7,
                    "hoverOn": true
                },
                "_tooltip": null,
                "_frameStyle": {
                    "borderColor": "#E1E4E8",
                    "borderLineWidth": 1,
                    "borderLineDash": [],
                    "shadowBlur": 0,
                    "shadowColor": "black",
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "cornerRadius": 0
                },
                "_columnResize": {
                    "lineColor": "#416EFF",
                    "bgColor": "#D9E2FF",
                    "lineWidth": 1,
                    "width": 3
                },
                "_dragHeaderSplitLine": {
                    "lineColor": "blue",
                    "lineWidth": 2,
                    "shadowBlockColor": "rgba(204,204,204,0.3)"
                },
                "_frozenColumnLine": {
                    "shadow": {
                        "width": 3,
                        "startColor": "rgba(225, 228, 232, 0.6)",
                        "endColor": "rgba(225, 228, 232, 0.6)"
                    }
                },
                "_selectionStyle": null,
                "_axisStyle": null,
                "internalTheme": {
                    "obj": {
                        "underlayBackgroundColor": "#FFF",
                        "defaultStyle": {
                            "borderColor": "#E1E4E8",
                            "color": "#000",
                            "bgColor": "#ECF1F5"
                        },
                        "headerStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold",
                            "bgColor": "#ECF1F5",
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "rowHeaderStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold",
                            "bgColor": "#ECF1F5",
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "cornerHeaderStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold"
                        },
                        "bodyStyle": {
                            "fontSize": 14,
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "frameStyle": {
                            "borderColor": "#E1E4E8",
                            "borderLineWidth": 1,
                            "borderLineDash": [],
                            "cornerRadius": 0,
                            "shadowBlur": 0,
                            "shadowOffsetX": 0,
                            "shadowOffsetY": 0,
                            "shadowColor": "black"
                        },
                        "columnResize": {
                            "lineWidth": 1,
                            "lineColor": "#416EFF",
                            "bgColor": "#D9E2FF",
                            "width": 3
                        },
                        "frozenColumnLine": {
                            "shadow": {
                                "width": 3,
                                "startColor": "rgba(225, 228, 232, 0.6)",
                                "endColor": "rgba(225, 228, 232, 0.6)"
                            }
                        },
                        "selectionStyle": {
                            "cellBgColor": "rgba(0, 0, 255,0.1)",
                            "cellBorderLineWidth": 2,
                            "inlineColumnBgColor": "#CCE0FF",
                            "inlineRowBgColor": "#CCE0FF",
                            "cellBorderColor": "#0000ff"
                        }
                    },
                    "superTheme": {
                        "underlayBackgroundColor": "#FFF",
                        "defaultStyle": {
                            "borderColor": "#E1E4E8",
                            "color": "#000",
                            "bgColor": "#ECF1F5"
                        },
                        "headerStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold",
                            "bgColor": "#ECF1F5",
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "rowHeaderStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold",
                            "bgColor": "#ECF1F5",
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "cornerHeaderStyle": {
                            "fontSize": 16,
                            "fontWeight": "bold"
                        },
                        "bodyStyle": {
                            "fontSize": 14,
                            "hover": {
                                "cellBgColor": "#CCE0FF",
                                "inlineRowBgColor": "#F3F8FF",
                                "inlineColumnBgColor": "#F3F8FF"
                            }
                        },
                        "frameStyle": {
                            "borderColor": "#E1E4E8",
                            "borderLineWidth": 1,
                            "borderLineDash": [],
                            "cornerRadius": 0,
                            "shadowBlur": 0,
                            "shadowOffsetX": 0,
                            "shadowOffsetY": 0,
                            "shadowColor": "black"
                        },
                        "columnResize": {
                            "lineWidth": 1,
                            "lineColor": "#416EFF",
                            "bgColor": "#D9E2FF",
                            "width": 3
                        },
                        "frozenColumnLine": {
                            "shadow": {
                                "width": 3,
                                "startColor": "rgba(225, 228, 232, 0.6)",
                                "endColor": "rgba(225, 228, 232, 0.6)"
                            }
                        },
                        "selectionStyle": {
                            "cellBgColor": "rgba(0, 0, 255,0.1)",
                            "cellBorderLineWidth": 2,
                            "inlineColumnBgColor": "#CCE0FF",
                            "inlineRowBgColor": "#CCE0FF",
                            "cellBorderColor": "#0000ff"
                        }
                    }
                }
            }
        }
    },
    "container": {}
}`

**Comment by TryChai** [comment]
起码跟有数据时一样吧 不能没数据跟有数据表头不一致吧 而且 还少了几列  没有填满 看起来很奇怪

**Comment by fangsmile** [comment]
维度值是从records分析出来的   没有records就不会有表头树结构的
