### ISSUE TITLE
[Bug] widthMode: 'adaptive'在连续setRecords时拖动列宽计算错误

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#796]
### Version

0.17.2

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/basic-functionality/width-mode-adaptive

### Steps to Reproduce

https://visactor.io/vtable/demo/basic-functionality/width-mode-adaptive
let  tableInstance;
  fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/VTable/North_American_Superstore_data.json')
    .then((res) => res.json())
    .then((data) => {

const columns =[
    {
        "field": "Order ID",
        "title": "Order ID",
        "width": "auto"
    },
    {
        "field": "Customer ID",
        "title": "Customer ID",
        "width": "auto"
    },
    {
        "field": "Product Name",
        "title": "Product Name",
        "width": "auto"
    },
    {
        "field": "Category",
        "title": "Category",
        "width": "auto"
    },
    {
        "field": "Sub-Category",
        "title": "Sub-Category",
        "width": "auto"
    },
    {
        "field": "Region",
        "title": "Region",
        "width": "auto"
    },
    {
        "field": "City",
        "title": "City",
        "width": "auto"
    },
    {
        "field": "Order Date",
        "title": "Order Date",
        "width": "auto"
    },
    {
        "field": "Quantity",
        "title": "Quantity",
        "width": "auto"
    },
    {
        "field": "Sales",
        "title": "Sales",
        "width": "auto"
    },
    {
        "field": "Profit",
        "title": "Profit",
        "width": "auto"
    }
];

const option = {
  records:data,
  columns,
  widthMode: 'adaptive'
};
setInterval(()=>{
    tableInstance.setRecords(data)
},1000)
tableInstance = new VTable.ListTable(document.getElementById(CONTAINER_ID),option);
window['tableInstance'] = tableInstance;
    })

### Current Behavior

widthMode: 'adaptive'在连续setRecords时拖动列宽计算错误

### Expected Behavior

widthMode: 'adaptive'在连续setRecords时拖动列宽计算正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
连续setRecords时拖动列宽  这个交互过程是什么样子的呀
