### ISSUE TITLE
[Bug] 基础表格 按住鼠标 移动鼠标 报错

### ISSUE THREAD

**Issue by TryChai** [VisActor/VTable#799]
### Version

0.16.1

### Link to Minimal Reproduction

no link some picture

### Steps to Reproduce

基础表格 按住鼠标 移动鼠标 报错

### Current Behavior

基础表格 按住鼠标 移动鼠标 报错
![image](https://github.com/VisActor/VTable/assets/30064871/efe27fc3-85f0-42b9-aa45-67cea3cf7591)

### Expected Behavior

基础表格 按住鼠标 移动鼠标 不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by TryChai** [comment]
![Uploading 动画.gif…]()

**Comment by TryChai** [comment]
![动画](https://github.com/VisActor/VTable/assets/30064871/efd4d9fb-93ab-4317-bf59-aa0cd4e0da2e)

**Comment by fangsmile** [comment]
@TryChai 提供下复现环境呢？我这例子没有这个问题呢

**Comment by fangsmile** [comment]
disableSelect 开启后就报错了。明天发版本

**Comment by TryChai** [comment]
为什么 0.16.0 的版本不会
