### ISSUE TITLE
[Bug] 透视表整体设置边框圆角问题

### ISSUE THREAD

**Issue by InModeration** [VisActor/VTable#801]
### Version

0.17.2

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/style/style

### Steps to Reproduce

1. 打开上述官方的样例，选择SDK版本0.17.2
2. 在option中添加
```javascript
frameStyle: { cornerRadius: 20 }
``` 

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/41774233/8eb82e9d-ab0f-43c4-9c17-cd54e67b6390)
1. frame增加了圆角，但是其没有border，所以拐角处没有border
<img width="1608" alt="image" src="https://github.com/VisActor/VTable/assets/41774233/25ad4a34-3e31-4318-943a-d96fc3acc2f9">
2. frame如果加了border，此时会和其他的column、row、corner的border重叠

### Expected Behavior

能够实现透视表「有圆角」且「有边框」

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
没太明白 `frame如果加了border，此时会和其他的column、row、corner的border重叠`

**Comment by InModeration** [comment]
> 没太明白 `frame如果加了border，此时会和其他的column、row、corner的border重叠` ![image](https://private-user-images.githubusercontent.com/25134429/293651322-ad29a3ff-73ab-4485-94ba-dac17e637835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTc3NDksIm5iZiI6MTcwNDE5NzQ0OSwicGF0aCI6Ii8yNTEzNDQyOS8yOTM2NTEzMjItYWQyOWEzZmYtNzNhYi00NDg1LTk0YmEtZGFjMTdlNjM3ODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MmI0ZmI4NDM5NDcxN2MxZThjYzM2MzYwMWY0NmI0ZDZhZTQ2ZTNhY2JmMGFiZDBkOTZjODI2MmFmZDk0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cdEY0Vv0EV20-PmzYcK8K_AQFkpZGRQadlfEoVjqDU) frame border是在单元格的border外的，应该没有和单元格border重合

我的意思就是如果要实现整个表格有borderRadius，看起来需要给frame设置border才可以；但是如果frame加上了border，就与其他的border重复了。即我想实现这样的场景：
<img width="263" alt="image" src="https://github.com/VisActor/VTable/assets/41774233/72ed6113-1450-443f-b905-f428b744bc1e">

**Comment by Rui-Sun** [comment]
我明白了，需要支持一下单元格支持圆角，这个我们加一下
