### ISSUE TITLE
[Question] 默认tooltip样式可以修改吗

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#805]
![image](https://github.com/VisActor/VTable/assets/66556312/af3dfab5-f801-4f32-a544-98e5f132cf94)
这个默认tooltip样式可以改吗

**Comment by jickchen34** [comment]
![image](https://github.com/VisActor/VTable/assets/66556312/62a113c3-d057-41f0-8794-96631c48ebd6)
配置tooltipStyle好像无法生效

**Comment by fangsmile** [comment]
有bug  我们修复下
