### ISSUE TITLE
[Bug] Web Components  中 部分功能不正常

### ISSUE THREAD

**Issue by xiaofeihe** [VisActor/VTable#814]
### Version

0.17.2

### Link to Minimal Reproduction

 https://codesandbox.io/p/sandbox/vtable-bug-report-forked-y2lptd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqozula800072v6j8bfy8wla%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqozula700032v6jh1z4c8l8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqozula800042v6jr6sjpuie%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqozula800062v6j6o5dyz4j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqozula700032v6jh1z4c8l8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqozula700022v6jbqe6drzn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A57%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A57%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqozula700032v6jh1z4c8l8%2522%252C%2522activeTabId%2522%253A%2522clqozula700022v6jbqe6drzn%2522%257D%252C%2522clqozula800062v6j6o5dyz4j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqozula800052v6j4vhz4dyh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqozula800062v6j6o5dyz4j%2522%252C%2522activeTabId%2522%253A%2522clqozula800052v6j4vhz4dyh%2522%257D%252C%2522clqozula800042v6jr6sjpuie%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqozula800042v6jr6sjpuie%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

我们准备封装 Web Components  方便 使用，但封装后 鼠标放 表头 菜单 跑到 表的底部了 如下图
![image](https://github.com/VisActor/VTable/assets/1018509/cfba4b71-f8ec-4967-9ae1-db654981291f)
正常的应该如下图：
![image](https://github.com/VisActor/VTable/assets/1018509/2e8d08df-cfd5-4e69-b7cd-9a21a43fa9d8)

重现代码如下：

 ` 
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8" />
    <title>vtable demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="https://unpkg.com/@visactor/vtable/dist/vtable.min.js"></script>
</head>
<body>
    <template id="vTableTemplate">
        <div style="width: 900px;height:400px;"></div>
    </template>
    <h1>Vtable demo 页面</h1>
    <script>
        //自定义组件，方便 后期调用
        class vTable extends HTMLElement {
            constructor() {
                super();
                var shadow = this.attachShadow({ mode: 'open' });

                var templateElem = document.getElementById('vTableTemplate');
                var content = templateElem.content.cloneNode(true);
                const dropmenu = [
                    {
                        "text": "固定列",
                        "menuKey": "pinColumn",
                        "icon": {
                            "svg": "<svg t=\"1703465166825\" class=\"icon\" viewBox=\"0 0 1024 1024\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" p-id=\"4300\" width=\"14\" height=\"14\"><path d=\"M393.846154 64.174932l117.454119 0.399843H512.499805l117.454119-0.399843-10.395939 10.395939c-18.89262 18.89262-28.488872 44.982429-26.28973 71.472081l20.292073 250.502148c2.998829 36.68567 18.092932 72.171808 42.483405 99.661069l34.186646 38.684889-122.252245-0.899648-55.478329-0.399844h-0.99961l-55.478329 0.399844-122.452167 0.799687 34.186646-38.684888c24.390472-27.589223 39.484576-62.9754 42.483405-99.66107l20.292074-250.402187c2.199141-26.589613-7.397111-52.679422-26.289731-71.472081l-10.395939-10.395939m281.889887-64.174932h-0.199922L512.399844 0.599766h-0.799688L348.36392 0h-0.199922c-20.891839 0-39.684498 13.494729-45.582194 33.58688-4.098399 13.994533-1.899258 30.887934 17.79305 47.581414l38.584927 38.584927c5.597813 5.597813 8.39672 13.294807 7.796955 21.091761L346.464662 391.247169c-1.899258 23.190941-11.195627 45.08239-26.589613 62.475596l-61.87583 69.872706c-8.696603 9.796173-13.894572 22.291292-14.394377 35.386177-0.299883 8.996486 1.599375 18.89262 8.596642 27.28934 6.897306 8.296759 17.293245 12.894963 27.989067 12.894963h0.299882l175.931277-1.199532 55.178446 422.834831 0.399844 3.098789 0.399844-3.098789 55.178446-422.834831 175.931277 1.199532h0.299882c10.795783 0 21.191722-4.598204 27.989067-12.894963 6.897306-8.39672 8.796564-18.292854 8.596642-27.28934-0.399844-13.094885-5.697774-25.590004-14.394377-35.386177l-61.87583-69.872706c-15.393987-17.393206-24.690355-39.284654-26.589613-62.475596l-20.292074-250.402187c-0.599766-7.796954 2.199141-15.593909 7.796955-21.091761l38.584927-38.584927c19.692308-16.693479 21.891449-33.58688 17.79305-47.581414-5.997657-19.992191-24.790316-33.58688-45.682155-33.58688z\" p-id=\"4301\" fill=\"#666666\"></path></svg>"
                        },
                        "children": [
                            {
                                "text": "不固定",
                                "menuKey": "noPin"
                            },
                            {
                                "text": "固定左侧",
                                "menuKey": "pinLeft"
                            },
                            {
                                "text": "固定右侧",
                                "menuKey": "pinRight"
                            }
                        ]
                    },
                    {
                        "text": "分组",
                        "menuKey": "group",
                        "icon": {
                            "svg": "<svg t=\"1703465232298\" class=\"icon\" viewBox=\"0 0 1024 1024\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" p-id=\"8089\" width=\"14\" height=\"14\"><path d=\"M863.008 384C916.576 384 960 341.024 960 288V160c0-53.024-43.424-96-96.992-96H160.992C107.424 64 64 106.976 64 160v128c0 53.024 43.424 96 96.992 96H320v128a32 32 0 0 0 32 32h288v96H160.992C107.424 640 64 682.976 64 736v128c0 53.024 43.424 96 96.992 96h702.016C916.576 960 960 917.024 960 864v-128c0-53.024-43.424-96-96.992-96H704v-128a32 32 0 0 0-32-32h-288v-96h479.008z m0 320c17.856 0 32.32 14.336 32.32 32v128c0 17.664-14.464 32-32.32 32H160.992c-17.856 0-32.32-14.336-32.32-32v-128c0-17.664 14.464-32 32.32-32h702.016zM128.672 288V160c0-17.664 14.464-32 32.32-32h702.016c17.856 0 32.32 14.336 32.32 32v128c0 17.664-14.464 32-32.32 32H160.992c-17.856 0-32.32-14.336-32.32-32z\" p-id=\"666666\" fill=\"#a8adb3\"></path><path d=\"M320 832h384a32 32 0 0 0 0-64H320a32 32 0 0 0 0 64zM736 224a32 32 0 0 0-32-32H320a32 32 0 0 0 0 64h384a32 32 0 0 0 32-32z\" p-id=\"8091\" fill=\"#666666\"></path></svg>"
                        }
                    }
                ];
                window.option = {
                    "widthMode": "standard",
                    "records": [
                        {
                            "data1": "数据1-1",
                            "data2": "数据2-1",
                            "data3": "数据3-1",
                            "data4": "数据4-1",
                            "data5": "数据5-1",
                            "data6": 11
                        },
                        {
                            "data1": "数据1-4",
                            "data2": "数据2-3",
                            "data3": "数据3-10",
                            "data4": "数据4-8",
                            "data5": "数据5-4",
                            "data6": 10
                        }

                    ],
                    "columns": [
                        {
                            "field": "data1",
                            "title": "data1",
                            "width": "auto",
                            "sort": true,
                            "dropDownMenu": dropmenu

                        },
                        {
                            "field": "data2",
                            "title": "data2",
                            "width": "auto",
                            "sort": true,
                            "dropDownMenu": dropmenu
                        },
                        {
                            "field": "data3",
                            "title": "data3",
                            "width": "auto",
                            "sort": true,
                            "dropDownMenu": dropmenu
                        },
                        {
                            "field": "data4",
                            "title": "data4",
                            "width": "auto",
                            "sort": true,
                            "dropDownMenu": dropmenu
                        },
                        {
                            "field": "data5",
                            "title": "data5",
                            "width": "auto",
                            "sort": true,
                            "dropDownMenu": dropmenu
                        }
                    ]
                };
                const tableInstance = new VTable.ListTable(content.querySelector('div'), option);
                shadow.appendChild(content);
            }
        }
        window.customElements.define('v-table', vTable);
    </script>
    <v-table> </v-table>
</body>
</html>
`

### Current Behavior

我希望 vtable 能在 Web Components 中正常工作

### Expected Behavior

头部下拉菜单 位置错误，希望修复。

### Environment

```markdown
- OS:ubuntu
- Browser: chrome 122
- Framework: null
```

**Comment by fangsmile** [comment]
收到

**Comment by Rui-Sun** [comment]
这个问题是因为vtable在全局注册的css样式，无法作用到shadow下的dom元素导致的。如果要解决这个问题，需要手动把vtable的相关样式复制一份到shadow内
![image](https://github.com/VisActor/VTable/assets/25134429/ab4b72b0-60f1-44b8-bcf6-bbfe429cc655)
具体可以参考一下https://codesandbox.io/p/sandbox/vtable-bug-report-forked-g6ctgv?file=%2Findex.html%3A22%2C41

**Comment by xiaofeihe** [comment]
谢谢，可以使用了。
