### ISSUE TITLE
 取消表格默认margin，以及设定容器背景色，如何实现

### ISSUE THREAD

**Issue by liujianya371** [VisActor/VTable#842]
![image](https://github.com/VisActor/VTable/assets/4703288/4eb79458-76f1-4da5-abd3-adeded92f88d)

如图 : 1 想取消margin。2 表格容器设置的宽高，内容不足以撑满，canvas较大内容区域能设置样式，非内容区域怎么设置。

**Comment by fangsmile** [comment]
背景色：
![image](https://github.com/VisActor/VTable/assets/3468473/0403eab9-3469-41b6-9f91-d462169c48f1)
margin：
![image](https://github.com/VisActor/VTable/assets/3468473/fc806ee4-777a-4526-b0b4-01b505b301f6)
确认下theme这几个配置你需要重新配上0
@liujianya371

**Comment by liujianya371** [comment]
@fangsmile 感谢，完美解决
