### ISSUE TITLE
选中单元格，按键盘方向上下左右键不生效

### ISSUE THREAD

**Issue by liujianya371** [VisActor/VTable#845]
<img width="965" alt="image" src="https://github.com/VisActor/VTable/assets/4703288/95469d1d-4c46-4e61-b957-cc14eff8583a">
首次渲染，选中单元格按方向上下左右键不生效，需要点击一下空白区域，在选中 单元格，按上下左右键才会生效，这是什么原因，如何解决

**Comment by fangsmile** [comment]
什么版本？ 可以用一下最新版0.17.4
