### ISSUE TITLE
[Bug] 在react-activation中使用会报错

### ISSUE THREAD

**Issue by RyzenPan** [VisActor/VTable#847]
### Version

0.17.4

### Link to Minimal Reproduction

-

### Steps to Reproduce

使用react-activation包住ListTable之后，会报forEach错误

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

使用react-activation包住ListTable之后，会报forEach错误
![image](https://github.com/VisActor/VTable/assets/56830619/d0d551ed-50ea-42f4-bfac-d50ffb39286b)
![image](https://github.com/VisActor/VTable/assets/56830619/7919ee42-c98e-499f-9874-8bf96051957c)

**Comment by Rui-Sun** [comment]
`header`目前已经弃用了，改成`columns`应该就可以了

**Comment by RyzenPan** [comment]
> `header`目前已经弃用了，改成`columns`应该就可以了

好的，希望官网文档可以更新一下，https://visactor.io/vtable/guide/Developer_Ecology/react
