### ISSUE TITLE
[Feature] 希望PivotTable能够支持 x与y轴线统一配置成线性轴线

### ISSUE THREAD

**Issue by zzsssssss** [VisActor/VTable#864]
### What problem does this feature solve?

能够实现类似于下图功能：
![线性轴线](https://github.com/VisActor/VTable/assets/82629043/c13605a1-75e0-4fd2-bac8-1e09ed7c7fe0)

### What does the proposed API look like?

`const spec={
indicators:{
chartSpec:{
 axes:[{
orient: 'left',
 type: 'linear'
},{
orient: 'bottom',
 type: 'linear'
}]
}
}
}`

**Comment by fangsmile** [comment]
已支持
