### ISSUE TITLE
怎么取选中的行，有没有API。

### ISSUE THREAD

**Issue by zhoubo416** [VisActor/VTable#868]
{
    headerType: 'checkbox', //指定表头单元格显示为复选框
    cellType: 'checkbox', //指定body单元格显示为复选框
    field: 'isCheck',
    width: '50',
    style: {
      textAlign: 'center',
    },
  },
目前感觉单元格选中和 check选中比较混乱，我希望可以拿到我选择了哪些行数据，应该怎么做？
<img width="990" alt="image" src="https://github.com/VisActor/VTable/assets/66418017/b820aba7-5203-4d87-81d3-8da27495af14">

**Comment by fangsmile** [comment]
![image](https://github.com/VisActor/VTable/assets/3468473/407026aa-d997-48af-95f8-86546bac191d)
这个接口可以获取到数据的选中与否
 @zhoubo416

**Comment by zhoubo416** [comment]
多谢，可以解决我的问题
