### ISSUE TITLE
多列多表头大数据量时，如何打印vtable

### ISSUE THREAD

**Issue by chh0122** [VisActor/VTable#869]
我尝试使用了html2canvas来将vtable的dom结构转换成pdf后打印，发现多列时电脑一屏展示以及打印不全。请教下该如何解决这种情况呢？

**Comment by chh0122** [comment]
使用的是pivotTable

**Comment by fangsmile** [comment]
导出整个表格内容的图片 这个接口后续会提供 可以关注下。目前的话 建议将列宽调整至全部能显示出来的效果再打印页面 @chh0122

**Comment by chh0122** [comment]
> 导出整个表格内容的图片 这个接口后续会提供 可以关注下。目前的话 建议将列宽调整至全部能显示出来的效果再打印页面 @chh0122
好的非常感谢
