### ISSUE TITLE
修改冻结列的icon样式 feature

### ISSUE THREAD

**Issue by Sunny20202020** [VisActor/VTable#871]
![image](https://github.com/VisActor/VTable/assets/112694469/ddcbead2-efaf-45cd-8ff7-df4c3cca28ab)
图中红框的列我都加了冻结,以下问题:
1.这个icon在没有激活的状态下或者hover的时候颜色不明显.我怎么修改这个样式呢?(我说的样式包含: 激活样式+未激活样式+hover样式+size)
2.如果我想换成别的icon怎么换

**Comment by Sunny20202020** [comment]
![image](https://github.com/VisActor/VTable/assets/112694469/e083e686-5ca6-4901-bceb-d89f8601f0e5)
![image](https://github.com/VisActor/VTable/assets/112694469/91671ac9-0a9b-4301-a5fb-dc9f192acab2)

我们要求表格可以放大缩小, 我是通过点击右下角的-+来控制一个变量的大小,然后根据这个变量来计算defaultRowHeight & defaultHeaderRowHeight & headerStyle以及bodyStyle中的fontSize, 但是图中可以看到,冻结列的icon并没有随着头部的字体一起放大缩小

**Comment by fangsmile** [comment]
https://visactor.io/vtable/guide/custom_define/custom_icon  可以自定义icon替换内部的图标 @Sunny20202020

**Comment by Sunny20202020** [comment]
如果我只想改变下icon的大小和颜色 也只能自定义吗? 
有没有可以支持下就简单的修改下不同状态的颜色呢
还有icon的大小可以自动跟随header中设置的字体大小的动态自适应吗
@fangsmile

**Comment by fangsmile** [comment]
目前没有跟随的能力  可以提个需求 我们后面支持上

**Comment by fangsmile** [comment]
有需求可以再提issue 这个我先关闭了
