### ISSUE TITLE
希望增加 获取 新增、修改、删除行的接口，并修改过未保存的单元格要做标记

### ISSUE THREAD

**Issue by harvenzhang** [VisActor/VTable#877]
### What problem does this feature solve?

可以方便地将新增的、修改的、删除的记录集发送给后端处理：
如 getInsertedRecords, getUpdatedRecords, getRemovedRecords, getChangedRecords

### What does the proposed API look like?

如 getInsertedRecords, getUpdatedRecords, getRemovedRecords, getChangedRecords

**Comment by fangsmile** [comment]
获取 新增、修改、删除行的接口  已经实现。如有其他需求可以进一步提issue

**Comment by gyssoft** [comment]
没有找到获取新增，修改数据的功能接口。接口只只有updateDatas,没有getupdatedatas
