### ISSUE TITLE
[Bug] click scroll to bottom then mouse wheel scroll up ,then cells render error

### ISSUE THREAD

**Issue by fangsmile** [VisActor/VTable#878]
### Version

develop

### Link to Minimal Reproduction

1

### Steps to Reproduce

list demo:
先点击滚动条到最底部 然后鼠标往上滚动 发现单元格错位

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/3468473/6b648b69-46a1-4501-912a-f0f245cda052)

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed by [0.19.0](https://www.npmjs.com/package/@visactor/vtable/v/0.19.0)
