### ISSUE TITLE
[Bug] 开启 autoFillWidth 并冻结多列后，在调整窗口大小时，无法正确适应新的窗口大小

### ISSUE THREAD

**Issue by luda-dev** [VisActor/VTable#882]
### Version

0.17.8

### Link to Minimal Reproduction

-1

### Steps to Reproduce

 开启 autoFillWidth 并冻结多列后，在调整窗口大小时，无法正确适应新的窗口大小

### Current Behavior

![4959d80e-5a24-4f5b-91a9-a3c1322090a1](https://github.com/VisActor/VTable/assets/24386577/0b462201-8848-4b56-856f-a8384e1f12d1)

### Expected Behavior

-1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
帮忙提供下数据和配置吧 我这边没复现出来 @luda-dev
