### ISSUE TITLE
[Feature] ListTable 对表行进行换位

### ISSUE THREAD

**Issue by luda-dev** [VisActor/VTable#883]
### What problem does this feature solve?

大概是这个样子

![aeee7a0f-88d8-41a3-b434-13e838692c8f](https://github.com/VisActor/VTable/assets/24386577/43bfce9e-6710-49a3-b59b-accabaef17f3)

### What does the proposed API look like?

大概是上面的样子

**Comment by fangsmile** [comment]
已实现  可以通过行号功能来使用
