### ISSUE TITLE
[Feature] react项目中使用可编辑表格，自定义单元格类型能否插入其他组件

### ISSUE THREAD

**Issue by mmmaomao21** [VisActor/VTable#885]
### What problem does this feature solve?

自定义单元格类型想设置一些自定义组件，现在是不可以的吗？

### What does the proposed API look like?

直接插入class类组件等

**Comment by martesi** [comment]
目前 react-vtable 还没有直接提供这样的功能，不过如 @luda-dev 提到的那样，你可以间接地使用这样的功能，比如像 #1005 里面一样在 `onStart`（aka `beginEdit`）时创建你需要的编辑器。不过这个例子里的代码需要进行一些调整：
- 如果你需要消费 context，你应该使用 [`createPortal`](https://react.dev/reference/react-dom/createPortal) 而不是新建一个 root 节点
- 如果你使用了 [`createRoot`](https://react.dev/reference/react-dom/client/createRoot)，你应该在 endEdit 时调用 root 上的 [`unmount`](https://react.dev/reference/react-dom/client/createRoot#root-unmount) 来释放资源
- 如果你使用 react 18-，你应该调用 [`render`](https://react.dev/reference/react-dom/render) 并使用 [`unmountComponentAtNode`](https://react.dev/reference/react-dom/unmountComponentAtNode) 来释放资源

如果 react-vtable 需要添加这样的支持的话，你希望 API 是什么样呢？

**Comment by fangsmile** [comment]
https://visactor.io/vtable/demo-react/custom-layout/cell-custom-dom
https://visactor.io/vtable/demo-react/functional-components/arco-select-editor

估计需求已经实现，可以验证下。如果有问题可以再提issue
