### ISSUE TITLE
[Feature] 新增交互-行高调整

### ISSUE THREAD

**Issue by LiChangyi** [VisActor/VTable#887]
### What problem does this feature solve?

我们需要在表格中展示图片。（width: 100%, height: 100%）。虽然目前支持了列宽调整，但是不支持行高调整，所以即使托大列宽，图片在表格中展示的尺寸还是很小的。
所以希望新增行高调整。

### What does the proposed API look like?

API 可以和 `columnResizeMode`  保持一致。

**Comment by fangsmile** [comment]
已支持
