### ISSUE TITLE
react项目，当前vtable自定义单元格合并目前不支持jsx语法，麻烦支持下，感谢

### ISSUE THREAD

**Issue by Wal1e** [VisActor/VTable#890]
### What problem does this feature solve?

![image](https://github.com/VisActor/VTable/assets/20591468/b612f757-c56f-46ed-acf6-84d948b6aaa7)
期望支持jsx语法，目前很多交互和UI都不能实现

当前API[customMergeCell](https://visactor.io/vtable/guide/basic_function/merge_cell)

### What does the proposed API look like?
![image](https://github.com/VisActor/VTable/assets/20591468/2d5771f1-1388-4514-9fce-8749215bfea2)

[地址](https://project.feishu.cn/home/template/rjkf)

**Comment by alonesmall** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/e04ecfab-fcd7-480d-a9c5-21dd2c3b1c0a">
为什么关掉呢？官网还是没有支持jsx语法哎。
