### ISSUE TITLE
[Bug] 透视表的tooltip在超出表格后不会自动销毁

### ISSUE THREAD

**Issue by InModeration** [VisActor/VTable#905]
### Version

0.17.9

### Link to Minimal Reproduction

https://www.visactor.io/vtable/demo/table-type/pivot-table-tree

### Steps to Reproduce

1. 打开上述官方demo
2. 设置透视表的option.tooltip.isShowOverflowTextTooltip = true
3. 调整列宽使单元格文本出现...省略
4. hover该单元格弹出tooltip，滚动窗口
5. tooltip超出表格，复现该问题

### Current Behavior

https://github.com/VisActor/VTable/assets/41774233/e48a9825-ce0a-424c-99d7-cf295025fc8f

### Expected Behavior

和ListTable表现一致，tooltip可以自动销毁

### Environment

```markdown
- OS: Mac OS
- Browser: Chrome
- Framework:
```

**Comment by fangsmile** [comment]
收到反馈 我们排查下
