### ISSUE TITLE
如何实现表格内搜索功能

### ISSUE THREAD

**Issue by liujianya371** [VisActor/VTable#906]
由于是大数据表格，会存在很多看不到的列表头，行，以及单元格。那么想快速找到某一列，某一行，或者某一单元格，如何实现？
1 搜索header列表头，并定位到那一列。
2 搜索row行表头，并定位到那一行。
3 搜索单元格里的内容，并 定位到那一个单元格。
需要考虑搜索单元格有多个单元格可能会有相同内容的情况。
这些如何实现呀。

**Comment by fangsmile** [comment]
搜索能力 这个季度会加上的

**Comment by liujianya371** [comment]
好的，请问有具体时间吗？

**Comment by fangsmile** [comment]
快的话这个月 慢的话下个月😄

**Comment by gaoxiaosong1113** [comment]
> 快的话这个月 慢的话下个月😄

加油！！，很期待

**Comment by fangsmile** [comment]
已支持

**Comment by DreamerHYfly** [comment]
fieldsToSearch传入字段后，不管用。
