### ISSUE TITLE
[Feature] autoWidth模式能否根据fieldFormat之后的内容确定列宽

### ISSUE THREAD

**Issue by jickchen34** [VisActor/VTable#913]
### What problem does this feature solve?

 autoWidth模式根据fieldFormat之后的内容确定列宽

### What does the proposed API look like?

字段不变，修改计算列宽的规则

**Comment by jickchen34** [comment]
![image](https://github.com/VisActor/VTable/assets/66556312/36a74712-7eac-4705-8c80-e802c39569e4)
希望根据fieldFormat 之后最大的宽度计算，能够展示完整完整数据

**Comment by fangsmile** [comment]
内部有个最低列宽的限制 你可以设置成你期望的最大列宽
![image](https://github.com/VisActor/VTable/assets/3468473/8b61db9e-6729-4917-acfe-d87a96867483)

**Comment by jickchen34** [comment]
我希望可以动态计算最大列宽，可以加一个配置吗
