### ISSUE TITLE
[Bug] 透视组合图 TypeError: Cannot read properties of undefined (reading 'createCanvas')

### ISSUE THREAD

**Issue by a1419735487** [VisActor/VTable#915]
### Version

0.17.9

### Link to Minimal Reproduction

-1

### Steps to Reproduce

相同的版本和配置，在官网的编辑器上可以正常显示，使用vue3+ts无法渲染图表，并报错TypeError: Cannot read properties of undefined (reading 'createCanvas')
![9S$8AX7F8X6ZB)CMAI`Z85K](https://github.com/VisActor/VTable/assets/72694814/9d0dd1ec-4f66-453b-be72-0118045993bb)

### Current Behavior

初步判断createCanvas方法中this.envContribution的值为undefined
DefaultGlobal类中对其唯一进行赋值的setActiveEnvContribution从未被调用

### Expected Behavior

解决此问题

### Environment

```markdown
- OS: Window10
- Browser: Chrome 120
- Framework:Vue@3
```

**Comment by fangsmile** [comment]
这个问题 可以先尝试清理node_modules 以及lock.yaml文件  清理干净后重新安装包

如果还有问题可以安装0.17.10-alpha.6 再清理试试

**Comment by a1419735487** [comment]
> 这个问题 可以先尝试清理node_modules 以及lock.yaml文件 清理干净后重新安装包
> 
> 如果还有问题可以安装0.17.10-alpha.6 再清理试试

还是不行，包括[](https://www.visactor.io/vtable/faq/20-How%20to%20use%20VTable%20in%20Vue)中提到的官方demo也出现该问题，是否是因为对vue的支持方面出了问题？
![image](https://github.com/VisActor/VTable/assets/72694814/5df64782-a514-4593-a3dd-45655fa71621)

**Comment by fangsmile** [comment]
你的整个项目可以发我一下吗 @a1419735487

**Comment by fangsmile** [comment]
![飞书20240117-114201](https://github.com/VisActor/VTable/assets/3468473/2f25263f-13b9-4951-8716-7df2bbd6205d)
可以加飞书群 联系我哈

**Comment by a1419735487** [comment]
> 你的整个项目可以发我一下吗 @a1419735487

你可以使用你们的在线demo进行测试，环境和写法基本一致
https://codesandbox.io/p/devbox/mystifying-hamilton-3wl76r?file=%2Fpackage.json

**Comment by fangsmile** [comment]
https://codesandbox.io/p/devbox/vchart-demo-vue-73h8wl  这个例子修复了 链接用新的这个

**Comment by a1419735487** [comment]
> https://codesandbox.io/p/devbox/vchart-demo-vue-73h8wl 这个例子修复了 链接用新的这个

对比旧的例子后我尝试删除node_modules和package-lock.json并重新install解决了，感谢！
