### ISSUE TITLE
[Feature] 点击/编辑/hover 等事件触发的时候是否可以返回当前列的field

### ISSUE THREAD

**Issue by gaoxiaosong1113** [VisActor/VTable#921]
### What problem does this feature solve?

在处理列数据编辑的时候，可以通过field快速修改对应的数据，现在修改数据还需要做个映射

### What does the proposed API look like?

```
{
    "col": 3,
    "row": 33,
    "rawValue": "",
    "field":"field",
    "changedValue": ""
}
```

**Comment by fangsmile** [comment]
用这个接口吧 
![image](https://github.com/VisActor/VTable/assets/3468473/565f3da4-c38c-4290-8c7a-0aa0ceeb4e41)

**Comment by gaoxiaosong1113** [comment]
> 用这个接口吧 ![image](https://private-user-images.githubusercontent.com/3468473/296713388-565f3da4-c38c-4290-8c7a-0aa0ceeb4e41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTE2OTMsIm5iZiI6MTcwNTMxMTM5MywicGF0aCI6Ii8zNDY4NDczLzI5NjcxMzM4OC01NjVmM2RhNC1jMzhjLTQyOTAtOGM3YS0wYWEwY2VlYjRlNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDkzNjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU2OGQ4YTczZmUxY2FlMWQzMzk3OTMzMDg3ZTEyZWY0NTM2MjgxODI3ZTRmZjc3NzI2Nzc4MzU5ZjBkZTgwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2_DhiTbtnDR9lEwUETyLEBNjK4KXIgvWqWqfoLmi1fs)

好的多谢
