### ISSUE TITLE
[Bug] 切换transpose 后再切回多了固定列图标

### ISSUE THREAD

**Issue by kkkisme** [VisActor/VTable#924]
### Version

0.17.9

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/react-vtable-forked-nv399g?file=%2Fsrc%2Findex.tsx%3A30%2C10

### Steps to Reproduce

如下图

### Current Behavior

![PixPin_2024-01-16_10-00-35](https://github.com/VisActor/VTable/assets/18638401/04ce5aee-f2c3-4c80-b055-d9d657592905)

### Expected Behavior

没有多余的固定列图标

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到 我们看一下
