### ISSUE TITLE
[Bug] 合并单元格单元格高度出现问题

### ISSUE THREAD

**Issue by LiChangyi** [VisActor/VTable#927]
### Version

0.17.9

### Link to Minimal Reproduction

无

### Steps to Reproduce

```typescript
const records = Array.from({ length: 100 }).map((_, i) => ({
  id: i,
  image: "https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/VTable/media/pigeon.jpeg",
  prompt: `A full body photograph of inverted ${i}`
}));

const columns: VTable.ColumnsDefine =[
  {
    field: 'image',
    title: '参考图',
    cellType: 'image',
    mergeCell: true,
    width: 240,
  },
  {
    field: 'prompt',
    title: 'Prompt',
    mergeCell: true,
    width: 240
  }
];
```

### Current Behavior

图片高度存在问题，目前太小了。见下图，图片宽度很大（符合预期），但是图片的高度太小，被压缩了。

![Xnip2024-01-16_11-47-27](https://github.com/VisActor/VTable/assets/27627416/49d0fc0a-220a-49dd-ac85-d8e1aa65a484)

### Expected Behavior

图片高度自适应，理论上图片宽高应该是自适应的。默认一边撑满，另外一边保持图片比例自适应。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
图片没上传上来
