### ISSUE TITLE
[refactor] 同时设置 frameStyle 和 bodyStyle 边框，最外层会有重复

### ISSUE THREAD

**Issue by LiChangyi** [VisActor/VTable#935]
### Version

0.17.9

### Link to Minimal Reproduction

无

### Steps to Reproduce

无

### Current Behavior

同时设置 bodyStyle.borderColor 和 frameStyle.borderColor 时，borderWidth 均为 1，在表格边缘，边框是 2px

### Expected Behavior

希望是 1px

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
收到

**Comment by fangsmile** [comment]
https://juejin.cn/post/7367549541958991924  可以参考这个解决
