### ISSUE TITLE
[Feature] 支持在画布的指定区域绘制

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VTable#959]
### What problem does this feature solve?

大屏等期望表格和其他元素一起绘制的场景

### What does the proposed API look like?

initOption: {
  viewBox: {x,y,width,height}
}

**Comment by Rui-Sun** [comment]
* 传入canvas&viewbox
* 更新viewbox
* 异步/同步?

**Comment by Rui-Sun** [comment]
* 禁止交互
* table增加chart option
* menu位置【bug】

**Comment by Rui-Sun** [comment]
- [ ] spec 更新模式
- [ ] spec后处理接口
- [ ] 位置判断单元格坐标接口
- [ ] 清除指定单元格chart图片缓存

**Comment by Rui-Sun** [comment]
[ ] updateViewBox性能优化：在尺寸不变时，不执行resize
