### ISSUE TITLE
[Feature] 增加支持选中整行&支持取消选中对应cell/row功能

### ISSUE THREAD

**Issue by xyjk0917** [VisActor/VTable#968]
### What problem does this feature solve?

能否增加支持选中整行&ctrl多选时点击已经选中的cell/row时支持取消选中的功能

### What does the proposed API look like?

cellSelectMode: 'cell'/'row'
selectCancel: true/false

**Comment by fangsmile** [comment]
收到 后续会完善 感谢建议

**Comment by li936393** [comment]
ctrl或shift能支持选中多行,选中以后能通过事件或者外部暴露方法能获取到选中的行数据
