### ISSUE TITLE
[Feature]cellType为sparkline时，hover到线图上是否可以显示该点的tooltip信息

### ISSUE THREAD

**Issue by liujinjian1016** [VisActor/VTable#969]
### What problem does this feature solve?

cellType为sparkline时，hover上去显示点的同时，能否显示toolTip，没有找到相关配置，
或者目前是否有相关event可以实现类似的效果

### What does the proposed API look like?

sparklineSpec.tooltip.visible = Boolean

**Comment by fangsmile** [comment]
MOUSEOVER_CHART_SYMBOL
这个事件可以监听到 然后弹出你自己的tooltip
https://visactor.io/vtable/api/events#MOUSEOVER_CHART_SYMBOL

**Comment by liujinjian1016** [comment]
已经找到解决方案，可以监听 MOUSEOVER_CHART_SYMBOL事件

**Comment by liujinjian1016** [comment]
> MOUSEOVER_CHART_SYMBOL 这个事件可以监听到 然后弹出你自己的tooltip https://visactor.io/vtable/api/events#MOUSEOVER_CHART_SYMBOL

嗯嗯收到，谢谢
