### ISSUE TITLE
[Feature] listTable支持行拖拽

### ISSUE THREAD

**Issue by li936393** [VisActor/VTable#974]
### What problem does this feature solve?

ListTable支持点击任意cell可选中当前row，如下图所示:
![Uploading 20240122133348.jpg…]()
，可将当前行进行拖拽调整数据位置，拖拽位置后可通过事件（类似change_header_position那样暴露）或外部暴露方法获取拖拽后的数据，如原始数据row1 row2 row3 row4...row1000,拖拽后数据row1000,row5,row89...,row1

### What does the proposed API look like?

tableInstance.on("change_row_position",(args)=>{
    //TODO...
    })
or
tableInstance.getRecords() 返回当前表格数据经过处理后的数据，处理包括排序、过滤等

**Comment by fangsmile** [comment]
收到。不过你上传的图片没有成功

**Comment by li936393** [comment]
![20240122133348](https://github.com/VisActor/VTable/assets/19741687/60f770b3-83bd-484b-b74e-6dcfc8d0af8c)
