### ISSUE TITLE
[Feature] 希望可以通过API 单独设置单元格样式并且单独更新

### ISSUE THREAD

**Issue by zhijun0451** [VisActor/VTable#976]
### What problem does this feature solve?

希望可以通过API 单独设置单元格样式并且单独更新

### What does the proposed API look like?

希望可以通过API 单独设置单元格样式并且单独更新

**Comment by fangsmile** [comment]
收到

**Comment by fangsmile** [comment]
已支持  可以参考自定义样式的用法

**Comment by zhijun0451** [comment]
您好我是郅军，您的邮件我已经收到谢谢。
