### ISSUE TITLE
[Feature] 支持排序、筛选、搜索结合的功能

### ISSUE THREAD

**Issue by ZiQiangWang** [VisActor/VTable#977]
### What problem does this feature solve?

目前vtable支持内置的排序功能，搜索并定位到单元格是通过外部数据处理实现，排序后vtable数据与外部数据不一致，导致定位定位错误

### What does the proposed API look like?

- 提供search方法，支持单元格内容搜索，返回匹配的单元格信息列表。
- search 方法支持复杂匹配的配置，如忽略大小写、正则等

**Comment by fangsmile** [comment]
收到

**Comment by fangsmile** [comment]
目前已经支持了 @ZiQiangWang 可以验证下  如果有问题可以再提issue
