### ISSUE TITLE
[Bug] 复制粘贴最后一行不起作用

### ISSUE THREAD

**Issue by gaoxiaosong1113** [VisActor/VTable#979]
### Version

0.17.10

### Link to Minimal Reproduction

https://visactor.io/vtable/demo/interaction/copy-paste-cell-value

### Steps to Reproduce

滚动到最后一行进行复制粘贴，不触发修改，最后一行互相复制粘贴不好使，其他行正常

### Current Behavior

滚动到最后一行进行复制粘贴，不触发修改

### Expected Behavior

可以正常复制粘贴

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:react
```

**Comment by fangsmile** [comment]
收到

**Comment by gaoxiaosong1113** [comment]
@fangsmile   新发现，最后一行和最后一列都有这个问题
