### ISSUE TITLE
[Bug] react 组件中调整records数据时行高不对

### ISSUE THREAD

**Issue by gaoxiaosong1113** [VisActor/VTable#981]
### Version

0.17.10

### Link to Minimal Reproduction

https://codesandbox.io/p/devbox/react-vtable-forked-6ctmz2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7k1yim0006356kgxv6ob8h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7k1yil0002356kc202jikz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7k1yik0001356ki478393g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr7k1yil0002356kc202jikz%2522%252C%2522activeTabId%2522%253A%2522clr7k1yik0001356ki478393g%2522%257D%252C%2522clr7k1yil0005356k95l0e6vw%2522%253A%257B%2522id%2522%253A%2522clr7k1yil0005356k95l0e6vw%2522%252C%2522activeTabId%2522%253A%2522clropmtnr00mg356k12n7rsby%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clropmtnr00mg356k12n7rsby%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr7k1yil0003356k313qrry0%2522%253A%257B%2522id%2522%253A%2522clr7k1yil0003356k313qrry0%2522%252C%2522tabs%2522%253A%255B%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

1.records设置了100行
2.点击切换后，records设置成只有一行或者少于一屏
3.行高会自动平分

### Current Behavior

![image](https://github.com/VisActor/VTable/assets/16183057/98698eb2-261d-4340-a92a-e8ff49f1e8c3)
![image](https://github.com/VisActor/VTable/assets/16183057/0d6b8eae-1791-4105-aed5-99fa59a35fe7)

### Expected Behavior

应该保持行高的高度

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:react
```

**Comment by Rui-Sun** [comment]
https://www.visactor.io/vtable/option/ListTable#autoFillHeight
