### ISSUE TITLE
[Bug] 数据列过多时，拖动滚动条至最底部&最右侧，会有卡卡顿和白屏

### ISSUE THREAD

**Issue by ZiQiangWang** [VisActor/VTable#982]
### Version

0.18.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/vtable-export-umd-forked-kljslz?file=%2Fsrc%2Findex.ts%3A17%2C10

### Steps to Reproduce

使用 [测试数据.json](https://github.com/VisActor/VTable/files/14017700/default.json) 代替代码中的option。

### Current Behavior

拖动到底部，并拖动到最右侧，从底部开始向上拖动滚动条，可以观测到卡顿和白屏

### Expected Behavior

不要卡顿和白屏

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rui-Sun** [comment]
fixed by [0.18.4](https://www.npmjs.com/package/@visactor/vtable/v/0.18.4)
